CREATE VIEW dbo.vw_TransactionSummary
AS
	SELECT T.SiteGuid,
	T.TransID,
	T.InventoryDate,
	T.TransDateTime,
	T.OwnerID,
	T.ManagerID,
	T.ShipToID,
	T.AutoComplete,
	T.BillToID,
	T.CarrierID,
	T.ConjoinTransID,
	T.DestinationRegistrationID1,
	T.DestinationRegistrationID2,
	T.DestinationSerialNumber1,
	T.DestinationSerialNumber2,
	T.EffectiveDate,
	T.ExpirationDate,
	T.Flag01,
	T.LegacyNumber,
	T.OperatorID,
	T.PONumber,
	T.RequestedDeliveryDate,
	T.ReversalType,
	T.ScheduledDate,
	T.ShipmentNumber,
	T.ShipperID,
	T.[Site],
	T.SupplierID,
	T.TimeIn,
	T.[TimeOut],
	L.ArmNumber,
	L.AdditiveProfileID,
	L.BatchNumber,
	dbo.udf_ConvertFromSIUnits(L.Density, S.DensityUnitIndex, S.DensityDecimalPlaces) AS Density,
	L.DestinationCompartmentID,
	L.DestinationRegistrationID,
	L.InvoiceLineNumber,
	L.InvoiceNumber,
	L.LineNumber,
	L.LoadingLocationID,
	L.MeterID,
	L.MeterStart,
	L.MeterStartDateTime,
	L.MeterStop,
	L.MeterStopDateTime,
	dbo.udf_ConvertFromSIUnits(L.PresetAmount, dbo.udf_ProductTypeFactor(L.ProductType, S.AdditiveVolumeUnitIndex, S.VolumeUnitIndex), dbo.udf_ProductTypeFactor(L.ProductType, S.AdditiveVolumeDecimalPlaces, S.VolumeDecimalPlaces)) AS PresetAmount,
	L.StorageLocationID,
	dbo.udf_ConvertFromSIUnits(L.Temperature, S.TemperatureUnitIndex, S.TemperatureDecimalPlaces) AS Temperature,
	Round( L.Vcf, 5) Vcf,
	L.Product,
	L.TransactionLineItemGuid,
	dbo.udf_ConvertFromSIUnits(L.GrossQuantity,dbo.udf_ProductTypeFactor(L.ProductType, S.AdditiveVolumeUnitIndex, S.VolumeUnitIndex), dbo.udf_ProductTypeFactor(L.ProductType, S.AdditiveVolumeDecimalPlaces,S.VolumeDecimalPlaces)) AS GrossQuantity,
	dbo.udf_ConvertFromSIUnits(L.NetQuantity,dbo.udf_ProductTypeFactor(L.ProductType, S.AdditiveVolumeUnitIndex, S.VolumeUnitIndex), dbo.udf_ProductTypeFactor(L.ProductType, S.AdditiveVolumeDecimalPlaces,S.VolumeDecimalPlaces)) AS NetQuantity,
	dbo.udf_ConvertFromSIUnits(L.DeliveredGrossQuantity,dbo.udf_ProductTypeFactor(L.ProductType, S.AdditiveVolumeUnitIndex, S.VolumeUnitIndex), dbo.udf_ProductTypeFactor(L.ProductType, S.AdditiveVolumeDecimalPlaces,S.VolumeDecimalPlaces)) AS DeliveredGrossQuantity,
	dbo.udf_ConvertFromSIUnits(L.DeliveredNetQuantity,dbo.udf_ProductTypeFactor(L.ProductType, S.AdditiveVolumeUnitIndex, S.VolumeUnitIndex), dbo.udf_ProductTypeFactor(L.ProductType, S.AdditiveVolumeDecimalPlaces,S.VolumeDecimalPlaces)) AS DeliveredNetQuantity,
	dbo.udf_ConvertFromSIUnits(L.MassQuantity, S.MassUnitIndex, S.MassDecimalPlaces) AS MassQuantity,
	L.DeliveredGrossManualValueFlag,
	L.DeliveredNetManualValueFlag,
	dbo.udf_ConvertFromSIUnits(L.Pressure, S.PressureUnitIndex, S.PressureDecimalPlaces) AS Pressure,
	TS.TransactionStatusName AS TransactionStatus,
	T.LookupTransactionStatusIndex,
	T.AliasName,
	T.DeleteFlag,
	T.DocumentNumber,
	SUBSTRING(N.Notes, 1, 256) AS Notes
	FROM dbo.tblTransactionLineItems L
		INNER JOIN dbo.tblTransactions T ON L.TransactionGuid = T.TransactionGuid
		INNER JOIN dbo.tblSites S ON T.SiteGuid = S.SiteGuid
		INNER JOIN lookup.tblTransactionStatus TS ON T.LookupTransactionStatusIndex = TS.TransactionStatusIndex
		INNER JOIN dbo.tblGeneralConfiguration GC ON S.SiteGuid = GC.SiteGuid
		LEFT JOIN dbo.tblTransactionNotes N ON T.TransactionGuid = N.TransactionGuid
	WHERE GC.ShowDeletedTrxFlag = 1 OR T.DeleteFlag = 0
GO