CREATE PROCEDURE [dbo].[gsp_TransactionsUpdateByPK]
(
		@TransactionGuid uniqueidentifier
	,	@TransID nvarchar(64)=NULL
	,	@AliasName nvarchar(32)=NULL
	,	@SubType nvarchar(20)=NULL
	,	@Site nvarchar(30)=NULL
	,	@TransReferenceID nvarchar(64)=NULL
	,	@InventoryDate date=NULL
	,	@ShipToID nvarchar(100)=NULL
	,	@ShipToCode nvarchar(10)=NULL
	,	@SupplierID nvarchar(100)=NULL
	,	@SupplierCode nvarchar(10)=NULL
	,	@RequestedDeliveryDate datetimeoffset(7)=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@TransDateTime datetimeoffset(7)=NULL
	,	@TransVersion bigint=NULL
	,	@SCACCode nvarchar(4)=NULL
	,	@CardNumber nvarchar(30)=NULL
	,	@ShipmentNumber nvarchar(30)=NULL
	,	@ShipperID nvarchar(100)=NULL
	,	@ShipperCode nvarchar(10)=NULL
	,	@OwnerID nvarchar(100)=NULL
	,	@OwnerCode nvarchar(10)=NULL
	,	@ManagerID nvarchar(100)=NULL
	,	@ManagerCode nvarchar(10)=NULL
	,	@CarrierID nvarchar(100)=NULL
	,	@CarrierCode nvarchar(10)=NULL
	,	@ConjoinTransID nvarchar(64)=NULL
	,	@ReversedTransID nvarchar(64)=NULL
	,	@LinkedDocumentNumber nvarchar(64)=NULL
	,	@ReversalType nvarchar(2)=NULL
	,	@PONumber nvarchar(14)=NULL
	,	@TimeIn datetimeoffset(7)=NULL
	,	@TimeOut datetimeoffset(7)=NULL
	,	@TimeEnd datetimeoffset(7)=NULL
	,	@RoutingID nvarchar(30)=NULL
	,	@TicketSource nvarchar(20)=NULL
	,	@LoadID nvarchar(50)=NULL
	,	@BillToID nvarchar(100)=NULL
	,	@BillToCode nvarchar(10)=NULL
	,	@DriverIdentificationNumber nvarchar(50)=NULL
	,	@CreditAmount float=NULL
	,	@CardExpiration datetimeoffset(7)=NULL
	,	@CardName nvarchar(30)=NULL
	,	@CardType nvarchar(30)=NULL
	,	@CashAmount float=NULL
	,	@RouteOriginationDate datetimeoffset(7)=NULL
	,	@InternationalRouteIndicator bit=NULL
	,	@PreviousRoutingID nvarchar(30)=NULL
	,	@ShippingDocumentNumber nvarchar(30)=NULL
	,	@DocumentNumber nvarchar(30)=NULL
	,	@STD datetimeoffset(7)=NULL
	,	@ETD datetimeoffset(7)=NULL
	,	@STA datetimeoffset(7)=NULL
	,	@ETA datetimeoffset(7)=NULL
	,	@SFT datetimeoffset(7)=NULL
	,	@FST datetimeoffset(7)=NULL
	,	@EstimatedFuelingDuration int=NULL
	,	@DeleteFlag bit=NULL
	,	@TicketMode nvarchar(15)=NULL
	,	@DestinationRegistrationID1 nvarchar(30)=NULL
	,	@DestinationSerialNumber1 nvarchar(10)=NULL
	,	@DestinationEquipmentType1 nvarchar(50)=NULL
	,	@DestinationEquipmentModel1 nvarchar(20)=NULL
	,	@DestinationCompanyEquipmentID1 nvarchar(30)=NULL
	,	@DestinationRegistrationID2 nvarchar(30)=NULL
	,	@DestinationSerialNumber2 nvarchar(10)=NULL
	,	@DestinationEquipmentType2 nvarchar(50)=NULL
	,	@DestinationEquipmentModel2 nvarchar(20)=NULL
	,	@DestinationCompanyEquipmentID2 nvarchar(30)=NULL
	,	@DestinationRegistrationID3 nvarchar(30)=NULL
	,	@DestinationSerialNumber3 nvarchar(10)=NULL
	,	@DestinationEquipmentType3 nvarchar(50)=NULL
	,	@DestinationEquipmentModel3 nvarchar(20)=NULL
	,	@DestinationCompanyEquipmentID3 nvarchar(30)=NULL
	,	@SourceRegistrationID1 nvarchar(30)=NULL
	,	@SourceSerialNumber1 nvarchar(10)=NULL
	,	@SourceEquipmentType1 nvarchar(50)=NULL
	,	@SourceEquipmentModel1 nvarchar(20)=NULL
	,	@SourceCompanyEquipmentID1 nvarchar(30)=NULL
	,	@SourceRegistrationID2 nvarchar(30)=NULL
	,	@SourceSerialNumber2 nvarchar(10)=NULL
	,	@SourceEquipmentType2 nvarchar(50)=NULL
	,	@SourceEquipmentModel2 nvarchar(20)=NULL
	,	@SourceCompanyEquipmentID2 nvarchar(30)=NULL
	,	@SourceRegistrationID3 nvarchar(30)=NULL
	,	@SourceSerialNumber3 nvarchar(10)=NULL
	,	@SourceEquipmentType3 nvarchar(50)=NULL
	,	@SourceEquipmentModel3 nvarchar(20)=NULL
	,	@SourceCompanyEquipmentID3 nvarchar(30)=NULL
	,	@OperatorID nvarchar(50)=NULL
	,	@EffectiveDate datetimeoffset(7)=NULL
	,	@ExpirationDate datetimeoffset(7)=NULL
	,	@ScheduledDate datetimeoffset(7)=NULL
	,	@AutoComplete bit=NULL
	,	@Flag01 bit=NULL
	,	@Flag02 bit=NULL
	,	@Flag03 bit=NULL
	,	@Flag04 bit=NULL
	,	@Flag05 bit=NULL
	,	@Flag06 bit=NULL
	,	@Number01 float=NULL
	,	@Number02 float=NULL
	,	@Number03 float=NULL
	,	@Number04 float=NULL
	,	@Number05 float=NULL
	,	@Number06 float=NULL
	,	@ContactFirstName nvarchar(50)=NULL
	,	@ContactSurname nvarchar(50)=NULL
	,	@Date01 datetimeoffset(7)=NULL
	,	@Date02 datetimeoffset(7)=NULL
	,	@Date03 datetimeoffset(7)=NULL
	,	@Date04 datetimeoffset(7)=NULL
	,	@LegacyNumber nvarchar(50)=NULL
	,	@Country nvarchar(50)=NULL
	,	@ContactInfo nvarchar(50)=NULL
	,	@AssociatedDocNumber nvarchar(30)=NULL
	,	@AssociatedCLIN nvarchar(10)=NULL
	,	@SubmittedToAccounting bit=NULL
	,	@FuelCardID nvarchar(50)=NULL
	,	@AssociatedTransportOrderNumber nvarchar(30)=NULL
	,	@RequestedDateTime datetimeoffset(7)=NULL
	,	@DispatchedDateTime datetimeoffset(7)=NULL
	,	@ErrorFlag bit=NULL
	,	@SiteGuid uniqueidentifier=NULL
	,	@LookupTransTypeIndex smallint=NULL
	,	@LookupTransactionStatusIndex int=NULL
	,	@LookupOriginApplicationIndex int=NULL
	,	@TransactionAliasGuid uniqueidentifier=NULL
	,	@BillToCompanyGuid uniqueidentifier=NULL
	,	@Destination1EquipmentGuid uniqueidentifier=NULL
	,	@Destination2EquipmentGuid uniqueidentifier=NULL
	,	@Destination3EquipmentGuid uniqueidentifier=NULL
	,	@FinalStationIATAGuid uniqueidentifier=NULL
	,	@FuelCardGuid uniqueidentifier=NULL
	,	@ManagerCompanyGuid uniqueidentifier=NULL
	,	@NextStationIATAGuid uniqueidentifier=NULL
	,	@OperatorPersonnelGuid uniqueidentifier=NULL
	,	@OriginStationIATAGuid uniqueidentifier=NULL
	,	@OwnerCompanyGuid uniqueidentifier=NULL
	,	@PreviousStationIATAGuid uniqueidentifier=NULL
	,	@ShipperCompanyGuid uniqueidentifier=NULL
	,	@ShipToCompanyGuid uniqueidentifier=NULL
	,	@Source1EquipmentGuid uniqueidentifier=NULL
	,	@Source2EquipmentGuid uniqueidentifier=NULL
	,	@Source3EquipmentGuid uniqueidentifier=NULL
	,	@SupplierCompanyGuid uniqueidentifier=NULL
	,	@CarrierCompanyGuid uniqueidentifier=NULL
	,	@ReasonCodeGuid uniqueidentifier=NULL
	,	@OriginStationIATAID nvarchar(50)=NULL
	,	@PreviousStationIATAID nvarchar(50)=NULL
	,	@NextStationIATAID nvarchar(50)=NULL
	,	@FinalStationIATAID nvarchar(50)=NULL
	,	@OperatorName nvarchar(150)=NULL
	,	@FuelAdditiveFlag bit=NULL
	,	@IssuePoint nvarchar(max)=NULL
	,	@IssuePointNumber nvarchar(max)=NULL
	,	@RadioNumber nvarchar(max)=NULL
	,	@GateID nvarchar(10)=NULL
	,	@GateGuid uniqueidentifier=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideTransID BIT=0 
	,	@NullOverrideAliasName BIT=0 
	,	@NullOverrideSubType BIT=0 
	,	@NullOverrideSite BIT=0 
	,	@NullOverrideTransReferenceID BIT=0 
	,	@NullOverrideInventoryDate BIT=0 
	,	@NullOverrideShipToID BIT=0 
	,	@NullOverrideShipToCode BIT=0 
	,	@NullOverrideSupplierID BIT=0 
	,	@NullOverrideSupplierCode BIT=0 
	,	@NullOverrideRequestedDeliveryDate BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverrideTransDateTime BIT=0 
	,	@NullOverrideTransVersion BIT=0 
	,	@NullOverrideSCACCode BIT=0 
	,	@NullOverrideCardNumber BIT=0 
	,	@NullOverrideShipmentNumber BIT=0 
	,	@NullOverrideShipperID BIT=0 
	,	@NullOverrideShipperCode BIT=0 
	,	@NullOverrideOwnerID BIT=0 
	,	@NullOverrideOwnerCode BIT=0 
	,	@NullOverrideManagerID BIT=0 
	,	@NullOverrideManagerCode BIT=0 
	,	@NullOverrideCarrierID BIT=0 
	,	@NullOverrideCarrierCode BIT=0 
	,	@NullOverrideConjoinTransID BIT=0 
	,	@NullOverrideReversedTransID BIT=0 
	,	@NullOverrideLinkedDocumentNumber BIT=0 
	,	@NullOverrideReversalType BIT=0 
	,	@NullOverridePONumber BIT=0 
	,	@NullOverrideTimeIn BIT=0 
	,	@NullOverrideTimeOut BIT=0 
	,	@NullOverrideTimeEnd BIT=0 
	,	@NullOverrideRoutingID BIT=0 
	,	@NullOverrideTicketSource BIT=0 
	,	@NullOverrideLoadID BIT=0 
	,	@NullOverrideBillToID BIT=0 
	,	@NullOverrideBillToCode BIT=0 
	,	@NullOverrideDriverIdentificationNumber BIT=0 
	,	@NullOverrideCreditAmount BIT=0 
	,	@NullOverrideCardExpiration BIT=0 
	,	@NullOverrideCardName BIT=0 
	,	@NullOverrideCardType BIT=0 
	,	@NullOverrideCashAmount BIT=0 
	,	@NullOverrideRouteOriginationDate BIT=0 
	,	@NullOverrideInternationalRouteIndicator BIT=0 
	,	@NullOverridePreviousRoutingID BIT=0 
	,	@NullOverrideShippingDocumentNumber BIT=0 
	,	@NullOverrideDocumentNumber BIT=0 
	,	@NullOverrideSTD BIT=0 
	,	@NullOverrideETD BIT=0 
	,	@NullOverrideSTA BIT=0 
	,	@NullOverrideETA BIT=0 
	,	@NullOverrideSFT BIT=0 
	,	@NullOverrideFST BIT=0 
	,	@NullOverrideEstimatedFuelingDuration BIT=0 
	,	@NullOverrideDeleteFlag BIT=0 
	,	@NullOverrideTicketMode BIT=0 
	,	@NullOverrideDestinationRegistrationID1 BIT=0 
	,	@NullOverrideDestinationSerialNumber1 BIT=0 
	,	@NullOverrideDestinationEquipmentType1 BIT=0 
	,	@NullOverrideDestinationEquipmentModel1 BIT=0 
	,	@NullOverrideDestinationCompanyEquipmentID1 BIT=0 
	,	@NullOverrideDestinationRegistrationID2 BIT=0 
	,	@NullOverrideDestinationSerialNumber2 BIT=0 
	,	@NullOverrideDestinationEquipmentType2 BIT=0 
	,	@NullOverrideDestinationEquipmentModel2 BIT=0 
	,	@NullOverrideDestinationCompanyEquipmentID2 BIT=0 
	,	@NullOverrideDestinationRegistrationID3 BIT=0 
	,	@NullOverrideDestinationSerialNumber3 BIT=0 
	,	@NullOverrideDestinationEquipmentType3 BIT=0 
	,	@NullOverrideDestinationEquipmentModel3 BIT=0 
	,	@NullOverrideDestinationCompanyEquipmentID3 BIT=0 
	,	@NullOverrideSourceRegistrationID1 BIT=0 
	,	@NullOverrideSourceSerialNumber1 BIT=0 
	,	@NullOverrideSourceEquipmentType1 BIT=0 
	,	@NullOverrideSourceEquipmentModel1 BIT=0 
	,	@NullOverrideSourceCompanyEquipmentID1 BIT=0 
	,	@NullOverrideSourceRegistrationID2 BIT=0 
	,	@NullOverrideSourceSerialNumber2 BIT=0 
	,	@NullOverrideSourceEquipmentType2 BIT=0 
	,	@NullOverrideSourceEquipmentModel2 BIT=0 
	,	@NullOverrideSourceCompanyEquipmentID2 BIT=0 
	,	@NullOverrideSourceRegistrationID3 BIT=0 
	,	@NullOverrideSourceSerialNumber3 BIT=0 
	,	@NullOverrideSourceEquipmentType3 BIT=0 
	,	@NullOverrideSourceEquipmentModel3 BIT=0 
	,	@NullOverrideSourceCompanyEquipmentID3 BIT=0 
	,	@NullOverrideOperatorID BIT=0 
	,	@NullOverrideEffectiveDate BIT=0 
	,	@NullOverrideExpirationDate BIT=0 
	,	@NullOverrideScheduledDate BIT=0 
	,	@NullOverrideAutoComplete BIT=0 
	,	@NullOverrideFlag01 BIT=0 
	,	@NullOverrideFlag02 BIT=0 
	,	@NullOverrideFlag03 BIT=0 
	,	@NullOverrideFlag04 BIT=0 
	,	@NullOverrideFlag05 BIT=0 
	,	@NullOverrideFlag06 BIT=0 
	,	@NullOverrideNumber01 BIT=0 
	,	@NullOverrideNumber02 BIT=0 
	,	@NullOverrideNumber03 BIT=0 
	,	@NullOverrideNumber04 BIT=0 
	,	@NullOverrideNumber05 BIT=0 
	,	@NullOverrideNumber06 BIT=0 
	,	@NullOverrideContactFirstName BIT=0 
	,	@NullOverrideContactSurname BIT=0 
	,	@NullOverrideDate01 BIT=0 
	,	@NullOverrideDate02 BIT=0 
	,	@NullOverrideDate03 BIT=0 
	,	@NullOverrideDate04 BIT=0 
	,	@NullOverrideLegacyNumber BIT=0 
	,	@NullOverrideCountry BIT=0 
	,	@NullOverrideContactInfo BIT=0 
	,	@NullOverrideAssociatedDocNumber BIT=0 
	,	@NullOverrideAssociatedCLIN BIT=0 
	,	@NullOverrideSubmittedToAccounting BIT=0 
	,	@NullOverrideFuelCardID BIT=0 
	,	@NullOverrideAssociatedTransportOrderNumber BIT=0 
	,	@NullOverrideRequestedDateTime BIT=0 
	,	@NullOverrideDispatchedDateTime BIT=0 
	,	@NullOverrideErrorFlag BIT=0 
	,	@NullOverrideSiteGuid BIT=0 
	,	@NullOverrideLookupTransTypeIndex BIT=0 
	,	@NullOverrideLookupTransactionStatusIndex BIT=0 
	,	@NullOverrideLookupOriginApplicationIndex BIT=0 
	,	@NullOverrideTransactionAliasGuid BIT=0 
	,	@NullOverrideBillToCompanyGuid BIT=0 
	,	@NullOverrideDestination1EquipmentGuid BIT=0 
	,	@NullOverrideDestination2EquipmentGuid BIT=0 
	,	@NullOverrideDestination3EquipmentGuid BIT=0 
	,	@NullOverrideFinalStationIATAGuid BIT=0 
	,	@NullOverrideFuelCardGuid BIT=0 
	,	@NullOverrideManagerCompanyGuid BIT=0 
	,	@NullOverrideNextStationIATAGuid BIT=0 
	,	@NullOverrideOperatorPersonnelGuid BIT=0 
	,	@NullOverrideOriginStationIATAGuid BIT=0 
	,	@NullOverrideOwnerCompanyGuid BIT=0 
	,	@NullOverridePreviousStationIATAGuid BIT=0 
	,	@NullOverrideShipperCompanyGuid BIT=0 
	,	@NullOverrideShipToCompanyGuid BIT=0 
	,	@NullOverrideSource1EquipmentGuid BIT=0 
	,	@NullOverrideSource2EquipmentGuid BIT=0 
	,	@NullOverrideSource3EquipmentGuid BIT=0 
	,	@NullOverrideSupplierCompanyGuid BIT=0 
	,	@NullOverrideCarrierCompanyGuid BIT=0 
	,	@NullOverrideReasonCodeGuid BIT=0 
	,	@NullOverrideOriginStationIATAID BIT=0 
	,	@NullOverridePreviousStationIATAID BIT=0 
	,	@NullOverrideNextStationIATAID BIT=0 
	,	@NullOverrideFinalStationIATAID BIT=0 
	,	@NullOverrideOperatorName BIT=0 
	,	@NullOverrideFuelAdditiveFlag BIT=0 
	,	@NullOverrideIssuePoint BIT=0 
	,	@NullOverrideIssuePointNumber BIT=0 
	,	@NullOverrideRadioNumber BIT=0
	,	@NullOverrideGateID Bit=0
	,	@NullOverrideGateGuid Bit=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_TransactionsUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:29.8844356 -05:00
	-- Purpose: Update table [dbo].[tblTransactions]
	-- Notes:
	-- 1. @TransactionGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblTransactions] WHERE TransactionGuid=@TransactionGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblTransactions] SET
			[TransID]=(CASE ISNULL(@NullOverrideTransID,0) WHEN 1 THEN @TransID ELSE ISNULL(@TransID,[TransID]) END)
		,	[AliasName]=(CASE ISNULL(@NullOverrideAliasName,0) WHEN 1 THEN @AliasName ELSE ISNULL(@AliasName,[AliasName]) END)
		,	[SubType]=(CASE ISNULL(@NullOverrideSubType,0) WHEN 1 THEN @SubType ELSE ISNULL(@SubType,[SubType]) END)
		,	[Site]=(CASE ISNULL(@NullOverrideSite,0) WHEN 1 THEN @Site ELSE ISNULL(@Site,[Site]) END)
		,	[TransReferenceID]=(CASE ISNULL(@NullOverrideTransReferenceID,0) WHEN 1 THEN @TransReferenceID ELSE ISNULL(@TransReferenceID,[TransReferenceID]) END)
		,	[InventoryDate]=(CASE ISNULL(@NullOverrideInventoryDate,0) WHEN 1 THEN @InventoryDate ELSE ISNULL(@InventoryDate,[InventoryDate]) END)
		,	[ShipToID]=(CASE ISNULL(@NullOverrideShipToID,0) WHEN 1 THEN @ShipToID ELSE ISNULL(@ShipToID,[ShipToID]) END)
		,	[ShipToCode]=(CASE ISNULL(@NullOverrideShipToCode,0) WHEN 1 THEN @ShipToCode ELSE ISNULL(@ShipToCode,[ShipToCode]) END)
		,	[SupplierID]=(CASE ISNULL(@NullOverrideSupplierID,0) WHEN 1 THEN @SupplierID ELSE ISNULL(@SupplierID,[SupplierID]) END)
		,	[SupplierCode]=(CASE ISNULL(@NullOverrideSupplierCode,0) WHEN 1 THEN @SupplierCode ELSE ISNULL(@SupplierCode,[SupplierCode]) END)
		,	[RequestedDeliveryDate]=(CASE ISNULL(@NullOverrideRequestedDeliveryDate,0) WHEN 1 THEN @RequestedDeliveryDate ELSE ISNULL(@RequestedDeliveryDate,[RequestedDeliveryDate]) END)
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[TransDateTime]=(CASE ISNULL(@NullOverrideTransDateTime,0) WHEN 1 THEN @TransDateTime ELSE ISNULL(@TransDateTime,[TransDateTime]) END)
		,	[TransVersion]=(CASE ISNULL(@NullOverrideTransVersion,0) WHEN 1 THEN @TransVersion ELSE ISNULL(@TransVersion,[TransVersion]) END)
		,	[SCACCode]=(CASE ISNULL(@NullOverrideSCACCode,0) WHEN 1 THEN @SCACCode ELSE ISNULL(@SCACCode,[SCACCode]) END)
		,	[CardNumber]=(CASE ISNULL(@NullOverrideCardNumber,0) WHEN 1 THEN @CardNumber ELSE ISNULL(@CardNumber,[CardNumber]) END)
		,	[ShipmentNumber]=(CASE ISNULL(@NullOverrideShipmentNumber,0) WHEN 1 THEN @ShipmentNumber ELSE ISNULL(@ShipmentNumber,[ShipmentNumber]) END)
		,	[ShipperID]=(CASE ISNULL(@NullOverrideShipperID,0) WHEN 1 THEN @ShipperID ELSE ISNULL(@ShipperID,[ShipperID]) END)
		,	[ShipperCode]=(CASE ISNULL(@NullOverrideShipperCode,0) WHEN 1 THEN @ShipperCode ELSE ISNULL(@ShipperCode,[ShipperCode]) END)
		,	[OwnerID]=(CASE ISNULL(@NullOverrideOwnerID,0) WHEN 1 THEN @OwnerID ELSE ISNULL(@OwnerID,[OwnerID]) END)
		,	[OwnerCode]=(CASE ISNULL(@NullOverrideOwnerCode,0) WHEN 1 THEN @OwnerCode ELSE ISNULL(@OwnerCode,[OwnerCode]) END)
		,	[ManagerID]=(CASE ISNULL(@NullOverrideManagerID,0) WHEN 1 THEN @ManagerID ELSE ISNULL(@ManagerID,[ManagerID]) END)
		,	[ManagerCode]=(CASE ISNULL(@NullOverrideManagerCode,0) WHEN 1 THEN @ManagerCode ELSE ISNULL(@ManagerCode,[ManagerCode]) END)
		,	[CarrierID]=(CASE ISNULL(@NullOverrideCarrierID,0) WHEN 1 THEN @CarrierID ELSE ISNULL(@CarrierID,[CarrierID]) END)
		,	[CarrierCode]=(CASE ISNULL(@NullOverrideCarrierCode,0) WHEN 1 THEN @CarrierCode ELSE ISNULL(@CarrierCode,[CarrierCode]) END)
		,	[ConjoinTransID]=(CASE ISNULL(@NullOverrideConjoinTransID,0) WHEN 1 THEN @ConjoinTransID ELSE ISNULL(@ConjoinTransID,[ConjoinTransID]) END)
		,	[ReversedTransID]=(CASE ISNULL(@NullOverrideReversedTransID,0) WHEN 1 THEN @ReversedTransID ELSE ISNULL(@ReversedTransID,[ReversedTransID]) END)
		,	[LinkedDocumentNumber]=(CASE ISNULL(@NullOverrideLinkedDocumentNumber,0) WHEN 1 THEN @LinkedDocumentNumber ELSE ISNULL(@LinkedDocumentNumber,[LinkedDocumentNumber]) END)
		,	[ReversalType]=(CASE ISNULL(@NullOverrideReversalType,0) WHEN 1 THEN @ReversalType ELSE ISNULL(@ReversalType,[ReversalType]) END)
		,	[PONumber]=(CASE ISNULL(@NullOverridePONumber,0) WHEN 1 THEN @PONumber ELSE ISNULL(@PONumber,[PONumber]) END)
		,	[TimeIn]=(CASE ISNULL(@NullOverrideTimeIn,0) WHEN 1 THEN @TimeIn ELSE ISNULL(@TimeIn,[TimeIn]) END)
		,	[TimeOut]=(CASE ISNULL(@NullOverrideTimeOut,0) WHEN 1 THEN @TimeOut ELSE ISNULL(@TimeOut,[TimeOut]) END)
		,	[TimeEnd]=(CASE ISNULL(@NullOverrideTimeEnd,0) WHEN 1 THEN @TimeEnd ELSE ISNULL(@TimeEnd,[TimeEnd]) END)
		,	[RoutingID]=(CASE ISNULL(@NullOverrideRoutingID,0) WHEN 1 THEN @RoutingID ELSE ISNULL(@RoutingID,[RoutingID]) END)
		,	[TicketSource]=(CASE ISNULL(@NullOverrideTicketSource,0) WHEN 1 THEN @TicketSource ELSE ISNULL(@TicketSource,[TicketSource]) END)
		,	[LoadID]=(CASE ISNULL(@NullOverrideLoadID,0) WHEN 1 THEN @LoadID ELSE ISNULL(@LoadID,[LoadID]) END)
		,	[BillToID]=(CASE ISNULL(@NullOverrideBillToID,0) WHEN 1 THEN @BillToID ELSE ISNULL(@BillToID,[BillToID]) END)
		,	[BillToCode]=(CASE ISNULL(@NullOverrideBillToCode,0) WHEN 1 THEN @BillToCode ELSE ISNULL(@BillToCode,[BillToCode]) END)
		,	[DriverIdentificationNumber]=(CASE ISNULL(@NullOverrideDriverIdentificationNumber,0) WHEN 1 THEN @DriverIdentificationNumber ELSE ISNULL(@DriverIdentificationNumber,[DriverIdentificationNumber]) END)
		,	[CreditAmount]=(CASE ISNULL(@NullOverrideCreditAmount,0) WHEN 1 THEN @CreditAmount ELSE ISNULL(@CreditAmount,[CreditAmount]) END)
		,	[CardExpiration]=(CASE ISNULL(@NullOverrideCardExpiration,0) WHEN 1 THEN @CardExpiration ELSE ISNULL(@CardExpiration,[CardExpiration]) END)
		,	[CardName]=(CASE ISNULL(@NullOverrideCardName,0) WHEN 1 THEN @CardName ELSE ISNULL(@CardName,[CardName]) END)
		,	[CardType]=(CASE ISNULL(@NullOverrideCardType,0) WHEN 1 THEN @CardType ELSE ISNULL(@CardType,[CardType]) END)
		,	[CashAmount]=(CASE ISNULL(@NullOverrideCashAmount,0) WHEN 1 THEN @CashAmount ELSE ISNULL(@CashAmount,[CashAmount]) END)
		,	[RouteOriginationDate]=(CASE ISNULL(@NullOverrideRouteOriginationDate,0) WHEN 1 THEN @RouteOriginationDate ELSE ISNULL(@RouteOriginationDate,[RouteOriginationDate]) END)
		,	[InternationalRouteIndicator]=(CASE ISNULL(@NullOverrideInternationalRouteIndicator,0) WHEN 1 THEN @InternationalRouteIndicator ELSE ISNULL(@InternationalRouteIndicator,[InternationalRouteIndicator]) END)
		,	[PreviousRoutingID]=(CASE ISNULL(@NullOverridePreviousRoutingID,0) WHEN 1 THEN @PreviousRoutingID ELSE ISNULL(@PreviousRoutingID,[PreviousRoutingID]) END)
		,	[ShippingDocumentNumber]=(CASE ISNULL(@NullOverrideShippingDocumentNumber,0) WHEN 1 THEN @ShippingDocumentNumber ELSE ISNULL(@ShippingDocumentNumber,[ShippingDocumentNumber]) END)
		,	[DocumentNumber]=(CASE ISNULL(@NullOverrideDocumentNumber,0) WHEN 1 THEN @DocumentNumber ELSE ISNULL(@DocumentNumber,[DocumentNumber]) END)
		,	[STD]=(CASE ISNULL(@NullOverrideSTD,0) WHEN 1 THEN @STD ELSE ISNULL(@STD,[STD]) END)
		,	[ETD]=(CASE ISNULL(@NullOverrideETD,0) WHEN 1 THEN @ETD ELSE ISNULL(@ETD,[ETD]) END)
		,	[STA]=(CASE ISNULL(@NullOverrideSTA,0) WHEN 1 THEN @STA ELSE ISNULL(@STA,[STA]) END)
		,	[ETA]=(CASE ISNULL(@NullOverrideETA,0) WHEN 1 THEN @ETA ELSE ISNULL(@ETA,[ETA]) END)
		,	[SFT]=(CASE ISNULL(@NullOverrideSFT,0) WHEN 1 THEN @SFT ELSE ISNULL(@SFT,[SFT]) END)
		,	[FST]=(CASE ISNULL(@NullOverrideFST,0) WHEN 1 THEN @FST ELSE ISNULL(@FST,[FST]) END)
		,	[EstimatedFuelingDuration]=(CASE ISNULL(@NullOverrideEstimatedFuelingDuration,0) WHEN 1 THEN @EstimatedFuelingDuration ELSE ISNULL(@EstimatedFuelingDuration,[EstimatedFuelingDuration]) END)
		,	[DeleteFlag]=(CASE ISNULL(@NullOverrideDeleteFlag,0) WHEN 1 THEN @DeleteFlag ELSE ISNULL(@DeleteFlag,[DeleteFlag]) END)
		,	[TicketMode]=(CASE ISNULL(@NullOverrideTicketMode,0) WHEN 1 THEN @TicketMode ELSE ISNULL(@TicketMode,[TicketMode]) END)
		,	[DestinationRegistrationID1]=(CASE ISNULL(@NullOverrideDestinationRegistrationID1,0) WHEN 1 THEN @DestinationRegistrationID1 ELSE ISNULL(@DestinationRegistrationID1,[DestinationRegistrationID1]) END)
		,	[DestinationSerialNumber1]=(CASE ISNULL(@NullOverrideDestinationSerialNumber1,0) WHEN 1 THEN @DestinationSerialNumber1 ELSE ISNULL(@DestinationSerialNumber1,[DestinationSerialNumber1]) END)
		,	[DestinationEquipmentType1]=(CASE ISNULL(@NullOverrideDestinationEquipmentType1,0) WHEN 1 THEN @DestinationEquipmentType1 ELSE ISNULL(@DestinationEquipmentType1,[DestinationEquipmentType1]) END)
		,	[DestinationEquipmentModel1]=(CASE ISNULL(@NullOverrideDestinationEquipmentModel1,0) WHEN 1 THEN @DestinationEquipmentModel1 ELSE ISNULL(@DestinationEquipmentModel1,[DestinationEquipmentModel1]) END)
		,	[DestinationCompanyEquipmentID1]=(CASE ISNULL(@NullOverrideDestinationCompanyEquipmentID1,0) WHEN 1 THEN @DestinationCompanyEquipmentID1 ELSE ISNULL(@DestinationCompanyEquipmentID1,[DestinationCompanyEquipmentID1]) END)
		,	[DestinationRegistrationID2]=(CASE ISNULL(@NullOverrideDestinationRegistrationID2,0) WHEN 1 THEN @DestinationRegistrationID2 ELSE ISNULL(@DestinationRegistrationID2,[DestinationRegistrationID2]) END)
		,	[DestinationSerialNumber2]=(CASE ISNULL(@NullOverrideDestinationSerialNumber2,0) WHEN 1 THEN @DestinationSerialNumber2 ELSE ISNULL(@DestinationSerialNumber2,[DestinationSerialNumber2]) END)
		,	[DestinationEquipmentType2]=(CASE ISNULL(@NullOverrideDestinationEquipmentType2,0) WHEN 1 THEN @DestinationEquipmentType2 ELSE ISNULL(@DestinationEquipmentType2,[DestinationEquipmentType2]) END)
		,	[DestinationEquipmentModel2]=(CASE ISNULL(@NullOverrideDestinationEquipmentModel2,0) WHEN 1 THEN @DestinationEquipmentModel2 ELSE ISNULL(@DestinationEquipmentModel2,[DestinationEquipmentModel2]) END)
		,	[DestinationCompanyEquipmentID2]=(CASE ISNULL(@NullOverrideDestinationCompanyEquipmentID2,0) WHEN 1 THEN @DestinationCompanyEquipmentID2 ELSE ISNULL(@DestinationCompanyEquipmentID2,[DestinationCompanyEquipmentID2]) END)
		,	[DestinationRegistrationID3]=(CASE ISNULL(@NullOverrideDestinationRegistrationID3,0) WHEN 1 THEN @DestinationRegistrationID3 ELSE ISNULL(@DestinationRegistrationID3,[DestinationRegistrationID3]) END)
		,	[DestinationSerialNumber3]=(CASE ISNULL(@NullOverrideDestinationSerialNumber3,0) WHEN 1 THEN @DestinationSerialNumber3 ELSE ISNULL(@DestinationSerialNumber3,[DestinationSerialNumber3]) END)
		,	[DestinationEquipmentType3]=(CASE ISNULL(@NullOverrideDestinationEquipmentType3,0) WHEN 1 THEN @DestinationEquipmentType3 ELSE ISNULL(@DestinationEquipmentType3,[DestinationEquipmentType3]) END)
		,	[DestinationEquipmentModel3]=(CASE ISNULL(@NullOverrideDestinationEquipmentModel3,0) WHEN 1 THEN @DestinationEquipmentModel3 ELSE ISNULL(@DestinationEquipmentModel3,[DestinationEquipmentModel3]) END)
		,	[DestinationCompanyEquipmentID3]=(CASE ISNULL(@NullOverrideDestinationCompanyEquipmentID3,0) WHEN 1 THEN @DestinationCompanyEquipmentID3 ELSE ISNULL(@DestinationCompanyEquipmentID3,[DestinationCompanyEquipmentID3]) END)
		,	[SourceRegistrationID1]=(CASE ISNULL(@NullOverrideSourceRegistrationID1,0) WHEN 1 THEN @SourceRegistrationID1 ELSE ISNULL(@SourceRegistrationID1,[SourceRegistrationID1]) END)
		,	[SourceSerialNumber1]=(CASE ISNULL(@NullOverrideSourceSerialNumber1,0) WHEN 1 THEN @SourceSerialNumber1 ELSE ISNULL(@SourceSerialNumber1,[SourceSerialNumber1]) END)
		,	[SourceEquipmentType1]=(CASE ISNULL(@NullOverrideSourceEquipmentType1,0) WHEN 1 THEN @SourceEquipmentType1 ELSE ISNULL(@SourceEquipmentType1,[SourceEquipmentType1]) END)
		,	[SourceEquipmentModel1]=(CASE ISNULL(@NullOverrideSourceEquipmentModel1,0) WHEN 1 THEN @SourceEquipmentModel1 ELSE ISNULL(@SourceEquipmentModel1,[SourceEquipmentModel1]) END)
		,	[SourceCompanyEquipmentID1]=(CASE ISNULL(@NullOverrideSourceCompanyEquipmentID1,0) WHEN 1 THEN @SourceCompanyEquipmentID1 ELSE ISNULL(@SourceCompanyEquipmentID1,[SourceCompanyEquipmentID1]) END)
		,	[SourceRegistrationID2]=(CASE ISNULL(@NullOverrideSourceRegistrationID2,0) WHEN 1 THEN @SourceRegistrationID2 ELSE ISNULL(@SourceRegistrationID2,[SourceRegistrationID2]) END)
		,	[SourceSerialNumber2]=(CASE ISNULL(@NullOverrideSourceSerialNumber2,0) WHEN 1 THEN @SourceSerialNumber2 ELSE ISNULL(@SourceSerialNumber2,[SourceSerialNumber2]) END)
		,	[SourceEquipmentType2]=(CASE ISNULL(@NullOverrideSourceEquipmentType2,0) WHEN 1 THEN @SourceEquipmentType2 ELSE ISNULL(@SourceEquipmentType2,[SourceEquipmentType2]) END)
		,	[SourceEquipmentModel2]=(CASE ISNULL(@NullOverrideSourceEquipmentModel2,0) WHEN 1 THEN @SourceEquipmentModel2 ELSE ISNULL(@SourceEquipmentModel2,[SourceEquipmentModel2]) END)
		,	[SourceCompanyEquipmentID2]=(CASE ISNULL(@NullOverrideSourceCompanyEquipmentID2,0) WHEN 1 THEN @SourceCompanyEquipmentID2 ELSE ISNULL(@SourceCompanyEquipmentID2,[SourceCompanyEquipmentID2]) END)
		,	[SourceRegistrationID3]=(CASE ISNULL(@NullOverrideSourceRegistrationID3,0) WHEN 1 THEN @SourceRegistrationID3 ELSE ISNULL(@SourceRegistrationID3,[SourceRegistrationID3]) END)
		,	[SourceSerialNumber3]=(CASE ISNULL(@NullOverrideSourceSerialNumber3,0) WHEN 1 THEN @SourceSerialNumber3 ELSE ISNULL(@SourceSerialNumber3,[SourceSerialNumber3]) END)
		,	[SourceEquipmentType3]=(CASE ISNULL(@NullOverrideSourceEquipmentType3,0) WHEN 1 THEN @SourceEquipmentType3 ELSE ISNULL(@SourceEquipmentType3,[SourceEquipmentType3]) END)
		,	[SourceEquipmentModel3]=(CASE ISNULL(@NullOverrideSourceEquipmentModel3,0) WHEN 1 THEN @SourceEquipmentModel3 ELSE ISNULL(@SourceEquipmentModel3,[SourceEquipmentModel3]) END)
		,	[SourceCompanyEquipmentID3]=(CASE ISNULL(@NullOverrideSourceCompanyEquipmentID3,0) WHEN 1 THEN @SourceCompanyEquipmentID3 ELSE ISNULL(@SourceCompanyEquipmentID3,[SourceCompanyEquipmentID3]) END)
		,	[OperatorID]=(CASE ISNULL(@NullOverrideOperatorID,0) WHEN 1 THEN @OperatorID ELSE ISNULL(@OperatorID,[OperatorID]) END)
		,	[EffectiveDate]=(CASE ISNULL(@NullOverrideEffectiveDate,0) WHEN 1 THEN @EffectiveDate ELSE ISNULL(@EffectiveDate,[EffectiveDate]) END)
		,	[ExpirationDate]=(CASE ISNULL(@NullOverrideExpirationDate,0) WHEN 1 THEN @ExpirationDate ELSE ISNULL(@ExpirationDate,[ExpirationDate]) END)
		,	[ScheduledDate]=(CASE ISNULL(@NullOverrideScheduledDate,0) WHEN 1 THEN @ScheduledDate ELSE ISNULL(@ScheduledDate,[ScheduledDate]) END)
		,	[AutoComplete]=(CASE ISNULL(@NullOverrideAutoComplete,0) WHEN 1 THEN @AutoComplete ELSE ISNULL(@AutoComplete,[AutoComplete]) END)
		,	[Flag01]=(CASE ISNULL(@NullOverrideFlag01,0) WHEN 1 THEN @Flag01 ELSE ISNULL(@Flag01,[Flag01]) END)
		,	[Flag02]=(CASE ISNULL(@NullOverrideFlag02,0) WHEN 1 THEN @Flag02 ELSE ISNULL(@Flag02,[Flag02]) END)
		,	[Flag03]=(CASE ISNULL(@NullOverrideFlag03,0) WHEN 1 THEN @Flag03 ELSE ISNULL(@Flag03,[Flag03]) END)
		,	[Flag04]=(CASE ISNULL(@NullOverrideFlag04,0) WHEN 1 THEN @Flag04 ELSE ISNULL(@Flag04,[Flag04]) END)
		,	[Flag05]=(CASE ISNULL(@NullOverrideFlag05,0) WHEN 1 THEN @Flag05 ELSE ISNULL(@Flag05,[Flag05]) END)
		,	[Flag06]=(CASE ISNULL(@NullOverrideFlag06,0) WHEN 1 THEN @Flag06 ELSE ISNULL(@Flag06,[Flag06]) END)
		,	[Number01]=(CASE ISNULL(@NullOverrideNumber01,0) WHEN 1 THEN @Number01 ELSE ISNULL(@Number01,[Number01]) END)
		,	[Number02]=(CASE ISNULL(@NullOverrideNumber02,0) WHEN 1 THEN @Number02 ELSE ISNULL(@Number02,[Number02]) END)
		,	[Number03]=(CASE ISNULL(@NullOverrideNumber03,0) WHEN 1 THEN @Number03 ELSE ISNULL(@Number03,[Number03]) END)
		,	[Number04]=(CASE ISNULL(@NullOverrideNumber04,0) WHEN 1 THEN @Number04 ELSE ISNULL(@Number04,[Number04]) END)
		,	[Number05]=(CASE ISNULL(@NullOverrideNumber05,0) WHEN 1 THEN @Number05 ELSE ISNULL(@Number05,[Number05]) END)
		,	[Number06]=(CASE ISNULL(@NullOverrideNumber06,0) WHEN 1 THEN @Number06 ELSE ISNULL(@Number06,[Number06]) END)
		,	[ContactFirstName]=(CASE ISNULL(@NullOverrideContactFirstName,0) WHEN 1 THEN @ContactFirstName ELSE ISNULL(@ContactFirstName,[ContactFirstName]) END)
		,	[ContactSurname]=(CASE ISNULL(@NullOverrideContactSurname,0) WHEN 1 THEN @ContactSurname ELSE ISNULL(@ContactSurname,[ContactSurname]) END)
		,	[Date01]=(CASE ISNULL(@NullOverrideDate01,0) WHEN 1 THEN @Date01 ELSE ISNULL(@Date01,[Date01]) END)
		,	[Date02]=(CASE ISNULL(@NullOverrideDate02,0) WHEN 1 THEN @Date02 ELSE ISNULL(@Date02,[Date02]) END)
		,	[Date03]=(CASE ISNULL(@NullOverrideDate03,0) WHEN 1 THEN @Date03 ELSE ISNULL(@Date03,[Date03]) END)
		,	[Date04]=(CASE ISNULL(@NullOverrideDate04,0) WHEN 1 THEN @Date04 ELSE ISNULL(@Date04,[Date04]) END)
		,	[LegacyNumber]=(CASE ISNULL(@NullOverrideLegacyNumber,0) WHEN 1 THEN @LegacyNumber ELSE ISNULL(@LegacyNumber,[LegacyNumber]) END)
		,	[Country]=(CASE ISNULL(@NullOverrideCountry,0) WHEN 1 THEN @Country ELSE ISNULL(@Country,[Country]) END)
		,	[ContactInfo]=(CASE ISNULL(@NullOverrideContactInfo,0) WHEN 1 THEN @ContactInfo ELSE ISNULL(@ContactInfo,[ContactInfo]) END)
		,	[AssociatedDocNumber]=(CASE ISNULL(@NullOverrideAssociatedDocNumber,0) WHEN 1 THEN @AssociatedDocNumber ELSE ISNULL(@AssociatedDocNumber,[AssociatedDocNumber]) END)
		,	[AssociatedCLIN]=(CASE ISNULL(@NullOverrideAssociatedCLIN,0) WHEN 1 THEN @AssociatedCLIN ELSE ISNULL(@AssociatedCLIN,[AssociatedCLIN]) END)
		,	[SubmittedToAccounting]=(CASE ISNULL(@NullOverrideSubmittedToAccounting,0) WHEN 1 THEN @SubmittedToAccounting ELSE ISNULL(@SubmittedToAccounting,[SubmittedToAccounting]) END)
		,	[FuelCardID]=(CASE ISNULL(@NullOverrideFuelCardID,0) WHEN 1 THEN @FuelCardID ELSE ISNULL(@FuelCardID,[FuelCardID]) END)
		,	[AssociatedTransportOrderNumber]=(CASE ISNULL(@NullOverrideAssociatedTransportOrderNumber,0) WHEN 1 THEN @AssociatedTransportOrderNumber ELSE ISNULL(@AssociatedTransportOrderNumber,[AssociatedTransportOrderNumber]) END)
		,	[RequestedDateTime]=(CASE ISNULL(@NullOverrideRequestedDateTime,0) WHEN 1 THEN @RequestedDateTime ELSE ISNULL(@RequestedDateTime,[RequestedDateTime]) END)
		,	[DispatchedDateTime]=(CASE ISNULL(@NullOverrideDispatchedDateTime,0) WHEN 1 THEN @DispatchedDateTime ELSE ISNULL(@DispatchedDateTime,[DispatchedDateTime]) END)
		,	[ErrorFlag]=(CASE ISNULL(@NullOverrideErrorFlag,0) WHEN 1 THEN @ErrorFlag ELSE ISNULL(@ErrorFlag,[ErrorFlag]) END)
		,	[SiteGuid]=(CASE ISNULL(@NullOverrideSiteGuid,0) WHEN 1 THEN @SiteGuid ELSE ISNULL(@SiteGuid,[SiteGuid]) END)
		,	[LookupTransTypeIndex]=(CASE ISNULL(@NullOverrideLookupTransTypeIndex,0) WHEN 1 THEN @LookupTransTypeIndex ELSE ISNULL(@LookupTransTypeIndex,[LookupTransTypeIndex]) END)
		,	[LookupTransactionStatusIndex]=(CASE ISNULL(@NullOverrideLookupTransactionStatusIndex,0) WHEN 1 THEN @LookupTransactionStatusIndex ELSE ISNULL(@LookupTransactionStatusIndex,[LookupTransactionStatusIndex]) END)
		,	[LookupOriginApplicationIndex]=(CASE ISNULL(@NullOverrideLookupOriginApplicationIndex,0) WHEN 1 THEN @LookupOriginApplicationIndex ELSE ISNULL(@LookupOriginApplicationIndex,[LookupOriginApplicationIndex]) END)
		,	[TransactionAliasGuid]=(CASE ISNULL(@NullOverrideTransactionAliasGuid,0) WHEN 1 THEN @TransactionAliasGuid ELSE ISNULL(@TransactionAliasGuid,[TransactionAliasGuid]) END)
		,	[BillToCompanyGuid]=(CASE ISNULL(@NullOverrideBillToCompanyGuid,0) WHEN 1 THEN @BillToCompanyGuid ELSE ISNULL(@BillToCompanyGuid,[BillToCompanyGuid]) END)
		,	[Destination1EquipmentGuid]=(CASE ISNULL(@NullOverrideDestination1EquipmentGuid,0) WHEN 1 THEN @Destination1EquipmentGuid ELSE ISNULL(@Destination1EquipmentGuid,[Destination1EquipmentGuid]) END)
		,	[Destination2EquipmentGuid]=(CASE ISNULL(@NullOverrideDestination2EquipmentGuid,0) WHEN 1 THEN @Destination2EquipmentGuid ELSE ISNULL(@Destination2EquipmentGuid,[Destination2EquipmentGuid]) END)
		,	[Destination3EquipmentGuid]=(CASE ISNULL(@NullOverrideDestination3EquipmentGuid,0) WHEN 1 THEN @Destination3EquipmentGuid ELSE ISNULL(@Destination3EquipmentGuid,[Destination3EquipmentGuid]) END)
		,	[FinalStationIATAGuid]=(CASE ISNULL(@NullOverrideFinalStationIATAGuid,0) WHEN 1 THEN @FinalStationIATAGuid ELSE ISNULL(@FinalStationIATAGuid,[FinalStationIATAGuid]) END)
		,	[FuelCardGuid]=(CASE ISNULL(@NullOverrideFuelCardGuid,0) WHEN 1 THEN @FuelCardGuid ELSE ISNULL(@FuelCardGuid,[FuelCardGuid]) END)
		,	[ManagerCompanyGuid]=(CASE ISNULL(@NullOverrideManagerCompanyGuid,0) WHEN 1 THEN @ManagerCompanyGuid ELSE ISNULL(@ManagerCompanyGuid,[ManagerCompanyGuid]) END)
		,	[NextStationIATAGuid]=(CASE ISNULL(@NullOverrideNextStationIATAGuid,0) WHEN 1 THEN @NextStationIATAGuid ELSE ISNULL(@NextStationIATAGuid,[NextStationIATAGuid]) END)
		,	[OperatorPersonnelGuid]=(CASE ISNULL(@NullOverrideOperatorPersonnelGuid,0) WHEN 1 THEN @OperatorPersonnelGuid ELSE ISNULL(@OperatorPersonnelGuid,[OperatorPersonnelGuid]) END)
		,	[OriginStationIATAGuid]=(CASE ISNULL(@NullOverrideOriginStationIATAGuid,0) WHEN 1 THEN @OriginStationIATAGuid ELSE ISNULL(@OriginStationIATAGuid,[OriginStationIATAGuid]) END)
		,	[OwnerCompanyGuid]=(CASE ISNULL(@NullOverrideOwnerCompanyGuid,0) WHEN 1 THEN @OwnerCompanyGuid ELSE ISNULL(@OwnerCompanyGuid,[OwnerCompanyGuid]) END)
		,	[PreviousStationIATAGuid]=(CASE ISNULL(@NullOverridePreviousStationIATAGuid,0) WHEN 1 THEN @PreviousStationIATAGuid ELSE ISNULL(@PreviousStationIATAGuid,[PreviousStationIATAGuid]) END)
		,	[ShipperCompanyGuid]=(CASE ISNULL(@NullOverrideShipperCompanyGuid,0) WHEN 1 THEN @ShipperCompanyGuid ELSE ISNULL(@ShipperCompanyGuid,[ShipperCompanyGuid]) END)
		,	[ShipToCompanyGuid]=(CASE ISNULL(@NullOverrideShipToCompanyGuid,0) WHEN 1 THEN @ShipToCompanyGuid ELSE ISNULL(@ShipToCompanyGuid,[ShipToCompanyGuid]) END)
		,	[Source1EquipmentGuid]=(CASE ISNULL(@NullOverrideSource1EquipmentGuid,0) WHEN 1 THEN @Source1EquipmentGuid ELSE ISNULL(@Source1EquipmentGuid,[Source1EquipmentGuid]) END)
		,	[Source2EquipmentGuid]=(CASE ISNULL(@NullOverrideSource2EquipmentGuid,0) WHEN 1 THEN @Source2EquipmentGuid ELSE ISNULL(@Source2EquipmentGuid,[Source2EquipmentGuid]) END)
		,	[Source3EquipmentGuid]=(CASE ISNULL(@NullOverrideSource3EquipmentGuid,0) WHEN 1 THEN @Source3EquipmentGuid ELSE ISNULL(@Source3EquipmentGuid,[Source3EquipmentGuid]) END)
		,	[SupplierCompanyGuid]=(CASE ISNULL(@NullOverrideSupplierCompanyGuid,0) WHEN 1 THEN @SupplierCompanyGuid ELSE ISNULL(@SupplierCompanyGuid,[SupplierCompanyGuid]) END)
		,	[CarrierCompanyGuid]=(CASE ISNULL(@NullOverrideCarrierCompanyGuid,0) WHEN 1 THEN @CarrierCompanyGuid ELSE ISNULL(@CarrierCompanyGuid,[CarrierCompanyGuid]) END)
		,	[ReasonCodeGuid]=(CASE ISNULL(@NullOverrideReasonCodeGuid,0) WHEN 1 THEN @ReasonCodeGuid ELSE ISNULL(@ReasonCodeGuid,[ReasonCodeGuid]) END)
		,	[OriginStationIATAID]=(CASE ISNULL(@NullOverrideOriginStationIATAID,0) WHEN 1 THEN @OriginStationIATAID ELSE ISNULL(@OriginStationIATAID,[OriginStationIATAID]) END)
		,	[PreviousStationIATAID]=(CASE ISNULL(@NullOverridePreviousStationIATAID,0) WHEN 1 THEN @PreviousStationIATAID ELSE ISNULL(@PreviousStationIATAID,[PreviousStationIATAID]) END)
		,	[NextStationIATAID]=(CASE ISNULL(@NullOverrideNextStationIATAID,0) WHEN 1 THEN @NextStationIATAID ELSE ISNULL(@NextStationIATAID,[NextStationIATAID]) END)
		,	[FinalStationIATAID]=(CASE ISNULL(@NullOverrideFinalStationIATAID,0) WHEN 1 THEN @FinalStationIATAID ELSE ISNULL(@FinalStationIATAID,[FinalStationIATAID]) END)
		,	[OperatorName]=(CASE ISNULL(@NullOverrideOperatorName,0) WHEN 1 THEN @OperatorName ELSE ISNULL(@OperatorName,[OperatorName]) END)
		,	[FuelAdditiveFlag]=(CASE ISNULL(@NullOverrideFuelAdditiveFlag,0) WHEN 1 THEN @FuelAdditiveFlag ELSE ISNULL(@FuelAdditiveFlag,[FuelAdditiveFlag]) END)
		,	[IssuePoint]=(CASE ISNULL(@NullOverrideIssuePoint,0) WHEN 1 THEN @IssuePoint ELSE ISNULL(@IssuePoint,[IssuePoint]) END)
		,	[IssuePointNumber]=(CASE ISNULL(@NullOverrideIssuePointNumber,0) WHEN 1 THEN @IssuePointNumber ELSE ISNULL(@IssuePointNumber,[IssuePointNumber]) END)
		,	[RadioNumber]=(CASE ISNULL(@NullOverrideRadioNumber,0) WHEN 1 THEN @RadioNumber ELSE ISNULL(@RadioNumber,[RadioNumber]) END)
		,	[GateID]=(CASE ISNULL(@NullOverrideGateID,0) WHEN 1 THEN @GateID ELSE ISNULL(@GateID,[GateID]) END)
		,	[GateGuid]=(CASE ISNULL(@NullOverrideGateGuid,0) WHEN 1 THEN @GateGuid ELSE ISNULL(@GateGuid,[GateGuid]) END)
		WHERE	TransactionGuid=@TransactionGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblTransactions]           
		WHERE TransactionGuid=@TransactionGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_TransactionsUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
