CREATE PROCEDURE [dbo].[gsp_SitesUpdateByPK]
(
		@SiteGuid uniqueidentifier
	,	@ID nvarchar(30)=NULL
	,	@Number nvarchar(30)=NULL
	,	@SPLCCode nvarchar(30)=NULL
	,	@Address1 nvarchar(30)=NULL
	,	@Address2 nvarchar(30)=NULL
	,	@City nvarchar(60)=NULL
	,	@State nvarchar(20)=NULL
	,	@Zip nvarchar(11)=NULL
	,	@Country nvarchar(30)=NULL
	,	@Phone nvarchar(20)=NULL
	,	@FAX nvarchar(20)=NULL
	,	@EmailAddress nvarchar(30)=NULL
	,	@EmergencyContact nvarchar(30)=NULL
	,	@EmergencyPhone nvarchar(20)=NULL
	,	@Enabled bit=NULL
	,	@SiteGroupFlag bit=NULL
	,	@TimeZone nvarchar(50)=NULL
	,	@LevelUnitIndex int=NULL
	,	@TemperatureUnitIndex int=NULL
	,	@DensityUnitIndex int=NULL
	,	@PressureUnitIndex int=NULL
	,	@FlowUnitIndex int=NULL
	,	@VolumeUnitIndex int=NULL
	,	@MassUnitIndex int=NULL
	,	@AdditiveVolumeUnitIndex int=NULL
	,	@AdditiveProfileCycleAmountUnitIndex int=NULL
	,	@AdditiveProfileRateUnitIndex int=NULL
	,	@LevelDecimalPlaces tinyint=NULL
	,	@TemperatureDecimalPlaces tinyint=NULL
	,	@DensityDecimalPlaces tinyint=NULL
	,	@PressureDecimalPlaces tinyint=NULL
	,	@FlowDecimalPlaces tinyint=NULL
	,	@VolumeDecimalPlaces tinyint=NULL
	,	@MassDecimalPlaces tinyint=NULL
	,	@AdditiveVolumeDecimalPlaces tinyint=NULL
	,	@AdditiveProfileCycleAmountDecimalPlaces tinyint=NULL
	,	@AdditiveProfileRateDecimalPlaces tinyint=NULL
	,	@InhibitAccessAfterHours bit=NULL
	,	@InhibitMultipleCardIns bit=NULL
	,	@AccessCardInRequired bit=NULL
	,	@CheckSiteNumber bit=NULL
	,	@PromptForCustomerCard bit=NULL
	,	@PromptForTractorOrTanker bit=NULL
	,	@PromptForFirstTrailer bit=NULL
	,	@PromptForSecondTrailer bit=NULL
	,	@PromptForCompartment bit=NULL
	,	@EnforceDriverEquipmentMatch bit=NULL
	,	@EnableAdditiveAccounting bit=NULL
	,	@UseCompanyEquipmentIdentifiers bit=NULL
	,	@UseLastKnownGoodTankData bit=NULL
	,	@MaximumLoadAmount float=NULL
	,	@MaximumLoadTime int=NULL
	,	@MaximumIdleTime int=NULL
	,	@MaximumFlushAmount float=NULL
	,	@MaximumMeterProvingAmount float=NULL
	,	@MaximumReturnsAmount float=NULL
	,	@MaximumNumberOfActiveArms int=NULL
	,	@DriverTimeoutPeriod int=NULL
	,	@DriverWarningPeriod int=NULL
	,	@MaximumPrompts int=NULL
	,	@MaximumVehicleWeight float=NULL
	,	@LoadByNet bit=NULL
	,	@PromptForShipmentNumber bit=NULL
	,	@MaximumProductTemperature float=NULL
	,	@ListEquipment bit=NULL
	,	@DeferStationChanges bit=NULL
	,	@InhibitBOLWithBrokenBlends bit=NULL
	,	@InhibitBOLWithImproperAdditization bit=NULL
	,	@InhibitOverweightBOL bit=NULL
	,	@ExceptionBOLPrinter nvarchar(80)=NULL
	,	@EnableAutomaticBOLPrinting bit=NULL
	,	@AutomaticBOLStartNumber int=NULL
	,	@AutomaticBOLEndNumber int=NULL
	,	@AutomaticBOLNextNumber int=NULL
	,	@SeparateManualBOLNumbering bit=NULL
	,	@ManualBOLStartNumber int=NULL
	,	@ManualBOLEndNumber int=NULL
	,	@ManualBOLNextNumber int=NULL
	,	@TransactionStartNumber int=NULL
	,	@TransactionEndNumber int=NULL
	,	@TransactionNextNumber int=NULL
	,	@OrderStartNumber int=NULL
	,	@OrderEndNumber int=NULL
	,	@OrderNextNumber int=NULL
	,	@NumberPrefix nvarchar(10)=NULL
	,	@OpenTransactionWindow int=NULL
	,	@AdministrativeLockDate datetimeoffset(7)=NULL
	,	@OperationalLockDate datetimeoffset(7)=NULL
	,	@MaximumDaysToRetainLogs int=NULL
	,	@EnableDebugLogging bit=NULL
	,	@EnableAuditLogging bit=NULL
	,	@AutomaticallyPrintAlarmsAndEvents bit=NULL
	,	@AlarmAndEventPrinter nvarchar(80)=NULL
	,	@MailServer nvarchar(50)=NULL
	,	@MailFrom nvarchar(50)=NULL
	,	@MailUserName nvarchar(50)=NULL
	,	@MailPassword nvarchar(50)=NULL
	,	@DialupName nvarchar(50)=NULL
	,	@SCADASystem nvarchar(50)=NULL
	,	@InhibitTemplateGraphics bit=NULL
	,	@RefreshInterval int=NULL
	,	@InhibitEndOfDayOperations bit=NULL
	,	@InhibitEndOfMonthOperations bit=NULL
	,	@EndOfDayWarningPeriod int=NULL
	,	@InhibitAutomaticPhysicalInventory bit=NULL
	,	@InhibitAutomaticMeterCloseout bit=NULL
	,	@InhibitAutomaticReportGeneration bit=NULL
	,	@InhibitAutomaticAdjustmentDistribution bit=NULL
	,	@InhibitAutomaticCloseout bit=NULL
	,	@InhibitTankScan bit=NULL
	,	@ReportDirectory nvarchar(80)=NULL
	,	@ManageReports bit=NULL
	,	@ManagedReportDirectory nvarchar(80)=NULL
	,	@VRURateLimit float=NULL
	,	@VRUHourlyLimit float=NULL
	,	@VRUDailyLimit float=NULL
	,	@VRUYearlyLimit float=NULL
	,	@VRUCurrentYearLimit float=NULL
	,	@VRURateActual float=NULL
	,	@VRUHourlyActual float=NULL
	,	@VRUDailyActual float=NULL
	,	@VRUYearlyActual float=NULL
	,	@VRUCurrentYearActual float=NULL
	,	@VRURateLimitEnabled bit=NULL
	,	@VRUHourlyLimitEnabled bit=NULL
	,	@VRUDailyLimitEnabled bit=NULL
	,	@VRUYearlyLimitEnabled bit=NULL
	,	@VRUCurrentYearLimitEnabled bit=NULL
	,	@WatchdogPeriod int=NULL
	,	@WatchdogCounterStart int=NULL
	,	@WatchdogCounterEnd int=NULL
	,	@NumberDecimalSeparator nvarchar(1)=NULL
	,	@NumberGroupSeparator nvarchar(1)=NULL
	,	@ListSeparator nvarchar(1)=NULL
	,	@TimePattern nvarchar(20)=NULL
	,	@TimeSeparator nvarchar(1)=NULL
	,	@AMSymbol nvarchar(2)=NULL
	,	@PMSymbol nvarchar(2)=NULL
	,	@ShortDatePattern nvarchar(20)=NULL
	,	@DateSeparator nvarchar(1)=NULL
	,	@LongDatePattern nvarchar(30)=NULL
	,	@TwoDigitCalendarEndYear int=NULL
	,	@UserData1 nvarchar(60)=NULL
	,	@UserData2 nvarchar(60)=NULL
	,	@UserData3 nvarchar(60)=NULL
	,	@UserData4 nvarchar(60)=NULL
	,	@UserData5 nvarchar(60)=NULL
	,	@UserData6 nvarchar(60)=NULL
	,	@UserData7 nvarchar(60)=NULL
	,	@UserData8 nvarchar(60)=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@MinTimeAllowedToChangePwd int=NULL
	,	@MinPwdCharacterLength int=NULL
	,	@PwdExpirationInDays int=NULL
	,	@PwdLockoutThreshold int=NULL
	,	@CheckForPreviousPwd bit=NULL
	,	@StrongPwdUse int=NULL
	,	@PwdHistoryCount int=NULL
	,	@ApplyToAllSiteMembers bit=NULL
	,	@InactivityDisablePeriod int=NULL
	,	@EnforceSingleOwner bit=NULL
	,	@InhibitBOLSummaryAutoPopulate bit=NULL
	,	@InhibitOrderSummaryAutoPopulate bit=NULL
	,	@InhibitSupplyOrderSummaryAutoPopulate bit=NULL
	,	@InvoiceStartNumber int=NULL
	,	@InvoiceEndNumber int=NULL
	,	@InvoiceNextNumber int=NULL
	,	@PromptForReturns bit=NULL
	,	@PromptForTruckCard bit=NULL
	,	@StartingShortCardNumber int=NULL
	,	@UseShortCardNumber bit=NULL
	,	@ExcessVarianceCount tinyint=NULL
	,	@ExcessVarianceTolerance float=NULL
	,	@DisableArchivePeriod int=NULL
	,	@ExportArchiveDir nvarchar(255)=NULL
	,	@ImportArchiveDir nvarchar(255)=NULL
	,	@GroupLedgerByID bit=NULL
	,	@InhibitSiteLedgerRollup bit=NULL
	,	@UseTankReconciliation bit=NULL
	,	@LookupNumberGroupSizesTypeIndex int=NULL
	,	@LookupQuantityDisplayDefaultIndex tinyint=NULL
	,	@LookupSecondaryStorageFillMethodIndex tinyint=NULL
	,	@LookupMailConnectModeIndex tinyint=NULL
	,	@LookupWatchdogModeIndex tinyint=NULL
	,	@Contact1Name nvarchar(30)=NULL
	,	@Contact1Address1 nvarchar(30)=NULL
	,	@Contact1Address2 nvarchar(30)=NULL
	,	@Contact1City nvarchar(60)=NULL
	,	@Contact1State nvarchar(20)=NULL
	,	@Contact1Zip nvarchar(11)=NULL
	,	@Contact1Country nvarchar(30)=NULL
	,	@Contact1PhoneOffice nvarchar(20)=NULL
	,	@Contact1Fax nvarchar(20)=NULL
	,	@Contact1EmailAddress nvarchar(30)=NULL
	,	@Contact2Name nvarchar(30)=NULL
	,	@Contact2Address1 nvarchar(30)=NULL
	,	@Contact2Address2 nvarchar(30)=NULL
	,	@Contact2City nvarchar(60)=NULL
	,	@Contact2State nvarchar(20)=NULL
	,	@Contact2Zip nvarchar(11)=NULL
	,	@Contact2Country nvarchar(30)=NULL
	,	@Contact2PhoneOffice nvarchar(20)=NULL
	,	@Contact2Fax nvarchar(20)=NULL
	,	@Contact2EmailAddress nvarchar(30)=NULL
	,	@Contact1PhoneMobile nvarchar(20)=NULL
	,	@Contact2PhoneMobile nvarchar(20)=NULL
	,	@EnablePasswordHint bit=NULL
	,	@EnablePasswordReset bit=NULL
	,	@MeterReconciliationToleranceIsPercent bit=NULL
	,	@MeterReconciliationReportName nvarchar(60)=NULL
	,	@TranslatedHelpURL nvarchar(250)=NULL
	,	@AllowUseOfSpecialChars bit=NULL
	,	@EnablePeriodicSyncFlag bit=NULL
	,	@PeriodicSyncIntervalMinutes int=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideID BIT=0 
	,	@NullOverrideNumber BIT=0 
	,	@NullOverrideSPLCCode BIT=0 
	,	@NullOverrideAddress1 BIT=0 
	,	@NullOverrideAddress2 BIT=0 
	,	@NullOverrideCity BIT=0 
	,	@NullOverrideState BIT=0 
	,	@NullOverrideZip BIT=0 
	,	@NullOverrideCountry BIT=0 
	,	@NullOverridePhone BIT=0 
	,	@NullOverrideFAX BIT=0 
	,	@NullOverrideEmailAddress BIT=0 
	,	@NullOverrideEmergencyContact BIT=0 
	,	@NullOverrideEmergencyPhone BIT=0 
	,	@NullOverrideEnabled BIT=0 
	,	@NullOverrideSiteGroupFlag BIT=0 
	,	@NullOverrideTimeZone BIT=0 
	,	@NullOverrideLevelUnitIndex BIT=0 
	,	@NullOverrideTemperatureUnitIndex BIT=0 
	,	@NullOverrideDensityUnitIndex BIT=0 
	,	@NullOverridePressureUnitIndex BIT=0 
	,	@NullOverrideFlowUnitIndex BIT=0 
	,	@NullOverrideVolumeUnitIndex BIT=0 
	,	@NullOverrideMassUnitIndex BIT=0 
	,	@NullOverrideAdditiveVolumeUnitIndex BIT=0 
	,	@NullOverrideAdditiveProfileCycleAmountUnitIndex BIT=0 
	,	@NullOverrideAdditiveProfileRateUnitIndex BIT=0 
	,	@NullOverrideLevelDecimalPlaces BIT=0 
	,	@NullOverrideTemperatureDecimalPlaces BIT=0 
	,	@NullOverrideDensityDecimalPlaces BIT=0 
	,	@NullOverridePressureDecimalPlaces BIT=0 
	,	@NullOverrideFlowDecimalPlaces BIT=0 
	,	@NullOverrideVolumeDecimalPlaces BIT=0 
	,	@NullOverrideMassDecimalPlaces BIT=0 
	,	@NullOverrideAdditiveVolumeDecimalPlaces BIT=0 
	,	@NullOverrideAdditiveProfileCycleAmountDecimalPlaces BIT=0 
	,	@NullOverrideAdditiveProfileRateDecimalPlaces BIT=0 
	,	@NullOverrideInhibitAccessAfterHours BIT=0 
	,	@NullOverrideInhibitMultipleCardIns BIT=0 
	,	@NullOverrideAccessCardInRequired BIT=0 
	,	@NullOverrideCheckSiteNumber BIT=0 
	,	@NullOverridePromptForCustomerCard BIT=0 
	,	@NullOverridePromptForTractorOrTanker BIT=0 
	,	@NullOverridePromptForFirstTrailer BIT=0 
	,	@NullOverridePromptForSecondTrailer BIT=0 
	,	@NullOverridePromptForCompartment BIT=0 
	,	@NullOverrideEnforceDriverEquipmentMatch BIT=0 
	,	@NullOverrideEnableAdditiveAccounting BIT=0 
	,	@NullOverrideUseCompanyEquipmentIdentifiers BIT=0 
	,	@NullOverrideUseLastKnownGoodTankData BIT=0 
	,	@NullOverrideMaximumLoadAmount BIT=0 
	,	@NullOverrideMaximumLoadTime BIT=0 
	,	@NullOverrideMaximumIdleTime BIT=0 
	,	@NullOverrideMaximumFlushAmount BIT=0 
	,	@NullOverrideMaximumMeterProvingAmount BIT=0 
	,	@NullOverrideMaximumReturnsAmount BIT=0 
	,	@NullOverrideMaximumNumberOfActiveArms BIT=0 
	,	@NullOverrideDriverTimeoutPeriod BIT=0 
	,	@NullOverrideDriverWarningPeriod BIT=0 
	,	@NullOverrideMaximumPrompts BIT=0 
	,	@NullOverrideMaximumVehicleWeight BIT=0 
	,	@NullOverrideLoadByNet BIT=0 
	,	@NullOverridePromptForShipmentNumber BIT=0 
	,	@NullOverrideMaximumProductTemperature BIT=0 
	,	@NullOverrideListEquipment BIT=0 
	,	@NullOverrideDeferStationChanges BIT=0 
	,	@NullOverrideInhibitBOLWithBrokenBlends BIT=0 
	,	@NullOverrideInhibitBOLWithImproperAdditization BIT=0 
	,	@NullOverrideInhibitOverweightBOL BIT=0 
	,	@NullOverrideExceptionBOLPrinter BIT=0 
	,	@NullOverrideEnableAutomaticBOLPrinting BIT=0 
	,	@NullOverrideAutomaticBOLStartNumber BIT=0 
	,	@NullOverrideAutomaticBOLEndNumber BIT=0 
	,	@NullOverrideAutomaticBOLNextNumber BIT=0 
	,	@NullOverrideSeparateManualBOLNumbering BIT=0 
	,	@NullOverrideManualBOLStartNumber BIT=0 
	,	@NullOverrideManualBOLEndNumber BIT=0 
	,	@NullOverrideManualBOLNextNumber BIT=0 
	,	@NullOverrideTransactionStartNumber BIT=0 
	,	@NullOverrideTransactionEndNumber BIT=0 
	,	@NullOverrideTransactionNextNumber BIT=0 
	,	@NullOverrideOrderStartNumber BIT=0 
	,	@NullOverrideOrderEndNumber BIT=0 
	,	@NullOverrideOrderNextNumber BIT=0 
	,	@NullOverrideNumberPrefix BIT=0 
	,	@NullOverrideOpenTransactionWindow BIT=0 
	,	@NullOverrideAdministrativeLockDate BIT=0 
	,	@NullOverrideOperationalLockDate BIT=0 
	,	@NullOverrideMaximumDaysToRetainLogs BIT=0 
	,	@NullOverrideEnableDebugLogging BIT=0 
	,	@NullOverrideEnableAuditLogging BIT=0 
	,	@NullOverrideAutomaticallyPrintAlarmsAndEvents BIT=0 
	,	@NullOverrideAlarmAndEventPrinter BIT=0 
	,	@NullOverrideMailServer BIT=0 
	,	@NullOverrideMailFrom BIT=0 
	,	@NullOverrideMailUserName BIT=0 
	,	@NullOverrideMailPassword BIT=0 
	,	@NullOverrideDialupName BIT=0 
	,	@NullOverrideSCADASystem BIT=0 
	,	@NullOverrideInhibitTemplateGraphics BIT=0 
	,	@NullOverrideRefreshInterval BIT=0 
	,	@NullOverrideInhibitEndOfDayOperations BIT=0 
	,	@NullOverrideInhibitEndOfMonthOperations BIT=0 
	,	@NullOverrideEndOfDayWarningPeriod BIT=0 
	,	@NullOverrideInhibitAutomaticPhysicalInventory BIT=0 
	,	@NullOverrideInhibitAutomaticMeterCloseout BIT=0 
	,	@NullOverrideInhibitAutomaticReportGeneration BIT=0 
	,	@NullOverrideInhibitAutomaticAdjustmentDistribution BIT=0 
	,	@NullOverrideInhibitAutomaticCloseout BIT=0 
	,	@NullOverrideInhibitTankScan BIT=0 
	,	@NullOverrideReportDirectory BIT=0 
	,	@NullOverrideManageReports BIT=0 
	,	@NullOverrideManagedReportDirectory BIT=0 
	,	@NullOverrideVRURateLimit BIT=0 
	,	@NullOverrideVRUHourlyLimit BIT=0 
	,	@NullOverrideVRUDailyLimit BIT=0 
	,	@NullOverrideVRUYearlyLimit BIT=0 
	,	@NullOverrideVRUCurrentYearLimit BIT=0 
	,	@NullOverrideVRURateActual BIT=0 
	,	@NullOverrideVRUHourlyActual BIT=0 
	,	@NullOverrideVRUDailyActual BIT=0 
	,	@NullOverrideVRUYearlyActual BIT=0 
	,	@NullOverrideVRUCurrentYearActual BIT=0 
	,	@NullOverrideVRURateLimitEnabled BIT=0 
	,	@NullOverrideVRUHourlyLimitEnabled BIT=0 
	,	@NullOverrideVRUDailyLimitEnabled BIT=0 
	,	@NullOverrideVRUYearlyLimitEnabled BIT=0 
	,	@NullOverrideVRUCurrentYearLimitEnabled BIT=0 
	,	@NullOverrideWatchdogPeriod BIT=0 
	,	@NullOverrideWatchdogCounterStart BIT=0 
	,	@NullOverrideWatchdogCounterEnd BIT=0 
	,	@NullOverrideNumberDecimalSeparator BIT=0 
	,	@NullOverrideNumberGroupSeparator BIT=0 
	,	@NullOverrideListSeparator BIT=0 
	,	@NullOverrideTimePattern BIT=0 
	,	@NullOverrideTimeSeparator BIT=0 
	,	@NullOverrideAMSymbol BIT=0 
	,	@NullOverridePMSymbol BIT=0 
	,	@NullOverrideShortDatePattern BIT=0 
	,	@NullOverrideDateSeparator BIT=0 
	,	@NullOverrideLongDatePattern BIT=0 
	,	@NullOverrideTwoDigitCalendarEndYear BIT=0 
	,	@NullOverrideUserData1 BIT=0 
	,	@NullOverrideUserData2 BIT=0 
	,	@NullOverrideUserData3 BIT=0 
	,	@NullOverrideUserData4 BIT=0 
	,	@NullOverrideUserData5 BIT=0 
	,	@NullOverrideUserData6 BIT=0 
	,	@NullOverrideUserData7 BIT=0 
	,	@NullOverrideUserData8 BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverrideMinTimeAllowedToChangePwd BIT=0 
	,	@NullOverrideMinPwdCharacterLength BIT=0 
	,	@NullOverridePwdExpirationInDays BIT=0 
	,	@NullOverridePwdLockoutThreshold BIT=0 
	,	@NullOverrideCheckForPreviousPwd BIT=0 
	,	@NullOverrideStrongPwdUse BIT=0 
	,	@NullOverridePwdHistoryCount BIT=0 
	,	@NullOverrideApplyToAllSiteMembers BIT=0 
	,	@NullOverrideInactivityDisablePeriod BIT=0 
	,	@NullOverrideEnforceSingleOwner BIT=0 
	,	@NullOverrideInhibitBOLSummaryAutoPopulate BIT=0 
	,	@NullOverrideInhibitOrderSummaryAutoPopulate BIT=0 
	,	@NullOverrideInhibitSupplyOrderSummaryAutoPopulate BIT=0 
	,	@NullOverrideInvoiceStartNumber BIT=0 
	,	@NullOverrideInvoiceEndNumber BIT=0 
	,	@NullOverrideInvoiceNextNumber BIT=0 
	,	@NullOverridePromptForReturns BIT=0 
	,	@NullOverridePromptForTruckCard BIT=0 
	,	@NullOverrideStartingShortCardNumber BIT=0 
	,	@NullOverrideUseShortCardNumber BIT=0 
	,	@NullOverrideExcessVarianceCount BIT=0 
	,	@NullOverrideExcessVarianceTolerance BIT=0 
	,	@NullOverrideDisableArchivePeriod BIT=0 
	,	@NullOverrideExportArchiveDir BIT=0 
	,	@NullOverrideImportArchiveDir BIT=0 
	,	@NullOverrideGroupLedgerByID BIT=0 
	,	@NullOverrideInhibitSiteLedgerRollup BIT=0 
	,	@NullOverrideUseTankReconciliation BIT=0 
	,	@NullOverrideLookupNumberGroupSizesTypeIndex BIT=0 
	,	@NullOverrideLookupQuantityDisplayDefaultIndex BIT=0 
	,	@NullOverrideLookupSecondaryStorageFillMethodIndex BIT=0 
	,	@NullOverrideLookupMailConnectModeIndex BIT=0 
	,	@NullOverrideLookupWatchdogModeIndex BIT=0 
	,	@NullOverrideContact1Name BIT=0 
	,	@NullOverrideContact1Address1 BIT=0 
	,	@NullOverrideContact1Address2 BIT=0 
	,	@NullOverrideContact1City BIT=0 
	,	@NullOverrideContact1State BIT=0 
	,	@NullOverrideContact1Zip BIT=0 
	,	@NullOverrideContact1Country BIT=0 
	,	@NullOverrideContact1PhoneOffice BIT=0 
	,	@NullOverrideContact1Fax BIT=0 
	,	@NullOverrideContact1EmailAddress BIT=0 
	,	@NullOverrideContact2Name BIT=0 
	,	@NullOverrideContact2Address1 BIT=0 
	,	@NullOverrideContact2Address2 BIT=0 
	,	@NullOverrideContact2City BIT=0 
	,	@NullOverrideContact2State BIT=0 
	,	@NullOverrideContact2Zip BIT=0 
	,	@NullOverrideContact2Country BIT=0 
	,	@NullOverrideContact2PhoneOffice BIT=0 
	,	@NullOverrideContact2Fax BIT=0 
	,	@NullOverrideContact2EmailAddress BIT=0 
	,	@NullOverrideContact1PhoneMobile BIT=0 
	,	@NullOverrideContact2PhoneMobile BIT=0 
	,	@NullOverrideEnablePasswordHint BIT=0 
	,	@NullOverrideEnablePasswordReset BIT=0 
	,	@NullOverrideMeterReconciliationToleranceIsPercent BIT=0 
	,	@NullOverrideMeterReconciliationReportName BIT=0 
	,	@NullOverrideTranslatedHelpURL BIT=0 
	,	@NullOverrideAllowUseOfSpecialChars BIT=0 
	,	@NullOverrideEnablePeriodicSyncFlag BIT=0 
	,	@NullOverridePeriodicSyncIntervalMinutes BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_SitesUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:29.7514223 -05:00
	-- Purpose: Update table [dbo].[tblSites]
	-- Notes:
	-- 1. @SiteGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblSites] WHERE SiteGuid=@SiteGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblSites] SET
			[ID]=(CASE ISNULL(@NullOverrideID,0) WHEN 1 THEN @ID ELSE ISNULL(@ID,[ID]) END)
		,	[Number]=(CASE ISNULL(@NullOverrideNumber,0) WHEN 1 THEN @Number ELSE ISNULL(@Number,[Number]) END)
		,	[SPLCCode]=(CASE ISNULL(@NullOverrideSPLCCode,0) WHEN 1 THEN @SPLCCode ELSE ISNULL(@SPLCCode,[SPLCCode]) END)
		,	[Address1]=(CASE ISNULL(@NullOverrideAddress1,0) WHEN 1 THEN @Address1 ELSE ISNULL(@Address1,[Address1]) END)
		,	[Address2]=(CASE ISNULL(@NullOverrideAddress2,0) WHEN 1 THEN @Address2 ELSE ISNULL(@Address2,[Address2]) END)
		,	[City]=(CASE ISNULL(@NullOverrideCity,0) WHEN 1 THEN @City ELSE ISNULL(@City,[City]) END)
		,	[State]=(CASE ISNULL(@NullOverrideState,0) WHEN 1 THEN @State ELSE ISNULL(@State,[State]) END)
		,	[Zip]=(CASE ISNULL(@NullOverrideZip,0) WHEN 1 THEN @Zip ELSE ISNULL(@Zip,[Zip]) END)
		,	[Country]=(CASE ISNULL(@NullOverrideCountry,0) WHEN 1 THEN @Country ELSE ISNULL(@Country,[Country]) END)
		,	[Phone]=(CASE ISNULL(@NullOverridePhone,0) WHEN 1 THEN @Phone ELSE ISNULL(@Phone,[Phone]) END)
		,	[FAX]=(CASE ISNULL(@NullOverrideFAX,0) WHEN 1 THEN @FAX ELSE ISNULL(@FAX,[FAX]) END)
		,	[EmailAddress]=(CASE ISNULL(@NullOverrideEmailAddress,0) WHEN 1 THEN @EmailAddress ELSE ISNULL(@EmailAddress,[EmailAddress]) END)
		,	[EmergencyContact]=(CASE ISNULL(@NullOverrideEmergencyContact,0) WHEN 1 THEN @EmergencyContact ELSE ISNULL(@EmergencyContact,[EmergencyContact]) END)
		,	[EmergencyPhone]=(CASE ISNULL(@NullOverrideEmergencyPhone,0) WHEN 1 THEN @EmergencyPhone ELSE ISNULL(@EmergencyPhone,[EmergencyPhone]) END)
		,	[Enabled]=(CASE ISNULL(@NullOverrideEnabled,0) WHEN 1 THEN @Enabled ELSE ISNULL(@Enabled,[Enabled]) END)
		,	[SiteGroupFlag]=(CASE ISNULL(@NullOverrideSiteGroupFlag,0) WHEN 1 THEN @SiteGroupFlag ELSE ISNULL(@SiteGroupFlag,[SiteGroupFlag]) END)
		,	[TimeZone]=(CASE ISNULL(@NullOverrideTimeZone,0) WHEN 1 THEN @TimeZone ELSE ISNULL(@TimeZone,[TimeZone]) END)
		,	[LevelUnitIndex]=(CASE ISNULL(@NullOverrideLevelUnitIndex,0) WHEN 1 THEN @LevelUnitIndex ELSE ISNULL(@LevelUnitIndex,[LevelUnitIndex]) END)
		,	[TemperatureUnitIndex]=(CASE ISNULL(@NullOverrideTemperatureUnitIndex,0) WHEN 1 THEN @TemperatureUnitIndex ELSE ISNULL(@TemperatureUnitIndex,[TemperatureUnitIndex]) END)
		,	[DensityUnitIndex]=(CASE ISNULL(@NullOverrideDensityUnitIndex,0) WHEN 1 THEN @DensityUnitIndex ELSE ISNULL(@DensityUnitIndex,[DensityUnitIndex]) END)
		,	[PressureUnitIndex]=(CASE ISNULL(@NullOverridePressureUnitIndex,0) WHEN 1 THEN @PressureUnitIndex ELSE ISNULL(@PressureUnitIndex,[PressureUnitIndex]) END)
		,	[FlowUnitIndex]=(CASE ISNULL(@NullOverrideFlowUnitIndex,0) WHEN 1 THEN @FlowUnitIndex ELSE ISNULL(@FlowUnitIndex,[FlowUnitIndex]) END)
		,	[VolumeUnitIndex]=(CASE ISNULL(@NullOverrideVolumeUnitIndex,0) WHEN 1 THEN @VolumeUnitIndex ELSE ISNULL(@VolumeUnitIndex,[VolumeUnitIndex]) END)
		,	[MassUnitIndex]=(CASE ISNULL(@NullOverrideMassUnitIndex,0) WHEN 1 THEN @MassUnitIndex ELSE ISNULL(@MassUnitIndex,[MassUnitIndex]) END)
		,	[AdditiveVolumeUnitIndex]=(CASE ISNULL(@NullOverrideAdditiveVolumeUnitIndex,0) WHEN 1 THEN @AdditiveVolumeUnitIndex ELSE ISNULL(@AdditiveVolumeUnitIndex,[AdditiveVolumeUnitIndex]) END)
		,	[AdditiveProfileCycleAmountUnitIndex]=(CASE ISNULL(@NullOverrideAdditiveProfileCycleAmountUnitIndex,0) WHEN 1 THEN @AdditiveProfileCycleAmountUnitIndex ELSE ISNULL(@AdditiveProfileCycleAmountUnitIndex,[AdditiveProfileCycleAmountUnitIndex]) END)
		,	[AdditiveProfileRateUnitIndex]=(CASE ISNULL(@NullOverrideAdditiveProfileRateUnitIndex,0) WHEN 1 THEN @AdditiveProfileRateUnitIndex ELSE ISNULL(@AdditiveProfileRateUnitIndex,[AdditiveProfileRateUnitIndex]) END)
		,	[LevelDecimalPlaces]=(CASE ISNULL(@NullOverrideLevelDecimalPlaces,0) WHEN 1 THEN @LevelDecimalPlaces ELSE ISNULL(@LevelDecimalPlaces,[LevelDecimalPlaces]) END)
		,	[TemperatureDecimalPlaces]=(CASE ISNULL(@NullOverrideTemperatureDecimalPlaces,0) WHEN 1 THEN @TemperatureDecimalPlaces ELSE ISNULL(@TemperatureDecimalPlaces,[TemperatureDecimalPlaces]) END)
		,	[DensityDecimalPlaces]=(CASE ISNULL(@NullOverrideDensityDecimalPlaces,0) WHEN 1 THEN @DensityDecimalPlaces ELSE ISNULL(@DensityDecimalPlaces,[DensityDecimalPlaces]) END)
		,	[PressureDecimalPlaces]=(CASE ISNULL(@NullOverridePressureDecimalPlaces,0) WHEN 1 THEN @PressureDecimalPlaces ELSE ISNULL(@PressureDecimalPlaces,[PressureDecimalPlaces]) END)
		,	[FlowDecimalPlaces]=(CASE ISNULL(@NullOverrideFlowDecimalPlaces,0) WHEN 1 THEN @FlowDecimalPlaces ELSE ISNULL(@FlowDecimalPlaces,[FlowDecimalPlaces]) END)
		,	[VolumeDecimalPlaces]=(CASE ISNULL(@NullOverrideVolumeDecimalPlaces,0) WHEN 1 THEN @VolumeDecimalPlaces ELSE ISNULL(@VolumeDecimalPlaces,[VolumeDecimalPlaces]) END)
		,	[MassDecimalPlaces]=(CASE ISNULL(@NullOverrideMassDecimalPlaces,0) WHEN 1 THEN @MassDecimalPlaces ELSE ISNULL(@MassDecimalPlaces,[MassDecimalPlaces]) END)
		,	[AdditiveVolumeDecimalPlaces]=(CASE ISNULL(@NullOverrideAdditiveVolumeDecimalPlaces,0) WHEN 1 THEN @AdditiveVolumeDecimalPlaces ELSE ISNULL(@AdditiveVolumeDecimalPlaces,[AdditiveVolumeDecimalPlaces]) END)
		,	[AdditiveProfileCycleAmountDecimalPlaces]=(CASE ISNULL(@NullOverrideAdditiveProfileCycleAmountDecimalPlaces,0) WHEN 1 THEN @AdditiveProfileCycleAmountDecimalPlaces ELSE ISNULL(@AdditiveProfileCycleAmountDecimalPlaces,[AdditiveProfileCycleAmountDecimalPlaces]) END)
		,	[AdditiveProfileRateDecimalPlaces]=(CASE ISNULL(@NullOverrideAdditiveProfileRateDecimalPlaces,0) WHEN 1 THEN @AdditiveProfileRateDecimalPlaces ELSE ISNULL(@AdditiveProfileRateDecimalPlaces,[AdditiveProfileRateDecimalPlaces]) END)
		,	[InhibitAccessAfterHours]=(CASE ISNULL(@NullOverrideInhibitAccessAfterHours,0) WHEN 1 THEN @InhibitAccessAfterHours ELSE ISNULL(@InhibitAccessAfterHours,[InhibitAccessAfterHours]) END)
		,	[InhibitMultipleCardIns]=(CASE ISNULL(@NullOverrideInhibitMultipleCardIns,0) WHEN 1 THEN @InhibitMultipleCardIns ELSE ISNULL(@InhibitMultipleCardIns,[InhibitMultipleCardIns]) END)
		,	[AccessCardInRequired]=(CASE ISNULL(@NullOverrideAccessCardInRequired,0) WHEN 1 THEN @AccessCardInRequired ELSE ISNULL(@AccessCardInRequired,[AccessCardInRequired]) END)
		,	[CheckSiteNumber]=(CASE ISNULL(@NullOverrideCheckSiteNumber,0) WHEN 1 THEN @CheckSiteNumber ELSE ISNULL(@CheckSiteNumber,[CheckSiteNumber]) END)
		,	[PromptForCustomerCard]=(CASE ISNULL(@NullOverridePromptForCustomerCard,0) WHEN 1 THEN @PromptForCustomerCard ELSE ISNULL(@PromptForCustomerCard,[PromptForCustomerCard]) END)
		,	[PromptForTractorOrTanker]=(CASE ISNULL(@NullOverridePromptForTractorOrTanker,0) WHEN 1 THEN @PromptForTractorOrTanker ELSE ISNULL(@PromptForTractorOrTanker,[PromptForTractorOrTanker]) END)
		,	[PromptForFirstTrailer]=(CASE ISNULL(@NullOverridePromptForFirstTrailer,0) WHEN 1 THEN @PromptForFirstTrailer ELSE ISNULL(@PromptForFirstTrailer,[PromptForFirstTrailer]) END)
		,	[PromptForSecondTrailer]=(CASE ISNULL(@NullOverridePromptForSecondTrailer,0) WHEN 1 THEN @PromptForSecondTrailer ELSE ISNULL(@PromptForSecondTrailer,[PromptForSecondTrailer]) END)
		,	[PromptForCompartment]=(CASE ISNULL(@NullOverridePromptForCompartment,0) WHEN 1 THEN @PromptForCompartment ELSE ISNULL(@PromptForCompartment,[PromptForCompartment]) END)
		,	[EnforceDriverEquipmentMatch]=(CASE ISNULL(@NullOverrideEnforceDriverEquipmentMatch,0) WHEN 1 THEN @EnforceDriverEquipmentMatch ELSE ISNULL(@EnforceDriverEquipmentMatch,[EnforceDriverEquipmentMatch]) END)
		,	[EnableAdditiveAccounting]=(CASE ISNULL(@NullOverrideEnableAdditiveAccounting,0) WHEN 1 THEN @EnableAdditiveAccounting ELSE ISNULL(@EnableAdditiveAccounting,[EnableAdditiveAccounting]) END)
		,	[UseCompanyEquipmentIdentifiers]=(CASE ISNULL(@NullOverrideUseCompanyEquipmentIdentifiers,0) WHEN 1 THEN @UseCompanyEquipmentIdentifiers ELSE ISNULL(@UseCompanyEquipmentIdentifiers,[UseCompanyEquipmentIdentifiers]) END)
		,	[UseLastKnownGoodTankData]=(CASE ISNULL(@NullOverrideUseLastKnownGoodTankData,0) WHEN 1 THEN @UseLastKnownGoodTankData ELSE ISNULL(@UseLastKnownGoodTankData,[UseLastKnownGoodTankData]) END)
		,	[MaximumLoadAmount]=(CASE ISNULL(@NullOverrideMaximumLoadAmount,0) WHEN 1 THEN @MaximumLoadAmount ELSE ISNULL(@MaximumLoadAmount,[MaximumLoadAmount]) END)
		,	[MaximumLoadTime]=(CASE ISNULL(@NullOverrideMaximumLoadTime,0) WHEN 1 THEN @MaximumLoadTime ELSE ISNULL(@MaximumLoadTime,[MaximumLoadTime]) END)
		,	[MaximumIdleTime]=(CASE ISNULL(@NullOverrideMaximumIdleTime,0) WHEN 1 THEN @MaximumIdleTime ELSE ISNULL(@MaximumIdleTime,[MaximumIdleTime]) END)
		,	[MaximumFlushAmount]=(CASE ISNULL(@NullOverrideMaximumFlushAmount,0) WHEN 1 THEN @MaximumFlushAmount ELSE ISNULL(@MaximumFlushAmount,[MaximumFlushAmount]) END)
		,	[MaximumMeterProvingAmount]=(CASE ISNULL(@NullOverrideMaximumMeterProvingAmount,0) WHEN 1 THEN @MaximumMeterProvingAmount ELSE ISNULL(@MaximumMeterProvingAmount,[MaximumMeterProvingAmount]) END)
		,	[MaximumReturnsAmount]=(CASE ISNULL(@NullOverrideMaximumReturnsAmount,0) WHEN 1 THEN @MaximumReturnsAmount ELSE ISNULL(@MaximumReturnsAmount,[MaximumReturnsAmount]) END)
		,	[MaximumNumberOfActiveArms]=(CASE ISNULL(@NullOverrideMaximumNumberOfActiveArms,0) WHEN 1 THEN @MaximumNumberOfActiveArms ELSE ISNULL(@MaximumNumberOfActiveArms,[MaximumNumberOfActiveArms]) END)
		,	[DriverTimeoutPeriod]=(CASE ISNULL(@NullOverrideDriverTimeoutPeriod,0) WHEN 1 THEN @DriverTimeoutPeriod ELSE ISNULL(@DriverTimeoutPeriod,[DriverTimeoutPeriod]) END)
		,	[DriverWarningPeriod]=(CASE ISNULL(@NullOverrideDriverWarningPeriod,0) WHEN 1 THEN @DriverWarningPeriod ELSE ISNULL(@DriverWarningPeriod,[DriverWarningPeriod]) END)
		,	[MaximumPrompts]=(CASE ISNULL(@NullOverrideMaximumPrompts,0) WHEN 1 THEN @MaximumPrompts ELSE ISNULL(@MaximumPrompts,[MaximumPrompts]) END)
		,	[MaximumVehicleWeight]=(CASE ISNULL(@NullOverrideMaximumVehicleWeight,0) WHEN 1 THEN @MaximumVehicleWeight ELSE ISNULL(@MaximumVehicleWeight,[MaximumVehicleWeight]) END)
		,	[LoadByNet]=(CASE ISNULL(@NullOverrideLoadByNet,0) WHEN 1 THEN @LoadByNet ELSE ISNULL(@LoadByNet,[LoadByNet]) END)
		,	[PromptForShipmentNumber]=(CASE ISNULL(@NullOverridePromptForShipmentNumber,0) WHEN 1 THEN @PromptForShipmentNumber ELSE ISNULL(@PromptForShipmentNumber,[PromptForShipmentNumber]) END)
		,	[MaximumProductTemperature]=(CASE ISNULL(@NullOverrideMaximumProductTemperature,0) WHEN 1 THEN @MaximumProductTemperature ELSE ISNULL(@MaximumProductTemperature,[MaximumProductTemperature]) END)
		,	[ListEquipment]=(CASE ISNULL(@NullOverrideListEquipment,0) WHEN 1 THEN @ListEquipment ELSE ISNULL(@ListEquipment,[ListEquipment]) END)
		,	[DeferStationChanges]=(CASE ISNULL(@NullOverrideDeferStationChanges,0) WHEN 1 THEN @DeferStationChanges ELSE ISNULL(@DeferStationChanges,[DeferStationChanges]) END)
		,	[InhibitBOLWithBrokenBlends]=(CASE ISNULL(@NullOverrideInhibitBOLWithBrokenBlends,0) WHEN 1 THEN @InhibitBOLWithBrokenBlends ELSE ISNULL(@InhibitBOLWithBrokenBlends,[InhibitBOLWithBrokenBlends]) END)
		,	[InhibitBOLWithImproperAdditization]=(CASE ISNULL(@NullOverrideInhibitBOLWithImproperAdditization,0) WHEN 1 THEN @InhibitBOLWithImproperAdditization ELSE ISNULL(@InhibitBOLWithImproperAdditization,[InhibitBOLWithImproperAdditization]) END)
		,	[InhibitOverweightBOL]=(CASE ISNULL(@NullOverrideInhibitOverweightBOL,0) WHEN 1 THEN @InhibitOverweightBOL ELSE ISNULL(@InhibitOverweightBOL,[InhibitOverweightBOL]) END)
		,	[ExceptionBOLPrinter]=(CASE ISNULL(@NullOverrideExceptionBOLPrinter,0) WHEN 1 THEN @ExceptionBOLPrinter ELSE ISNULL(@ExceptionBOLPrinter,[ExceptionBOLPrinter]) END)
		,	[EnableAutomaticBOLPrinting]=(CASE ISNULL(@NullOverrideEnableAutomaticBOLPrinting,0) WHEN 1 THEN @EnableAutomaticBOLPrinting ELSE ISNULL(@EnableAutomaticBOLPrinting,[EnableAutomaticBOLPrinting]) END)
		,	[AutomaticBOLStartNumber]=(CASE ISNULL(@NullOverrideAutomaticBOLStartNumber,0) WHEN 1 THEN @AutomaticBOLStartNumber ELSE ISNULL(@AutomaticBOLStartNumber,[AutomaticBOLStartNumber]) END)
		,	[AutomaticBOLEndNumber]=(CASE ISNULL(@NullOverrideAutomaticBOLEndNumber,0) WHEN 1 THEN @AutomaticBOLEndNumber ELSE ISNULL(@AutomaticBOLEndNumber,[AutomaticBOLEndNumber]) END)
		,	[AutomaticBOLNextNumber]=(CASE ISNULL(@NullOverrideAutomaticBOLNextNumber,0) WHEN 1 THEN @AutomaticBOLNextNumber ELSE ISNULL(@AutomaticBOLNextNumber,[AutomaticBOLNextNumber]) END)
		,	[SeparateManualBOLNumbering]=(CASE ISNULL(@NullOverrideSeparateManualBOLNumbering,0) WHEN 1 THEN @SeparateManualBOLNumbering ELSE ISNULL(@SeparateManualBOLNumbering,[SeparateManualBOLNumbering]) END)
		,	[ManualBOLStartNumber]=(CASE ISNULL(@NullOverrideManualBOLStartNumber,0) WHEN 1 THEN @ManualBOLStartNumber ELSE ISNULL(@ManualBOLStartNumber,[ManualBOLStartNumber]) END)
		,	[ManualBOLEndNumber]=(CASE ISNULL(@NullOverrideManualBOLEndNumber,0) WHEN 1 THEN @ManualBOLEndNumber ELSE ISNULL(@ManualBOLEndNumber,[ManualBOLEndNumber]) END)
		,	[ManualBOLNextNumber]=(CASE ISNULL(@NullOverrideManualBOLNextNumber,0) WHEN 1 THEN @ManualBOLNextNumber ELSE ISNULL(@ManualBOLNextNumber,[ManualBOLNextNumber]) END)
		,	[TransactionStartNumber]=(CASE ISNULL(@NullOverrideTransactionStartNumber,0) WHEN 1 THEN @TransactionStartNumber ELSE ISNULL(@TransactionStartNumber,[TransactionStartNumber]) END)
		,	[TransactionEndNumber]=(CASE ISNULL(@NullOverrideTransactionEndNumber,0) WHEN 1 THEN @TransactionEndNumber ELSE ISNULL(@TransactionEndNumber,[TransactionEndNumber]) END)
		,	[TransactionNextNumber]=(CASE ISNULL(@NullOverrideTransactionNextNumber,0) WHEN 1 THEN @TransactionNextNumber ELSE ISNULL(@TransactionNextNumber,[TransactionNextNumber]) END)
		,	[OrderStartNumber]=(CASE ISNULL(@NullOverrideOrderStartNumber,0) WHEN 1 THEN @OrderStartNumber ELSE ISNULL(@OrderStartNumber,[OrderStartNumber]) END)
		,	[OrderEndNumber]=(CASE ISNULL(@NullOverrideOrderEndNumber,0) WHEN 1 THEN @OrderEndNumber ELSE ISNULL(@OrderEndNumber,[OrderEndNumber]) END)
		,	[OrderNextNumber]=(CASE ISNULL(@NullOverrideOrderNextNumber,0) WHEN 1 THEN @OrderNextNumber ELSE ISNULL(@OrderNextNumber,[OrderNextNumber]) END)
		,	[NumberPrefix]=(CASE ISNULL(@NullOverrideNumberPrefix,0) WHEN 1 THEN @NumberPrefix ELSE ISNULL(@NumberPrefix,[NumberPrefix]) END)
		,	[OpenTransactionWindow]=(CASE ISNULL(@NullOverrideOpenTransactionWindow,0) WHEN 1 THEN @OpenTransactionWindow ELSE ISNULL(@OpenTransactionWindow,[OpenTransactionWindow]) END)
		,	[AdministrativeLockDate]=(CASE ISNULL(@NullOverrideAdministrativeLockDate,0) WHEN 1 THEN @AdministrativeLockDate ELSE ISNULL(@AdministrativeLockDate,[AdministrativeLockDate]) END)
		,	[OperationalLockDate]=(CASE ISNULL(@NullOverrideOperationalLockDate,0) WHEN 1 THEN @OperationalLockDate ELSE ISNULL(@OperationalLockDate,[OperationalLockDate]) END)
		,	[MaximumDaysToRetainLogs]=(CASE ISNULL(@NullOverrideMaximumDaysToRetainLogs,0) WHEN 1 THEN @MaximumDaysToRetainLogs ELSE ISNULL(@MaximumDaysToRetainLogs,[MaximumDaysToRetainLogs]) END)
		,	[EnableDebugLogging]=(CASE ISNULL(@NullOverrideEnableDebugLogging,0) WHEN 1 THEN @EnableDebugLogging ELSE ISNULL(@EnableDebugLogging,[EnableDebugLogging]) END)
		,	[EnableAuditLogging]=(CASE ISNULL(@NullOverrideEnableAuditLogging,0) WHEN 1 THEN @EnableAuditLogging ELSE ISNULL(@EnableAuditLogging,[EnableAuditLogging]) END)
		,	[AutomaticallyPrintAlarmsAndEvents]=(CASE ISNULL(@NullOverrideAutomaticallyPrintAlarmsAndEvents,0) WHEN 1 THEN @AutomaticallyPrintAlarmsAndEvents ELSE ISNULL(@AutomaticallyPrintAlarmsAndEvents,[AutomaticallyPrintAlarmsAndEvents]) END)
		,	[AlarmAndEventPrinter]=(CASE ISNULL(@NullOverrideAlarmAndEventPrinter,0) WHEN 1 THEN @AlarmAndEventPrinter ELSE ISNULL(@AlarmAndEventPrinter,[AlarmAndEventPrinter]) END)
		,	[MailServer]=(CASE ISNULL(@NullOverrideMailServer,0) WHEN 1 THEN @MailServer ELSE ISNULL(@MailServer,[MailServer]) END)
		,	[MailFrom]=(CASE ISNULL(@NullOverrideMailFrom,0) WHEN 1 THEN @MailFrom ELSE ISNULL(@MailFrom,[MailFrom]) END)
		,	[MailUserName]=(CASE ISNULL(@NullOverrideMailUserName,0) WHEN 1 THEN @MailUserName ELSE ISNULL(@MailUserName,[MailUserName]) END)
		,	[MailPassword]=(CASE ISNULL(@NullOverrideMailPassword,0) WHEN 1 THEN @MailPassword ELSE ISNULL(@MailPassword,[MailPassword]) END)
		,	[DialupName]=(CASE ISNULL(@NullOverrideDialupName,0) WHEN 1 THEN @DialupName ELSE ISNULL(@DialupName,[DialupName]) END)
		,	[SCADASystem]=(CASE ISNULL(@NullOverrideSCADASystem,0) WHEN 1 THEN @SCADASystem ELSE ISNULL(@SCADASystem,[SCADASystem]) END)
		,	[InhibitTemplateGraphics]=(CASE ISNULL(@NullOverrideInhibitTemplateGraphics,0) WHEN 1 THEN @InhibitTemplateGraphics ELSE ISNULL(@InhibitTemplateGraphics,[InhibitTemplateGraphics]) END)
		,	[RefreshInterval]=(CASE ISNULL(@NullOverrideRefreshInterval,0) WHEN 1 THEN @RefreshInterval ELSE ISNULL(@RefreshInterval,[RefreshInterval]) END)
		,	[InhibitEndOfDayOperations]=(CASE ISNULL(@NullOverrideInhibitEndOfDayOperations,0) WHEN 1 THEN @InhibitEndOfDayOperations ELSE ISNULL(@InhibitEndOfDayOperations,[InhibitEndOfDayOperations]) END)
		,	[InhibitEndOfMonthOperations]=(CASE ISNULL(@NullOverrideInhibitEndOfMonthOperations,0) WHEN 1 THEN @InhibitEndOfMonthOperations ELSE ISNULL(@InhibitEndOfMonthOperations,[InhibitEndOfMonthOperations]) END)
		,	[EndOfDayWarningPeriod]=(CASE ISNULL(@NullOverrideEndOfDayWarningPeriod,0) WHEN 1 THEN @EndOfDayWarningPeriod ELSE ISNULL(@EndOfDayWarningPeriod,[EndOfDayWarningPeriod]) END)
		,	[InhibitAutomaticPhysicalInventory]=(CASE ISNULL(@NullOverrideInhibitAutomaticPhysicalInventory,0) WHEN 1 THEN @InhibitAutomaticPhysicalInventory ELSE ISNULL(@InhibitAutomaticPhysicalInventory,[InhibitAutomaticPhysicalInventory]) END)
		,	[InhibitAutomaticMeterCloseout]=(CASE ISNULL(@NullOverrideInhibitAutomaticMeterCloseout,0) WHEN 1 THEN @InhibitAutomaticMeterCloseout ELSE ISNULL(@InhibitAutomaticMeterCloseout,[InhibitAutomaticMeterCloseout]) END)
		,	[InhibitAutomaticReportGeneration]=(CASE ISNULL(@NullOverrideInhibitAutomaticReportGeneration,0) WHEN 1 THEN @InhibitAutomaticReportGeneration ELSE ISNULL(@InhibitAutomaticReportGeneration,[InhibitAutomaticReportGeneration]) END)
		,	[InhibitAutomaticAdjustmentDistribution]=(CASE ISNULL(@NullOverrideInhibitAutomaticAdjustmentDistribution,0) WHEN 1 THEN @InhibitAutomaticAdjustmentDistribution ELSE ISNULL(@InhibitAutomaticAdjustmentDistribution,[InhibitAutomaticAdjustmentDistribution]) END)
		,	[InhibitAutomaticCloseout]=(CASE ISNULL(@NullOverrideInhibitAutomaticCloseout,0) WHEN 1 THEN @InhibitAutomaticCloseout ELSE ISNULL(@InhibitAutomaticCloseout,[InhibitAutomaticCloseout]) END)
		,	[InhibitTankScan]=(CASE ISNULL(@NullOverrideInhibitTankScan,0) WHEN 1 THEN @InhibitTankScan ELSE ISNULL(@InhibitTankScan,[InhibitTankScan]) END)
		,	[ReportDirectory]=(CASE ISNULL(@NullOverrideReportDirectory,0) WHEN 1 THEN @ReportDirectory ELSE ISNULL(@ReportDirectory,[ReportDirectory]) END)
		,	[ManageReports]=(CASE ISNULL(@NullOverrideManageReports,0) WHEN 1 THEN @ManageReports ELSE ISNULL(@ManageReports,[ManageReports]) END)
		,	[ManagedReportDirectory]=(CASE ISNULL(@NullOverrideManagedReportDirectory,0) WHEN 1 THEN @ManagedReportDirectory ELSE ISNULL(@ManagedReportDirectory,[ManagedReportDirectory]) END)
		,	[VRURateLimit]=(CASE ISNULL(@NullOverrideVRURateLimit,0) WHEN 1 THEN @VRURateLimit ELSE ISNULL(@VRURateLimit,[VRURateLimit]) END)
		,	[VRUHourlyLimit]=(CASE ISNULL(@NullOverrideVRUHourlyLimit,0) WHEN 1 THEN @VRUHourlyLimit ELSE ISNULL(@VRUHourlyLimit,[VRUHourlyLimit]) END)
		,	[VRUDailyLimit]=(CASE ISNULL(@NullOverrideVRUDailyLimit,0) WHEN 1 THEN @VRUDailyLimit ELSE ISNULL(@VRUDailyLimit,[VRUDailyLimit]) END)
		,	[VRUYearlyLimit]=(CASE ISNULL(@NullOverrideVRUYearlyLimit,0) WHEN 1 THEN @VRUYearlyLimit ELSE ISNULL(@VRUYearlyLimit,[VRUYearlyLimit]) END)
		,	[VRUCurrentYearLimit]=(CASE ISNULL(@NullOverrideVRUCurrentYearLimit,0) WHEN 1 THEN @VRUCurrentYearLimit ELSE ISNULL(@VRUCurrentYearLimit,[VRUCurrentYearLimit]) END)
		,	[VRURateActual]=(CASE ISNULL(@NullOverrideVRURateActual,0) WHEN 1 THEN @VRURateActual ELSE ISNULL(@VRURateActual,[VRURateActual]) END)
		,	[VRUHourlyActual]=(CASE ISNULL(@NullOverrideVRUHourlyActual,0) WHEN 1 THEN @VRUHourlyActual ELSE ISNULL(@VRUHourlyActual,[VRUHourlyActual]) END)
		,	[VRUDailyActual]=(CASE ISNULL(@NullOverrideVRUDailyActual,0) WHEN 1 THEN @VRUDailyActual ELSE ISNULL(@VRUDailyActual,[VRUDailyActual]) END)
		,	[VRUYearlyActual]=(CASE ISNULL(@NullOverrideVRUYearlyActual,0) WHEN 1 THEN @VRUYearlyActual ELSE ISNULL(@VRUYearlyActual,[VRUYearlyActual]) END)
		,	[VRUCurrentYearActual]=(CASE ISNULL(@NullOverrideVRUCurrentYearActual,0) WHEN 1 THEN @VRUCurrentYearActual ELSE ISNULL(@VRUCurrentYearActual,[VRUCurrentYearActual]) END)
		,	[VRURateLimitEnabled]=(CASE ISNULL(@NullOverrideVRURateLimitEnabled,0) WHEN 1 THEN @VRURateLimitEnabled ELSE ISNULL(@VRURateLimitEnabled,[VRURateLimitEnabled]) END)
		,	[VRUHourlyLimitEnabled]=(CASE ISNULL(@NullOverrideVRUHourlyLimitEnabled,0) WHEN 1 THEN @VRUHourlyLimitEnabled ELSE ISNULL(@VRUHourlyLimitEnabled,[VRUHourlyLimitEnabled]) END)
		,	[VRUDailyLimitEnabled]=(CASE ISNULL(@NullOverrideVRUDailyLimitEnabled,0) WHEN 1 THEN @VRUDailyLimitEnabled ELSE ISNULL(@VRUDailyLimitEnabled,[VRUDailyLimitEnabled]) END)
		,	[VRUYearlyLimitEnabled]=(CASE ISNULL(@NullOverrideVRUYearlyLimitEnabled,0) WHEN 1 THEN @VRUYearlyLimitEnabled ELSE ISNULL(@VRUYearlyLimitEnabled,[VRUYearlyLimitEnabled]) END)
		,	[VRUCurrentYearLimitEnabled]=(CASE ISNULL(@NullOverrideVRUCurrentYearLimitEnabled,0) WHEN 1 THEN @VRUCurrentYearLimitEnabled ELSE ISNULL(@VRUCurrentYearLimitEnabled,[VRUCurrentYearLimitEnabled]) END)
		,	[WatchdogPeriod]=(CASE ISNULL(@NullOverrideWatchdogPeriod,0) WHEN 1 THEN @WatchdogPeriod ELSE ISNULL(@WatchdogPeriod,[WatchdogPeriod]) END)
		,	[WatchdogCounterStart]=(CASE ISNULL(@NullOverrideWatchdogCounterStart,0) WHEN 1 THEN @WatchdogCounterStart ELSE ISNULL(@WatchdogCounterStart,[WatchdogCounterStart]) END)
		,	[WatchdogCounterEnd]=(CASE ISNULL(@NullOverrideWatchdogCounterEnd,0) WHEN 1 THEN @WatchdogCounterEnd ELSE ISNULL(@WatchdogCounterEnd,[WatchdogCounterEnd]) END)
		,	[NumberDecimalSeparator]=(CASE ISNULL(@NullOverrideNumberDecimalSeparator,0) WHEN 1 THEN @NumberDecimalSeparator ELSE ISNULL(@NumberDecimalSeparator,[NumberDecimalSeparator]) END)
		,	[NumberGroupSeparator]=(CASE ISNULL(@NullOverrideNumberGroupSeparator,0) WHEN 1 THEN @NumberGroupSeparator ELSE ISNULL(@NumberGroupSeparator,[NumberGroupSeparator]) END)
		,	[ListSeparator]=(CASE ISNULL(@NullOverrideListSeparator,0) WHEN 1 THEN @ListSeparator ELSE ISNULL(@ListSeparator,[ListSeparator]) END)
		,	[TimePattern]=(CASE ISNULL(@NullOverrideTimePattern,0) WHEN 1 THEN @TimePattern ELSE ISNULL(@TimePattern,[TimePattern]) END)
		,	[TimeSeparator]=(CASE ISNULL(@NullOverrideTimeSeparator,0) WHEN 1 THEN @TimeSeparator ELSE ISNULL(@TimeSeparator,[TimeSeparator]) END)
		,	[AMSymbol]=(CASE ISNULL(@NullOverrideAMSymbol,0) WHEN 1 THEN @AMSymbol ELSE ISNULL(@AMSymbol,[AMSymbol]) END)
		,	[PMSymbol]=(CASE ISNULL(@NullOverridePMSymbol,0) WHEN 1 THEN @PMSymbol ELSE ISNULL(@PMSymbol,[PMSymbol]) END)
		,	[ShortDatePattern]=(CASE ISNULL(@NullOverrideShortDatePattern,0) WHEN 1 THEN @ShortDatePattern ELSE ISNULL(@ShortDatePattern,[ShortDatePattern]) END)
		,	[DateSeparator]=(CASE ISNULL(@NullOverrideDateSeparator,0) WHEN 1 THEN @DateSeparator ELSE ISNULL(@DateSeparator,[DateSeparator]) END)
		,	[LongDatePattern]=(CASE ISNULL(@NullOverrideLongDatePattern,0) WHEN 1 THEN @LongDatePattern ELSE ISNULL(@LongDatePattern,[LongDatePattern]) END)
		,	[TwoDigitCalendarEndYear]=(CASE ISNULL(@NullOverrideTwoDigitCalendarEndYear,0) WHEN 1 THEN @TwoDigitCalendarEndYear ELSE ISNULL(@TwoDigitCalendarEndYear,[TwoDigitCalendarEndYear]) END)
		,	[UserData1]=(CASE ISNULL(@NullOverrideUserData1,0) WHEN 1 THEN @UserData1 ELSE ISNULL(@UserData1,[UserData1]) END)
		,	[UserData2]=(CASE ISNULL(@NullOverrideUserData2,0) WHEN 1 THEN @UserData2 ELSE ISNULL(@UserData2,[UserData2]) END)
		,	[UserData3]=(CASE ISNULL(@NullOverrideUserData3,0) WHEN 1 THEN @UserData3 ELSE ISNULL(@UserData3,[UserData3]) END)
		,	[UserData4]=(CASE ISNULL(@NullOverrideUserData4,0) WHEN 1 THEN @UserData4 ELSE ISNULL(@UserData4,[UserData4]) END)
		,	[UserData5]=(CASE ISNULL(@NullOverrideUserData5,0) WHEN 1 THEN @UserData5 ELSE ISNULL(@UserData5,[UserData5]) END)
		,	[UserData6]=(CASE ISNULL(@NullOverrideUserData6,0) WHEN 1 THEN @UserData6 ELSE ISNULL(@UserData6,[UserData6]) END)
		,	[UserData7]=(CASE ISNULL(@NullOverrideUserData7,0) WHEN 1 THEN @UserData7 ELSE ISNULL(@UserData7,[UserData7]) END)
		,	[UserData8]=(CASE ISNULL(@NullOverrideUserData8,0) WHEN 1 THEN @UserData8 ELSE ISNULL(@UserData8,[UserData8]) END)
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[MinTimeAllowedToChangePwd]=(CASE ISNULL(@NullOverrideMinTimeAllowedToChangePwd,0) WHEN 1 THEN @MinTimeAllowedToChangePwd ELSE ISNULL(@MinTimeAllowedToChangePwd,[MinTimeAllowedToChangePwd]) END)
		,	[MinPwdCharacterLength]=(CASE ISNULL(@NullOverrideMinPwdCharacterLength,0) WHEN 1 THEN @MinPwdCharacterLength ELSE ISNULL(@MinPwdCharacterLength,[MinPwdCharacterLength]) END)
		,	[PwdExpirationInDays]=(CASE ISNULL(@NullOverridePwdExpirationInDays,0) WHEN 1 THEN @PwdExpirationInDays ELSE ISNULL(@PwdExpirationInDays,[PwdExpirationInDays]) END)
		,	[PwdLockoutThreshold]=(CASE ISNULL(@NullOverridePwdLockoutThreshold,0) WHEN 1 THEN @PwdLockoutThreshold ELSE ISNULL(@PwdLockoutThreshold,[PwdLockoutThreshold]) END)
		,	[CheckForPreviousPwd]=(CASE ISNULL(@NullOverrideCheckForPreviousPwd,0) WHEN 1 THEN @CheckForPreviousPwd ELSE ISNULL(@CheckForPreviousPwd,[CheckForPreviousPwd]) END)
		,	[StrongPwdUse]=(CASE ISNULL(@NullOverrideStrongPwdUse,0) WHEN 1 THEN @StrongPwdUse ELSE ISNULL(@StrongPwdUse,[StrongPwdUse]) END)
		,	[PwdHistoryCount]=(CASE ISNULL(@NullOverridePwdHistoryCount,0) WHEN 1 THEN @PwdHistoryCount ELSE ISNULL(@PwdHistoryCount,[PwdHistoryCount]) END)
		,	[ApplyToAllSiteMembers]=(CASE ISNULL(@NullOverrideApplyToAllSiteMembers,0) WHEN 1 THEN @ApplyToAllSiteMembers ELSE ISNULL(@ApplyToAllSiteMembers,[ApplyToAllSiteMembers]) END)
		,	[InactivityDisablePeriod]=(CASE ISNULL(@NullOverrideInactivityDisablePeriod,0) WHEN 1 THEN @InactivityDisablePeriod ELSE ISNULL(@InactivityDisablePeriod,[InactivityDisablePeriod]) END)
		,	[EnforceSingleOwner]=(CASE ISNULL(@NullOverrideEnforceSingleOwner,0) WHEN 1 THEN @EnforceSingleOwner ELSE ISNULL(@EnforceSingleOwner,[EnforceSingleOwner]) END)
		,	[InhibitBOLSummaryAutoPopulate]=(CASE ISNULL(@NullOverrideInhibitBOLSummaryAutoPopulate,0) WHEN 1 THEN @InhibitBOLSummaryAutoPopulate ELSE ISNULL(@InhibitBOLSummaryAutoPopulate,[InhibitBOLSummaryAutoPopulate]) END)
		,	[InhibitOrderSummaryAutoPopulate]=(CASE ISNULL(@NullOverrideInhibitOrderSummaryAutoPopulate,0) WHEN 1 THEN @InhibitOrderSummaryAutoPopulate ELSE ISNULL(@InhibitOrderSummaryAutoPopulate,[InhibitOrderSummaryAutoPopulate]) END)
		,	[InhibitSupplyOrderSummaryAutoPopulate]=(CASE ISNULL(@NullOverrideInhibitSupplyOrderSummaryAutoPopulate,0) WHEN 1 THEN @InhibitSupplyOrderSummaryAutoPopulate ELSE ISNULL(@InhibitSupplyOrderSummaryAutoPopulate,[InhibitSupplyOrderSummaryAutoPopulate]) END)
		,	[InvoiceStartNumber]=(CASE ISNULL(@NullOverrideInvoiceStartNumber,0) WHEN 1 THEN @InvoiceStartNumber ELSE ISNULL(@InvoiceStartNumber,[InvoiceStartNumber]) END)
		,	[InvoiceEndNumber]=(CASE ISNULL(@NullOverrideInvoiceEndNumber,0) WHEN 1 THEN @InvoiceEndNumber ELSE ISNULL(@InvoiceEndNumber,[InvoiceEndNumber]) END)
		,	[InvoiceNextNumber]=(CASE ISNULL(@NullOverrideInvoiceNextNumber,0) WHEN 1 THEN @InvoiceNextNumber ELSE ISNULL(@InvoiceNextNumber,[InvoiceNextNumber]) END)
		,	[PromptForReturns]=(CASE ISNULL(@NullOverridePromptForReturns,0) WHEN 1 THEN @PromptForReturns ELSE ISNULL(@PromptForReturns,[PromptForReturns]) END)
		,	[PromptForTruckCard]=(CASE ISNULL(@NullOverridePromptForTruckCard,0) WHEN 1 THEN @PromptForTruckCard ELSE ISNULL(@PromptForTruckCard,[PromptForTruckCard]) END)
		,	[StartingShortCardNumber]=(CASE ISNULL(@NullOverrideStartingShortCardNumber,0) WHEN 1 THEN @StartingShortCardNumber ELSE ISNULL(@StartingShortCardNumber,[StartingShortCardNumber]) END)
		,	[UseShortCardNumber]=(CASE ISNULL(@NullOverrideUseShortCardNumber,0) WHEN 1 THEN @UseShortCardNumber ELSE ISNULL(@UseShortCardNumber,[UseShortCardNumber]) END)
		,	[ExcessVarianceCount]=(CASE ISNULL(@NullOverrideExcessVarianceCount,0) WHEN 1 THEN @ExcessVarianceCount ELSE ISNULL(@ExcessVarianceCount,[ExcessVarianceCount]) END)
		,	[ExcessVarianceTolerance]=(CASE ISNULL(@NullOverrideExcessVarianceTolerance,0) WHEN 1 THEN @ExcessVarianceTolerance ELSE ISNULL(@ExcessVarianceTolerance,[ExcessVarianceTolerance]) END)
		,	[DisableArchivePeriod]=(CASE ISNULL(@NullOverrideDisableArchivePeriod,0) WHEN 1 THEN @DisableArchivePeriod ELSE ISNULL(@DisableArchivePeriod,[DisableArchivePeriod]) END)
		,	[ExportArchiveDir]=(CASE ISNULL(@NullOverrideExportArchiveDir,0) WHEN 1 THEN @ExportArchiveDir ELSE ISNULL(@ExportArchiveDir,[ExportArchiveDir]) END)
		,	[ImportArchiveDir]=(CASE ISNULL(@NullOverrideImportArchiveDir,0) WHEN 1 THEN @ImportArchiveDir ELSE ISNULL(@ImportArchiveDir,[ImportArchiveDir]) END)
		,	[GroupLedgerByID]=(CASE ISNULL(@NullOverrideGroupLedgerByID,0) WHEN 1 THEN @GroupLedgerByID ELSE ISNULL(@GroupLedgerByID,[GroupLedgerByID]) END)
		,	[InhibitSiteLedgerRollup]=(CASE ISNULL(@NullOverrideInhibitSiteLedgerRollup,0) WHEN 1 THEN @InhibitSiteLedgerRollup ELSE ISNULL(@InhibitSiteLedgerRollup,[InhibitSiteLedgerRollup]) END)
		,	[UseTankReconciliation]=(CASE ISNULL(@NullOverrideUseTankReconciliation,0) WHEN 1 THEN @UseTankReconciliation ELSE ISNULL(@UseTankReconciliation,[UseTankReconciliation]) END)
		,	[LookupNumberGroupSizesTypeIndex]=(CASE ISNULL(@NullOverrideLookupNumberGroupSizesTypeIndex,0) WHEN 1 THEN @LookupNumberGroupSizesTypeIndex ELSE ISNULL(@LookupNumberGroupSizesTypeIndex,[LookupNumberGroupSizesTypeIndex]) END)
		,	[LookupQuantityDisplayDefaultIndex]=(CASE ISNULL(@NullOverrideLookupQuantityDisplayDefaultIndex,0) WHEN 1 THEN @LookupQuantityDisplayDefaultIndex ELSE ISNULL(@LookupQuantityDisplayDefaultIndex,[LookupQuantityDisplayDefaultIndex]) END)
		,	[LookupSecondaryStorageFillMethodIndex]=(CASE ISNULL(@NullOverrideLookupSecondaryStorageFillMethodIndex,0) WHEN 1 THEN @LookupSecondaryStorageFillMethodIndex ELSE ISNULL(@LookupSecondaryStorageFillMethodIndex,[LookupSecondaryStorageFillMethodIndex]) END)
		,	[LookupMailConnectModeIndex]=(CASE ISNULL(@NullOverrideLookupMailConnectModeIndex,0) WHEN 1 THEN @LookupMailConnectModeIndex ELSE ISNULL(@LookupMailConnectModeIndex,[LookupMailConnectModeIndex]) END)
		,	[LookupWatchdogModeIndex]=(CASE ISNULL(@NullOverrideLookupWatchdogModeIndex,0) WHEN 1 THEN @LookupWatchdogModeIndex ELSE ISNULL(@LookupWatchdogModeIndex,[LookupWatchdogModeIndex]) END)
		,	[Contact1Name]=(CASE ISNULL(@NullOverrideContact1Name,0) WHEN 1 THEN @Contact1Name ELSE ISNULL(@Contact1Name,[Contact1Name]) END)
		,	[Contact1Address1]=(CASE ISNULL(@NullOverrideContact1Address1,0) WHEN 1 THEN @Contact1Address1 ELSE ISNULL(@Contact1Address1,[Contact1Address1]) END)
		,	[Contact1Address2]=(CASE ISNULL(@NullOverrideContact1Address2,0) WHEN 1 THEN @Contact1Address2 ELSE ISNULL(@Contact1Address2,[Contact1Address2]) END)
		,	[Contact1City]=(CASE ISNULL(@NullOverrideContact1City,0) WHEN 1 THEN @Contact1City ELSE ISNULL(@Contact1City,[Contact1City]) END)
		,	[Contact1State]=(CASE ISNULL(@NullOverrideContact1State,0) WHEN 1 THEN @Contact1State ELSE ISNULL(@Contact1State,[Contact1State]) END)
		,	[Contact1Zip]=(CASE ISNULL(@NullOverrideContact1Zip,0) WHEN 1 THEN @Contact1Zip ELSE ISNULL(@Contact1Zip,[Contact1Zip]) END)
		,	[Contact1Country]=(CASE ISNULL(@NullOverrideContact1Country,0) WHEN 1 THEN @Contact1Country ELSE ISNULL(@Contact1Country,[Contact1Country]) END)
		,	[Contact1PhoneOffice]=(CASE ISNULL(@NullOverrideContact1PhoneOffice,0) WHEN 1 THEN @Contact1PhoneOffice ELSE ISNULL(@Contact1PhoneOffice,[Contact1PhoneOffice]) END)
		,	[Contact1Fax]=(CASE ISNULL(@NullOverrideContact1Fax,0) WHEN 1 THEN @Contact1Fax ELSE ISNULL(@Contact1Fax,[Contact1Fax]) END)
		,	[Contact1EmailAddress]=(CASE ISNULL(@NullOverrideContact1EmailAddress,0) WHEN 1 THEN @Contact1EmailAddress ELSE ISNULL(@Contact1EmailAddress,[Contact1EmailAddress]) END)
		,	[Contact2Name]=(CASE ISNULL(@NullOverrideContact2Name,0) WHEN 1 THEN @Contact2Name ELSE ISNULL(@Contact2Name,[Contact2Name]) END)
		,	[Contact2Address1]=(CASE ISNULL(@NullOverrideContact2Address1,0) WHEN 1 THEN @Contact2Address1 ELSE ISNULL(@Contact2Address1,[Contact2Address1]) END)
		,	[Contact2Address2]=(CASE ISNULL(@NullOverrideContact2Address2,0) WHEN 1 THEN @Contact2Address2 ELSE ISNULL(@Contact2Address2,[Contact2Address2]) END)
		,	[Contact2City]=(CASE ISNULL(@NullOverrideContact2City,0) WHEN 1 THEN @Contact2City ELSE ISNULL(@Contact2City,[Contact2City]) END)
		,	[Contact2State]=(CASE ISNULL(@NullOverrideContact2State,0) WHEN 1 THEN @Contact2State ELSE ISNULL(@Contact2State,[Contact2State]) END)
		,	[Contact2Zip]=(CASE ISNULL(@NullOverrideContact2Zip,0) WHEN 1 THEN @Contact2Zip ELSE ISNULL(@Contact2Zip,[Contact2Zip]) END)
		,	[Contact2Country]=(CASE ISNULL(@NullOverrideContact2Country,0) WHEN 1 THEN @Contact2Country ELSE ISNULL(@Contact2Country,[Contact2Country]) END)
		,	[Contact2PhoneOffice]=(CASE ISNULL(@NullOverrideContact2PhoneOffice,0) WHEN 1 THEN @Contact2PhoneOffice ELSE ISNULL(@Contact2PhoneOffice,[Contact2PhoneOffice]) END)
		,	[Contact2Fax]=(CASE ISNULL(@NullOverrideContact2Fax,0) WHEN 1 THEN @Contact2Fax ELSE ISNULL(@Contact2Fax,[Contact2Fax]) END)
		,	[Contact2EmailAddress]=(CASE ISNULL(@NullOverrideContact2EmailAddress,0) WHEN 1 THEN @Contact2EmailAddress ELSE ISNULL(@Contact2EmailAddress,[Contact2EmailAddress]) END)
		,	[Contact1PhoneMobile]=(CASE ISNULL(@NullOverrideContact1PhoneMobile,0) WHEN 1 THEN @Contact1PhoneMobile ELSE ISNULL(@Contact1PhoneMobile,[Contact1PhoneMobile]) END)
		,	[Contact2PhoneMobile]=(CASE ISNULL(@NullOverrideContact2PhoneMobile,0) WHEN 1 THEN @Contact2PhoneMobile ELSE ISNULL(@Contact2PhoneMobile,[Contact2PhoneMobile]) END)
		,	[EnablePasswordHint]=(CASE ISNULL(@NullOverrideEnablePasswordHint,0) WHEN 1 THEN @EnablePasswordHint ELSE ISNULL(@EnablePasswordHint,[EnablePasswordHint]) END)
		,	[EnablePasswordReset]=(CASE ISNULL(@NullOverrideEnablePasswordReset,0) WHEN 1 THEN @EnablePasswordReset ELSE ISNULL(@EnablePasswordReset,[EnablePasswordReset]) END)
		,	[MeterReconciliationToleranceIsPercent]=(CASE ISNULL(@NullOverrideMeterReconciliationToleranceIsPercent,0) WHEN 1 THEN @MeterReconciliationToleranceIsPercent ELSE ISNULL(@MeterReconciliationToleranceIsPercent,[MeterReconciliationToleranceIsPercent]) END)
		,	[MeterReconciliationReportName]=(CASE ISNULL(@NullOverrideMeterReconciliationReportName,0) WHEN 1 THEN @MeterReconciliationReportName ELSE ISNULL(@MeterReconciliationReportName,[MeterReconciliationReportName]) END)
		,	[TranslatedHelpURL]=(CASE ISNULL(@NullOverrideTranslatedHelpURL,0) WHEN 1 THEN @TranslatedHelpURL ELSE ISNULL(@TranslatedHelpURL,[TranslatedHelpURL]) END)
		,	[AllowUseOfSpecialChars]=(CASE ISNULL(@NullOverrideAllowUseOfSpecialChars,0) WHEN 1 THEN @AllowUseOfSpecialChars ELSE ISNULL(@AllowUseOfSpecialChars,[AllowUseOfSpecialChars]) END)
		,	[EnablePeriodicSyncFlag]=(CASE ISNULL(@NullOverrideEnablePeriodicSyncFlag,0) WHEN 1 THEN @EnablePeriodicSyncFlag ELSE ISNULL(@EnablePeriodicSyncFlag,[EnablePeriodicSyncFlag]) END)
		,	[PeriodicSyncIntervalMinutes]=(CASE ISNULL(@NullOverridePeriodicSyncIntervalMinutes,0) WHEN 1 THEN @PeriodicSyncIntervalMinutes ELSE ISNULL(@PeriodicSyncIntervalMinutes,[PeriodicSyncIntervalMinutes]) END)
		WHERE	SiteGuid=@SiteGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblSites]           
		WHERE SiteGuid=@SiteGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_SitesUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
