CREATE PROCEDURE [dbo].[gsp_AllocationLineItemsUpdateByPK]
(
		@AllocationLineItemGuid uniqueidentifier
	,	@Limit float=NULL
	,	@Next float=NULL
	,	@ResetMultiple int=NULL
	,	@ResetDate datetimeoffset(7)=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@LookupAllocationTypeIndex int=NULL
	,	@LookupResetMethodIndex int=NULL
	,	@LookupResetPeriodIndex int=NULL
	,	@AllocationGuid uniqueidentifier=NULL
	,	@AssignedProductGuid uniqueidentifier=NULL
	,	@AssignedApplicationStringGuid uniqueidentifier=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideLimit BIT=0 
	,	@NullOverrideNext BIT=0 
	,	@NullOverrideResetMultiple BIT=0 
	,	@NullOverrideResetDate BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverrideLookupAllocationTypeIndex BIT=0 
	,	@NullOverrideLookupResetMethodIndex BIT=0 
	,	@NullOverrideLookupResetPeriodIndex BIT=0 
	,	@NullOverrideAllocationGuid BIT=0 
	,	@NullOverrideAssignedProductGuid BIT=0 
	,	@NullOverrideAssignedApplicationStringGuid BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_AllocationLineItemsUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:29.3563828 -05:00
	-- Purpose: Update table [dbo].[tblAllocationLineItems]
	-- Notes:
	-- 1. @AllocationLineItemGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblAllocationLineItems] WHERE AllocationLineItemGuid=@AllocationLineItemGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblAllocationLineItems] SET
			[Limit]=(CASE ISNULL(@NullOverrideLimit,0) WHEN 1 THEN @Limit ELSE ISNULL(@Limit,[Limit]) END)
		,	[Next]=(CASE ISNULL(@NullOverrideNext,0) WHEN 1 THEN @Next ELSE ISNULL(@Next,[Next]) END)
		,	[ResetMultiple]=(CASE ISNULL(@NullOverrideResetMultiple,0) WHEN 1 THEN @ResetMultiple ELSE ISNULL(@ResetMultiple,[ResetMultiple]) END)
		,	[ResetDate]=(CASE ISNULL(@NullOverrideResetDate,0) WHEN 1 THEN @ResetDate ELSE ISNULL(@ResetDate,[ResetDate]) END)
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[LookupAllocationTypeIndex]=(CASE ISNULL(@NullOverrideLookupAllocationTypeIndex,0) WHEN 1 THEN @LookupAllocationTypeIndex ELSE ISNULL(@LookupAllocationTypeIndex,[LookupAllocationTypeIndex]) END)
		,	[LookupResetMethodIndex]=(CASE ISNULL(@NullOverrideLookupResetMethodIndex,0) WHEN 1 THEN @LookupResetMethodIndex ELSE ISNULL(@LookupResetMethodIndex,[LookupResetMethodIndex]) END)
		,	[LookupResetPeriodIndex]=(CASE ISNULL(@NullOverrideLookupResetPeriodIndex,0) WHEN 1 THEN @LookupResetPeriodIndex ELSE ISNULL(@LookupResetPeriodIndex,[LookupResetPeriodIndex]) END)
		,	[AllocationGuid]=(CASE ISNULL(@NullOverrideAllocationGuid,0) WHEN 1 THEN @AllocationGuid ELSE ISNULL(@AllocationGuid,[AllocationGuid]) END)
		,	[AssignedProductGuid]=(CASE ISNULL(@NullOverrideAssignedProductGuid,0) WHEN 1 THEN @AssignedProductGuid ELSE ISNULL(@AssignedProductGuid,[AssignedProductGuid]) END)
		,	[AssignedApplicationStringGuid]=(CASE ISNULL(@NullOverrideAssignedApplicationStringGuid,0) WHEN 1 THEN @AssignedApplicationStringGuid ELSE ISNULL(@AssignedApplicationStringGuid,[AssignedApplicationStringGuid]) END)
		WHERE	AllocationLineItemGuid=@AllocationLineItemGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblAllocationLineItems]           
		WHERE AllocationLineItemGuid=@AllocationLineItemGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_AllocationLineItemsUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
