CREATE PROCEDURE [dbo].[gsp_ExportRequestUpdateByPK]
(
		@ExportRequestGuid uniqueidentifier
	,	@RequestID nvarchar(200)=NULL
	,	@InterfaceID nvarchar(200)=NULL
	,	@OwnerCode nvarchar(10)=NULL
	,	@UploadStagingFolder nvarchar(200)=NULL
	,	@ArchiveFolder nvarchar(200)=NULL
	,	@ConnectionInfo nvarchar(max)=NULL
	,	@SendingCompanyCode nvarchar(50)=NULL
	,	@SendViaFTP bit=NULL
	,	@SendSecure bit=NULL
	,	@CompanyNames nvarchar(max)=NULL
	,	@LatestRowVersion bigint=NULL
	,	@LastExportTime datetimeoffset(7)=NULL
	,	@ExportFrequency int=NULL
	,	@BaselineDate datetimeoffset(7)=NULL
	,	@ExcludeEmptyFiles bit=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,   @SendMethod INT=0
	,	@WebServicePluginType NVARCHAR(100)=NULL
	,	@WebServiceConfiguration NVARCHAR(512)=NULL
	,	@NullOverrideRequestID BIT=0 
	,	@NullOverrideInterfaceID BIT=0 
	,	@NullOverrideOwnerCode BIT=0 
	,	@NullOverrideUploadStagingFolder BIT=0 
	,	@NullOverrideArchiveFolder BIT=0 
	,	@NullOverrideConnectionInfo BIT=0 
	,	@NullOverrideSendingCompanyCode BIT=0 
	,	@NullOverrideSendViaFTP BIT=0 
	,	@NullOverrideSendSecure BIT=0 
	,	@NullOverrideCompanyNames BIT=0 
	,	@NullOverrideLatestRowVersion BIT=0 
	,	@NullOverrideLastExportTime BIT=0 
	,	@NullOverrideExportFrequency BIT=0 
	,	@NullOverrideBaselineDate BIT=0 
	,	@NullOverrideExcludeEmptyFiles BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverrideSendMethod BIT=0
	,	@NullOverrideWebServicePluginType BIT=0
	,	@NullOverrideWebServiceConfiguration BIT=0
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_ExportRequestUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:29.5073979 -05:00
	-- Purpose: Update table [dbo].[tblExportRequest]
	-- Notes:
	-- 1. @ExportRequestGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblExportRequest] WHERE ExportRequestGuid=@ExportRequestGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblExportRequest] SET
			[RequestID]=(CASE ISNULL(@NullOverrideRequestID,0) WHEN 1 THEN @RequestID ELSE ISNULL(@RequestID,[RequestID]) END)
		,	[InterfaceID]=(CASE ISNULL(@NullOverrideInterfaceID,0) WHEN 1 THEN @InterfaceID ELSE ISNULL(@InterfaceID,[InterfaceID]) END)
		,	[OwnerCode]=(CASE ISNULL(@NullOverrideOwnerCode,0) WHEN 1 THEN @OwnerCode ELSE ISNULL(@OwnerCode,[OwnerCode]) END)
		,	[UploadStagingFolder]=(CASE ISNULL(@NullOverrideUploadStagingFolder,0) WHEN 1 THEN @UploadStagingFolder ELSE ISNULL(@UploadStagingFolder,[UploadStagingFolder]) END)
		,	[ArchiveFolder]=(CASE ISNULL(@NullOverrideArchiveFolder,0) WHEN 1 THEN @ArchiveFolder ELSE ISNULL(@ArchiveFolder,[ArchiveFolder]) END)
		,	[ConnectionInfo]=(CASE ISNULL(@NullOverrideConnectionInfo,0) WHEN 1 THEN @ConnectionInfo ELSE ISNULL(@ConnectionInfo,[ConnectionInfo]) END)
		,	[SendingCompanyCode]=(CASE ISNULL(@NullOverrideSendingCompanyCode,0) WHEN 1 THEN @SendingCompanyCode ELSE ISNULL(@SendingCompanyCode,[SendingCompanyCode]) END)
		,	[SendViaFTP]=(CASE ISNULL(@NullOverrideSendViaFTP,0) WHEN 1 THEN @SendViaFTP ELSE ISNULL(@SendViaFTP,[SendViaFTP]) END)
		,	[SendSecure]=(CASE ISNULL(@NullOverrideSendSecure,0) WHEN 1 THEN @SendSecure ELSE ISNULL(@SendSecure,[SendSecure]) END)
		,	[CompanyNames]=(CASE ISNULL(@NullOverrideCompanyNames,0) WHEN 1 THEN @CompanyNames ELSE ISNULL(@CompanyNames,[CompanyNames]) END)
		,	[LatestRowVersion]=(CASE ISNULL(@NullOverrideLatestRowVersion,0) WHEN 1 THEN @LatestRowVersion ELSE ISNULL(@LatestRowVersion,[LatestRowVersion]) END)
		,	[LastExportTime]=(CASE ISNULL(@NullOverrideLastExportTime,0) WHEN 1 THEN @LastExportTime ELSE ISNULL(@LastExportTime,[LastExportTime]) END)
		,	[ExportFrequency]=(CASE ISNULL(@NullOverrideExportFrequency,0) WHEN 1 THEN @ExportFrequency ELSE ISNULL(@ExportFrequency,[ExportFrequency]) END)
		,	[BaselineDate]=(CASE ISNULL(@NullOverrideBaselineDate,0) WHEN 1 THEN @BaselineDate ELSE ISNULL(@BaselineDate,[BaselineDate]) END)
		,	[ExcludeEmptyFiles]=(CASE ISNULL(@NullOverrideExcludeEmptyFiles,0) WHEN 1 THEN @ExcludeEmptyFiles ELSE ISNULL(@ExcludeEmptyFiles,[ExcludeEmptyFiles]) END)
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[SendMethod]=CASE ISNULL(@NullOverrideSendMethod,0) WHEN 1 THEN @SendMethod ELSE ISNULL(@SendMethod,[SendMethod]) END
		,	[WebServicePluginType]=CASE ISNULL(@NullOverrideWebServicePluginType,0) WHEN 1 THEN @WebServicePluginType ELSE ISNULL(@WebServicePluginType,[WebServicePluginType]) END
		,	[WebServiceConfiguration]=CASE ISNULL(@NullOverrideWebServiceConfiguration,0) WHEN 1 THEN @WebServiceConfiguration ELSE ISNULL(@WebServiceConfiguration,[WebServiceConfiguration]) END
		WHERE	ExportRequestGuid=@ExportRequestGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblExportRequest]           
		WHERE ExportRequestGuid=@ExportRequestGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_ExportRequestUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
