CREATE PROCEDURE [dbo].[gsp_TestSetTankResultsUpdateByPK]
(
		@TestSetTankResultGuid uniqueidentifier
	,	@ResultTimeStamp datetimeoffset(7)=NULL
	,	@TestSetName nvarchar(80)=NULL
	,	@Inspector nvarchar(100)=NULL
	,	@Supervisor nvarchar(100)=NULL
	,	@TankID nvarchar(50)=NULL
	,	@SampleNumber int=NULL
	,	@SampleSize float=NULL
	,	@IsRetest bit=NULL
	,	@PreviousSampleNumber int=NULL
	,	@DocumentNumber nvarchar(50)=NULL
	,	@Memo nvarchar(1000)=NULL
	,	@GallonsRepresented float=NULL
	,	@Override bit=NULL
	,	@DeleteFlag bit=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@SiteGuid uniqueidentifier=NULL
	,	@LookupTestSetStatusIndex int=NULL
	,	@TankGuid uniqueidentifier=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideResultTimeStamp BIT=0 
	,	@NullOverrideTestSetName BIT=0 
	,	@NullOverrideInspector BIT=0 
	,	@NullOverrideSupervisor BIT=0 
	,	@NullOverrideTankID BIT=0 
	,	@NullOverrideSampleNumber BIT=0 
	,	@NullOverrideSampleSize BIT=0 
	,	@NullOverrideIsRetest BIT=0 
	,	@NullOverridePreviousSampleNumber BIT=0 
	,	@NullOverrideDocumentNumber BIT=0 
	,	@NullOverrideMemo BIT=0 
	,	@NullOverrideGallonsRepresented BIT=0 
	,	@NullOverrideOverride BIT=0 
	,	@NullOverrideDeleteFlag BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverrideSiteGuid BIT=0 
	,	@NullOverrideLookupTestSetStatusIndex BIT=0 
	,	@NullOverrideTankGuid BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_TestSetTankResultsUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:29.8384310 -05:00
	-- Purpose: Update table [dbo].[tblTestSetTankResults]
	-- Notes:
	-- 1. @TestSetTankResultGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblTestSetTankResults] WHERE TestSetTankResultGuid=@TestSetTankResultGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblTestSetTankResults] SET
			[ResultTimeStamp]=(CASE ISNULL(@NullOverrideResultTimeStamp,0) WHEN 1 THEN @ResultTimeStamp ELSE ISNULL(@ResultTimeStamp,[ResultTimeStamp]) END)
		,	[TestSetName]=(CASE ISNULL(@NullOverrideTestSetName,0) WHEN 1 THEN @TestSetName ELSE ISNULL(@TestSetName,[TestSetName]) END)
		,	[Inspector]=(CASE ISNULL(@NullOverrideInspector,0) WHEN 1 THEN @Inspector ELSE ISNULL(@Inspector,[Inspector]) END)
		,	[Supervisor]=(CASE ISNULL(@NullOverrideSupervisor,0) WHEN 1 THEN @Supervisor ELSE ISNULL(@Supervisor,[Supervisor]) END)
		,	[TankID]=(CASE ISNULL(@NullOverrideTankID,0) WHEN 1 THEN @TankID ELSE ISNULL(@TankID,[TankID]) END)
		,	[SampleNumber]=(CASE ISNULL(@NullOverrideSampleNumber,0) WHEN 1 THEN @SampleNumber ELSE ISNULL(@SampleNumber,[SampleNumber]) END)
		,	[SampleSize]=(CASE ISNULL(@NullOverrideSampleSize,0) WHEN 1 THEN @SampleSize ELSE ISNULL(@SampleSize,[SampleSize]) END)
		,	[IsRetest]=(CASE ISNULL(@NullOverrideIsRetest,0) WHEN 1 THEN @IsRetest ELSE ISNULL(@IsRetest,[IsRetest]) END)
		,	[PreviousSampleNumber]=(CASE ISNULL(@NullOverridePreviousSampleNumber,0) WHEN 1 THEN @PreviousSampleNumber ELSE ISNULL(@PreviousSampleNumber,[PreviousSampleNumber]) END)
		,	[DocumentNumber]=(CASE ISNULL(@NullOverrideDocumentNumber,0) WHEN 1 THEN @DocumentNumber ELSE ISNULL(@DocumentNumber,[DocumentNumber]) END)
		,	[Memo]=(CASE ISNULL(@NullOverrideMemo,0) WHEN 1 THEN @Memo ELSE ISNULL(@Memo,[Memo]) END)
		,	[GallonsRepresented]=(CASE ISNULL(@NullOverrideGallonsRepresented,0) WHEN 1 THEN @GallonsRepresented ELSE ISNULL(@GallonsRepresented,[GallonsRepresented]) END)
		,	[Override]=(CASE ISNULL(@NullOverrideOverride,0) WHEN 1 THEN @Override ELSE ISNULL(@Override,[Override]) END)
		,	[DeleteFlag]=(CASE ISNULL(@NullOverrideDeleteFlag,0) WHEN 1 THEN @DeleteFlag ELSE ISNULL(@DeleteFlag,[DeleteFlag]) END)
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[SiteGuid]=(CASE ISNULL(@NullOverrideSiteGuid,0) WHEN 1 THEN @SiteGuid ELSE ISNULL(@SiteGuid,[SiteGuid]) END)
		,	[LookupTestSetStatusIndex]=(CASE ISNULL(@NullOverrideLookupTestSetStatusIndex,0) WHEN 1 THEN @LookupTestSetStatusIndex ELSE ISNULL(@LookupTestSetStatusIndex,[LookupTestSetStatusIndex]) END)
		,	[TankGuid]=(CASE ISNULL(@NullOverrideTankGuid,0) WHEN 1 THEN @TankGuid ELSE ISNULL(@TankGuid,[TankGuid]) END)
		WHERE	TestSetTankResultGuid=@TestSetTankResultGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblTestSetTankResults]           
		WHERE TestSetTankResultGuid=@TestSetTankResultGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_TestSetTankResultsUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
