CREATE PROCEDURE [dbo].[gsp_TransactionLineItemUserDataUpdateByPK]
(
		@TransactionLineItemUserDataGuid uniqueidentifier
	,	@UserData1 nvarchar(60)=NULL
	,	@UserData2 nvarchar(60)=NULL
	,	@UserData3 nvarchar(60)=NULL
	,	@UserData4 nvarchar(60)=NULL
	,	@UserData5 nvarchar(60)=NULL
	,	@UserData6 nvarchar(60)=NULL
	,	@UserData7 nvarchar(60)=NULL
	,	@UserData8 nvarchar(60)=NULL
	,	@UserData9 nvarchar(60)=NULL
	,	@UserData10 nvarchar(60)=NULL
	,	@UserData11 nvarchar(60)=NULL
	,	@UserData12 nvarchar(60)=NULL
	,	@UserData13 nvarchar(60)=NULL
	,	@UserData14 nvarchar(60)=NULL
	,	@UserData15 nvarchar(60)=NULL
	,	@UserData16 nvarchar(60)=NULL
	,	@UserData17 nvarchar(60)=NULL
	,	@UserData18 nvarchar(60)=NULL
	,	@UserData19 nvarchar(60)=NULL
	,	@UserData20 nvarchar(60)=NULL
	,	@UserData21 nvarchar(60)=NULL
	,	@UserData22 nvarchar(60)=NULL
	,	@UserData23 nvarchar(60)=NULL
	,	@UserData24 nvarchar(60)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@TransactionLineItemGuid uniqueidentifier=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideUserData1 BIT=0 
	,	@NullOverrideUserData2 BIT=0 
	,	@NullOverrideUserData3 BIT=0 
	,	@NullOverrideUserData4 BIT=0 
	,	@NullOverrideUserData5 BIT=0 
	,	@NullOverrideUserData6 BIT=0 
	,	@NullOverrideUserData7 BIT=0 
	,	@NullOverrideUserData8 BIT=0 
	,	@NullOverrideUserData9 BIT=0 
	,	@NullOverrideUserData10 BIT=0 
	,	@NullOverrideUserData11 BIT=0 
	,	@NullOverrideUserData12 BIT=0 
	,	@NullOverrideUserData13 BIT=0 
	,	@NullOverrideUserData14 BIT=0 
	,	@NullOverrideUserData15 BIT=0 
	,	@NullOverrideUserData16 BIT=0 
	,	@NullOverrideUserData17 BIT=0 
	,	@NullOverrideUserData18 BIT=0 
	,	@NullOverrideUserData19 BIT=0 
	,	@NullOverrideUserData20 BIT=0 
	,	@NullOverrideUserData21 BIT=0 
	,	@NullOverrideUserData22 BIT=0 
	,	@NullOverrideUserData23 BIT=0 
	,	@NullOverrideUserData24 BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverrideTransactionLineItemGuid BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_TransactionLineItemUserDataUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:29.8734345 -05:00
	-- Purpose: Update table [dbo].[tblTransactionLineItemUserData]
	-- Notes:
	-- 1. @TransactionLineItemUserDataGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblTransactionLineItemUserData] WHERE TransactionLineItemUserDataGuid=@TransactionLineItemUserDataGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblTransactionLineItemUserData] SET
			[UserData1]=(CASE ISNULL(@NullOverrideUserData1,0) WHEN 1 THEN @UserData1 ELSE ISNULL(@UserData1,[UserData1]) END)
		,	[UserData2]=(CASE ISNULL(@NullOverrideUserData2,0) WHEN 1 THEN @UserData2 ELSE ISNULL(@UserData2,[UserData2]) END)
		,	[UserData3]=(CASE ISNULL(@NullOverrideUserData3,0) WHEN 1 THEN @UserData3 ELSE ISNULL(@UserData3,[UserData3]) END)
		,	[UserData4]=(CASE ISNULL(@NullOverrideUserData4,0) WHEN 1 THEN @UserData4 ELSE ISNULL(@UserData4,[UserData4]) END)
		,	[UserData5]=(CASE ISNULL(@NullOverrideUserData5,0) WHEN 1 THEN @UserData5 ELSE ISNULL(@UserData5,[UserData5]) END)
		,	[UserData6]=(CASE ISNULL(@NullOverrideUserData6,0) WHEN 1 THEN @UserData6 ELSE ISNULL(@UserData6,[UserData6]) END)
		,	[UserData7]=(CASE ISNULL(@NullOverrideUserData7,0) WHEN 1 THEN @UserData7 ELSE ISNULL(@UserData7,[UserData7]) END)
		,	[UserData8]=(CASE ISNULL(@NullOverrideUserData8,0) WHEN 1 THEN @UserData8 ELSE ISNULL(@UserData8,[UserData8]) END)
		,	[UserData9]=(CASE ISNULL(@NullOverrideUserData9,0) WHEN 1 THEN @UserData9 ELSE ISNULL(@UserData9,[UserData9]) END)
		,	[UserData10]=(CASE ISNULL(@NullOverrideUserData10,0) WHEN 1 THEN @UserData10 ELSE ISNULL(@UserData10,[UserData10]) END)
		,	[UserData11]=(CASE ISNULL(@NullOverrideUserData11,0) WHEN 1 THEN @UserData11 ELSE ISNULL(@UserData11,[UserData11]) END)
		,	[UserData12]=(CASE ISNULL(@NullOverrideUserData12,0) WHEN 1 THEN @UserData12 ELSE ISNULL(@UserData12,[UserData12]) END)
		,	[UserData13]=(CASE ISNULL(@NullOverrideUserData13,0) WHEN 1 THEN @UserData13 ELSE ISNULL(@UserData13,[UserData13]) END)
		,	[UserData14]=(CASE ISNULL(@NullOverrideUserData14,0) WHEN 1 THEN @UserData14 ELSE ISNULL(@UserData14,[UserData14]) END)
		,	[UserData15]=(CASE ISNULL(@NullOverrideUserData15,0) WHEN 1 THEN @UserData15 ELSE ISNULL(@UserData15,[UserData15]) END)
		,	[UserData16]=(CASE ISNULL(@NullOverrideUserData16,0) WHEN 1 THEN @UserData16 ELSE ISNULL(@UserData16,[UserData16]) END)
		,	[UserData17]=(CASE ISNULL(@NullOverrideUserData17,0) WHEN 1 THEN @UserData17 ELSE ISNULL(@UserData17,[UserData17]) END)
		,	[UserData18]=(CASE ISNULL(@NullOverrideUserData18,0) WHEN 1 THEN @UserData18 ELSE ISNULL(@UserData18,[UserData18]) END)
		,	[UserData19]=(CASE ISNULL(@NullOverrideUserData19,0) WHEN 1 THEN @UserData19 ELSE ISNULL(@UserData19,[UserData19]) END)
		,	[UserData20]=(CASE ISNULL(@NullOverrideUserData20,0) WHEN 1 THEN @UserData20 ELSE ISNULL(@UserData20,[UserData20]) END)
		,	[UserData21]=(CASE ISNULL(@NullOverrideUserData21,0) WHEN 1 THEN @UserData21 ELSE ISNULL(@UserData21,[UserData21]) END)
		,	[UserData22]=(CASE ISNULL(@NullOverrideUserData22,0) WHEN 1 THEN @UserData22 ELSE ISNULL(@UserData22,[UserData22]) END)
		,	[UserData23]=(CASE ISNULL(@NullOverrideUserData23,0) WHEN 1 THEN @UserData23 ELSE ISNULL(@UserData23,[UserData23]) END)
		,	[UserData24]=(CASE ISNULL(@NullOverrideUserData24,0) WHEN 1 THEN @UserData24 ELSE ISNULL(@UserData24,[UserData24]) END)
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[TransactionLineItemGuid]=(CASE ISNULL(@NullOverrideTransactionLineItemGuid,0) WHEN 1 THEN @TransactionLineItemGuid ELSE ISNULL(@TransactionLineItemGuid,[TransactionLineItemGuid]) END)
		WHERE	TransactionLineItemUserDataGuid=@TransactionLineItemUserDataGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblTransactionLineItemUserData]           
		WHERE TransactionLineItemUserDataGuid=@TransactionLineItemUserDataGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_TransactionLineItemUserDataUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
