CREATE PROCEDURE [dbo].[gsp_SessionsUpdateByPK]
(
		@SessionGuid uniqueidentifier
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@Timeout int=NULL
	,	@SiteGuid uniqueidentifier=NULL
	,	@LoginSiteGuid uniqueidentifier=NULL
	,	@UserGuid uniqueidentifier=NULL
	,	@SqlServerSessionID int=NULL
	,	@SynchronizationNodeGuid uniqueidentifier=NULL
	,	@ClientIpAddress nvarchar(50)=NULL
	,	@WebServerName nvarchar(500)=NULL
	,	@WebServerIpAddress nvarchar(50)=NULL
	,	@SessionTokenID uniqueidentifier=NULL
	,	@SessionFailedFlag bit=NULL
	,	@CSRFToken nvarchar(256)=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverrideTimeout BIT=0 
	,	@NullOverrideSiteGuid BIT=0 
	,	@NullOverrideLoginSiteGuid BIT=0 
	,	@NullOverrideUserGuid BIT=0 
	,	@NullOverrideSqlServerSessionID BIT=0 
	,	@NullOverrideSynchronizationNodeGuid BIT=0 
	,	@NullOverrideClientIpAddress BIT=0 
	,	@NullOverrideWebServerName BIT=0 
	,	@NullOverrideWebServerIpAddress BIT=0 
	,	@NullOverrideSessionTokenID BIT=0 
	,	@NullOverrideSessionFailedFlag BIT=0 
	,	@NullOverrideCSRFToken BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_SessionsUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:29.7454217 -05:00
	-- Purpose: Update table [dbo].[tblSessions]
	-- Notes:
	-- 1. @SessionGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblSessions] WHERE SessionGuid=@SessionGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblSessions] SET
			[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[Timeout]=(CASE ISNULL(@NullOverrideTimeout,0) WHEN 1 THEN @Timeout ELSE ISNULL(@Timeout,[Timeout]) END)
		,	[SiteGuid]=(CASE ISNULL(@NullOverrideSiteGuid,0) WHEN 1 THEN @SiteGuid ELSE ISNULL(@SiteGuid,[SiteGuid]) END)
		,	[LoginSiteGuid]=(CASE ISNULL(@NullOverrideLoginSiteGuid,0) WHEN 1 THEN @LoginSiteGuid ELSE ISNULL(@LoginSiteGuid,[LoginSiteGuid]) END)
		,	[UserGuid]=(CASE ISNULL(@NullOverrideUserGuid,0) WHEN 1 THEN @UserGuid ELSE ISNULL(@UserGuid,[UserGuid]) END)
		,	[SqlServerSessionID]=(CASE ISNULL(@NullOverrideSqlServerSessionID,0) WHEN 1 THEN @SqlServerSessionID ELSE ISNULL(@SqlServerSessionID,[SqlServerSessionID]) END)
		,	[SynchronizationNodeGuid]=(CASE ISNULL(@NullOverrideSynchronizationNodeGuid,0) WHEN 1 THEN @SynchronizationNodeGuid ELSE ISNULL(@SynchronizationNodeGuid,[SynchronizationNodeGuid]) END)
		,	[ClientIpAddress]=(CASE ISNULL(@NullOverrideClientIpAddress,0) WHEN 1 THEN @ClientIpAddress ELSE ISNULL(@ClientIpAddress,[ClientIpAddress]) END)
		,	[WebServerName]=(CASE ISNULL(@NullOverrideWebServerName,0) WHEN 1 THEN @WebServerName ELSE ISNULL(@WebServerName,[WebServerName]) END)
		,	[WebServerIpAddress]=(CASE ISNULL(@NullOverrideWebServerIpAddress,0) WHEN 1 THEN @WebServerIpAddress ELSE ISNULL(@WebServerIpAddress,[WebServerIpAddress]) END)
		,	[SessionTokenID]=(CASE ISNULL(@NullOverrideSessionTokenID,0) WHEN 1 THEN @SessionTokenID ELSE ISNULL(@SessionTokenID,[SessionTokenID]) END)
		,	[SessionFailedFlag]=(CASE ISNULL(@NullOverrideSessionFailedFlag,0) WHEN 1 THEN @SessionFailedFlag ELSE ISNULL(@SessionFailedFlag,[SessionFailedFlag]) END)
		,	[CSRFToken]=(CASE ISNULL(@NullOverrideCSRFToken,0) WHEN 1 THEN @CSRFToken ELSE ISNULL(@CSRFToken,[CSRFToken]) END)
		WHERE	SessionGuid=@SessionGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblSessions]           
		WHERE SessionGuid=@SessionGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_SessionsUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
