CREATE PROCEDURE [dbo].[gsp_PointTemplateUpdateByPK]
(
		@PointTemplateGuid uniqueidentifier
	,	@ID nvarchar(30)=NULL
	,	@Description nvarchar(50)=NULL
	,	@Standard bit=NULL
	,	@ExecutionInterval int=NULL
	,	@LevelUnitIndex int=NULL
	,	@TemperatureUnitIndex int=NULL
	,	@DensityUnitIndex int=NULL
	,	@PressureUnitIndex int=NULL
	,	@FlowUnitIndex int=NULL
	,	@VolumeUnitIndex int=NULL
	,	@MassUnitIndex int=NULL
	,	@VelocityUnitIndex int=NULL
	,	@MassFlowUnitIndex int=NULL
	,	@LevelDecimalPlaces tinyint=NULL
	,	@TemperatureDecimalPlaces tinyint=NULL
	,	@DensityDecimalPlaces tinyint=NULL
	,	@PressureDecimalPlaces tinyint=NULL
	,	@FlowDecimalPlaces tinyint=NULL
	,	@VolumeDecimalPlaces tinyint=NULL
	,	@MassDecimalPlaces tinyint=NULL
	,	@VelocityDecimalPlaces tinyint=NULL
	,	@MassFlowDecimalPlaces tinyint=NULL
	,	@LevelMaximum float=NULL
	,	@LevelMinimum float=NULL
	,	@TemperatureMaximum float=NULL
	,	@TemperatureMinimum float=NULL
	,	@DensityMaximum float=NULL
	,	@DensityMinimum float=NULL
	,	@PressureMaximum float=NULL
	,	@PressureMinimum float=NULL
	,	@VolumetricFlowMaximum float=NULL
	,	@VolumetricFlowMinimum float=NULL
	,	@VolumeMaximum float=NULL
	,	@VolumeMinimum float=NULL
	,	@MassMaximum float=NULL
	,	@MassMinimum float=NULL
	,	@VelocityMaximum float=NULL
	,	@VelocityMinimum float=NULL
	,	@MassFlowMaximum float=NULL
	,	@MassFlowMinimum float=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@SiteGuid uniqueidentifier=NULL
	,	@PointTemplateTypeApplicationStringGuid uniqueidentifier=NULL
	,	@ProfileImageGuid uniqueidentifier=NULL
	,	@DefaultDrawingGuid uniqueidentifier=NULL
	,	@PointCommandStatus XML=NULL
	,	@DeviceAlarmMaps XML=NULL
	,	@PointLogicScript nvarchar(max)=null
	,	@Version int=null 
	,	@_ClusterIdx bigint=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideID BIT=0 
	,	@NullOverrideDescription BIT=0 
	,	@NullOverrideStandard BIT=0 
	,	@NullOverrideExecutionInterval BIT=0 
	,	@NullOverrideLevelUnitIndex BIT=0 
	,	@NullOverrideTemperatureUnitIndex BIT=0 
	,	@NullOverrideDensityUnitIndex BIT=0 
	,	@NullOverridePressureUnitIndex BIT=0 
	,	@NullOverrideFlowUnitIndex BIT=0 
	,	@NullOverrideVolumeUnitIndex BIT=0 
	,	@NullOverrideMassUnitIndex BIT=0 
	,	@NullOverrideVelocityUnitIndex BIT=0 
	,	@NullOverrideMassFlowUnitIndex BIT=0 
	,	@NullOverrideLevelDecimalPlaces BIT=0 
	,	@NullOverrideTemperatureDecimalPlaces BIT=0 
	,	@NullOverrideDensityDecimalPlaces BIT=0 
	,	@NullOverridePressureDecimalPlaces BIT=0 
	,	@NullOverrideFlowDecimalPlaces BIT=0 
	,	@NullOverrideVolumeDecimalPlaces BIT=0 
	,	@NullOverrideMassDecimalPlaces BIT=0 
	,	@NullOverrideVelocityDecimalPlaces BIT=0 
	,	@NullOverrideMassFlowDecimalPlaces BIT=0 
	,	@NullOverrideLevelMaximum BIT=0 
	,	@NullOverrideLevelMinimum BIT=0 
	,	@NullOverrideTemperatureMaximum BIT=0 
	,	@NullOverrideTemperatureMinimum BIT=0 
	,	@NullOverrideDensityMaximum BIT=0 
	,	@NullOverrideDensityMinimum BIT=0 
	,	@NullOverridePressureMaximum BIT=0 
	,	@NullOverridePressureMinimum BIT=0 
	,	@NullOverrideVolumetricFlowMaximum BIT=0 
	,	@NullOverrideVolumetricFlowMinimum BIT=0 
	,	@NullOverrideVolumeMaximum BIT=0 
	,	@NullOverrideVolumeMinimum BIT=0 
	,	@NullOverrideMassMaximum BIT=0 
	,	@NullOverrideMassMinimum BIT=0 
	,	@NullOverrideVelocityMaximum BIT=0 
	,	@NullOverrideVelocityMinimum BIT=0 
	,	@NullOverrideMassFlowMaximum BIT=0 
	,	@NullOverrideMassFlowMinimum BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverrideSiteGuid BIT=0 
	,	@NullOverridePointTemplateTypeApplicationStringGuid BIT=0
	,	@NullOverrideProfileImageGuid BIT=0
	,	@NullOverrideDefaultDrawingGuid BIT=0 
	,	@NullOverridePointCommandStatus BIT = 0
	,	@NullOverrideDeviceAlarmMaps BIT = 0
	,	@NullOverridePointLogicScript BIT = 0
	,	@NullOverrideVersion BIT = 0
	,	@NullOverride_ClusterIdx BIT=0	
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_PointTemplateUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2015-12-18 07:52:08.9301774 -05:00
	-- Purpose: Update table [dbo].[tblPointTemplate]
	-- Notes:
	-- 1. @PointTemplateGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblPointTemplate] WHERE PointTemplateGuid=@PointTemplateGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblPointTemplate] SET
			[ID]=(CASE ISNULL(@NullOverrideID,0) WHEN 1 THEN @ID ELSE ISNULL(@ID,[ID]) END)
		,	[Description]=(CASE ISNULL(@NullOverrideDescription,0) WHEN 1 THEN @Description ELSE ISNULL(@Description,[Description]) END)
		,	[Standard]=(CASE ISNULL(@NullOverrideStandard,0) WHEN 1 THEN @Standard ELSE ISNULL(@Standard,[Standard]) END)
		,	[ExecutionInterval]=(CASE ISNULL(@NullOverrideExecutionInterval,0) WHEN 1 THEN @ExecutionInterval ELSE ISNULL(@ExecutionInterval,[ExecutionInterval]) END)
		,	[LevelUnitIndex]=(CASE ISNULL(@NullOverrideLevelUnitIndex,0) WHEN 1 THEN @LevelUnitIndex ELSE ISNULL(@LevelUnitIndex,[LevelUnitIndex]) END)
		,	[TemperatureUnitIndex]=(CASE ISNULL(@NullOverrideTemperatureUnitIndex,0) WHEN 1 THEN @TemperatureUnitIndex ELSE ISNULL(@TemperatureUnitIndex,[TemperatureUnitIndex]) END)
		,	[DensityUnitIndex]=(CASE ISNULL(@NullOverrideDensityUnitIndex,0) WHEN 1 THEN @DensityUnitIndex ELSE ISNULL(@DensityUnitIndex,[DensityUnitIndex]) END)
		,	[PressureUnitIndex]=(CASE ISNULL(@NullOverridePressureUnitIndex,0) WHEN 1 THEN @PressureUnitIndex ELSE ISNULL(@PressureUnitIndex,[PressureUnitIndex]) END)
		,	[FlowUnitIndex]=(CASE ISNULL(@NullOverrideFlowUnitIndex,0) WHEN 1 THEN @FlowUnitIndex ELSE ISNULL(@FlowUnitIndex,[FlowUnitIndex]) END)
		,	[VolumeUnitIndex]=(CASE ISNULL(@NullOverrideVolumeUnitIndex,0) WHEN 1 THEN @VolumeUnitIndex ELSE ISNULL(@VolumeUnitIndex,[VolumeUnitIndex]) END)
		,	[MassUnitIndex]=(CASE ISNULL(@NullOverrideMassUnitIndex,0) WHEN 1 THEN @MassUnitIndex ELSE ISNULL(@MassUnitIndex,[MassUnitIndex]) END)
		,	[VelocityUnitIndex]=(CASE ISNULL(@NullOverrideVelocityUnitIndex,0) WHEN 1 THEN @VelocityUnitIndex ELSE ISNULL(@VelocityUnitIndex,[VelocityUnitIndex]) END)
		,	[MassFlowUnitIndex]=(CASE ISNULL(@NullOverrideMassFlowUnitIndex,0) WHEN 1 THEN @MassFlowUnitIndex ELSE ISNULL(@MassFlowUnitIndex,[MassFlowUnitIndex]) END)
		,	[LevelDecimalPlaces]=(CASE ISNULL(@NullOverrideLevelDecimalPlaces,0) WHEN 1 THEN @LevelDecimalPlaces ELSE ISNULL(@LevelDecimalPlaces,[LevelDecimalPlaces]) END)
		,	[TemperatureDecimalPlaces]=(CASE ISNULL(@NullOverrideTemperatureDecimalPlaces,0) WHEN 1 THEN @TemperatureDecimalPlaces ELSE ISNULL(@TemperatureDecimalPlaces,[TemperatureDecimalPlaces]) END)
		,	[DensityDecimalPlaces]=(CASE ISNULL(@NullOverrideDensityDecimalPlaces,0) WHEN 1 THEN @DensityDecimalPlaces ELSE ISNULL(@DensityDecimalPlaces,[DensityDecimalPlaces]) END)
		,	[PressureDecimalPlaces]=(CASE ISNULL(@NullOverridePressureDecimalPlaces,0) WHEN 1 THEN @PressureDecimalPlaces ELSE ISNULL(@PressureDecimalPlaces,[PressureDecimalPlaces]) END)
		,	[FlowDecimalPlaces]=(CASE ISNULL(@NullOverrideFlowDecimalPlaces,0) WHEN 1 THEN @FlowDecimalPlaces ELSE ISNULL(@FlowDecimalPlaces,[FlowDecimalPlaces]) END)
		,	[VolumeDecimalPlaces]=(CASE ISNULL(@NullOverrideVolumeDecimalPlaces,0) WHEN 1 THEN @VolumeDecimalPlaces ELSE ISNULL(@VolumeDecimalPlaces,[VolumeDecimalPlaces]) END)
		,	[MassDecimalPlaces]=(CASE ISNULL(@NullOverrideMassDecimalPlaces,0) WHEN 1 THEN @MassDecimalPlaces ELSE ISNULL(@MassDecimalPlaces,[MassDecimalPlaces]) END)
		,	[VelocityDecimalPlaces]=(CASE ISNULL(@NullOverrideVelocityDecimalPlaces,0) WHEN 1 THEN @VelocityDecimalPlaces ELSE ISNULL(@VelocityDecimalPlaces,[VelocityDecimalPlaces]) END)
		,	[MassFlowDecimalPlaces]=(CASE ISNULL(@NullOverrideMassFlowDecimalPlaces,0) WHEN 1 THEN @MassFlowDecimalPlaces ELSE ISNULL(@MassFlowDecimalPlaces,[MassFlowDecimalPlaces]) END)
		,	[LevelMaximum]=(CASE ISNULL(@NullOverrideLevelMaximum,0) WHEN 1 THEN @LevelMaximum ELSE ISNULL(@LevelMaximum,[LevelMaximum]) END)
		,	[LevelMinimum]=(CASE ISNULL(@NullOverrideLevelMinimum,0) WHEN 1 THEN @LevelMinimum ELSE ISNULL(@LevelMinimum,[LevelMinimum]) END)
		,	[TemperatureMaximum]=(CASE ISNULL(@NullOverrideTemperatureMaximum,0) WHEN 1 THEN @TemperatureMaximum ELSE ISNULL(@TemperatureMaximum,[TemperatureMaximum]) END)
		,	[TemperatureMinimum]=(CASE ISNULL(@NullOverrideTemperatureMinimum,0) WHEN 1 THEN @TemperatureMinimum ELSE ISNULL(@TemperatureMinimum,[TemperatureMinimum]) END)
		,	[DensityMaximum]=(CASE ISNULL(@NullOverrideDensityMaximum,0) WHEN 1 THEN @DensityMaximum ELSE ISNULL(@DensityMaximum,[DensityMaximum]) END)
		,	[DensityMinimum]=(CASE ISNULL(@NullOverrideDensityMinimum,0) WHEN 1 THEN @DensityMinimum ELSE ISNULL(@DensityMinimum,[DensityMinimum]) END)
		,	[PressureMaximum]=(CASE ISNULL(@NullOverridePressureMaximum,0) WHEN 1 THEN @PressureMaximum ELSE ISNULL(@PressureMaximum,[PressureMaximum]) END)
		,	[PressureMinimum]=(CASE ISNULL(@NullOverridePressureMinimum,0) WHEN 1 THEN @PressureMinimum ELSE ISNULL(@PressureMinimum,[PressureMinimum]) END)
		,	[VolumetricFlowMaximum]=(CASE ISNULL(@NullOverrideVolumetricFlowMaximum,0) WHEN 1 THEN @VolumetricFlowMaximum ELSE ISNULL(@VolumetricFlowMaximum,[VolumetricFlowMaximum]) END)
		,	[VolumetricFlowMinimum]=(CASE ISNULL(@NullOverrideVolumetricFlowMinimum,0) WHEN 1 THEN @VolumetricFlowMinimum ELSE ISNULL(@VolumetricFlowMinimum,[VolumetricFlowMinimum]) END)
		,	[VolumeMaximum]=(CASE ISNULL(@NullOverrideVolumeMaximum,0) WHEN 1 THEN @VolumeMaximum ELSE ISNULL(@VolumeMaximum,[VolumeMaximum]) END)
		,	[VolumeMinimum]=(CASE ISNULL(@NullOverrideVolumeMinimum,0) WHEN 1 THEN @VolumeMinimum ELSE ISNULL(@VolumeMinimum,[VolumeMinimum]) END)
		,	[MassMaximum]=(CASE ISNULL(@NullOverrideMassMaximum,0) WHEN 1 THEN @MassMaximum ELSE ISNULL(@MassMaximum,[MassMaximum]) END)
		,	[MassMinimum]=(CASE ISNULL(@NullOverrideMassMinimum,0) WHEN 1 THEN @MassMinimum ELSE ISNULL(@MassMinimum,[MassMinimum]) END)
		,	[VelocityMaximum]=(CASE ISNULL(@NullOverrideVelocityMaximum,0) WHEN 1 THEN @VelocityMaximum ELSE ISNULL(@VelocityMaximum,[VelocityMaximum]) END)
		,	[VelocityMinimum]=(CASE ISNULL(@NullOverrideVelocityMinimum,0) WHEN 1 THEN @VelocityMinimum ELSE ISNULL(@VelocityMinimum,[VelocityMinimum]) END)
		,	[MassFlowMaximum]=(CASE ISNULL(@NullOverrideMassFlowMaximum,0) WHEN 1 THEN @MassFlowMaximum ELSE ISNULL(@MassFlowMaximum,[MassFlowMaximum]) END)
		,	[MassFlowMinimum]=(CASE ISNULL(@NullOverrideMassFlowMinimum,0) WHEN 1 THEN @MassFlowMinimum ELSE ISNULL(@MassFlowMinimum,[MassFlowMinimum]) END)
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[SiteGuid]=(CASE ISNULL(@NullOverrideSiteGuid,0) WHEN 1 THEN @SiteGuid ELSE ISNULL(@SiteGuid,[SiteGuid]) END)		
		,	[PointTemplateTypeApplicationStringGuid]=(CASE ISNULL(@NullOverridePointTemplateTypeApplicationStringGuid,0) WHEN 1 THEN @PointTemplateTypeApplicationStringGuid ELSE ISNULL(@PointTemplateTypeApplicationStringGuid,[PointTemplateTypeApplicationStringGuid]) END)
		,	[ProfileImageGuid]=(CASE ISNULL(@NullOverrideProfileImageGuid,0) WHEN 1 THEN @ProfileImageGuid ELSE ISNULL(@ProfileImageGuid,[ProfileImageGuid]) END)
		,  [DefaultDrawingGuid]=(CASE ISNULL(@NullOverrideDefaultDrawingGuid,0) WHEN 1 THEN @DefaultDrawingGuid ELSE ISNULL(@DefaultDrawingGuid,[DefaultDrawingGuid]) END)
		,	[PointCommandStatus] = (CASE ISNULL(@NullOverridePointCommandStatus,0) WHEN 1 THEN @PointCommandStatus ELSE ISNULL(@PointCommandStatus,[PointCommandStatus]) END)
		,	[DeviceAlarmMaps] = (CASE ISNULL(@NullOverrideDeviceAlarmMaps,0) WHEN 1 THEN @DeviceAlarmMaps ELSE ISNULL(@DeviceAlarmMaps,[DeviceAlarmMaps]) END)
		,	[PointLogicScript] = (CASE ISNULL(@NullOverridePointLogicScript,0) WHEN 1 THEN @PointLogicScript ELSE ISNULL(@PointLogicScript,[PointLogicScript]) END)
		,	[Version] = (CASE ISNULL(@NullOverrideVersion,0) WHEN 1 THEN @Version ELSE ISNULL(@Version,[Version]) END)
			WHERE	PointTemplateGuid=@PointTemplateGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblPointTemplate]           
		WHERE PointTemplateGuid=@PointTemplateGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_PointTemplateUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
GO
 
