CREATE PROCEDURE [dbo].[gsp_TransactionPIDXUpdateByPK]
(
		@TransactionPIDXGuid uniqueidentifier
	,	@AuthorizationNumber nvarchar(8)=NULL
	,	@SentFlag bit=NULL
	,	@DateSent datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@BrokenBlend bit=NULL
	,	@PIDXProfileGuid uniqueidentifier=NULL
	,	@TransactionGuid uniqueidentifier=NULL
	,	@CompanyPersonnelToShipToBillToGuid uniqueidentifier=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideAuthorizationNumber BIT=0 
	,	@NullOverrideSentFlag BIT=0 
	,	@NullOverrideDateSent BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverrideBrokenBlend BIT=0 
	,	@NullOverridePIDXProfileGuid BIT=0 
	,	@NullOverrideTransactionGuid BIT=0 
	,	@NullOverrideCompanyPersonnelToShipToBillToGuid BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_TransactionPIDXUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:29.8814353 -05:00
	-- Purpose: Update table [dbo].[tblTransactionPIDX]
	-- Notes:
	-- 1. @TransactionPIDXGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblTransactionPIDX] WHERE TransactionPIDXGuid=@TransactionPIDXGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblTransactionPIDX] SET
			[AuthorizationNumber]=(CASE ISNULL(@NullOverrideAuthorizationNumber,0) WHEN 1 THEN @AuthorizationNumber ELSE ISNULL(@AuthorizationNumber,[AuthorizationNumber]) END)
		,	[SentFlag]=(CASE ISNULL(@NullOverrideSentFlag,0) WHEN 1 THEN @SentFlag ELSE ISNULL(@SentFlag,[SentFlag]) END)
		,	[DateSent]=(CASE ISNULL(@NullOverrideDateSent,0) WHEN 1 THEN @DateSent ELSE ISNULL(@DateSent,[DateSent]) END)
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[BrokenBlend]=(CASE ISNULL(@NullOverrideBrokenBlend,0) WHEN 1 THEN @BrokenBlend ELSE ISNULL(@BrokenBlend,[BrokenBlend]) END)
		,	[PIDXProfileGuid]=(CASE ISNULL(@NullOverridePIDXProfileGuid,0) WHEN 1 THEN @PIDXProfileGuid ELSE ISNULL(@PIDXProfileGuid,[PIDXProfileGuid]) END)
		,	[TransactionGuid]=(CASE ISNULL(@NullOverrideTransactionGuid,0) WHEN 1 THEN @TransactionGuid ELSE ISNULL(@TransactionGuid,[TransactionGuid]) END)
		,	[CompanyPersonnelToShipToBillToGuid]=(CASE ISNULL(@NullOverrideCompanyPersonnelToShipToBillToGuid,0) WHEN 1 THEN @CompanyPersonnelToShipToBillToGuid ELSE ISNULL(@CompanyPersonnelToShipToBillToGuid,[CompanyPersonnelToShipToBillToGuid]) END)
		WHERE	TransactionPIDXGuid=@TransactionPIDXGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblTransactionPIDX]           
		WHERE TransactionPIDXGuid=@TransactionPIDXGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_TransactionPIDXUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
