CREATE PROCEDURE [dbo].[gsp_TankQualityTagLogUpdateByPK]
(
		@TankQualityTagLogGuid uniqueidentifier
	,	@TankID nvarchar(50)=NULL
	,	@VesselType nvarchar(50)=NULL
	,	@QualityTagName nvarchar(50)=NULL
	,	@TaggedDate datetimeoffset(7)=NULL
	,	@TaggedBy nvarchar(50)=NULL
	,	@Memo nvarchar(1000)=NULL
	,	@RemovedDate datetimeoffset(7)=NULL
	,	@RemovedBy nvarchar(255)=NULL
	,	@DeleteFlag bit=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@TagNumber int=NULL
	,	@SiteGuid uniqueidentifier=NULL
	,	@LookupVesselTypeIndex int=NULL
	,	@QualityTagGuid uniqueidentifier=NULL
	,	@TankGuid uniqueidentifier=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideTankID BIT=0 
	,	@NullOverrideVesselType BIT=0 
	,	@NullOverrideQualityTagName BIT=0 
	,	@NullOverrideTaggedDate BIT=0 
	,	@NullOverrideTaggedBy BIT=0 
	,	@NullOverrideMemo BIT=0 
	,	@NullOverrideRemovedDate BIT=0 
	,	@NullOverrideRemovedBy BIT=0 
	,	@NullOverrideDeleteFlag BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverrideTagNumber BIT=0 
	,	@NullOverrideSiteGuid BIT=0 
	,	@NullOverrideLookupVesselTypeIndex BIT=0 
	,	@NullOverrideQualityTagGuid BIT=0 
	,	@NullOverrideTankGuid BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_TankQualityTagLogUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:29.8224294 -05:00
	-- Purpose: Update table [dbo].[tblTankQualityTagLog]
	-- Notes:
	-- 1. @TankQualityTagLogGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblTankQualityTagLog] WHERE TankQualityTagLogGuid=@TankQualityTagLogGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblTankQualityTagLog] SET
			[TankID]=(CASE ISNULL(@NullOverrideTankID,0) WHEN 1 THEN @TankID ELSE ISNULL(@TankID,[TankID]) END)
		,	[VesselType]=(CASE ISNULL(@NullOverrideVesselType,0) WHEN 1 THEN @VesselType ELSE ISNULL(@VesselType,[VesselType]) END)
		,	[QualityTagName]=(CASE ISNULL(@NullOverrideQualityTagName,0) WHEN 1 THEN @QualityTagName ELSE ISNULL(@QualityTagName,[QualityTagName]) END)
		,	[TaggedDate]=(CASE ISNULL(@NullOverrideTaggedDate,0) WHEN 1 THEN @TaggedDate ELSE ISNULL(@TaggedDate,[TaggedDate]) END)
		,	[TaggedBy]=(CASE ISNULL(@NullOverrideTaggedBy,0) WHEN 1 THEN @TaggedBy ELSE ISNULL(@TaggedBy,[TaggedBy]) END)
		,	[Memo]=(CASE ISNULL(@NullOverrideMemo,0) WHEN 1 THEN @Memo ELSE ISNULL(@Memo,[Memo]) END)
		,	[RemovedDate]=(CASE ISNULL(@NullOverrideRemovedDate,0) WHEN 1 THEN @RemovedDate ELSE ISNULL(@RemovedDate,[RemovedDate]) END)
		,	[RemovedBy]=(CASE ISNULL(@NullOverrideRemovedBy,0) WHEN 1 THEN @RemovedBy ELSE ISNULL(@RemovedBy,[RemovedBy]) END)
		,	[DeleteFlag]=(CASE ISNULL(@NullOverrideDeleteFlag,0) WHEN 1 THEN @DeleteFlag ELSE ISNULL(@DeleteFlag,[DeleteFlag]) END)
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[TagNumber]=(CASE ISNULL(@NullOverrideTagNumber,0) WHEN 1 THEN @TagNumber ELSE ISNULL(@TagNumber,[TagNumber]) END)
		,	[SiteGuid]=(CASE ISNULL(@NullOverrideSiteGuid,0) WHEN 1 THEN @SiteGuid ELSE ISNULL(@SiteGuid,[SiteGuid]) END)
		,	[LookupVesselTypeIndex]=(CASE ISNULL(@NullOverrideLookupVesselTypeIndex,0) WHEN 1 THEN @LookupVesselTypeIndex ELSE ISNULL(@LookupVesselTypeIndex,[LookupVesselTypeIndex]) END)
		,	[QualityTagGuid]=(CASE ISNULL(@NullOverrideQualityTagGuid,0) WHEN 1 THEN @QualityTagGuid ELSE ISNULL(@QualityTagGuid,[QualityTagGuid]) END)
		,	[TankGuid]=(CASE ISNULL(@NullOverrideTankGuid,0) WHEN 1 THEN @TankGuid ELSE ISNULL(@TankGuid,[TankGuid]) END)
		WHERE	TankQualityTagLogGuid=@TankQualityTagLogGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblTankQualityTagLog]           
		WHERE TankQualityTagLogGuid=@TankQualityTagLogGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_TankQualityTagLogUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
