CREATE PROCEDURE [dbo].[gsp_EquipmentTypesUpdateByPK]
(
		@EquipmentTypeGuid uniqueidentifier
	,	@EqTypeName nvarchar(50)=NULL
	,	@EqTypeDescription nvarchar(50)=NULL
	,	@Capacity float=NULL
	,	@SafeFill float=NULL
	,	@Make nvarchar(20)=NULL
	,	@Model nvarchar(32)=NULL
	,	@Year smallint=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@DeleteFlag bit=NULL
	,	@IssPt nvarchar(20)=NULL
	,	@MultiCompartment bit=NULL
	,	@SiteGuid uniqueidentifier=NULL
	,	@LookupEquipmentTypeIndex int=NULL
	,	@ProductGuid uniqueidentifier=NULL
	,	@CustomerDesignator nvarchar(128)=NULL
	,	@ServiceTime float=NULL
	,	@VolumeUnits int=NULL
	,	@VolumeDecimalPlaces smallint=NULL
	,	@MassUnits int=NULL
	,	@MassDecimalPlaces smallint=NULL
	,	@WingToWingToleranceType smallint=NULL
	,	@WingToWingToleranceValue float=NULL
	,	@TankToTankToleranceType smallint=NULL
	,	@TankToTankToleranceValue float=NULL
	,	@FuelServiceToleranceType smallint=NULL
	,	@FuelServiceToleranceValue float=NULL
	,	@FuelServiceToleranceMaxType smallint=NULL
	,	@FuelServiceToleranceMaxValue float=NULL
	,	@AllowFuelingByWeight bit=NULL
	,	@LookupCompanyRoleIndex int=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideEqTypeName BIT=0 
	,	@NullOverrideEqTypeDescription BIT=0 
	,	@NullOverrideCapacity BIT=0 
	,	@NullOverrideSafeFill BIT=0 
	,	@NullOverrideMake BIT=0 
	,	@NullOverrideModel BIT=0 
	,	@NullOverrideYear BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverrideDeleteFlag BIT=0 
	,	@NullOverrideIssPt BIT=0 
	,	@NullOverrideMultiCompartment BIT=0 
	,	@NullOverrideSiteGuid BIT=0 
	,	@NullOverrideLookupEquipmentTypeIndex BIT=0 
	,	@NullOverrideProductGuid BIT=0 
	,	@NullOverrideCustomerDesignator BIT=0 
	,	@NullOverrideServiceTime BIT=0 
	,	@NullOverrideVolumeUnits BIT=0 
	,	@NullOverrideVolumeDecimalPlaces BIT=0 
	,	@NullOverrideMassUnits BIT=0 
	,	@NullOverrideMassDecimalPlaces BIT=0 
	,	@NullOverrideWingToWingToleranceType BIT=0 
	,	@NullOverrideWingToWingToleranceValue BIT=0 
	,	@NullOverrideTankToTankToleranceType BIT=0 
	,	@NullOverrideTankToTankToleranceValue BIT=0 
	,	@NullOverrideFuelServiceToleranceType BIT=0 
	,	@NullOverrideFuelServiceToleranceValue BIT=0 
	,	@NullOverrideFuelServiceToleranceMaxType BIT=0 
	,	@NullOverrideFuelServiceToleranceMaxValue BIT=0 
	,	@NullOverrideAllowFuelingByWeight BIT=0 
	,	@NullOverrideLookupCompanyRoleIndex BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_EquipmentTypesUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:29.4993971 -05:00
	-- Purpose: Update table [dbo].[tblEquipmentTypes]
	-- Notes:
	-- 1. @EquipmentTypeGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblEquipmentTypes] WHERE EquipmentTypeGuid=@EquipmentTypeGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblEquipmentTypes] SET
			[EqTypeName]=(CASE ISNULL(@NullOverrideEqTypeName,0) WHEN 1 THEN @EqTypeName ELSE ISNULL(@EqTypeName,[EqTypeName]) END)
		,	[EqTypeDescription]=(CASE ISNULL(@NullOverrideEqTypeDescription,0) WHEN 1 THEN @EqTypeDescription ELSE ISNULL(@EqTypeDescription,[EqTypeDescription]) END)
		,	[Capacity]=(CASE ISNULL(@NullOverrideCapacity,0) WHEN 1 THEN @Capacity ELSE ISNULL(@Capacity,[Capacity]) END)
		,	[SafeFill]=(CASE ISNULL(@NullOverrideSafeFill,0) WHEN 1 THEN @SafeFill ELSE ISNULL(@SafeFill,[SafeFill]) END)
		,	[Make]=(CASE ISNULL(@NullOverrideMake,0) WHEN 1 THEN @Make ELSE ISNULL(@Make,[Make]) END)
		,	[Model]=(CASE ISNULL(@NullOverrideModel,0) WHEN 1 THEN @Model ELSE ISNULL(@Model,[Model]) END)
		,	[Year]=(CASE ISNULL(@NullOverrideYear,0) WHEN 1 THEN @Year ELSE ISNULL(@Year,[Year]) END)
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[DeleteFlag]=(CASE ISNULL(@NullOverrideDeleteFlag,0) WHEN 1 THEN @DeleteFlag ELSE ISNULL(@DeleteFlag,[DeleteFlag]) END)
		,	[IssPt]=(CASE ISNULL(@NullOverrideIssPt,0) WHEN 1 THEN @IssPt ELSE ISNULL(@IssPt,[IssPt]) END)
		,	[MultiCompartment]=(CASE ISNULL(@NullOverrideMultiCompartment,0) WHEN 1 THEN @MultiCompartment ELSE ISNULL(@MultiCompartment,[MultiCompartment]) END)
		,	[SiteGuid]=(CASE ISNULL(@NullOverrideSiteGuid,0) WHEN 1 THEN @SiteGuid ELSE ISNULL(@SiteGuid,[SiteGuid]) END)
		,	[LookupEquipmentTypeIndex]=(CASE ISNULL(@NullOverrideLookupEquipmentTypeIndex,0) WHEN 1 THEN @LookupEquipmentTypeIndex ELSE ISNULL(@LookupEquipmentTypeIndex,[LookupEquipmentTypeIndex]) END)
		,	[ProductGuid]=(CASE ISNULL(@NullOverrideProductGuid,0) WHEN 1 THEN @ProductGuid ELSE ISNULL(@ProductGuid,[ProductGuid]) END)
		,	[CustomerDesignator]=(CASE ISNULL(@NullOverrideCustomerDesignator,0) WHEN 1 THEN @CustomerDesignator ELSE ISNULL(@CustomerDesignator,[CustomerDesignator]) END)
		,	[ServiceTime]=(CASE ISNULL(@NullOverrideServiceTime,0) WHEN 1 THEN @ServiceTime ELSE ISNULL(@ServiceTime,[ServiceTime]) END)
		,	[VolumeUnits]=(CASE ISNULL(@NullOverrideVolumeUnits,0) WHEN 1 THEN @VolumeUnits ELSE ISNULL(@VolumeUnits,[VolumeUnits]) END)
		,	[VolumeDecimalPlaces]=(CASE ISNULL(@NullOverrideVolumeDecimalPlaces,0) WHEN 1 THEN @VolumeDecimalPlaces ELSE ISNULL(@VolumeDecimalPlaces,[VolumeDecimalPlaces]) END)
		,	[MassUnits]=(CASE ISNULL(@NullOverrideMassUnits,0) WHEN 1 THEN @MassUnits ELSE ISNULL(@MassUnits,[MassUnits]) END)
		,	[MassDecimalPlaces]=(CASE ISNULL(@NullOverrideMassDecimalPlaces,0) WHEN 1 THEN @MassDecimalPlaces ELSE ISNULL(@MassDecimalPlaces,[MassDecimalPlaces]) END)
		,	[WingToWingToleranceType]=(CASE ISNULL(@NullOverrideWingToWingToleranceType,0) WHEN 1 THEN @WingToWingToleranceType ELSE ISNULL(@WingToWingToleranceType,[WingToWingToleranceType]) END)
		,	[WingToWingToleranceValue]=(CASE ISNULL(@NullOverrideWingToWingToleranceValue,0) WHEN 1 THEN @WingToWingToleranceValue ELSE ISNULL(@WingToWingToleranceValue,[WingToWingToleranceValue]) END)
		,	[TankToTankToleranceType]=(CASE ISNULL(@NullOverrideTankToTankToleranceType,0) WHEN 1 THEN @TankToTankToleranceType ELSE ISNULL(@TankToTankToleranceType,[TankToTankToleranceType]) END)
		,	[TankToTankToleranceValue]=(CASE ISNULL(@NullOverrideTankToTankToleranceValue,0) WHEN 1 THEN @TankToTankToleranceValue ELSE ISNULL(@TankToTankToleranceValue,[TankToTankToleranceValue]) END)
		,	[FuelServiceToleranceType]=(CASE ISNULL(@NullOverrideFuelServiceToleranceType,0) WHEN 1 THEN @FuelServiceToleranceType ELSE ISNULL(@FuelServiceToleranceType,[FuelServiceToleranceType]) END)
		,	[FuelServiceToleranceValue]=(CASE ISNULL(@NullOverrideFuelServiceToleranceValue,0) WHEN 1 THEN @FuelServiceToleranceValue ELSE ISNULL(@FuelServiceToleranceValue,[FuelServiceToleranceValue]) END)
		,	[FuelServiceToleranceMaxType]=(CASE ISNULL(@NullOverrideFuelServiceToleranceMaxType,0) WHEN 1 THEN @FuelServiceToleranceMaxType ELSE ISNULL(@FuelServiceToleranceMaxType,[FuelServiceToleranceMaxType]) END)
		,	[FuelServiceToleranceMaxValue]=(CASE ISNULL(@NullOverrideFuelServiceToleranceMaxValue,0) WHEN 1 THEN @FuelServiceToleranceMaxValue ELSE ISNULL(@FuelServiceToleranceMaxValue,[FuelServiceToleranceMaxValue]) END)
		,	[AllowFuelingByWeight]=(CASE ISNULL(@NullOverrideAllowFuelingByWeight,0) WHEN 1 THEN @AllowFuelingByWeight ELSE ISNULL(@AllowFuelingByWeight,[AllowFuelingByWeight]) END)
		,	[LookupCompanyRoleIndex]=(CASE ISNULL(@NullOverrideLookupCompanyRoleIndex,0) WHEN 1 THEN @LookupCompanyRoleIndex ELSE ISNULL(@LookupCompanyRoleIndex,[LookupCompanyRoleIndex]) END)
		WHERE	EquipmentTypeGuid=@EquipmentTypeGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblEquipmentTypes]           
		WHERE EquipmentTypeGuid=@EquipmentTypeGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_EquipmentTypesUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
