CREATE PROCEDURE [dbo].[gsp_SRMDuplicateMessageInformationUpdateByPK]
(
		@SRMDuplicateMessageInformationGuid uniqueidentifier
	,	@MessageSequenceNumber nvarchar(100)=NULL
	,	@FlightNumber nvarchar(10)=NULL
	,	@FlightOriginationDate datetimeoffset(7)=NULL
	,	@OriginIATACode nvarchar(10)=NULL
	,	@DestinationIATACode nvarchar(10)=NULL
	,	@AirlineIATACode nvarchar(10)=NULL
	,	@TimesLegFlown nvarchar(10)=NULL
	,	@HashValue nvarchar(32)=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideMessageSequenceNumber BIT=0 
	,	@NullOverrideFlightNumber BIT=0 
	,	@NullOverrideFlightOriginationDate BIT=0 
	,	@NullOverrideOriginIATACode BIT=0 
	,	@NullOverrideDestinationIATACode BIT=0 
	,	@NullOverrideAirlineIATACode BIT=0 
	,	@NullOverrideTimesLegFlown BIT=0 
	,	@NullOverrideHashValue BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_SRMDuplicateMessageInformationUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:29.7914263 -05:00
	-- Purpose: Update table [dbo].[tblSRMDuplicateMessageInformation]
	-- Notes:
	-- 1. @SRMDuplicateMessageInformationGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblSRMDuplicateMessageInformation] WHERE SRMDuplicateMessageInformationGuid=@SRMDuplicateMessageInformationGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblSRMDuplicateMessageInformation] SET
			[MessageSequenceNumber]=(CASE ISNULL(@NullOverrideMessageSequenceNumber,0) WHEN 1 THEN @MessageSequenceNumber ELSE ISNULL(@MessageSequenceNumber,[MessageSequenceNumber]) END)
		,	[FlightNumber]=(CASE ISNULL(@NullOverrideFlightNumber,0) WHEN 1 THEN @FlightNumber ELSE ISNULL(@FlightNumber,[FlightNumber]) END)
		,	[FlightOriginationDate]=(CASE ISNULL(@NullOverrideFlightOriginationDate,0) WHEN 1 THEN @FlightOriginationDate ELSE ISNULL(@FlightOriginationDate,[FlightOriginationDate]) END)
		,	[OriginIATACode]=(CASE ISNULL(@NullOverrideOriginIATACode,0) WHEN 1 THEN @OriginIATACode ELSE ISNULL(@OriginIATACode,[OriginIATACode]) END)
		,	[DestinationIATACode]=(CASE ISNULL(@NullOverrideDestinationIATACode,0) WHEN 1 THEN @DestinationIATACode ELSE ISNULL(@DestinationIATACode,[DestinationIATACode]) END)
		,	[AirlineIATACode]=(CASE ISNULL(@NullOverrideAirlineIATACode,0) WHEN 1 THEN @AirlineIATACode ELSE ISNULL(@AirlineIATACode,[AirlineIATACode]) END)
		,	[TimesLegFlown]=(CASE ISNULL(@NullOverrideTimesLegFlown,0) WHEN 1 THEN @TimesLegFlown ELSE ISNULL(@TimesLegFlown,[TimesLegFlown]) END)
		,	[HashValue]=(CASE ISNULL(@NullOverrideHashValue,0) WHEN 1 THEN @HashValue ELSE ISNULL(@HashValue,[HashValue]) END)
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		WHERE	SRMDuplicateMessageInformationGuid=@SRMDuplicateMessageInformationGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblSRMDuplicateMessageInformation]           
		WHERE SRMDuplicateMessageInformationGuid=@SRMDuplicateMessageInformationGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_SRMDuplicateMessageInformationUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
