CREATE PROCEDURE [dbo].[gsp_FuelCardsUpdateByPK]
(
		@FuelCardGuid uniqueidentifier
	,	@ID nvarchar(50)=NULL
	,	@Provider nvarchar(50)=NULL
	,	@ActivationStatus int=NULL
	,	@InactivityPeriod int=NULL
	,	@Notes nvarchar(max)=NULL
	,	@StatusModifiedDate datetimeoffset(7)=NULL
	,	@StatusModifiedBy nvarchar(50)=NULL
	,	@UserData1 nvarchar(60)=NULL
	,	@UserData2 nvarchar(60)=NULL
	,	@UserData3 nvarchar(60)=NULL
	,	@UserData4 nvarchar(60)=NULL
	,	@UserData5 nvarchar(60)=NULL
	,	@UserData6 nvarchar(60)=NULL
	,	@UserData7 nvarchar(60)=NULL
	,	@UserData8 nvarchar(60)=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@SiteGuid uniqueidentifier=NULL
	,	@BillToCompanyGuid uniqueidentifier=NULL
	,	@ManagerCompanyGuid uniqueidentifier=NULL
	,	@OwnerCompanyGuid uniqueidentifier=NULL
	,	@ShipperCompanyGuid uniqueidentifier=NULL
	,	@ShipToCompanyGuid uniqueidentifier=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideID BIT=0 
	,	@NullOverrideProvider BIT=0 
	,	@NullOverrideActivationStatus BIT=0 
	,	@NullOverrideInactivityPeriod BIT=0 
	,	@NullOverrideNotes BIT=0 
	,	@NullOverrideStatusModifiedDate BIT=0 
	,	@NullOverrideStatusModifiedBy BIT=0 
	,	@NullOverrideUserData1 BIT=0 
	,	@NullOverrideUserData2 BIT=0 
	,	@NullOverrideUserData3 BIT=0 
	,	@NullOverrideUserData4 BIT=0 
	,	@NullOverrideUserData5 BIT=0 
	,	@NullOverrideUserData6 BIT=0 
	,	@NullOverrideUserData7 BIT=0 
	,	@NullOverrideUserData8 BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverrideSiteGuid BIT=0 
	,	@NullOverrideBillToCompanyGuid BIT=0 
	,	@NullOverrideManagerCompanyGuid BIT=0 
	,	@NullOverrideOwnerCompanyGuid BIT=0 
	,	@NullOverrideShipperCompanyGuid BIT=0 
	,	@NullOverrideShipToCompanyGuid BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_FuelCardsUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:29.5193991 -05:00
	-- Purpose: Update table [dbo].[tblFuelCards]
	-- Notes:
	-- 1. @FuelCardGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblFuelCards] WHERE FuelCardGuid=@FuelCardGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblFuelCards] SET
			[ID]=(CASE ISNULL(@NullOverrideID,0) WHEN 1 THEN @ID ELSE ISNULL(@ID,[ID]) END)
		,	[Provider]=(CASE ISNULL(@NullOverrideProvider,0) WHEN 1 THEN @Provider ELSE ISNULL(@Provider,[Provider]) END)
		,	[ActivationStatus]=(CASE ISNULL(@NullOverrideActivationStatus,0) WHEN 1 THEN @ActivationStatus ELSE ISNULL(@ActivationStatus,[ActivationStatus]) END)
		,	[InactivityPeriod]=(CASE ISNULL(@NullOverrideInactivityPeriod,0) WHEN 1 THEN @InactivityPeriod ELSE ISNULL(@InactivityPeriod,[InactivityPeriod]) END)
		,	[Notes]=(CASE ISNULL(@NullOverrideNotes,0) WHEN 1 THEN @Notes ELSE ISNULL(@Notes,[Notes]) END)
		,	[StatusModifiedDate]=(CASE ISNULL(@NullOverrideStatusModifiedDate,0) WHEN 1 THEN @StatusModifiedDate ELSE ISNULL(@StatusModifiedDate,[StatusModifiedDate]) END)
		,	[StatusModifiedBy]=(CASE ISNULL(@NullOverrideStatusModifiedBy,0) WHEN 1 THEN @StatusModifiedBy ELSE ISNULL(@StatusModifiedBy,[StatusModifiedBy]) END)
		,	[UserData1]=(CASE ISNULL(@NullOverrideUserData1,0) WHEN 1 THEN @UserData1 ELSE ISNULL(@UserData1,[UserData1]) END)
		,	[UserData2]=(CASE ISNULL(@NullOverrideUserData2,0) WHEN 1 THEN @UserData2 ELSE ISNULL(@UserData2,[UserData2]) END)
		,	[UserData3]=(CASE ISNULL(@NullOverrideUserData3,0) WHEN 1 THEN @UserData3 ELSE ISNULL(@UserData3,[UserData3]) END)
		,	[UserData4]=(CASE ISNULL(@NullOverrideUserData4,0) WHEN 1 THEN @UserData4 ELSE ISNULL(@UserData4,[UserData4]) END)
		,	[UserData5]=(CASE ISNULL(@NullOverrideUserData5,0) WHEN 1 THEN @UserData5 ELSE ISNULL(@UserData5,[UserData5]) END)
		,	[UserData6]=(CASE ISNULL(@NullOverrideUserData6,0) WHEN 1 THEN @UserData6 ELSE ISNULL(@UserData6,[UserData6]) END)
		,	[UserData7]=(CASE ISNULL(@NullOverrideUserData7,0) WHEN 1 THEN @UserData7 ELSE ISNULL(@UserData7,[UserData7]) END)
		,	[UserData8]=(CASE ISNULL(@NullOverrideUserData8,0) WHEN 1 THEN @UserData8 ELSE ISNULL(@UserData8,[UserData8]) END)
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[SiteGuid]=(CASE ISNULL(@NullOverrideSiteGuid,0) WHEN 1 THEN @SiteGuid ELSE ISNULL(@SiteGuid,[SiteGuid]) END)
		,	[BillToCompanyGuid]=(CASE ISNULL(@NullOverrideBillToCompanyGuid,0) WHEN 1 THEN @BillToCompanyGuid ELSE ISNULL(@BillToCompanyGuid,[BillToCompanyGuid]) END)
		,	[ManagerCompanyGuid]=(CASE ISNULL(@NullOverrideManagerCompanyGuid,0) WHEN 1 THEN @ManagerCompanyGuid ELSE ISNULL(@ManagerCompanyGuid,[ManagerCompanyGuid]) END)
		,	[OwnerCompanyGuid]=(CASE ISNULL(@NullOverrideOwnerCompanyGuid,0) WHEN 1 THEN @OwnerCompanyGuid ELSE ISNULL(@OwnerCompanyGuid,[OwnerCompanyGuid]) END)
		,	[ShipperCompanyGuid]=(CASE ISNULL(@NullOverrideShipperCompanyGuid,0) WHEN 1 THEN @ShipperCompanyGuid ELSE ISNULL(@ShipperCompanyGuid,[ShipperCompanyGuid]) END)
		,	[ShipToCompanyGuid]=(CASE ISNULL(@NullOverrideShipToCompanyGuid,0) WHEN 1 THEN @ShipToCompanyGuid ELSE ISNULL(@ShipToCompanyGuid,[ShipToCompanyGuid]) END)
		WHERE	FuelCardGuid=@FuelCardGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblFuelCards]           
		WHERE FuelCardGuid=@FuelCardGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_FuelCardsUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
