CREATE PROCEDURE [dbo].[gsp_UsersUpdateByPK]
(
		@UserGuid uniqueidentifier
	,	@UserID udtUserID=NULL
	,	@Password varbinary=NULL
	,	@LastLoginDate datetimeoffset(7)=NULL
	,	@LastLogoffDate datetimeoffset(7)=NULL
	,	@ChangePassword bit=NULL
	,	@PasswordTimeStamp datetimeoffset(7)=NULL
	,	@Name nvarchar(50)=NULL
	,	@EmailAddress nvarchar(50)=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@PasswordHistory1 varbinary=NULL
	,	@PasswordHistory2 varbinary=NULL
	,	@PasswordHistory3 varbinary=NULL
	,	@PasswordHistory4 varbinary=NULL
	,	@PasswordHistory5 varbinary=NULL
	,	@PasswordHistory6 varbinary=NULL
	,	@PasswordHistory7 varbinary=NULL
	,	@PasswordHistory8 varbinary=NULL
	,	@PasswordHistory9 varbinary=NULL
	,	@PasswordHistory10 varbinary=NULL
	,	@PasswordHistory11 varbinary=NULL
	,	@PasswordHistory12 varbinary=NULL
	,	@PasswordHistory13 varbinary=NULL
	,	@PasswordHistory14 varbinary=NULL
	,	@PasswordHistory15 varbinary=NULL
	,	@PasswordHistory16 varbinary=NULL
	,	@PasswordHistory17 varbinary=NULL
	,	@PasswordHistory18 varbinary=NULL
	,	@PasswordHistory19 varbinary=NULL
	,	@PasswordHistory20 varbinary=NULL
	,	@PasswordHistory21 varbinary=NULL
	,	@PasswordHistory22 varbinary=NULL
	,	@PasswordHistory23 varbinary=NULL
	,	@PasswordHistory24 varbinary=NULL
	,	@PasswordLockoutCount int=NULL
	,	@InactivityLockout bit=NULL
	,	@InactivityLockoutDate datetimeoffset(7)=NULL
	,	@SiteGuid uniqueidentifier=NULL
	,	@PasswordHint varchar(40)=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideUserID BIT=0 
	,	@NullOverridePassword BIT=0 
	,	@NullOverrideLastLoginDate BIT=0 
	,	@NullOverrideLastLogoffDate BIT=0 
	,	@NullOverrideChangePassword BIT=0 
	,	@NullOverridePasswordTimeStamp BIT=0 
	,	@NullOverrideName BIT=0 
	,	@NullOverrideEmailAddress BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverridePasswordHistory1 BIT=0 
	,	@NullOverridePasswordHistory2 BIT=0 
	,	@NullOverridePasswordHistory3 BIT=0 
	,	@NullOverridePasswordHistory4 BIT=0 
	,	@NullOverridePasswordHistory5 BIT=0 
	,	@NullOverridePasswordHistory6 BIT=0 
	,	@NullOverridePasswordHistory7 BIT=0 
	,	@NullOverridePasswordHistory8 BIT=0 
	,	@NullOverridePasswordHistory9 BIT=0 
	,	@NullOverridePasswordHistory10 BIT=0 
	,	@NullOverridePasswordHistory11 BIT=0 
	,	@NullOverridePasswordHistory12 BIT=0 
	,	@NullOverridePasswordHistory13 BIT=0 
	,	@NullOverridePasswordHistory14 BIT=0 
	,	@NullOverridePasswordHistory15 BIT=0 
	,	@NullOverridePasswordHistory16 BIT=0 
	,	@NullOverridePasswordHistory17 BIT=0 
	,	@NullOverridePasswordHistory18 BIT=0 
	,	@NullOverridePasswordHistory19 BIT=0 
	,	@NullOverridePasswordHistory20 BIT=0 
	,	@NullOverridePasswordHistory21 BIT=0 
	,	@NullOverridePasswordHistory22 BIT=0 
	,	@NullOverridePasswordHistory23 BIT=0 
	,	@NullOverridePasswordHistory24 BIT=0 
	,	@NullOverridePasswordLockoutCount BIT=0 
	,	@NullOverrideInactivityLockout BIT=0 
	,	@NullOverrideInactivityLockoutDate BIT=0 
	,	@NullOverrideSiteGuid BIT=0 
	,	@NullOverridePasswordHint BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_UsersUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:29.9624434 -05:00
	-- Purpose: Update table [dbo].[tblUsers]
	-- Notes:
	-- 1. @UserGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblUsers] WHERE UserGuid=@UserGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblUsers] SET
			[UserID]=(CASE ISNULL(@NullOverrideUserID,0) WHEN 1 THEN @UserID ELSE ISNULL(@UserID,[UserID]) END)
		,	[Password]=(CASE ISNULL(@NullOverridePassword,0) WHEN 1 THEN @Password ELSE ISNULL(@Password,[Password]) END)
		,	[LastLoginDate]=(CASE ISNULL(@NullOverrideLastLoginDate,0) WHEN 1 THEN @LastLoginDate ELSE ISNULL(@LastLoginDate,[LastLoginDate]) END)
		,	[LastLogoffDate]=(CASE ISNULL(@NullOverrideLastLogoffDate,0) WHEN 1 THEN @LastLogoffDate ELSE ISNULL(@LastLogoffDate,[LastLogoffDate]) END)
		,	[ChangePassword]=(CASE ISNULL(@NullOverrideChangePassword,0) WHEN 1 THEN @ChangePassword ELSE ISNULL(@ChangePassword,[ChangePassword]) END)
		,	[PasswordTimeStamp]=(CASE ISNULL(@NullOverridePasswordTimeStamp,0) WHEN 1 THEN @PasswordTimeStamp ELSE ISNULL(@PasswordTimeStamp,[PasswordTimeStamp]) END)
		,	[Name]=(CASE ISNULL(@NullOverrideName,0) WHEN 1 THEN @Name ELSE ISNULL(@Name,[Name]) END)
		,	[EmailAddress]=(CASE ISNULL(@NullOverrideEmailAddress,0) WHEN 1 THEN @EmailAddress ELSE ISNULL(@EmailAddress,[EmailAddress]) END)
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[PasswordHistory1]=(CASE ISNULL(@NullOverridePasswordHistory1,0) WHEN 1 THEN @PasswordHistory1 ELSE ISNULL(@PasswordHistory1,[PasswordHistory1]) END)
		,	[PasswordHistory2]=(CASE ISNULL(@NullOverridePasswordHistory2,0) WHEN 1 THEN @PasswordHistory2 ELSE ISNULL(@PasswordHistory2,[PasswordHistory2]) END)
		,	[PasswordHistory3]=(CASE ISNULL(@NullOverridePasswordHistory3,0) WHEN 1 THEN @PasswordHistory3 ELSE ISNULL(@PasswordHistory3,[PasswordHistory3]) END)
		,	[PasswordHistory4]=(CASE ISNULL(@NullOverridePasswordHistory4,0) WHEN 1 THEN @PasswordHistory4 ELSE ISNULL(@PasswordHistory4,[PasswordHistory4]) END)
		,	[PasswordHistory5]=(CASE ISNULL(@NullOverridePasswordHistory5,0) WHEN 1 THEN @PasswordHistory5 ELSE ISNULL(@PasswordHistory5,[PasswordHistory5]) END)
		,	[PasswordHistory6]=(CASE ISNULL(@NullOverridePasswordHistory6,0) WHEN 1 THEN @PasswordHistory6 ELSE ISNULL(@PasswordHistory6,[PasswordHistory6]) END)
		,	[PasswordHistory7]=(CASE ISNULL(@NullOverridePasswordHistory7,0) WHEN 1 THEN @PasswordHistory7 ELSE ISNULL(@PasswordHistory7,[PasswordHistory7]) END)
		,	[PasswordHistory8]=(CASE ISNULL(@NullOverridePasswordHistory8,0) WHEN 1 THEN @PasswordHistory8 ELSE ISNULL(@PasswordHistory8,[PasswordHistory8]) END)
		,	[PasswordHistory9]=(CASE ISNULL(@NullOverridePasswordHistory9,0) WHEN 1 THEN @PasswordHistory9 ELSE ISNULL(@PasswordHistory9,[PasswordHistory9]) END)
		,	[PasswordHistory10]=(CASE ISNULL(@NullOverridePasswordHistory10,0) WHEN 1 THEN @PasswordHistory10 ELSE ISNULL(@PasswordHistory10,[PasswordHistory10]) END)
		,	[PasswordHistory11]=(CASE ISNULL(@NullOverridePasswordHistory11,0) WHEN 1 THEN @PasswordHistory11 ELSE ISNULL(@PasswordHistory11,[PasswordHistory11]) END)
		,	[PasswordHistory12]=(CASE ISNULL(@NullOverridePasswordHistory12,0) WHEN 1 THEN @PasswordHistory12 ELSE ISNULL(@PasswordHistory12,[PasswordHistory12]) END)
		,	[PasswordHistory13]=(CASE ISNULL(@NullOverridePasswordHistory13,0) WHEN 1 THEN @PasswordHistory13 ELSE ISNULL(@PasswordHistory13,[PasswordHistory13]) END)
		,	[PasswordHistory14]=(CASE ISNULL(@NullOverridePasswordHistory14,0) WHEN 1 THEN @PasswordHistory14 ELSE ISNULL(@PasswordHistory14,[PasswordHistory14]) END)
		,	[PasswordHistory15]=(CASE ISNULL(@NullOverridePasswordHistory15,0) WHEN 1 THEN @PasswordHistory15 ELSE ISNULL(@PasswordHistory15,[PasswordHistory15]) END)
		,	[PasswordHistory16]=(CASE ISNULL(@NullOverridePasswordHistory16,0) WHEN 1 THEN @PasswordHistory16 ELSE ISNULL(@PasswordHistory16,[PasswordHistory16]) END)
		,	[PasswordHistory17]=(CASE ISNULL(@NullOverridePasswordHistory17,0) WHEN 1 THEN @PasswordHistory17 ELSE ISNULL(@PasswordHistory17,[PasswordHistory17]) END)
		,	[PasswordHistory18]=(CASE ISNULL(@NullOverridePasswordHistory18,0) WHEN 1 THEN @PasswordHistory18 ELSE ISNULL(@PasswordHistory18,[PasswordHistory18]) END)
		,	[PasswordHistory19]=(CASE ISNULL(@NullOverridePasswordHistory19,0) WHEN 1 THEN @PasswordHistory19 ELSE ISNULL(@PasswordHistory19,[PasswordHistory19]) END)
		,	[PasswordHistory20]=(CASE ISNULL(@NullOverridePasswordHistory20,0) WHEN 1 THEN @PasswordHistory20 ELSE ISNULL(@PasswordHistory20,[PasswordHistory20]) END)
		,	[PasswordHistory21]=(CASE ISNULL(@NullOverridePasswordHistory21,0) WHEN 1 THEN @PasswordHistory21 ELSE ISNULL(@PasswordHistory21,[PasswordHistory21]) END)
		,	[PasswordHistory22]=(CASE ISNULL(@NullOverridePasswordHistory22,0) WHEN 1 THEN @PasswordHistory22 ELSE ISNULL(@PasswordHistory22,[PasswordHistory22]) END)
		,	[PasswordHistory23]=(CASE ISNULL(@NullOverridePasswordHistory23,0) WHEN 1 THEN @PasswordHistory23 ELSE ISNULL(@PasswordHistory23,[PasswordHistory23]) END)
		,	[PasswordHistory24]=(CASE ISNULL(@NullOverridePasswordHistory24,0) WHEN 1 THEN @PasswordHistory24 ELSE ISNULL(@PasswordHistory24,[PasswordHistory24]) END)
		,	[PasswordLockoutCount]=(CASE ISNULL(@NullOverridePasswordLockoutCount,0) WHEN 1 THEN @PasswordLockoutCount ELSE ISNULL(@PasswordLockoutCount,[PasswordLockoutCount]) END)
		,	[InactivityLockout]=(CASE ISNULL(@NullOverrideInactivityLockout,0) WHEN 1 THEN @InactivityLockout ELSE ISNULL(@InactivityLockout,[InactivityLockout]) END)
		,	[InactivityLockoutDate]=(CASE ISNULL(@NullOverrideInactivityLockoutDate,0) WHEN 1 THEN @InactivityLockoutDate ELSE ISNULL(@InactivityLockoutDate,[InactivityLockoutDate]) END)
		,	[SiteGuid]=(CASE ISNULL(@NullOverrideSiteGuid,0) WHEN 1 THEN @SiteGuid ELSE ISNULL(@SiteGuid,[SiteGuid]) END)
		,	[PasswordHint]=(CASE ISNULL(@NullOverridePasswordHint,0) WHEN 1 THEN @PasswordHint ELSE ISNULL(@PasswordHint,[PasswordHint]) END)
		WHERE	UserGuid=@UserGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblUsers]           
		WHERE UserGuid=@UserGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_UsersUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
