/*
	DROP TABLE [dbo].[FactFMUserToCompany]
*/
CREATE TABLE [dbo].[FactFMUserToCompany] (
    [SKey]        INT IDENTITY (1, 1) NOT NULL,
    [CompanySKey] INT NULL,
    [FMUserSKey]  INT NULL,
    CONSTRAINT [PK_FactFMUserToCompany] PRIMARY KEY CLUSTERED ([SKey] ASC) WITH (FILLFACTOR = 100)
)
GO
CREATE NONCLUSTERED INDEX [IX_FactFMUserToCompany_CompanySKey] ON [dbo].[FactFMUserToCompany]
(
	[CompanySKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FactFMUserToCompany_FMUserSKey] ON [dbo].[FactFMUserToCompany]
(
	[FMUserSKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]