/***************************************** 
	[dbo].[FactCloseoutSnapshot] 
*******************************************/

CREATE TABLE [dbo].[FactCloseoutSnapshot]
(
[SKey] [int] IDENTITY(1,1) NOT NULL,
[CloseoutDate] [date] NULL,
[CloseoutDateSKey] [int] NOT NULL DEFAULT(0),
[GrossBookInventorySI] [float] NULL,
[GrossBookInventoryUSGallon] [float] NULL,
[GrossBookPrice] [float] NULL,
[ManagerAddress1] [nvarchar](30) NULL,
[ManagerAddress2] [nvarchar](30) NULL,
[ManagerCity] [varchar](20) NULL,
[ManagerCode] [varchar](20) NULL, 
[ManagerCompanyName] [nvarchar](100) NULL,
[ManagerCompanyKey] [nvarchar](50) NULL,
[ManagerCompanySKey] [int] NOT NULL DEFAULT(0),
[ManagerCountry] [varchar](50) NULL,
[ManagerEmergencyContact] [nvarchar](30) NULL,
[ManagerId] [nvarchar](100) NULL, 
[ManagerLockedOut] [bit] NULL,
[ManagerState] [varchar](20) NULL,
[ManagerZip] [varchar](11) NULL,
[MassBookInventoryLb] [float] NULL,
[MassBookInventorySI] [float] NULL,
[MassBookPrice] [float] NULL,
[NetBookInventorySI] [float] NULL,
[NetBookInventoryUSGallon] [float] NULL,
[NetBookPrice] [float] NULL,
[OwnerAddress1] [nvarchar](30) NULL,
[OwnerAddress2] [nvarchar](30) NULL,
[OwnerCity] [varchar](20) NULL,
[OwnerCode] [varchar](20) NULL,
[OwnerCompanyKey] [nvarchar](50) NULL,
[OwnerCompanyName] [nvarchar](100) NULL,
[OwnerCompanySKey] [int] NOT NULL DEFAULT(0),
[OwnerCountry] [varchar](50) NULL,
[OwnerEmergencyContact] [nvarchar](30) NULL,
[OwnerId] [nvarchar](100) NULL,
[OwnerLockedOut] [bit] NULL, 
[OwnerState] [varchar](20) NULL,
[OwnerZip] [varchar](11) NULL,
[ProductAviationFuelFlag] [bit] NULL,
[ProductCode] [nvarchar](15) NULL, 
[ProductGroundFuel] [bit] NULL,
[ProductId] [nvarchar](30) NULL, 
[ProductLockedOut] [bit] NULL,
[ProductKey] [nvarchar](50) NULL,
[ProductSKey] [int] NOT NULL DEFAULT(0),
[ProductVolumeDecimalPlaces] [tinyint] NULL,
[SiteAddress1] [nvarchar](30) NULL,
[SiteAddress2] [nvarchar](30) NULL,
[SiteCity] [nvarchar](50) NULL,
[SiteContact1Name] [nvarchar](30) NULL,
[SiteCountry] [nvarchar](50) NULL,
[SiteDensityDecimalPlaces] [tinyint] NULL,
[SiteDensityUnitIndex] [int] NULL,
[SiteGroupFlag] [bit]  NULL,
[SiteId] [nvarchar](30) NULL,
[SitePhone] [nvarchar](20) NULL,
[SiteKey] [nvarchar](50) NULL,
[SiteSKey] [int] NOT NULL DEFAULT(0),
[SiteState] [nvarchar](20) NULL,
[SiteTemperatureDecimalPlaces] [tinyint] NULL,
[SiteTemperatureUnitIndex] [int] NULL,
[SiteTimeZone] [nvarchar](50) NULL,
[SiteVolumeDecimalPlaces] [tinyint] NULL,
[SiteVolumeUnitIndex] [int] NULL,
[SiteZip] [nvarchar](11) NULL,

[OwnerCloseoutKey] [nvarchar](50) NULL,
[AKey] [nvarchar](50) NULL,

[_RecordUpdatedDate] [datetimeoffset](7) NULL,
[_RecordUpdatedDateSKey] [int] NOT NULL DEFAULT(19000101),
[_IsRecordDeleted] [bit] NULL

CONSTRAINT [PK_OwnerCloseout_SKey] PRIMARY KEY CLUSTERED 
( [SKey] ASC 
))