CREATE TABLE [sync].[tblSyncTableTemplateData] (
    [SyncTableGuid]                     UNIQUEIDENTIFIER   NOT NULL,
    [LastSchemaDate]                    DATETIMEOFFSET (7) NULL,
    [IsSiteFilteredFlag]                BIT                CONSTRAINT [DF_tblSyncTableTemplateData_IsSiteFilteredFlag] DEFAULT ((0)) NOT NULL,
    [IsSiteFilteredOnDeleteFlag]        BIT                CONSTRAINT [DF_tblSyncTableTemplateData_IsSiteFilteredOnDeleteFlag] DEFAULT ((0)) NOT NULL,
    [SiteFilterColumnOverride]          NVARCHAR (512)     NULL,
    [SiteFilterJoinClause]              NVARCHAR (1024)    NULL,
    [SiteFilterWhereClause]             NVARCHAR (512)     NULL,
    [IsEntityAssignableFlag]            BIT                CONSTRAINT [DF_tblSyncTableTemplateData_IsEntityAssignableFlag] DEFAULT ((0)) NULL,
    [IsEntityAssignedBySiteFlag]        BIT                NULL,
    [GetEntityListFunction]             NVARCHAR (4000)    NULL,
    [GetEntityListOutputColumns]        NVARCHAR (4000)    NULL,
    [EntityAssignmentTableName]         NVARCHAR (2000)    NULL,
    [EntityAssignmentSiteMappingField]  NVARCHAR (2000)    NULL,
    [EntityAssignmentJoinField]         NVARCHAR (2000)    NULL,
    [EntityAssignmentJoinSourceField]   NVARCHAR (2000)    NULL,
    [EntityListToEntityJoinField]       NVARCHAR (1000)    NULL,
    [EntityListToEntityJoinSourceField] NVARCHAR (1000)    NULL,
    [GetEntityListFunctionWhereClause]  NVARCHAR (1000)    NULL,
    [PreloadIntoTableVariableFlag]      BIT                NULL,
    [PreloadTableVariableName]          NVARCHAR (175)     NULL,
    [PreloadTableVariableColumns]       NVARCHAR (2000)    NULL,
    [ExcludedColumns]                   NVARCHAR (1000)    NULL,
    [CreatedDate]                       DATETIMEOFFSET (7) CONSTRAINT [DF_tblSyncTableTemplateData_CreatedDate] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CreatedBy]                         NVARCHAR (100)     CONSTRAINT [DF_tblSyncTableTemplateData_CreatedBy] DEFAULT (suser_sname()) NULL,
    [UpdatedDate]                       DATETIMEOFFSET (7) CONSTRAINT [DF_tblSyncTableTemplateData_UpdatedDate] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [UpdatedBy]                         NVARCHAR (100)     CONSTRAINT [DF_tblSyncTableTemplateData_UpdatedBy] DEFAULT (suser_sname()) NULL,
    [_RowVersion]                       ROWVERSION         NOT NULL,
    CONSTRAINT [PK_tblSyncTableTemplateData] PRIMARY KEY NONCLUSTERED ([SyncTableGuid] ASC)
);

