CREATE PROCEDURE [map].[gsp_FMAEProductIDUpdateByPK]
(
		@FMAEProductIDMapGuid uniqueidentifier
	,	@FMAEProductID nvarchar(30)=NULL
	,	@ProductGuid uniqueidentifier=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideFMAEProductID BIT=0 
	,	@NullOverrideProductGuid BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [map].[gsp_FMAEProductIDUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:30.0254497 -05:00
	-- Purpose: Update table [map].[tblFMAEProductID]
	-- Notes:
	-- 1. @FMAEProductIDMapGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [map].[tblFMAEProductID] WHERE FMAEProductIDMapGuid=@FMAEProductIDMapGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [map].[tblFMAEProductID] SET
			[FMAEProductID]=(CASE ISNULL(@NullOverrideFMAEProductID,0) WHEN 1 THEN @FMAEProductID ELSE ISNULL(@FMAEProductID,[FMAEProductID]) END)
		,	[ProductGuid]=(CASE ISNULL(@NullOverrideProductGuid,0) WHEN 1 THEN @ProductGuid ELSE ISNULL(@ProductGuid,[ProductGuid]) END)
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		WHERE	FMAEProductIDMapGuid=@FMAEProductIDMapGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [map].[tblFMAEProductID]           
		WHERE FMAEProductIDMapGuid=@FMAEProductIDMapGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_FMAEProductIDUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
