CREATE PROCEDURE [map].[gsp_ModuleToPointTemplateUpdateByPK]
(
		@ModuleToPointTemplateGuid uniqueidentifier=NULL
	,	@ID nvarchar(30) 
	,	@Order int
	,	@ModuleToPointTemplateData xml=NULL
	,	@CreatedDate datetimeoffset(7)=NULL
	,	@CreatedBy udtUserID=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@PointTemplateGuid uniqueidentifier=NULL
	,	@ModuleGuid uniqueidentifier=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideID Bit=0
	,	@NullOverrideOrder BIT=0 
	,	@NullOverrideModuleToPointTemplateData BIT=0 
	,	@NullOverridePointTemplateGuid BIT=0
	,	@NullOverrideModuleGuid BIT=0
 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [map].[gsp_ModuleToPointTemplateUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2016-02-23 13:59:04.5395917 -05:00
	-- Purpose: Update table [map].[tblModuleToPointTemplate]
	-- Notes:
	-- 1. @ModuleToPointTemplateGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [map].[tblModuleToPointTemplate] WHERE ModuleToPointTemplateGuid=@ModuleToPointTemplateGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [map].[tblModuleToPointTemplate] SET
			[ID]=(CASE ISNULL(@NullOverrideID,0) WHEN 1 THEN @ID ELSE ISNULL(@ID,[ID]) END)
		,	[Order]=(CASE ISNULL(@NullOverrideOrder,0) WHEN 1 THEN @Order ELSE ISNULL(@Order,[Order]) END)
		,	[ModuleToPointTemplateData]=(CASE ISNULL(@NullOverrideModuleToPointTemplateData,0) WHEN 1 THEN @ModuleToPointTemplateData ELSE ISNULL(@ModuleToPointTemplateData,[ModuleToPointTemplateData]) END)
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[PointTemplateGuid]=(CASE ISNULL(@NullOverridePointTemplateGuid,0) WHEN 1 THEN @PointTemplateGuid ELSE ISNULL(@PointTemplateGuid,[PointTemplateGuid]) END)
		,	[ModuleGuid]=(CASE ISNULL(@NullOverrideModuleGuid,0) WHEN 1 THEN @ModuleGuid ELSE ISNULL(@ModuleGuid,[ModuleGuid]) END)
		WHERE	ModuleToPointTemplateGuid=@ModuleToPointTemplateGuid
		AND (
		[ID] <> (CASE ISNULL(@NullOverrideID,0) WHEN 1 THEN @ID ELSE ISNULL(@ID,[ID]) END)
		OR	[Order] <> (CASE ISNULL(@NullOverrideOrder,0) WHEN 1 THEN @Order ELSE ISNULL(@Order,[Order]) END)
		OR	ISNULL( CAST( [ModuleToPointTemplateData] AS NVARCHAR(MAX)), '') <> ISNULL(CASE ISNULL(@NullOverrideModuleToPointTemplateData,0) WHEN 1 THEN CAST( @ModuleToPointTemplateData AS NVARCHAR(MAX)) ELSE ISNULL(CAST( @ModuleToPointTemplateData AS NVARCHAR(MAX)),CAST( [ModuleToPointTemplateData] AS NVARCHAR(MAX))) END, '')
		OR	[UpdatedDate] <> ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		OR	[UpdatedBy] <>  ISNULL(@UpdatedBy,SUSER_SNAME())
		OR	[PointTemplateGuid] <> (CASE ISNULL(@NullOverridePointTemplateGuid,0) WHEN 1 THEN @PointTemplateGuid ELSE ISNULL(@PointTemplateGuid,[PointTemplateGuid]) END)
		OR	[ModuleGuid] <> (CASE ISNULL(@NullOverrideModuleGuid,0) WHEN 1 THEN @ModuleGuid ELSE ISNULL(@ModuleGuid,[ModuleGuid]) END)
		)
 
		SELECT @_RowVersion=_RowVersion        
		FROM [map].[tblModuleToPointTemplate]           
		WHERE ModuleToPointTemplateGuid=@ModuleToPointTemplateGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_ModuleToPointTemplateUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END
GO