	
CREATE PROCEDURE [map].[gsp_EntityAutoDistributionReasonCodeToSiteUpdateByPK]
(
		@AutoDistributionReasonCodeToSiteGuid uniqueidentifier
	,	@SiteGuid uniqueidentifier=NULL
	,	@AutoDistributionReasonCodeGuid uniqueidentifier=NULL
	,	@Description nvarchar(255)=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy nvarchar(50)=NULL
	,	@AssignedFromSiteGuid uniqueidentifier=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideSiteGuid BIT=0 
	,	@NullOverrideAutoDistributionReasonCodeGuid BIT=0 
	,	@NullOverrideDescription BIT=0 
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverrideAssignedFromSiteGuid BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [map].[gsp_EntityAutoDistributionReasonCodeToSiteUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2013-12-30 14:44:41.1271453 -05:00
	-- Purpose: Update table [map].[tblEntityAutoDistributionReasonCodeToSite]
	-- Notes:
	-- 1. @AutoDistributionReasonCodeToSiteGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [map].[tblEntityAutoDistributionReasonCodeToSite] WHERE AutoDistributionReasonCodeToSiteGuid=@AutoDistributionReasonCodeToSiteGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [map].[tblEntityAutoDistributionReasonCodeToSite] SET
			[SiteGuid]=(CASE ISNULL(@NullOverrideSiteGuid,0) WHEN 1 THEN @SiteGuid ELSE ISNULL(@SiteGuid,[SiteGuid]) END)
		,	[AutoDistributionReasonCodeGuid]=(CASE ISNULL(@NullOverrideAutoDistributionReasonCodeGuid,0) WHEN 1 THEN @AutoDistributionReasonCodeGuid ELSE ISNULL(@AutoDistributionReasonCodeGuid,[AutoDistributionReasonCodeGuid]) END)
		,	[Description]=(CASE ISNULL(@NullOverrideDescription,0) WHEN 1 THEN @Description ELSE ISNULL(@Description,[Description]) END)
		,	[UpdatedDate]=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())
		,	[UpdatedBy]= ISNULL(@UpdatedBy,SUSER_SNAME())
		,	[AssignedFromSiteGuid]=(CASE ISNULL(@NullOverrideAssignedFromSiteGuid,0) WHEN 1 THEN @AssignedFromSiteGuid ELSE ISNULL(@AssignedFromSiteGuid,[AssignedFromSiteGuid]) END)
		WHERE	AutoDistributionReasonCodeToSiteGuid=@AutoDistributionReasonCodeToSiteGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [map].[tblEntityAutoDistributionReasonCodeToSite]           
		WHERE AutoDistributionReasonCodeToSiteGuid=@AutoDistributionReasonCodeToSiteGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		IF(@_ErrNumber = 547 AND CHARINDEX('Uniqueness',@_ErrMessage,0) <> 0)
			RAISERROR('Operation would result in duplicate identifiers.',16,1);
		ELSE
		BEGIN
			SET @_ErrProcName= ERROR_PROCEDURE();        
			SET @_ErrLineNumber = ERROR_LINE();            
			SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
							+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
							+ 'Procedure Name: gsp_EntityAutoDistributionReasonCodeToSiteUpdateByPK' + CHAR(13)+CHAR(10)                  
							+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
			RAISERROR(@_ErrMessage,18,1);
		END      
	END CATCH    
END     
	
