CREATE TYPE [dbo].[PointTagType] AS TABLE
(
	[PointTagGuid] [uniqueidentifier] NOT NULL,
	[ID] [NVarChar](50)	NULL,
	[EngineeringUnitsType]	[INT] NULL,
	[EngineeringUnitsIndex] [INT]	NULL,
	[DecimalPlaces] [TINYINT]	NULL,
	[ServerEngineeringUnitsIndex] [INT]	NULL,
	[ValueType] [NVarChar] (max) NULL,
	[Status] [bigint] NULL,
	[Value] [xml] NULL,
	[ServerTimeStamp] [datetimeoffset] NULL,
	[SourceTimeStamp] [datetimeoffset] NULL,
	[Maximum] [FLOAT] NULL,
	[Minimum] [FLOAT] NULL,
	[PointTagInputOutputTypeIndex] [INT] NULL,
	[Input] [BIT] NULL,
	[AlarmStatus] [BIT] NULL,
	[ApplyPointEngineeringUnits] [BIT] NULL,
	[ApplyPointDecimalPlaces] [BIT] NULL,
	[ApplyPointMaximum] [BIT] NULL,
	[ApplyPointMinimum] [BIT] NULL,
	[OpcUaServerGuid] [uniqueidentifier] NULL,
	[OpcUaBrowsePath] [NVARCHAR](250) NULL,
	[OpcUaNamespaceUri] [NVARCHAR](250) NULL,
	[OpcUaPublishingInterval] [INT] NULL,
	[OpcUaNodeId] [NVARCHAR](250) NULL,
	[OpcUaIsReadable] [BIT] NULL,
	[OpcUaServerDataType] [INT] NULL,
	[OpcUaWriteHoldoffTime] [INT] NULL,
	[OpcUaWritePeriodicUpdateInterval] [INT] NULL,
	[AlarmsEnabled] [BIT] NULL,
	[InhibitInputOutputTypeConfiguration] [BIT] NULL,
	[InhibitOverride] [BIT] NULL,
	[Deadband] float(53) NULL,
	[Holdoff] int NULL,
	[Archived] [BIT] NULL,
	[CreatedDate] [datetimeoffset] NULL,
	[CreatedBy] [udtUserID] NULL,
	[UpdatedDate] [datetimeoffset] NULL,
	[UpdatedBy] [udtUserID] NULL,
	[PointGuid] [uniqueidentifier] NULL,
	[PointTemplateTagGuid] [uniqueidentifier] NULL

)
