



CREATE  PROCEDURE [dbo].[usp_GenerateStoredProcUpdateByPK](@TableNameList NVARCHAR(MAX)=NULL)
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @CreateTemplate VARCHAR(8000)
		,	@ParemeterListTemplate VARCHAR(8000)
		,	@NullOverrideTemplate VARCHAR(8000)
		,	@NoteTemplate VARCHAR(8000)
		,	@ValidateTemplate VARCHAR(8000)
		,	@UpdateFieldsTemplate VARCHAR(8000)
		,	@UpdateCriteriaTemplate VARCHAR(8000)
		,	@ExceptionTemplate	VARCHAR(8000)
		,	@RefreshRowVersionTemplate VARCHAR(8000)
		,	@LineReturn VARCHAR(10)
		,	@Tab VARCHAR(10)
		,	@TableExceptionList VARCHAR(max)
		,	@Version VARCHAR(50)

	DECLARE @Create VARCHAR(8000)
		,	@ParemeterList VARCHAR(8000)
		,	@NullOverrideList VARCHAR(8000)
		,	@Note VARCHAR(8000)
		,	@Validate VARCHAR(8000)
		,	@UpdateFields VARCHAR(8000)
		,	@Exception	VARCHAR(8000)
		,	@ParameterLine VARCHAR(8000)
		,	@NullOverrideParLine VARCHAR(8000)
		,	@UpdateLine VARCHAR(8000)
		,	@UpdateCriteria VARCHAR(8000)
		,	@RefreshRowVersion VARCHAR(8000)
		,	@UpdateBlock VARCHAR(8000)
		,	@ParameterDef VARCHAR(8000)
		
	DECLARE 
			@SchemaName VARCHAR(100)
		,	@TableName VARCHAR(300)
		,	@ColumnName VARCHAR(300)
		,	@ColumnType VARCHAR(100)
		,	@ColumnLength INT
		,	@IsNullable BIT
		,	@IsPrimaryKey BIT
		,	@IsForeignKey BIT
		,	@HasRowVersion BIT
		,	@IsIdentity BIT
		,	@WorkingTable VARCHAR(300)
		,	@WorkingSchemaName VARCHAR(100)
		,	@ColPkName NVARCHAR(300)
		,	@RowNumber INT
		,	@TotalRows INT
		,	@TotalOverrides INT
		,	@OverrideCount INT
		,	@TotalParameters INT
		,	@ParameterCount INT
	/********************************************/

	SET @Version = '1.0.003'

	/********************************************/

	SET @TableExceptionList = 'tblB2BResults'

--	SET @CreateTemplate =
--	'IF  EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N''[#SCHEMA#].[gsp_#LOGICAL_TABLE#UpdateByPK]'') AND type in (N''P'', N''PC''))      
--	DROP PROCEDURE [#SCHEMA#].[gsp_#LOGICAL_TABLE#UpdateByPK];  
--GO 

	SET @CreateTemplate = '
	
CREATE PROCEDURE [#SCHEMA#].[gsp_#LOGICAL_TABLE#UpdateByPK]
('
	
	
	SET @ParemeterListTemplate =
	'	#PAREMETER_LIST#
'
	
	SET @NullOverrideTemplate = 
	'	,	#PAREMETER_OVERRIDE_LIST#
)
AS
BEGIN'
	
	
	
	SET @NoteTemplate =
'	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [#SCHEMA#].[gsp_#LOGICAL_TABLE#UpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: #VERSION# / #DATE#
	-- Purpose: Update table [#SCHEMA#].[#PHISICAL_TABLE#]
	-- Notes:
	-- 1. @#COL_GUID# and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don''t match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid=''0000-...'',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid=''0000-...'', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------'
		
	SET @ValidateTemplate =	

	'		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [#SCHEMA#].[#PHISICAL_TABLE#] WHERE #COL_GUID#=@#COL_GUID# AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR(''Attempted to modify a stale copy of the record'',16,1);
			RETURN;
		END'

	SET @UpdateFieldsTemplate =
	'		UPDATE	[#SCHEMA#].[#PHYSICALTABLENAME#]        
			SET '

	SET @UpdateCriteriaTemplate =
	'		WHERE	#COL_GUID#=@#COL_GUID#;'        
				
	SET @RefreshRowVersionTemplate = 
	'		SELECT @_RowVersion=_RowVersion        
		FROM [#SCHEMA#].[#PHYSICALTABLENAME#]           
		WHERE #COL_GUID#=@#COL_GUID#;
	'
	SET @ExceptionTemplate=
	'	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = ''Error: '' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ ''Number: '' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ ''Procedure Name: gsp_#LOGICAL_TABLE#UpdateByPK'' + CHAR(13)+CHAR(10)                  
						+ ''Line Number: '' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'''') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	'
	DECLARE @ParamenterTable TABLE(RowNumber INT IDENTITY,ParameterDefinition VARCHAR(8000))
	DECLARE @NullOverrideParTable TABLE(RowNumber INT IDENTITY,NullOverridePar VARCHAR(8000))
	CREATE TABLE #ParameterTable (RowVersion INT IDENTITY, ParameterDefinition VARCHAR(8000))
	CREATE TABLE #UpdateLineTable (RowNumber INT IDENTITY, UpdateLineDefinition VARCHAR(8000))
	CREATE TABLE #OverrideParameter (RowNumber INT IDENTITY, OverrideDefinition VARCHAR(8000))


	SET @WorkingTable = ''
	SET @WorkingSchemaName = ''
	SET @LineReturn = CHAR(13)+CHAR(10)
	SET @Tab= CHAR(9)	

	--dbo.udf_SplitTableName(@TableNameList) stn ON (stn.TableName=fki.TableName)
	IF @TableNameList IS NULL
	BEGIN
		DECLARE TableInfoCursor CURSOR FOR
			SELECT	SchemaName
				,	TableName
				,	ColumnName
				,	ColumnType
				,	ColumnLength
				,	IsNullable
				,	IsPrimaryKey
				,	IsForeignKey
				,	IsIdentity

			FROM dbo.udf_GetTableColumnInfo() ta
			WHERE ta.SchemaName IN ('dbo','map')
			AND ta.ColumnName NOT LIKE 'Created%'
			--AND ColumnName <> 'UpdatedDate'
			AND ta.TableName NOT IN ('tblAuditLog','tblCompanyCrossReferenceMap')
			AND ta.TableName NOT LIKE 'tblEntity%'
			ORDER BY SchemaName,TableName,(CASE WHEN ColumnName = '_RowVersion' THEN 9999 WHEN IsPrimaryKey='1' THEN 0 ELSE ColumnID END)
	END
	ELSE
	BEGIN
		DECLARE TableInfoCursor CURSOR FOR
			SELECT	tab.SchemaName
				,	tab.TableName
				,	tab.ColumnName
				,	tab.ColumnType
				,	tab.ColumnLength
				,	tab.IsNullable
				,	tab.IsPrimaryKey
				,	tab.IsForeignKey
				,	tab.IsIdentity

			FROM dbo.udf_GetTableColumnInfo() tab
			INNER JOIN dbo.udf_SplitTableName(@TableNameList) stn ON (stn.TableName=tab.TableName)
			WHERE tab.SchemaName  IN ('dbo','map')
			AND tab.ColumnName NOT LIKE 'Created%'
			--AND ColumnName <> 'UpdatedDate'
			AND tab.TableName NOT IN ('tblAuditLog')	
			AND tab.TableName NOT LIKE 'tblEntity%'		
			ORDER BY tab.SchemaName,tab.TableName,(CASE WHEN tab.ColumnName = '_RowVersion' THEN 9999 WHEN tab.IsPrimaryKey='1' THEN 0 ELSE tab.ColumnID END)	
	END

		
	OPEN TableInfoCursor
	FETCH NEXT FROM TableInfoCursor INTO
		@SchemaName,@TableName,@ColumnName,@ColumnType,@ColumnLength,@IsNullable,@IsPrimaryKey,@IsForeignKey,@IsIdentity
	WHILE @@FETCH_STATUS=0
	BEGIN

		IF @WorkingTable <> @TableName
		BEGIN
			SET @Create = @CreateTemplate
			SET @ParemeterList = @ParemeterListTemplate
			SET @Validate = @ValidateTemplate
			SET @UpdateFields = @UpdateFieldsTemplate
			SET @UpdateCriteria = @UpdateCriteriaTemplate
			SET @Exception	= @ExceptionTemplate
			SET	@RefreshRowVersion= @RefreshRowVersionTemplate
			SET	@NullOverrideList = @NullOverrideTemplate
			
			SET @Note=@NoteTemplate

			SET @WorkingTable=@TableName
			SET @WorkingSchemaName=@SchemaName
			SET @HasRowVersion = 0


			SET @Create=REPLACE(@Create,'#SCHEMA#',@WorkingSchemaName)
			SET @Create=REPLACE(@Create,'#LOGICAL_TABLE#',REPLACE(@TableName,'tbl',''))
		
		
			SET @Exception=REPLACE(@Exception,'#LOGICAL_TABLE#',REPLACE(@TableName,'tbl',''))
				
			SET @Validate=REPLACE(@Validate,'#SCHEMA#',@WorkingSchemaName)
			SET @Validate=REPLACE(@Validate,'#PHISICAL_TABLE#',@TableName)

			SET @Note=REPLACE(@Note,'#SCHEMA#',@WorkingSchemaName)
			SET @Note=REPLACE(@Note,'#LOGICAL_TABLE#',REPLACE(@TableName,'tbl',''))
			SET @Note=REPLACE(@Note,'#PHISICAL_TABLE#',@TableName)
			SET	@Note=REPLACE(@Note,'#VERSION#',@Version)
			SET @Note=REPLACE(@Note,'#DATE#',CAST(SYSDATETIMEOFFSET() AS VARCHAR(50)))
			SET @ColPkName = ''
			PRINT @Create
		END
		SET @ParameterLine = NULL

		SET	@UpdateLine = NULL
		SET @NullOverrideParLine = NULL
		SET @UpdateBlock = ''
		
		TRUNCATE TABLE #UpdateLineTable
		TRUNCATE TABLE #OverrideParameter
		TRUNCATE TABLE #ParameterTable
		
		SET @RowNumber=0
		SET @TotalRows = 0
		SET @TotalOverrides = 0
		SET @OverrideCount = 0
		SET @ParameterCount=0
		SET @TotalParameters = 0
		SET @ColPkName = NULL
		WHILE @WorkingTable=@TableName AND @@FETCH_STATUS=0
		BEGIN
						
			IF @IsPrimaryKey=1
				SET @ColPkName = @ColumnName

			-- BUILD PARAMETER LIST
			IF @TotalParameters = 0
				SET @ParameterLine = '	@'+@ColumnName+' ' + REPLACE(@ColumnType,'timestamp','BINARY(8)')
			ELSE
				SET @ParameterLine = ',	@'+@ColumnName+' ' + @ColumnType
				
			IF @ColumnType IN ('VARCHAR','NVARCHAR','VARBINARY')
				IF @ColumnLength <> -1
					SET @ParameterLine += '(' + CAST(@ColumnLength/2 AS VARCHAR(5)) + ')'
				ELSE
					SET @ParameterLine += '(max)'
			IF @ColumnType = 'DATETIMEOFFSET'
				SET @ParameterLine += '(7)'
			IF @IsPrimaryKey=0 
				SET @ParameterLine += '=NULL'
				
			IF @ColumnName = '_RowVersion'
			BEGIN
				SET @ParameterLine += ' OUTPUT'
				SET @HasRowVersion = 1
			END
			
			INSERT INTO #ParameterTable(ParameterDefinition) VALUES(@ParameterLine)
			SET @TotalParameterS += 1;
			
			-- BUILD @NullOverridePar
			IF @ColumnName NOT IN('_RowVersion','UpdatedBy') AND @IsPrimaryKey = 0
			BEGIN
				SET @NullOverrideParLine = '	,	@NullOverride'+@ColumnName+' BIT=0 '-- + @LineReturn+@Tab
			
				INSERT INTO #OverrideParameter(OverrideDefinition) VALUES(@NullOverrideParLine)
				SET @TotalOverrides += 1
			END 	
			-- BUILD UPDATE VALUES
			IF @IsIdentity = 0
			BEGIN
				IF (@IsPrimaryKey = 0) AND (@ColumnName<>'_RowVersion')
				BEGIN
					IF @UpdateLine IS NULL
					BEGIN
						SET @UpdateLine = '	' 
					END
					ELSE
					BEGIN
						SET @UpdateLine += ',	' 
					END
					IF @IsForeignKey=1
					BEGIN	
						IF @ColumnType ='UNIQUEIDENTIFIER'
						BEGIN
							SET @UpdateLine += '['+@ColumnName+']=(CASE ISNULL(@NullOverride'+@ColumnName+',0) WHEN 1 THEN @'+@ColumnName+' ELSE ISNULL(@'+@ColumnName+',['+@ColumnName+']) END)'
						END
						ELSE
						BEGIN
							IF @ColumnName = 'UpdatedDate'
							BEGIN
								SET @UpdateLine = '	['+@ColumnName+']=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())'
							END
							ELSE
							BEGIN
								IF @ColumnName = 'UpdatedBy'
								BEGIN
									SET @UpdateLine = '	['+@ColumnName+']=ISNULL(@UpdatedDate,SUSER_SNAME())'
								END
								ELSE
								BEGIN
									IF (@ColumnType='int') OR (@ColumnType='smallint') OR (@ColumnType='bigint')
									BEGIN
										SET @UpdateLine += '['+@ColumnName+']=(CASE ISNULL(@NullOverride'+@ColumnName+',0) WHEN 1 THEN @'+@ColumnName+' ELSE ISNULL(@'+@ColumnName+',['+@ColumnName+']) END)'
									END
									ELSE
									BEGIN
										SET @UpdateLine += '['+@ColumnName+']=(CASE ISNULL(@NullOverride'+@ColumnName+',0) WHEN 1 THEN @'+@ColumnName+' ELSE ISNULL(@'+@ColumnName+',['+@ColumnName+']) END)'
									END
								END
							END
						END

					END
					ELSE
					BEGIN
						IF @ColumnName='UpdatedBy'
						BEGIN
							SET @UpdateLine += '['+@ColumnName+']= ISNULL(@'+@ColumnName+',SUSER_SNAME())'
						END
						ELSE
						BEGIN
							IF @ColumnName = 'UpdatedDate'
							BEGIN
								SET @UpdateLine = '	['+@ColumnName+']=ISNULL(@UpdatedDate,SYSDATETIMEOFFSET())'
							END
						
							ELSE						
						
							BEGIN
								SET @UpdateLine += '['+@ColumnName+']=(CASE ISNULL(@NullOverride'+@ColumnName+',0) WHEN 1 THEN @'+@ColumnName+' ELSE ISNULL(@'+@ColumnName+',['+@ColumnName+']) END)'
							END
						END
					END	
					
					-- print @UpdateLine
					
					IF @UpdateLine != ''
					BEGIN	
						INSERT INTO #UpdateLineTable(UpdateLineDefinition) 
						VALUES(@UpdateLine)
						SET @TotalRows += 1;
					END

						
					SET @UpdateLine = NULL
					

				END
			END
				
			FETCH NEXT FROM TableInfoCursor INTO
				@SchemaName,@TableName,@ColumnName,@ColumnType,@ColumnLength,@IsNullable,@IsPrimaryKey,@IsForeignKey,@IsIdentity
		END  

		SET @ParemeterList = REPLACE(@ParemeterList,'#PAREMETER_LIST#',@ParameterLine)
		SET @NullOverrideList = REPLACE(@NullOverrideList,'#PAREMETER_OVERRIDE_LIST#',@NullOverrideParLine)
		SET @UpdateFields = REPLACE(@UpdateFields,'#COL_GUID#',@ColPkName)
		SET @UpdateFields = REPLACE(@UpdateFields,'#SCHEMA#',@WorkingSchemaName)
		SET @UpdateFields = REPLACE(@UpdateFields,'#PHYSICALTABLENAME#',@TableName)
		
		-- PRINT PARAMETER DEFINITION
		SET @ParameterCount = 1
		WHILE @ParameterCount <= @TotalParameters
		BEGIN
			SELECT @ParameterDef = ParameterDefinition
			FROM #ParameterTable
			WHERE RowVersion = @ParameterCount
			
			PRINT '	'+@ParameterDef
			SET @ParameterCount += 1
		END
		
		--PRINT @NullOverrideList
		set @NullOverrideList = NULL
		SET @OverrideCount = 1
		WHILE @OverrideCount <= @TotalOverrides
		BEGIN
			SELECT @NullOverrideList=OverrideDefinition
			FROM #OverrideParameter
			WHERE RowNumber = @OverrideCount
			PRINT @NullOverrideList
			
			SET @OverrideCount += 1
		END

	PRINT 
	')
	AS
	BEGIN'
		SET @Note=REPLACE(@Note,'#COL_GUID#',@ColPkName)
		PRINT @Note
		
		PRINT '	SET NOCOUNT ON;'
		PRINT '	BEGIN TRY'
		
		IF @HasRowVersion=1
		BEGIN
			SET @Validate = REPLACE(@Validate,'#COL_GUID#',@ColPkName)
			PRINT @Validate
		END
			
		PRINT ''
		PRINT '		UPDATE ['+@WorkingSchemaName+'].['+@WorkingTable+'] SET'
		SET @RowNumber = 1;
		WHILE @RowNumber <= @TotalRows
		BEGIN
			SELECT @UpdateBlock=UpdateLineDefinition
			FROM #UpdateLineTable
			WHERE RowNumber=@RowNumber
			
			IF @RowNumber = 1
				PRINT '		' + @UpdateBlock
			ELSE
				PRINT '		,' + @UpdateBlock
			
			SET @RowNumber += 1;
			SET @UpdateBlock=''
		END
		
		SET @UpdateCriteria=REPLACE(@UpdateCriteria,'#COL_GUID#',@ColPkName)
		PRINT @UpdateCriteria
		PRINT ''
		
		IF @HasRowVersion = 1
		BEGIN
			SET @RefreshRowVersion=REPLACE(@RefreshRowVersion,'#SCHEMA#',@WorkingSchemaName)
			SET @RefreshRowVersion=REPLACE(@RefreshRowVersion,'#PHYSICALTABLENAME#',@WorkingTable)
			SET @RefreshRowVersion=REPLACE(@RefreshRowVersion,'#COL_GUID#',@ColPkName)

			PRINT @RefreshRowVersion
			PRINT ''
		END
			
		PRINT '	END TRY'
		
		PRINT @Exception
		PRINT 'GO'
		PRINT ''
		TRUNCATE TABLE #UpdateLineTable
		
		SET @TotalRows = 0;
	END
	DROP TABLE #UpdateLineTable
	DROP TABLE #OverrideParameter
	CLOSE TableInfoCursor
	DEALLOCATE TableInfoCursor

END


