CREATE TABLE [dbo].[tblLeakReport]
(
	[LeakReportId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [SiteId] NVARCHAR(30) NOT NULL, 
    [PointId] NVARCHAR(30) NOT NULL, 
    [TestMethod] NVARCHAR(30) NOT NULL, 
    [TestResult] NVARCHAR(30) NOT NULL, 
    [LeakRate] FLOAT NULL, 
    [StartTime] DATETIMEOFFSET NULL, 
    [EndTime] DATETIMEOFFSET NULL, 
    [LevelStart] FLOAT NULL, 
    [LevelEnd] FLOAT NULL, 
    [PressureStart] FLOAT NULL, 
    [PressureEnd] FLOAT NULL, 
    [MinTemp] FLOAT NULL, 
    [MaxTemp] FLOAT NULL, 
    [MinVolume] FLOAT NULL, 
    [MaxVolume] FLOAT NULL, 
    [CertRate] FLOAT NULL, 
    [WaterLevelStart] FLOAT NULL, 
    [WaterLevelEnd] FLOAT NULL, 
    [LeakThreshold] FLOAT NULL, 
    [TestType] NVARCHAR(30) NOT NULL, 
    [TimeStamp] DATETIMEOFFSET NOT NULL, 
    [DateInstalled] DATE NULL, 
    [TankGauge] NVARCHAR(50) NULL, 
    [LeakDetectionSystem] NVARCHAR(50) NULL, 
    [TankLengthOrHeight] FLOAT NULL, 
    [TankRadius] FLOAT NULL, 
    [TankVolume] FLOAT NULL, 
    [LiningMaterial] NVARCHAR(50) NULL, 
    [ConstructionMaterial] NVARCHAR(50) NULL, 
    [CathodicProtection] BIT NULL, 
    [OverfillProtection] BIT NULL, 
    [SpillProtection] BIT NULL,
    [VolumeEngineeringUnitIndex] int NULL, 
    [TemperatureEngineeringUnitIndex] int NULL, 
    [WaterLevelEngineeringUnitIndex] int NULL, 
    [ProductLevelEngineeringUnitIndex] int NULL,
    [PressureEngineeringUnitIndex] int NULL,
    [LeakRateEngineeringUnitIndex] int NULL, 
    [BasePointLevelUnitsIndex] int NULL, 
    [BasePointVolumeUnitsIndex] int NULL, 
    [TemperaturePrecision] INT NULL, 
    [VolumePrecision] INT NULL, 
    [LeakRatePrecision] INT NULL, 
    [ProductLevelPrecision] INT NULL, 
    [WaterLevelPrecision] INT NULL, 
    [PressurePrecision] INT NULL, 
    [PointDescription] NVARCHAR(50) NULL, 

)
