CREATE TABLE [dbo].[tblSitesShadow] (
	[ID]                                      NVARCHAR (30)      NULL,
	[Number]                                  NVARCHAR (30)      NULL,
	[SPLCCode]                                NVARCHAR (30)      NULL,
	[Address1]                                NVARCHAR (30)      NULL,
	[Address2]                                NVARCHAR (30)      NULL,
	[City]                                    NVARCHAR (60)      NULL,
	[State]                                   NVARCHAR (20)      NULL,
	[Zip]                                     NVARCHAR (11)      NULL,
	[Country]                                 NVARCHAR (30)      NULL,
	[Phone]                                   NVARCHAR (20)      NULL,
	[FAX]                                     NVARCHAR (20)      NULL,
	[EmailAddress]                            NVARCHAR (30)      NULL,
	[EmergencyContact]                        NVARCHAR (30)      NULL,
	[EmergencyPhone]                          NVARCHAR (20)      NULL,
	[Enabled]                                 BIT                NULL,
	[SiteGroupFlag]                           BIT                CONSTRAINT [DF_tblSitesShadow_SiteGroupFlag] DEFAULT ((0)) NULL,
	[TimeZone]                                NVARCHAR (50)      NULL,
	[LevelUnitIndex]                          INT                NULL,
	[TemperatureUnitIndex]                    INT                NULL,
	[DensityUnitIndex]                        INT                NULL,
	[PressureUnitIndex]                       INT                NULL,
	[FlowUnitIndex]                           INT                NULL,
	[VolumeUnitIndex]                         INT                NULL,
	[MassUnitIndex]                           INT                NULL,
	[AdditiveVolumeUnitIndex]                 INT                NULL,
	[AdditiveProfileCycleAmountUnitIndex]     INT                NULL,
	[AdditiveProfileRateUnitIndex]            INT                NULL,
	[LevelDecimalPlaces]                      TINYINT            NULL,
	[TemperatureDecimalPlaces]                TINYINT            NULL,
	[DensityDecimalPlaces]                    TINYINT            NULL,
	[PressureDecimalPlaces]                   TINYINT            NULL,
	[FlowDecimalPlaces]                       TINYINT            NULL,
	[VolumeDecimalPlaces]                     TINYINT            NULL,
	[MassDecimalPlaces]                       TINYINT            NULL,
	[AdditiveVolumeDecimalPlaces]             TINYINT            NULL,
	[AdditiveProfileCycleAmountDecimalPlaces] TINYINT            NULL,
	[AdditiveProfileRateDecimalPlaces]        TINYINT            NULL,
	[InhibitAccessAfterHours]                 BIT                NULL,
	[InhibitMultipleCardIns]                  BIT                NULL,
	[AccessCardInRequired]                    BIT                NULL,
	[CheckSiteNumber]                         BIT                NULL,
	[PromptForCustomerCard]                   BIT                NULL,
	[PromptForTractorOrTanker]                BIT                NULL,
	[PromptForFirstTrailer]                   BIT                NULL,
	[PromptForSecondTrailer]                  BIT                NULL,
	[PromptForCompartment]                    BIT                NULL,
	[EnforceDriverEquipmentMatch]             BIT                NULL,
	[EnableAdditiveAccounting]                BIT                NULL,
	[UseCompanyEquipmentIdentifiers]          BIT                NULL,
	[UseLastKnownGoodTankData]                BIT                NULL,
	[MaximumLoadAmount]                       FLOAT (53)         NULL,
	[MaximumLoadTime]                         INT                NULL,
	[MaximumIdleTime]                         INT                NULL,
	[MaximumFlushAmount]                      FLOAT (53)         NULL,
	[MaximumMeterProvingAmount]               FLOAT (53)         NULL,
	[MaximumReturnsAmount]                    FLOAT (53)         NULL,
	[MaximumNumberOfActiveArms]               INT                NULL,
	[DriverTimeoutPeriod]                     INT                NULL,
	[DriverWarningPeriod]                     INT                NULL,
	[MaximumPrompts]                          INT                NULL,
	[MaximumVehicleWeight]                    FLOAT (53)         NULL,
	[LoadByNet]                               BIT                NULL,
	[PromptForShipmentNumber]                 BIT                NULL,
	[MaximumProductTemperature]               FLOAT (53)         NULL,
	[ListEquipment]                           BIT                NULL,
	[DeferStationChanges]                     BIT                NULL,
	[InhibitBOLWithBrokenBlends]              BIT                NULL,
	[InhibitBOLWithImproperAdditization]      BIT                NULL,
	[InhibitOverweightBOL]                    BIT                NULL,
	[ExceptionBOLPrinter]                     NVARCHAR (80)      NULL,
	[EnableAutomaticBOLPrinting]              BIT                NULL,
	[AutomaticBOLStartNumber]                 INT                NULL,
	[AutomaticBOLEndNumber]                   INT                NULL,
	[AutomaticBOLNextNumber]                  INT                NULL,
	[SeparateManualBOLNumbering]              BIT                NULL,
	[ManualBOLStartNumber]                    INT                NULL,
	[ManualBOLEndNumber]                      INT                NULL,
	[ManualBOLNextNumber]                     INT                NULL,
	[TransactionStartNumber]                  INT                NULL,
	[TransactionEndNumber]                    INT                NULL,
	[TransactionNextNumber]                   INT                NULL,
	[OrderStartNumber]                        INT                NULL,
	[OrderEndNumber]                          INT                NULL,
	[OrderNextNumber]                         INT                NULL,
	[NumberPrefix]                            NVARCHAR (10)      NULL,
	[OpenTransactionWindow]                   INT                NULL,
	[AdministrativeLockDate]                  DATETIMEOFFSET (7) NULL,
	[OperationalLockDate]                     DATETIMEOFFSET (7) NULL,
	[MaximumDaysToRetainLogs]                 INT                NULL,
	[EnableDebugLogging]                      BIT                NULL,
	[EnableAuditLogging]                      BIT                NULL,
	[AutomaticallyPrintAlarmsAndEvents]       BIT                NULL,
	[AlarmAndEventPrinter]                    NVARCHAR (80)      NULL,
	[MailServer]                              NVARCHAR (50)      NULL,
	[MailFrom]                                NVARCHAR (50)      NULL,
	[MailUserName]                            NVARCHAR (50)      NULL,
	[MailPassword]                            NVARCHAR (50)      NULL,
	[DialupName]                              NVARCHAR (50)      NULL,
	[SCADASystem]                             NVARCHAR (50)      NULL,
	[InhibitTemplateGraphics]                 BIT                NULL,
	[RefreshInterval]                         INT                NULL,
	[InhibitEndOfDayOperations]               BIT                NULL,
	[InhibitEndOfMonthOperations]             BIT                NULL,
	[EndOfDayWarningPeriod]                   INT                NULL,
	[InhibitAutomaticPhysicalInventory]       BIT                NULL,
	[InhibitAutomaticMeterCloseout]           BIT                NULL,
	[InhibitAutomaticReportGeneration]        BIT                NULL,
	[InhibitAutomaticAdjustmentDistribution]  BIT                NULL,
	[InhibitAutomaticCloseout]                BIT                NULL,
	[InhibitTankScan]                         BIT                NULL,
	[ReportDirectory]                         NVARCHAR (80)      NULL,
	[ManageReports]                           BIT                NULL,
	[ManagedReportDirectory]                  NVARCHAR (80)      NULL,
	[VRURateLimit]                            FLOAT (53)         NULL,
	[VRUHourlyLimit]                          FLOAT (53)         NULL,
	[VRUDailyLimit]                           FLOAT (53)         NULL,
	[VRUYearlyLimit]                          FLOAT (53)         NULL,
	[VRUCurrentYearLimit]                     FLOAT (53)         NULL,
	[VRURateActual]                           FLOAT (53)         NULL,
	[VRUHourlyActual]                         FLOAT (53)         NULL,
	[VRUDailyActual]                          FLOAT (53)         NULL,
	[VRUYearlyActual]                         FLOAT (53)         NULL,
	[VRUCurrentYearActual]                    FLOAT (53)         NULL,
	[VRURateLimitEnabled]                     BIT                NULL,
	[VRUHourlyLimitEnabled]                   BIT                NULL,
	[VRUDailyLimitEnabled]                    BIT                NULL,
	[VRUYearlyLimitEnabled]                   BIT                NULL,
	[VRUCurrentYearLimitEnabled]              BIT                NULL,
	[WatchdogPeriod]                          INT                NULL,
	[WatchdogCounterStart]                    INT                NULL,
	[WatchdogCounterEnd]                      INT                NULL,
	[NumberDecimalSeparator]                  NVARCHAR (1)       NULL,
	[NumberGroupSeparator]                    NVARCHAR (1)       NULL,
	[ListSeparator]                           NVARCHAR (1)       NULL,
	[TimePattern]                             NVARCHAR (20)      NULL,
	[TimeSeparator]                           NVARCHAR (1)       NULL,
	[AMSymbol]                                NVARCHAR (2)       NULL,
	[PMSymbol]                                NVARCHAR (2)       NULL,
	[ShortDatePattern]                        NVARCHAR (20)      NULL,
	[DateSeparator]                           NVARCHAR (1)       NULL,
	[LongDatePattern]                         NVARCHAR (30)      NULL,
	[TwoDigitCalendarEndYear]                 INT                NULL,
	[UserData1]                               NVARCHAR (60)      NULL,
	[UserData2]                               NVARCHAR (60)      NULL,
	[UserData3]                               NVARCHAR (60)      NULL,
	[UserData4]                               NVARCHAR (60)      NULL,
	[UserData5]                               NVARCHAR (60)      NULL,
	[UserData6]                               NVARCHAR (60)      NULL,
	[UserData7]                               NVARCHAR (60)      NULL,
	[UserData8]                               NVARCHAR (60)      NULL,
	[CreatedDate]                             DATETIMEOFFSET (7) CONSTRAINT [DF_tblSitesShadow_CreatedDate] DEFAULT (sysdatetimeoffset()) NULL,
	[CreatedBy]                               [dbo].[udtUserID]  NULL,
	[UpdatedDate]                             DATETIMEOFFSET (7) CONSTRAINT [DF_tblSitesShadow_UpdatedDate] DEFAULT (sysdatetimeoffset()) NULL,
	[UpdatedBy]                               [dbo].[udtUserID]  NULL,
	[MinTimeAllowedToChangePwd]               INT                NULL,
	[MinPwdCharacterLength]                   INT                NULL,
	[PwdExpirationInDays]                     INT                NULL,
	[PwdLockoutThreshold]                     INT                NULL,
	[CheckForPreviousPwd]                     BIT                NULL,
	[StrongPwdUse]                            INT                NULL,
	[PwdHistoryCount]                         INT                NULL,
	[ApplyToAllSiteMembers]                   BIT                NULL,
	[InactivityDisablePeriod]                 INT                CONSTRAINT [DF_tblSitesShadow_InactivityDisablePeriod] DEFAULT ((30)) NULL,
	[EnforceSingleOwner]                      BIT                NULL,
	[InhibitBOLSummaryAutoPopulate]           BIT                NULL,
	[InhibitOrderSummaryAutoPopulate]         BIT                NULL,
	[InhibitSupplyOrderSummaryAutoPopulate]   BIT                NULL,
	[InvoiceStartNumber]                      INT                NULL,
	[InvoiceEndNumber]                        INT                NULL,
	[InvoiceNextNumber]                       INT                NULL,
	[PromptForReturns]                        BIT                NULL,
	[PromptForTruckCard]                      BIT                NULL,
	[StartingShortCardNumber]                 INT                NULL,
	[UseShortCardNumber]                      BIT                NULL,
	[ExcessVarianceCount]                     TINYINT            NULL,
	[ExcessVarianceTolerance]                 FLOAT (53)         NULL,
	[DisableArchivePeriod]                    INT                CONSTRAINT [DF_tblSitesShadow_DisableArchivePeriod] DEFAULT ((180)) NOT NULL,
	[ExportArchiveDir]                        NVARCHAR (255)     NULL,
	[ImportArchiveDir]                        NVARCHAR (255)     NULL,
	[GroupLedgerByID]                         BIT                NULL,
	[InhibitSiteLedgerRollup]                 BIT                NULL,
	[UseTankReconciliation]                   BIT                CONSTRAINT [DF_tblSitesShadow_UseTankReconciliation] DEFAULT ((0)) NOT NULL,
	[SiteGuid]                                UNIQUEIDENTIFIER   CONSTRAINT [DF_tblSitesShadow_GUID] DEFAULT (newid()) NOT NULL,
	[_RowVersion]                             ROWVERSION         NOT NULL,
	[LookupNumberGroupSizesTypeIndex]         INT                NULL,
	[LookupQuantityDisplayDefaultIndex]       TINYINT            NULL,
	[LookupSecondaryStorageFillMethodIndex]   TINYINT            NULL,
	[LookupMailConnectModeIndex]              TINYINT            NULL,
	[LookupWatchdogModeIndex]                 TINYINT            NULL,
	[Contact1Name]                            NVARCHAR (30)      NULL,
	[Contact1Address1]                        NVARCHAR (30)      NULL,
	[Contact1Address2]                        NVARCHAR (30)      NULL,
	[Contact1City]                            NVARCHAR (60)      NULL,
	[Contact1State]                           NVARCHAR (20)      NULL,
	[Contact1Zip]                             NVARCHAR (11)      NULL,
	[Contact1Country]                         NVARCHAR (30)      NULL,
	[Contact1PhoneOffice]                     NVARCHAR (20)      NULL,
	[Contact1Fax]                             NVARCHAR (20)      NULL,
	[Contact1EmailAddress]                    NVARCHAR (30)      NULL,
	[Contact2Name]                            NVARCHAR (30)      NULL,
	[Contact2Address1]                        NVARCHAR (30)      NULL,
	[Contact2Address2]                        NVARCHAR (30)      NULL,
	[Contact2City]                            NVARCHAR (60)      NULL,
	[Contact2State]                           NVARCHAR (20)      NULL,
	[Contact2Zip]                             NVARCHAR (11)      NULL,
	[Contact2Country]                         NVARCHAR (30)      NULL,
	[Contact2PhoneOffice]                     NVARCHAR (20)      NULL,
	[Contact2Fax]                             NVARCHAR (20)      NULL,
	[Contact2EmailAddress]                    NVARCHAR (30)      NULL,
	[Contact1PhoneMobile]                     NVARCHAR (20)      NULL,
	[Contact2PhoneMobile]                     NVARCHAR (20)      NULL,
	[EnablePasswordHint]                      BIT                CONSTRAINT [DF_tblSitesShadow_EnablePasswordHint] DEFAULT ((0)) NULL,
	[EnablePasswordReset]                     BIT                CONSTRAINT [DF_tblSitesShadow_EnablePasswordReset] DEFAULT ((0)) NULL,
	[MeterReconciliationToleranceIsPercent]   BIT                CONSTRAINT [DF_tblSitesShadow_MeterReconciliationToleranceIsPercent] DEFAULT ((0)) NOT NULL,
	[MeterReconciliationReportName]           NVARCHAR (60)      NULL,
	[TranslatedHelpURL]                       NVARCHAR (250)     NULL,
	[AllowUseOfSpecialChars]                  BIT                CONSTRAINT [DF_tblSitesShadow_AllowUseOfSpecialChar] DEFAULT ((1)) NOT NULL,
	[EnablePeriodicSyncFlag]                  BIT                CONSTRAINT [DF_tblSitesShadow_EnablePeriodicSyncFlag] DEFAULT ((0)) NOT NULL,
	[PeriodicSyncIntervalMinutes]             INT                CONSTRAINT [DF_tblSitesShadow_PeriodicSyncIntervalMinutes] DEFAULT ((0)) NOT NULL,
	[DisableSyncTransferFlag]                 BIT                CONSTRAINT [DF_tblSitesShadow_DisableSyncTransferFlag] DEFAULT ((0)) NOT NULL,
	[CardInTimeout]                           INT				 NULL,
	[TerminalControlNumber]					  nvarchar(9)		 NULL,
	[BlockCloseOnUnpostedBOL]                 BIT				 NULL,
	[InhibitLoadRackCardIns]                  BIT				 NULL,
	[PromptForThirdTrailer]                   BIT				 CONSTRAINT [DF_tblSitesShadow_PromptForThirdTrailer] DEFAULT ((0)) NULL,
	[PromptForTransactionCompletion]          BIT				 CONSTRAINT [DF_tblSitesShadow_PromptForTransactionCompletion] DEFAULT ((0)) NULL,
	[InhibitCustomerConfirmationPrompt]       BIT				 CONSTRAINT [DF_tblSitesShadow_InhibitCustomerConfirmationPrompt] DEFAULT ((0)) NULL,
	[EnableBOLPDFArchiving]                   BIT				 CONSTRAINT [DF_tblSitesShadow_EnableBOLPDFArchiving] DEFAULT ((0)) NULL,
	[BOLPDFArchivingPath]                     NVARCHAR (50)		 NULL,
	[RequireTrailerScully]                    BIT				 CONSTRAINT [DF_tblSitesShadow_RequireTrailerScully] DEFAULT ((0)) NULL,	
	[DeletedDate]                             DATETIMEOFFSET (7) NULL,
	[_ClusterIdx]                             BIGINT             IDENTITY (1, 1) NOT NULL,
	[Latitude]								  FLOAT NULL, 
	[Longitude]								  FLOAT NULL, 
	[Zoom]									  INT NULL,
	[Enterprise]							  BIT NULL,
	[OperateTabGroups]						  BIT NULL,
	[ActiveDirectorySiteGroupGuid]            UNIQUEIDENTIFIER NULL,
	[ServerEndPoint]		                  nvarchar(250) NULL,
	[SecurityMode]			                  nvarchar(50) NULL,
	[SecurityPolicy]		                  nvarchar(50) NULL,
	[MessageEncoding]		                  nvarchar(50) NULL,
	[UserIdentityMethod]	                  nvarchar(50) NULL,
	[UserId]				                  nvarchar(250) NULL,
	[UserPassword]			                  nvarchar(250) NULL,
	[UserCertificatePath]	                  nvarchar(250) NULL,
	[MaximumDaysToRetainArchive]              int NULL,
	[EnforceSalesOrderLimit]                  BIT                CONSTRAINT [DF_tblSitesShadow_EnforceSalesOrderLimit] DEFAULT ((0)) NOT NULL,
	[LeakDetectionQuietSamples]               INT NULL, 
	[LeakDetectionQuietTime]                  INT NULL, 
	[LeakDetectionQuietTimeFactor]            INT NULL, 
	[LeakDetectionUseMinWait]               BIT NULL, 
	[LeakDetectionReport]                     NVARCHAR(60) NULL, 
	[LeakDetectionPrinter]                    NVARCHAR(80) NULL, 
	[EnableAutomaticMovementTicketPrinting] BIT NULL,
	[MovementTicketReport]					  NVARCHAR(60) NULL, 
	[MovementTicketPrinter]					  NVARCHAR(80) NULL,
	[MaxOperateTabsAllowed] INT CONSTRAINT [DF_tblSitesShadow_MaxOperateTabsAllowed] DEFAULT ((10)) NOT NULL, 
   [CloseoutTime] TIME NULL, 
   [PointGroupFileExportDirectory]			NVARCHAR(255) NULL,
   [PointGroupDefaultFileName]			NVARCHAR(255) NULL,
	[EnableMovementTicketPDFArchiving] BIT NULL,
   [MovementTicketFileExportDirectory]			NVARCHAR(255) NULL,
   [MovementTicketExportFileName]			NVARCHAR(255) NULL,
	[MovementNumber]                    INT NULL,
	CONSTRAINT [PK_tblSitesShadow_GUID] PRIMARY KEY NONCLUSTERED ([SiteGuid] ASC),
	CONSTRAINT [FK_tblSitesShadow_AdditiveProfileCycleAmountUnitIndex] FOREIGN KEY ([AdditiveProfileCycleAmountUnitIndex]) REFERENCES [lookup].[tblEngineeringUnit] ([EngineeringUnitIndex]),
	CONSTRAINT [FK_tblSitesShadow_AdditiveProfileRateUnitIndex] FOREIGN KEY ([AdditiveProfileRateUnitIndex]) REFERENCES [lookup].[tblEngineeringUnit] ([EngineeringUnitIndex]),
	CONSTRAINT [FK_tblSitesShadow_AdditiveVolumeUnitIndex] FOREIGN KEY ([AdditiveVolumeUnitIndex]) REFERENCES [lookup].[tblEngineeringUnit] ([EngineeringUnitIndex]),
	CONSTRAINT [FK_tblSitesShadow_DensityUnitIndex] FOREIGN KEY ([DensityUnitIndex]) REFERENCES [lookup].[tblEngineeringUnit] ([EngineeringUnitIndex]),
	CONSTRAINT [FK_tblSitesShadow_FlowUnitIndex] FOREIGN KEY ([FlowUnitIndex]) REFERENCES [lookup].[tblEngineeringUnit] ([EngineeringUnitIndex]),
	CONSTRAINT [FK_tblSitesShadow_LevelUnitIndex] FOREIGN KEY ([LevelUnitIndex]) REFERENCES [lookup].[tblEngineeringUnit] ([EngineeringUnitIndex]),
	CONSTRAINT [FK_tblSitesShadow_LookupFillMethodIndex] FOREIGN KEY ([LookupSecondaryStorageFillMethodIndex]) REFERENCES [lookup].[tblFillMethod] ([FillMethodIndex]),
	CONSTRAINT [FK_tblSitesShadow_LookupMailServerConnectModeIndex] FOREIGN KEY ([LookupMailConnectModeIndex]) REFERENCES [lookup].[tblMailServerConnectMode] ([MailServerConnectModeIndex]),
	CONSTRAINT [FK_tblSitesShadow_LookupNumberGroupSizesTypeIndex] FOREIGN KEY ([LookupNumberGroupSizesTypeIndex]) REFERENCES [lookup].[tblNumberGroupSizesType] ([NumberGroupSizesTypeIndex]),
	CONSTRAINT [FK_tblSitesShadow_LookupQuantityDisplayIndex] FOREIGN KEY ([LookupQuantityDisplayDefaultIndex]) REFERENCES [lookup].[tblQuantityDisplay] ([QuantityDisplayIndex]),
	CONSTRAINT [FK_tblSitesShadow_LookupWatchdogModeIndex] FOREIGN KEY ([LookupWatchdogModeIndex]) REFERENCES [lookup].[tblWatchdogMode] ([WatchdogModeIndex]),
	CONSTRAINT [FK_tblSitesShadow_MassUnitIndex] FOREIGN KEY ([MassUnitIndex]) REFERENCES [lookup].[tblEngineeringUnit] ([EngineeringUnitIndex]),
	CONSTRAINT [FK_tblSitesShadow_PressureUnitIndex] FOREIGN KEY ([PressureUnitIndex]) REFERENCES [lookup].[tblEngineeringUnit] ([EngineeringUnitIndex]),
	CONSTRAINT [FK_tblSitesShadow_TemperatureUnitIndex] FOREIGN KEY ([TemperatureUnitIndex]) REFERENCES [lookup].[tblEngineeringUnit] ([EngineeringUnitIndex]),
	CONSTRAINT [FK_tblSitesShadow_VolumeUnitIndex] FOREIGN KEY ([VolumeUnitIndex]) REFERENCES [lookup].[tblEngineeringUnit] ([EngineeringUnitIndex])
);


GO



GO
CREATE UNIQUE NONCLUSTERED INDEX [IXU_tblSitesShadow_SiteGuid_CreatedDate]
    ON [dbo].[tblSitesShadow]([SiteGuid] ASC, [CreatedDate] ASC)
    INCLUDE([ID], [SiteGroupFlag], [AdministrativeLockDate], [OperationalLockDate], [Number], [LookupSecondaryStorageFillMethodIndex], [ExcessVarianceTolerance]);


GO
CREATE NONCLUSTERED INDEX [IX_tblSitesShadow_CreatedDate]
    ON [dbo].[tblSitesShadow]([CreatedDate] ASC);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_tblSitesShadow_ClusterIdx]
    ON [dbo].[tblSitesShadow]([_ClusterIdx] ASC);

