//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AcculoadOPCServer.rc
//
#define IDS_PROJNAME                    100
#define IDR_ACCULOADOPCSERVER           101
#define IDS_ERROR_ACCESS_DENIED         101
#define IDS_ERROR_ACCULOAD_EXISTS       102
#define IDR_DATAACCESS                  103
#define IDS_ERROR_ACCULOAD_NOT_FOUND    103
#define IDR_ACCULOADS                   104
#define IDS_ERROR_ARM_EXISTS            104
#define IDR_ARMS                        105
#define IDS_ERROR_ARM_NOT_FOUND         105
#define IDS_ERROR_ID_REQUIRED           106
#define IDS_ERROR_AT_LEAST_ONE_ARM_REQUIRED 107
#define IDS_ERROR_ADDRESS_CONFLICT      108
#define IDS_ERROR_PRODUCTS              109
#define IDR_OPCSERVER                   110
#define IDS_VENDOR_INFO                 110
#define IDS_CURRENT_FLOW_RATE_UNITS_MIN 111
#define IDS_DYNAMIC_VALUES              112
#define IDS_SYSTEM                      113
#define IDS_CURRENT_FLOW_RATE_UNITS_HR  114
#define IDS_CURRENT_RECIPE              115
#define IDS_PRODUCT_NUMBER              116
#define IDS_ALLOCATE_RECIPES            117
#define IDS_AUTHORIZE_TRANSACTION       118
#define IDS_CURRENT_PRESET_UNITS_MIN    119
#define IDS_CURRENT_DELIVERED_VOLUME    120
#define IDS_CURRENT_REMAINING_VOLUME    121
#define IDS_PROGRAM_ERROR               122
#define IDS_BACK_PRESSURE               123
#define IDS_AVERAGE_API                 124
#define IDS_AVERAGE_REFERENCE_DENSITY   125
#define IDS_AVERAGE_RELATIVE_DENSITY    126
#define IDS_HIGH_DENSITY                127
#define IDS_AVERAGE_VAPOR_PRESSURE      128
#define IDS_HIGH_FLOW                   129
#define IDS_HIGH_PRESSURE               130
#define IDS_HIGH_TEMPERATURE            131
#define IDS_CURRENT_TEMPERATURE         132
#define IDS_CURRENT_DENSITY             133
#define IDS_CURRENT_METER_FACTOR        134
#define IDS_CURRENT_VALVE_REQUESTED_POSITION 135
#define IDS_CURRENT_PERCENTAGE_OF_BATCH 136
#define IDS_DESIRED_PERCENTAGE_OF_BATCH 137
#define IDS_LOW_DENSITY                 138
#define IDS_LOW_FLOW                    139
#define IDS_LOW_PRESSURE                140
#define IDS_LOW_TEMPERATURE             141
#define IDS_ZERO_FLOW                   142
#define IDS_RAW_VOLUME                  143
#define IDS_GROSS_VOLUME                144
#define IDS_GST_VOLUME                  145
#define IDS_GSV_VOLUME                  146
#define IDS_MASS_TOTAL                  147
#define IDS_TRANSACTION                 148
#define IDS_AVERAGE_TEMPERATURE         149
#define IDS_AVERAGE_DENSITY             150
#define IDS_AVERAGE_PRESSURE            151
#define IDS_AVERAGE_METER_FACTOR        152
#define IDS_AVERAGE_CTL                 153
#define IDS_AVERAGE_CPL                 154
#define IDS_VOLUME                      155
#define IDS_RESET_STANDBY_MODE          156
#define IDS_RESET_POWERFAIL             157
#define IDS_CURRENT_BATCH               158
#define IDS_PRESET_AMOUNT               159
#define IDS_CLEAR_TRANSACTIONS          160
#define IDS_ERROR_PORT_EXISTS           161
#define IDS_ERROR_PORT_NOT_FOUND        162
#define IDS_LOG_OUT_OF_PROGRAM_MODE     163
#define IDS_STOP_ALL_ARMS               164
#define IDS_METER_FACTOR                165
#define IDS_GET_BATCH_NUMBER            166
#define IDS_GET_KEY                     167
#define IDS_PRESETTING_IN_PROGRESS      168
#define IDS_FORCE_FULL_SCREEN_VIEW      169
#define IDS_READ_REGISTER               170
#define IDS_WRITE_REGISTER              171
#define IDS_RCU_TRANS_HEADER            172
#define IDS_PROVING_MODE                173
#define IDS_POWER_UP                    174
#define IDS_RCU_STATUS                  175
#define IDS_CARD_STATUS                 176
#define IDS_CONFIGURED                  177
#define IDS_ADDITIVES                   178
#define IDS_BATCH                       179
#define IDS_ALARMS                      180
#define IDS_ROM_BAD                     181
#define IDS_RAM_BAD                     182
#define IDS_FLASH_ERROR                 183
#define IDS_RAM_CORRUPT                 184
#define IDS_FLASH_BACKUP_BAD            185
#define IDS_SYS_PROG_ERROR              186
#define IDS_EAAI_FAILURE                187
#define IDS_WATCHDOG                    188
#define IDS_BSE_FAILURE                 189
#define IDS_PASSCODE_RESET              190
#define IDS_POWERFAIL                   191
#define IDS_COMMUNICATION               192
#define IDS_CIVACON_COMM_FAILURE        193
#define IDS_SHARED_PRINTER              194
#define IDS_PTB_PRINTER                 195
#define IDS_USER_ALARM_01               196
#define IDS_USER_ALARM_02               197
#define IDS_USER_ALARM_03               198
#define IDS_USER_ALARM_04               199
#define IDS_USER_ALARM_05               200
#define IDS_USER_ALARM_06               201
#define IDS_USER_ALARM_07               202
#define IDS_USER_ALARM_08               203
#define IDS_USER_ALARM_09               204
#define IDS_USER_ALARM_10               205
#define IDS_ADD_PAK_1_POWERFAIL         206
#define IDS_ADD_PAK_2_POWERFAIL         207
#define IDS_ADD_PAK_1_DIAGNOSTIC        208
#define IDS_ADD_PAK_2_DIAGNOSTIC        209
#define IDS_ADD_PAK_1_AUTO_DETECT_FAILED 210
#define IDS_ADD_PAK_2_AUTO_DETECT_FAILED 211
#define IDS_ADD_PAK_1_COMM_FAIL         212
#define IDS_ADD_PAK_2_COMM_FAIL         213
#define IDS_DISPLAY_FAILURE             214
#define IDS_OVERRUN                     215
#define IDS_BLOCK_VALVE                 216
#define IDS_BLEND_HIGH                  217
#define IDS_BLEND_LOW                   218
#define IDS_TICKET                      219
#define IDS_CLEAN_LINE                  220
#define IDS_ADDITIVE_CLEAN_LINE         221
#define IDS_INJECTOR_NUMBER             222
#define IDS_FEEDBACK                    223
#define IDS_LOW_ADD_ERROR               224
#define IDS_EXCESS_PULSES               225
#define IDS_NO_PULSES                   226
#define IDS_FREQUENCY                   227
#define IDS_UNAUTH_FAILED               228
#define IDS_GENERAL_ADDITIVE_ERROR      229
#define IDS_OVER_SPEED                  230
#define IDS_COMMAND_REFUSED             231
#define IDS_AUTODETECT_FAIL             232
#define IDS_COMM_ERROR                  233
#define IDS_METER_NUMBER                234
#define IDS_TRANSMITTER_INTEGRITY       235
#define IDS_ARM_NUMBER                  236
#define IDS_PULSE_SECURITY              237
#define IDS_VALVE_FAULT                 238
#define IDS_TEMPERATURE_PROBE           239
#define IDS_PRESSURE_TRANSMITTER        240
#define IDS_DENSITY_TRANSMITTER         241
#define IDS_TURBINE_METER               242
#define IDS_INCLUDE_ADDITIVE_TOTALS     243
#define IDS_END_BATCH                   244
#define IDS_STATUS                      245
#define IDS_AUTHORIZED                  246
#define IDS_FLOWING                     247
#define IDS_RELEASED                    248
#define IDS_PROGRAM_MODE                249
#define IDS_KEYPAD_DATA_PENDING         250
#define IDS_BATCH_DONE                  251
#define IDS_TRANSACTION_IN_PROGRESS     252
#define IDS_IN_STANDBY_MODE             253
#define IDS_STORAGE_FULL                254
#define IDS_STANDBY_TRANSACTIONS_EXIST  255
#define IDS_TRANSACTION_DONE            256
#define IDS_ALARM_ON                    257
#define IDS_TYPE                        257
#define IDS_POWER_FAIL_OCCURED          258
#define IDS_DISPLAY_MESSAGE_TIME_OUT    259
#define IDS_DELAYED_PROMPT_IN_EFFECT    260
#define IDS_INPUT_01                    261
#define IDS_INPUT_02                    262
#define IDS_INPUT_03                    263
#define IDS_INPUT_04                    264
#define IDS_INPUT_05                    265
#define IDS_INPUT_06                    266
#define IDS_INPUT_07                    267
#define IDS_INPUT_08                    268
#define IDS_INPUT_09                    269
#define IDS_INPUT_10                    270
#define IDS_INPUT_11                    271
#define IDS_INPUT_12                    272
#define IDS_INPUT_13                    273
#define IDS_INPUT_14                    274
#define IDS_INPUT_15                    275
#define IDS_INPUT_16                    276
#define IDS_INPUT_17                    277
#define IDS_INPUT_18                    278
#define IDS_INPUT_19                    279
#define IDS_INPUT_20                    280
#define IDS_INPUT_21                    281
#define IDS_INPUT_22                    282
#define IDS_INPUT_23                    283
#define IDS_INPUT_24                    284
#define IDS_INPUT_25                    285
#define IDS_INPUT_26                    286
#define IDS_INPUT_27                    287
#define IDS_INPUT_28                    288
#define IDS_INPUT_29                    289
#define IDS_INPUT_30                    290
#define IDS_INPUT_31                    291
#define IDS_INPUT_32                    292
#define IDS_INPUT_33                    293
#define IDS_INPUT_34                    294
#define IDS_INPUT_35                    295
#define IDS_INPUT_36                    296
#define IDS_INPUT_37                    297
#define IDS_INPUT_38                    298
#define IDS_INPUT_39                    299
#define IDS_INPUT_40                    300
#define IDS_INPUT_41                    301
#define IDS_INPUT_42                    302
#define IDS_INPUT_43                    303
#define IDS_CHECKING_ENTRIES            304
#define IDS_PRINTING_IN_PROGRESS        305
#define IDS_PERMISSIVE_DELAY            306
#define IDS_PROGRAM_VALUE_CHANGED       307
#define IDS_END_TRANSACTION             308
#define IDS_STOP                        309
#define IDS_START                       310
#define IDS_SWING_ARM_POSITION          311
#define IDS_METER                       312
#define IDS_WRITE_SECOND_LINE           313
#define IDS_WRITE_THIRD_LINE            314
#define IDS_WRITE_FOURTH_LINE           315
#define IDS_WRITE_FIRST_LINE_WITH_PROMPT 316
#define IDS_WRITE_FIRST_LINE_WITH_PROMPT_ON_SET 317
#define IDS_WRITE_FIRST_LINE_WITH_PROMPT_ON_SET_NO_ECHO 318
#define IDS_WRITE_FIRST_LINE_WITH_PROMPT_NO_ECHO 319
#define IDS_KEYPAD_DATA                 320
#define IDS_DATA                        321
#define IDS_NEW_CARD_DATA               322
#define IDS_I_O_CONTROL                 323
#define IDS_GREEN_LED                   324
#define IDS_RED_LED                     325
#define IDS_BEEP                        326
#define IDS_CONTACT                     327
#define IDS_CARD_READER                 328
#define IDS_RESET_DATA                  329
#define IDS_RELEASE_KEYPAD_AND_DISPLAY  330
#define IDS_PROMPTS                     331
#define IDS_RESET_TRANSACTION_DONE      332
#define IDS_RESET_BATCH_DONE            333
#define IDS_NON_RESETTABLE_TOTALS       334
#define IDS_STARTED                     335
#define IDS_STOPPED                     336
#define IDS_HARDWARE_KEY_FAILURE        337
#define IDS_TEMPERATURE                 338
#define IDS_PRESSURE                    339
#define IDS_DENSITY                     340
#define IDS_ANALOG_INPUTS               341
#define IDS_DIGITAL_OUTPUTS             342
#define IDS_DIGITAL_INPUTS              343
#define IDS_RECIPES                     344
#define IDS_USED                        345
#define IDS_NAME                        346
#define IDS_HM_CLASS_PRODUCT            347
#define IDS_1ST_DELIVERED               348
#define IDS_1ST_PERCENTAGE              349
#define IDS_2ND_DELIVERED               350
#define IDS_2ND_PERCENTAGE              351
#define IDS_3RD_DELIVERED               352
#define IDS_3RD_PERCENTAGE              353
#define IDS_4TH_DELIVERED               354
#define IDS_4TH_PERCENTAGE              355
#define IDS_5TH_DELIVERED               356
#define IDS_5TH_PERCENTAGE              357
#define IDS_6TH_DELIVERED               358
#define IDS_6TH_PERCENTAGE              359
#define IDS_CLEAN_LINE_DEDUCT           360
#define IDS_ADDITIVE_INJECTOR_AMOUNT_PER_CYCLE 361
#define IDS_ADDITIVE_INJECTOR_RATE      362
#define IDS_ADDITIVE_INJECTOR_PRODUCTS_USING_INJECTOR 363
#define IDS_PRODUCT                     364
#define IDR_PORTS                       365
#define IDS_HOST_UP                     365
#define IDS_SET_DATE_AND_TIME           366
#define IDS_AUTHORIZE_AND_SET_BATCH_AMOUNT 367
#define IDR_MICROLOADS                  368
#define IDS_MASS_METER_TUBE             368
#define IDS_ERROR_MICROLOAD_NOT_FOUND   369
#define IDS_ERROR_MICROLOAD_EXISTS      370
#define IDS_WRITE_FIFTH_LINE            371
#define IDS_WRITE_SIXTH_LINE            372
#define IDS_WRITE_SEVENTH_LINE          373
#define IDS_MASS_METER_COMM_FAIL        374
#define IDS_MASS_METER_OVERDRIVE        375
#define IDS_CURRENT_PRESSURE            376
#define IDS_VAPOR_PRESSURE              377
#define IDS_TIME_OF_LAST_POWER_FAIL     378
#define IDS_PROGRAM_CODE_CHANGE         379
#define IDS_RESET_POWER_FAIL_ALARM      380
#define IDS_INPUT_IN_PROGRESS           381
#define IDS_INPUT_DONE                  382
#define IDS_TERMINAL_COMMAND            383
#define IDS_AUTHORIZE_PRESET            384
#define IDS_CLEAR_ALARMS                385
#define IDS_ADDITIVE_ALARMS             386
#define IDS_FCM_COMM                    387
#define IDS_PERMISSIVE                  388
#define IDS_UNDER_ADDITIZED             389
#define IDS_OVER_ADDITIZED              390
#define IDS_PUMP_STATUS                 391
#define IDS_INJECTION                   392
#define IDS_UNAUTHORIZED_FLOW           393
#define IDS_LINE_NOT_FLUSHED            394
#define IDS_METER_CREEP                 395
#define IDS_METER_ALARMS                396
#define IDS_FCM_INVALID_CONFIG          397
#define IDS_FCM_WDT_RESET               398
#define IDS_FCM_COMM_TIMEOUT            399
#define IDS_EXCESS_FLOW                 400
#define IDS_QUAD_ENCODING               401
#define IDS_DENSITY_ERROR               402
#define IDS_TEMP_ERROR                  403
#define IDS_VALVE_CONTROL               404
#define IDS_PRESSURE_ERROR              405
#define IDS_QUAD_ENCODING_A             406
#define IDS_QUAD_ENCODING_B             407
#define IDS_COMPONENT_ALARMS            408
#define IDS_METER_ALARM                 409
#define IDS_OVER_BLEND                  410
#define IDS_UNDER_BLEND                 411
#define IDS_API_TABLE                   412
#define IDS_BAY_ALARMS                  413
#define IDS_PERMISSIVE_0                414
#define IDS_PERMISSIVE_1                415
#define IDS_PERMISSIVE_2                416
#define IDS_PERMISSIVE_3                417
#define IDS_PERMISSIVE_4                418
#define IDS_PERMISSIVE_5                419
#define IDS_PERMISSIVE_6                420
#define IDS_PERMISSIVE_7                421
#define IDS_ALL_STOP                    422
#define IDS_PCM_COMM                    423
#define IDS_PRINTER_ERROR               424
#define IDS_FCM_TRACE                   425
#define IDS_PRESET_ALARMS               426
#define IDS_SWING_ARM_PERMISSIVE        427
#define IDS_BAY                         428
#define IDS_COMPONENT                   429
#define IDS_ADDITIVE                    430
#define IDS_METER_STOP                  431
#define IDS_ENABLE_PRESET               432
#define IDS_CONFIGURATION_ERROR         433
#define IDS_BATCH_COMPLETE              434
#define IDS_BATCH_END                   435
#define IDS_PRESET_MESSAGE              436
#define IDS_PRESET_STATUS               437
#define IDS_STATE                       438
#define IDS_ENABLED                     439
#define IDS_HOST_ENABLED                440
#define IDS_FLOW_ACTIVE                 441
#define IDS_BATCH_AUTHORIZED            442
#define IDS_REMOTE_MSG                  443
#define IDS_REMOTE_DESC                 444
#define IDS_LOAD_COMPLETE               445
#define IDS_BATCH_END_DONE              446
#define IDS_ARCHIVED                    447
#define IDS_BATCH_CLEARED               448
#define IDS_CLEAR_LOAD                  449
#define IDS_LOAD_CLEARED                450
#define IDS_TRANS_DONE                  451
#define IDS_PRESET_QUANTITY             452
#define IDS_FLOW_RATE                   453
#define IDS_GROSS_TOTALIZER             454
#define IDS_PROGRAM_KEY_ACTIVE          455
#define IDS_NET_VOLUME                  456
#define IDS_WEIGHTS_AND_MEASURES_KEY_ACTIVE 457
#define IDS_TERMINATING_KEY             458
#define IDS_FHOSTUP                     459
#define IDS_FPOWERUP                    460
#define IDS_FHOSTDOWN                   461
#define IDS_FCLEARPROD                  462
#define IDS_PRESET_STATE                463
#define IDS_LOG_MSG_QUEUED              464
#define IDS_TRANSACTION_TERMINATION     465
#define IDS_AVERAGE_CTPL                466
#define IDS_CARD_NUMBER                 467
#define IDS_COMPONENT1                  468
#define IDS_COMPONENT2                  469
#define IDS_COMPONENT3                  470
#define IDS_COMPONENT4                  471
#define IDS_COMPONENT5                  472
#define IDS_COMPONENT6                  473
#define IDS_COMPONENT7                  474
#define IDS_COMPONENT8                  475
#define IDS_CLEAN_LINE_PRODUCT          476
#define IDS_ARM_CLEAN_LINE_AMOUNT       477
#define IDS_ARM_CLEAN_LINE_PRODUCT      478
#define IDS_ARM_CLEAN_LINE_BLEND        479
#define IDS_ALARM                       480
#define IDS_RECIPE                      481
#define IDS_CURRENT_REFERENCE_DENSITY   482
#define IDS_FLOW_CONTROLLED_ADDITIVES   483
#define IDS_RESET_COMMFAIL_ALARM        484
#define IDS_RESET_COMM_FAIL_ALARM       484
#define IDS_QUERY_CARD                  576
#define IDS_CLEAR_DISPLAY               577
#define IDS_DISPLAY_TEXT                578
#define IDS_KEY_INPUT                   579
#define IDS_STRING_INPUT                580
#define IDS_QUERY_INPUT                 581
#define IDS_ABORT_INPUT                 582
#define IDS_RESET_DISPLAY               583
#define IDS_PORT_0                      584
#define IDS_PORT_1                      585
#define IDS_PORT_2                      586
#define IDS_PORT_3                      587
#define IDS_PORT_8                      588
#define IDS_PORT_10                     589
#define IDS_PORT_11                     590
#define IDS_PORT_12                     591
#define IDS_NET_TOTALIZER               592
#define IDS_ARM_PRODUCT_CONFIGURATION   593
#define IDS_NUMBER_OF_ARMS              594
#define IDS_PRESET_ARM_NUMBER           595
#define IDS_OPC_E_INVALIDHANDLE         63000
#define IDS_OPC_E_BADTYPE               63001
#define IDS_OPC_E_PUBLIC                63002
#define IDS_OPC_E_BADRIGHTS             63003
#define IDS_OPC_E_UNKNOWNITEMID         63004
#define IDS_OPC_E_INVALIDITEMID         63005
#define IDS_OPC_E_INVALIDFILTER         63006
#define IDS_OPC_E_UNKNOWNPATH           63007
#define IDS_OPC_E_RANGE                 63008
#define IDS_OPC_E_DUPLICATENAME         63009
#define IDS_OPC_S_UNSUPPORTEDRATE       63010
#define IDS_OPC_S_CLAMP                 63011
#define IDS_OPC_S_INUSE                 63012
#define IDS_OPC_E_INVALIDCONFIGFILE     63013
#define IDS_OPC_E_NOTFOUND              63014

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           371
#endif
#endif
