if (typeof (myscripts) == 'undefined') var myscripts = new Object(); function myclass_import(jsFile) { if (myscripts[jsFile] != null) return; var scriptElt = document.createElement('script'); scriptElt.type = 'text/javascript'; scriptElt.src = jsFile; document.getElementsByTagName('head')[0].appendChild(scriptElt); myscripts[jsFile] = jsFile }
myclass_import('../javascripts/csrftoken_min.js'); myclass_import('../javascripts/cfs.js'); var FMMenuBarLib = {}; FMMenuBarLib.initialized = !1; FMMenuBarLib.inFullScreenMode = !1; FMMenuBarLib.hideEvenIfNotDialog = !1; FMMenuBarLib.onSizeChanged = undefined; var gSiteGroupSelected = "UseSiteGroupActiveIcon"; var gSiteGroupUnSelected = "UseSiteGroupInactiveIcon"; var gSiteSelected = "UseSiteActiveIcon"; var gSiteUnSelected = "UseSiteInactiveIcon"; var gSiteBreak = "SiteBreak"; FMMenuBarLib.AlwaysTrue = function () { return !0 }
FMMenuBarLib.ShowHideExpansionIcon = function () {
    var menuData = GenerateContextMenuData(); if (menuData.items.length == 0) { $("#quickLinksShowExtra").hide() }
    else { $("#quickLinksShowExtra").show() }
}
closeSiteMenu = function () { $("#SiteSelect").select2("close") }; FMMenuBarLib.onLoad = function () {
    var quickLinksPanelState = "expanded"; if (window.localStorage.getItem('FMMenu_quickLinksPanelState') !== null) { quickLinksPanelState = window.localStorage.getItem('FMMenu_quickLinksPanelState') }
    $('#quickLinksPanelState').val(quickLinksPanelState); if (window.sessionStorage.inFullScreenMode == 'true') { FMMenuBarLib.enterFullScreenMode() }
    else {
        var fullScreenButton = document.getElementById("mhbFullScreenButton"); fullScreenButton.style.display = 'none'; if (document.getElementById("quickLinksPanelState").getAttribute("value") == "collapsed") { FMMenuBarLib.collapseQuickLinks() } else { FMMenuBarLib.expandQuickLinks() }
        FMMenuBarLib.positionQuickLinksLabel()
    }
    var headerBar = document.getElementById("ulHeaderBar"); headerBar.addEventListener('click', function (e) { if (e.target.id == 'ulHeaderBar' && e.clientX < 200 && e.clientY < 30) { e.preventDefault(); document.location.href = mainPage } }); $('#mhbUserIcon, #FMM_menu, #quickLinksBar').each(function () { this.addEventListener('mouseover', function (x) { closeSiteMenu() }) }); headerBar.addEventListener('mousemove', function (e) {
        if (e.target.id == 'ulHeaderBar' && e.clientX < 200 && e.clientY < 30) { headerBar.style.cursor = 'pointer' }
        else { headerBar.style.cursor = 'default' }
    })
}; FMMenuBarLib.onLoadDialogMode = function () { var ulHeaderBarElt = document.getElementById("ulHeaderBar"); ulHeaderBarElt.parentNode.removeChild(ulHeaderBarElt); var divMenuElt = document.getElementById("divMenu"); divMenuElt.parentNode.removeChild(divMenuElt); var divQuickLinksElt = document.getElementById("divQuickLinks"); divQuickLinksElt.parentNode.removeChild(divQuickLinksElt); var divSeparatorLineElt = document.getElementById("divSeparatorLine"); divSeparatorLineElt.parentNode.removeChild(divSeparatorLineElt) }; FMMenuBarLib.enterFullScreenMode = function () { var fullScreenButton = document.getElementById("mhbFullScreenButton"); fullScreenButton.style.display = ''; fullScreenButton.innerText = 'Close'; var aboutLink = document.getElementById("mhbAboutLink"); aboutLink.style.display = 'none'; var helpButton = document.getElementById("mhbHelpButton"); helpButton.style.display = 'none'; var logoutButton = document.getElementById("mhbLogoutButton"); logoutButton.style.display = 'none'; var siteDropDown = document.getElementById("mhbSiteDropDown"); siteDropDown.style.display = 'none'; var divMenuElem = document.getElementById("divMenu"); divMenuElem.style.display = 'none'; var divQuickLinksElem = document.getElementById("divQuickLinks"); divQuickLinksElem.style.display = 'none'; var divSeparatorLineElem = document.getElementById("divSeparatorLine"); divSeparatorLineElem.style.display = 'none'; FMMenuBarLib.inFullScreenMode = !0 }; FMMenuBarLib.exitFullScreenMode = function () { var fullScreenButton = document.getElementById("mhbFullScreenButton"); fullScreenButton.innerText = 'Full Screen'; var aboutLink = document.getElementById("mhbAboutLink"); aboutLink.style.display = ''; var helpButton = document.getElementById("mhbHelpButton"); helpButton.style.display = ''; var logoutButton = document.getElementById("mhbLogoutButton"); logoutButton.style.display = 'none'; var siteDropDown = document.getElementById("mhbSiteDropDown"); siteDropDown.style.display = ''; var divMenuElem = document.getElementById("divMenu"); divMenuElem.style.display = ''; var divQuickLinksElem = document.getElementById("divQuickLinks"); divQuickLinksElem.style.display = ''; var divSeparatorLineElem = document.getElementById("divSeparatorLine"); divSeparatorLineElem.style.display = ''; FMMenuBarLib.inFullScreenMode = !1 }; FMMenuBarLib.showFullScreenButton = function () { var fullScreenButton = document.getElementById("mhbFullScreenButton"); if (fullScreenButton) { fullScreenButton.style.display = '' } }; FMMenuBarLib.positionQuickLinksLabel = function () {
    var quickLinksLabelLi = document.getElementById("quickLinksLabelListItem"); if (quickLinksLabelLi != null) {
        if (document.getElementById("quickLinksBar").clientHeight < 40)
            quickLinksLabelLi.style.paddingTop = "0"; else quickLinksLabelLi.style.paddingTop = "12px"
    }
}; FMMenuBarLib.collapseQuickLinks = function () {
    window.localStorage.setItem('FMMenu_quickLinksPanelState', "collapsed"); document.getElementById("quickLinksPanelState").setAttribute("value", "collapsed"); document.getElementById("divQuickLinks").style.display = "none"; document.getElementById("collapseQuickLinksBtn").style.visibility = "hidden"; document.getElementById("expandQuickLinksBtn").style.visibility = "visible"; document.getElementById("quickLinkExpansionContractionDiv").style.backgroundColor = "#486899"; if (FMMenuBarLib.initialized && FMMenuBarLib.onSizeChanged) { FMMenuBarLib.onSizeChanged() }
    if ((typeof FMMenuBar !== 'undefined')) { FMMenuBar.SetIFrameSize() }
}; FMMenuBarLib.expandQuickLinks = function () {
    window.localStorage.setItem('FMMenu_quickLinksPanelState', "expanded"); document.getElementById("quickLinksPanelState").setAttribute("value", "expanded"); document.getElementById("divQuickLinks").style.display = "table"; document.getElementById("collapseQuickLinksBtn").style.visibility = "visible"; document.getElementById("expandQuickLinksBtn").style.visibility = "hidden"; document.getElementById("quickLinkExpansionContractionDiv").style.backgroundColor = "#3B577F"; if (FMMenuBarLib.initialized && FMMenuBarLib.onSizeChanged) { FMMenuBarLib.onSizeChanged() }
    FMMenuBarLib.ShowHideExpansionIcon(); if ((typeof FMMenuBar !== 'undefined')) { FMMenuBar.SetIFrameSize() }
}; FMMenuBarLib.openLegalInfo = function () { var dbVersion = document.getElementById("dbVer").getAttribute("value"); var fmVersion = document.getElementById("fmVer").getAttribute("value"); var bsName = document.getElementById("bsName").getAttribute("value"); var bsVersion = document.getElementById("bsVer").getAttribute("value"); var pageTitle = document.getElementById("pageTitle").getAttribute("value"); if (pageTitle == null || pageTitle === "EMPTY") { window.showModalDialog("../FMWebApp/LegalInfo.htm?DatabaseVersion=" + dbVersion + "&FMVersion=" + fmVersion + "&BusinessServiceName=" + bsName + "&BusinessServiceVersion=" + bsVersion + "&WebServerName=" + webServerName, "About", "dialogWidth: 650px; dialogHeight: 350px; scroll:no"); } else { window.showModalDialog("../FMWebApp/LegalInfo.htm?DatabaseVersion=" + dbVersion + "&FMVersion=" + fmVersion + "&BusinessServiceName=" + bsName + "&BusinessServiceVersion=" + bsVersion + "&WebServerName=" + webServerName + "&FMPageTitle=" + pageTitle, "About", "dialogWidth: 650px; dialogHeight: 350px; scroll:no"); } }; FMMenuBarLib.openPrivacyPolicy = function () { var ppPath = document.getElementById("ppPath").getAttribute("value"); window.showModalDialog(ppPath, "Privacy Policy", "dialogWidth: 700px; dialogHeight: 530px; scroll:no") }; FMMenuBarLib.fullScreenButtonOnClick = function () {
    if (window.sessionStorage.inFullScreenMode != 'true') {
        FMMenuBarLib.enterFullScreenMode(); window.sessionStorage.screenX = window.screenX; window.sessionStorage.screenY = window.screenY; window.sessionStorage.outerHeight = window.outerHeight; window.sessionStorage.outerWidth = window.outerWidth; window.moveTo(0, 0); window.resizeTo(screen.availWidth, screen.availHeight); if (FMMenuBarLib.onSizeChanged) { FMMenuBarLib.onSizeChanged() }
        window.sessionStorage.inFullScreenMode = 'true'
    }
    else {
        window.resizeTo(window.sessionStorage.outerWidth, window.sessionStorage.outerHeight); window.moveTo(window.sessionStorage.screenX, window.sessionStorage.screenY); FMMenuBarLib.exitFullScreenMode(); if (FMMenuBarLib.onSizeChanged) { FMMenuBarLib.onSizeChanged() }
        window.sessionStorage.inFullScreenMode = 'false'
    }
}; FMMenuBarLib.onPreRender = function () {
    if (window.self !== window.top || window.dialogArguments != null || FMMenuBarLib.hideEvenIfNotDialog) { FMMenuBarLib.onLoadDialogMode() } else { FMMenuBarLib.onLoad() }
    FMMenuBarLib.initialized = !0
}; FMMenuBarLib.clientHeight = function () { var height = 0; var ulHeaderBarElt = document.getElementById("ulHeaderBar"); height += ulHeaderBarElt.clientHeight; var divMenuElt = document.getElementById("divMenu"); height += divMenuElt.clientHeight; var divQuickLinksElt = document.getElementById("divQuickLinks"); height += divQuickLinksElt.clientHeight; var divSeparatorLineElt = document.getElementById("divSeparatorLine"); height += divSeparatorLineElt.clientHeight; var divSpacingElt = document.getElementById("divSpacing"); height += divSpacingElt.clientHeight; return height }; FMMenuBarLib.headerBarWidth = function () { var ulHeaderBarElt = document.getElementById("ulHeaderBar"); return ulHeaderBarElt.clientWidth }; var FMMenu = {}; FMMenu.RepopulateMenu = function () {
    var dataItem = sessionStorage.getItem('FMMenu'); if (dataItem != null) { var data = JSON.parse(dataItem); FMMenu.PopulateMenu(data) }
    else { FMMenu.onLoad() }
}; FMMenu.SiteSelectSuccess = function (data) {
    if (sessionStorage != null) { sessionStorage.setItem('FMMenu', JSON.stringify(data)) }
    FMMenu.PopulateMenu(data)
}; FMMenu.PopulateMenu = function (data) {
    $("#SiteSelect").change(FMMenu.SiteSelectChanged); $('#SiteSelect').children().remove().end(); var bSeparatorNeeded = !1; if (data.d.length <= 1) { $("#SiteSelect").prop('readonly', !0); bSeparatorNeeded = !1 }
    var isSiteGroupPrevious = !1; var isSiteGroupCurrent = !1; var iIndexOfBreak = 0; var count = data.d.length; $.each(data.d, function (key, value) {
        isSiteGroupCurrent = (value.Attributes.Keys[0] == 'GroupColor'); if (iIndexOfBreak == 0) { isSiteGroupPrevious = isSiteGroupCurrent }
        bSeparatorNeeded = (isSiteGroupCurrent != isSiteGroupPrevious); if (bSeparatorNeeded == !0 || iIndexOfBreak++ == count) { return !1 }
        else { isSiteGroupPrevious = isSiteGroupCurrent; return !0 }
    }); var i = 0; $.each(data.d, function (key, value) {
        var color = 'black'; var groupText = "" || value.Text; isSiteGroupCurrent = ((value.Attributes.Keys[0] == 'GroupColor') || (groupText.indexOf('Site Groups') >= 0)); var isSelected = value.Selected; var className = ""; if (isSiteGroupCurrent && isSelected) { className = gSiteGroupSelected }
        else if (isSiteGroupCurrent && !isSelected) { className = gSiteGroupUnSelected }
        else if (!isSiteGroupCurrent && isSelected) { className = gSiteSelected }
        else if (!isSiteGroupCurrent && !isSelected) { className = gSiteUnSelected }
        if (bSeparatorNeeded && (i + 1 == iIndexOfBreak)) { $('#SiteSelect').append($("<option></option>").attr("class", className).attr("value", value.Value).text(value.Text).prop('disabled', !value.Enabled).css({ 'color': color }).prop('selected', value.Selected)); $('#SiteSelect').append($("<option></option>").attr("class", "SiteBreak").attr("value", "SiteBreakID").text("").prop('disabled', !0).css({ 'color': "white" }).prop('selected', !1)) }
        else { $('#SiteSelect').append($("<option></option>").attr("class", className).attr("value", value.Value).text(value.Text).prop('disabled', !value.Enabled).css({ 'color': color }).prop('selected', value.Selected)) }
        i++
    }); $('#SiteSelect').removeAttr('disabled')
}; FMMenu.SiteSelectError = function (e) { if (console != 'undefined') { console.log(e.responseText) } }; FMMenu.onLoad = function () { $.ajax({ type: "POST", contentType: "application/json; charset=utf-8", dataType: "json", url: "../default.aspx/GetSites", data: JSON.stringify({}), success: FMMenu.SiteSelectSuccess, error: FMMenu.SiteSelectError }) }; FMMenu.SiteSelectChanged = function () { __doPostBack("SiteSelect", $(this).val()) }; FMMenu.AlternateUserSiteSelectChanged = function (siteGuid) { __doPostBack("SiteSelect", siteGuid) }; FMMenu.Nav = function (url, menuItem, menuGuid, securityToken) { $.ajax({ type: "POST", contentType: "application/json; charset=utf-8", dataType: "json", url: "../default.aspx/RegisterVisit", data: JSON.stringify({ menuItem: menuItem, menuGuid: menuGuid, securityToken: securityToken }), error: function (xhr, status, error) { var exception = JSON.parse(xhr.responseText); alert(exception.Message); window.top.location = "../" } }); window_open(url, '_self'); return !1 }; FMMenu.SiteSelectAdded = function formatSiteItem(site) {
    if (!site.id) { return site.text }
    var className = "SiteOptionCommmon "; switch (site.element.className) { case gSiteGroupSelected: className += "SiteGroupOptionActive"; break; case gSiteGroupUnSelected: className += "SiteGroupOptionInActive"; break; case gSiteSelected: className += "SiteOptionActive"; break; case gSiteUnSelected: className += "SiteOptionInActive"; break; case gSiteBreak: className += "SiteBreak"; break }
    var $site = $('<span class="' + className + '">' + site.text + '</span>'); return $site
}; if (!window.showModalDialog) {
    window.showModalDialog = function (arg1, arg2, arg3) {
        var w; var h; var resizable = "no"; var scroll = "no"; var status = "no"; var mdattrs = arg3.split(";"); for (i = 0; i < mdattrs.length; i++) {
            var mdattr = mdattrs[i].split(":"); var n = mdattr[0]; var v = mdattr[1]; if (n) { n = n.trim().toLowerCase() }
            if (v) { v = v.trim().toLowerCase() }
            if (n == "dialogheight") { h = v.replace("px", "") } else if (n == "dialogwidth") { w = v.replace("px", "") } else if (n == "resizable") { resizable = v } else if (n == "scroll") { scroll = v } else if (n == "status") { status = v }
        }
        var left = window.screenX + (window.outerWidth / 2) - (w / 2); var top = window.screenY + (window.outerHeight / 2) - (h / 2); var targetWin = window.open(arg1, arg1, 'toolbar=no, location=no, directories=no, status=' + status + ', menubar=no, scrollbars=' + scroll + ', resizable=' + resizable + ', copyhistory=no, width=' + w + ', height=' + h + ', top=' + top + ', left=' + left); targetWin.focus()
    }
}