/*
	DROP PROCEDURE [staging].[usp_LoadCompanyMasterRecordToDateRange]

	EXEC [staging].[usp_LoadCompanyMasterRecordToDateRange]
	
*/
CREATE PROCEDURE [staging].[usp_LoadCompanyMasterRecordToDateRange]
AS
BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [staging].[usp_LoadCompanyMasterRecordToDateRange]
	-- Author: Hansraj Bapoo
	-- Version/Date: 1.0.003 / 2012-07-13 14:21:10.4470770 -04:00
	-- Purpose: For each Company MasterRecord retrieve/build a set of date ranges that correspond to all possible data ranges for which 
	--          record versions have either been created or deleted, across all sites/sitegroups.
	-- Notes:
	-- 1. The MasterRecord-DataRange mappings generated by this operation is used to help determine the date ranges for which the 
	--    Entity-To-Site mappings need to be captured and resolved to the actual child record version key.
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY		
		
		TRUNCATE TABLE staging.tblCompanyMasterRecordToDateRange

		INSERT INTO staging.tblCompanyMasterRecordToDateRange
		(MasterRecordKey, StartDate, EndDate)
		SELECT DISTINCT MasterRecordKey, StartDate, EndDate
		FROM map.tblCompanyToMasterRecord
		ORDER BY StartDate, EndDate
					
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: [staging].[usp_LoadCompanyMasterRecordToDateRange]' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,16,1);      
	END CATCH    
	
END