/*
	DROP PROCEDURE [Staging].[usp_UpdateProductRecordVersionMappings]

	EXEC [staging].[usp_UpdateProductRecordVersionMappings]
	
*/
CREATE PROCEDURE [staging].[usp_UpdateProductRecordVersionMappings]
AS
BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [staging].[usp_UpdateProductRecordVersionMappings]
	-- Author: Hansraj Bapoo
	-- Version/Date: 1.0.003 / 2012-07-13 14:21:10.4470770 -04:00
	-- Purpose: For each Product-to-Site mapping, determine the exact Record Version Key applicable for the mapping.
	-- Notes:
	-- 1. This captures all direct or indirect impact on the Product-to-Site-toRecordVersionKey mappings due to either Product-to-Site changes
	--	  or Product record changes. Product record changes can be due to regular record updates, or as a result of Record Versioning being
	--    turned on or off.
	-- 2. The entity-to-site mappings captured by this procedure is date bound. The date ranges for each MasterRecord correspond to all the 
	--    date ranges that are found in the underlying dimension table for that MasterRecord. The procedure parses up the entity-to-site 
	--    hierarchy as necessary to identify the exact record version that is applicable for each entity-to-site mapping, for
	--    each date range.	
	-- 3. The mappings generated by this procedure is used later to resolve the Record Versioning references. E.g. a FuelsCard record points 
	--    to a Product using the MasterRecord of the Product. The exact Product record version that is applicable for the FuelsCard record can 
	--    be located readily using the mappings generated in this procedure, for the given Product master record and the FuelsCard record date.
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY		
		
		DECLARE @openEndedDate Datetimeoffset(7)		
		SELECT @openEndedDate = DATEADD(year, 100, GETDATE())

		--Capture the date ranges applicable to each Product MasterRecord
		EXEC [staging].[usp_LoadProductMasterRecordToDateRange]

		TRUNCATE TABLE staging.tblProductToSiteRecordVersionTemp
		TRUNCATE TABLE staging.tblProductToSiteRecordVersion

		--Capture the Entity-to-Site mappings.
		--For each mapping add one record entry for each Date Range identified for the MasterRecord in the mapping.
		--This ensures that the algorithm that follows will be forced to identify the record version for each mapping for each 
		--relevant time range, even those for which a record version is not readily available, i.e. cases where the record 
		--version needs to be fetched by walking up the entity-to-site hierarchy.
		INSERT INTO staging.tblProductToSiteRecordVersionTemp
		(ProductToSiteKey, ProductKey, SiteSKey, AssignedFromSiteSKey, RunningSiteSKey, RunningAssignedFromSiteSKey, StartDate, EndDate)
		SELECT a.ProductToSiteKey, a.ProductKey, a.SiteSKey, a.AssignedFromSiteSKey, a.SiteSKey, a.AssignedFromSiteSKey, b.StartDate, b.EndDate
		FROM map.tblEntityProductToSite a
		INNER JOIN (SELECT DISTINCT MasterRecordKey, StartDate, EndDate FROM staging.tblProductMasterRecordToDateRange) b
		ON b.MasterRecordKey = a.ProductKey

		--Identify and set all mapping records for which a recordversion exists for the AssignedTo Site.
		UPDATE a
		SET a.RecordVersionKey = b.ProductKey
		FROM staging.tblProductToSiteRecordVersionTemp a
		INNER JOIN map.tblProductToMasterRecord b
		ON b.MasterRecordKey = a.ProductKey
		AND b.SiteSKey = a.SiteSKey
		WHERE (a.StartDate >= b.StartDate) AND (a.StartDate < ISNULL(b.EndDate, @openEndedDate))

		WHILE ((SELECT COUNT(*) FROM staging.tblProductToSiteRecordVersionTemp WHERE RecordVersionKey IS NULL) > 0)
		BEGIN			
			--For each of the unresolved mappings, move up the entity-to-site hierarchy to the next sitegroup, and try to look for a record version owned by that sitegroup
			UPDATE staging.tblProductToSiteRecordVersionTemp SET RunningSiteSKey = RunningAssignedFromSiteSKey WHERE RecordVersionKey IS NULL

			UPDATE a 
			SET a.RunningAssignedFromSiteSKey = b.AssignedFromSiteSKey
			FROM staging.tblProductToSiteRecordVersionTemp a
			INNER JOIN map.tblEntityProductToSite b
			ON b.ProductKey = a.ProductKey
			AND b.SiteSKey = a.RunningSiteSKey 
			WHERE a.RecordVersionKey IS NULL			

			--Identify and set all mapping records for which a recordversion exists for the AssignedTo Site.
			UPDATE a
			SET a.RecordVersionKey = b.ProductKey
			FROM staging.tblProductToSiteRecordVersionTemp a
			INNER JOIN map.tblProductToMasterRecord b
			ON b.MasterRecordKey = a.ProductKey
			AND b.SiteSKey = a.RunningSiteSKey
			--WHERE a.StartDate BETWEEN b.StartDate AND ISNULL(b.EndDate, @openEndedDate)
			WHERE (a.StartDate >= b.StartDate) AND (a.StartDate < ISNULL(b.EndDate, @openEndedDate))
			AND a.RecordVersionKey IS NULL

			-- Prevent infinite looping. Look for mappings for which we have already reached to top assignement sitegroup, and yet the mappings cannot be resolved. 
			IF ((SELECT COUNT(*) FROM staging.tblProductToSiteRecordVersionTemp WHERE RecordVersionKey IS NULL AND RunningSiteSKey = RunningAssignedFromSiteSKey) > 0)
			BEGIN
				RAISERROR('Cannot locate Product record version for the assignment.',16,1); 
				RETURN;
			END
		END	

		--Handle entity-to-site mapping changes
		--Handle deleted entity-to-site mappings. Delete all null EndDate entries for which no active entity-to-site mappings exist anymore	
		DELETE a
		FROM  staging.tblProductToSiteRecordVersionTemp a
		WHERE a.EndDate IS NULL
		AND NOT EXISTS
		(
			SELECT * FROM map.tblEntityProductToSite b
			WHERE b.ProductKey = a.ProductKey
			AND b.SiteSKey = a.SiteSKey
			AND b.AssignedFromSiteSKey = a.AssignedFromSiteSKey
			AND b.EndedDate IS NULL
		)

		--Handle new entity-to-site mappings. 
		IF ((SELECT COUNT(*) FROM map.tblEntityProductToSite WHERE CreatedDate IS NULL) > 0)
		BEGIN
			RAISERROR('Missing CreatedDate on Product-To-Site mapping.',16,1); 
			RETURN;
		END

		--Delete all Child Record Version entries for which the Record Version StartDate preceeds the actual creation date of the Entity-to-Site mapping
		--In the case of child record versions, the entity-to-site is created first and then the child record version is created.
		--The entries with the invalid date ranges would have been introduced/inherited from the other pre-existing mappings for the same Master Record.
		DELETE a
		FROM  staging.tblProductToSiteRecordVersionTemp a
		INNER JOIN map.tblProductToMasterRecord b
		ON b.ProductKey = a.RecordVersionKey
		WHERE b.ProductKey <> b.MasterRecordKey
		AND NOT EXISTS
		(
			SELECT * FROM map.tblEntityProductToSite c
			WHERE c.ProductKey = a.ProductKey
			AND c.SiteSKey = a.SiteSKey
			AND c.AssignedFromSiteSKey = a.AssignedFromSiteSKey
			AND c.CreatedDate <= a.StartDate
			AND c.CreatedDate IS NOT NULL
		)

		-- Resolve the specific RecordVersionSKey reference for each mapping
		UPDATE a 
		SET a.RecordVersionSKey = b.SKey
		FROM staging.tblProductToSiteRecordVersionTemp a
		INNER JOIN DimProduct b
		ON b.AKey = a.RecordVersionKey
		WHERE a.StartDate >= b.StartDate AND a.StartDate < ISNULL(b.EndDate, @openEndedDate)

		-- Collapse the records by MasterRecord-Site-RecordVersionSKey	
		INSERT INTO staging.tblProductToSiteRecordVersion
		(ProductToSiteKey, ProductKey, SiteSKey, AssignedFromSiteSKey, RecordVersionKey, RecordVersionSKey, StartDate, EndDate)
		SELECT ProductToSiteKey, ProductKey, SiteSKey, AssignedFromSiteSKey, RecordVersionKey, RecordVersionSKey, MIN(StartDate), MAX(ISNULL(EndDate, @openEndedDate))
		FROM staging.tblProductToSiteRecordVersionTemp		
		GROUP BY ProductToSiteKey, ProductKey, SiteSKey, AssignedFromSiteSKey, RecordVersionKey, RecordVersionSKey
		ORDER BY ProductKey, SiteSKey, MIN(StartDate)

		-- Set the EndDate of the Open EndDate records back to Null
		UPDATE staging.tblProductToSiteRecordVersion
		SET EndDate = NULL
		WHERE EndDate = @openEndedDate	

		-- EndDate all open-end dated MasterRecord-Site combinations for which there is a later open-end date record, i.e. make sure that for each MasterRecord-Site combination there is at most only one open-endated record.		
		UPDATE a 
		SET a.EndDate = b.StartDate
		FROM staging.tblProductToSiteRecordVersion a
		INNER JOIN staging.tblProductToSiteRecordVersion b
		ON b.ProductKey = a.ProductKey
		AND b.SiteSKey = a.SiteSKey
		AND b.RowIndex = (a.RowIndex + 1)
		WHERE a.EndDate IS NULL		

		--Delete all End-Dated entries that do not overlap an Entity-to-Site mapping.
		--Two scenarios are valid:
		--1. The historical entity record starts after the entity-to-site mapping was created
		--2. The entity-to-site mapping created date falls somewhere between the historical entity record start and end date
		--The entries with the invalid date ranges would have been introduced/inherited through the arbitrary joins/combinations above
		DELETE a
		FROM  staging.tblProductToSiteRecordVersion a
		WHERE a.EndDate IS NOT NULL
		AND NOT EXISTS
		(
			SELECT * FROM map.tblEntityProductToSite c
			WHERE c.ProductKey = a.ProductKey
			AND c.SiteSKey = a.SiteSKey
			AND c.AssignedFromSiteSKey = a.AssignedFromSiteSKey
			AND 
			(
				((c.CreatedDate >= a.StartDate) AND (c.CreatedDate < ISNULL(a.EndDate, @openEndedDate)))
				OR
				((a.StartDate >= c.CreatedDate) AND (a.StartDate < ISNULL(c.EndedDate, @openEndedDate)))
			)
			AND c.CreatedDate IS NOT NULL
		)
		
		--For those EntityKey-AssignedFromSiteKey-AssignedToSiteKey combination records for which an entry exists with the same StartDate as that of the entity-to-site CreatedDate, delete all previous entries, even if they overlap onto the entity-to-site CreateDate.
		--This will correspond to the case of a child record version being created at the same time as the parent entity is mapped to a site.
		DELETE a
		FROM  staging.tblProductToSiteRecordVersion a
		INNER JOIN
		(
			SELECT b.ProductKey, c.SiteSKey, b.AssignedFromSiteSKey, b.StartDate FROM staging.tblProductToSiteRecordVersion b
			INNER JOIN map.tblEntityProductToSite c
			ON c.ProductKey = b.ProductKey
			AND c.SiteSKey = b.SiteSKey
			AND c.AssignedFromSiteSKey = b.AssignedFromSiteSKey
			AND c.CreatedDate = b.StartDate
			AND c.CreatedDate IS NOT NULL
		) d
		ON d.ProductKey = a.ProductKey
		AND d.SiteSKey = a.SiteSKey
		AND d.AssignedFromSiteSKey = a.AssignedFromSiteSKey
		WHERE a.StartDate < d.StartDate

		--Delete entries with invalid end date
		DELETE staging.tblProductToSiteRecordVersion
		WHERE ISNULL(EndDate, @openEndedDate) <= StartDate



		--Update the ProductToSiteRecordVersion mapping table
		MERGE map.tblProductToSiteRecordVersion AS tgt
		USING  
		(
			SELECT ProductToSiteKey, ProductKey, SiteSKey, AssignedFromSiteSKey, RecordVersionKey, RecordVersionSKey, StartDate, EndDate
			FROM staging.tblProductToSiteRecordVersion
		) AS src
		ON tgt.ProductKey = src.ProductKey AND tgt.AssignedFromSiteSKey = src.AssignedFromSiteSKey AND tgt.SiteSKey = src.SiteSKey AND tgt.StartDate = src.StartDate
		WHEN NOT MATCHED THEN
			INSERT (ProductToSiteKey, ProductKey, SiteSKey, AssignedFromSiteSKey, RecordVersionKey, RecordVersionSKey, StartDate, EndDate)
			VALUES (src.ProductToSiteKey, src.ProductKey, src.SiteSKey, src.AssignedFromSiteSKey, src.RecordVersionKey, src.RecordVersionSKey, src.StartDate, src.EndDate)
		WHEN MATCHED AND tgt.EndDate IS NULL AND src.RecordVersionSKey = tgt.RecordVersionSKey THEN
			UPDATE SET tgt.EndDate = src.EndDate;

		-- EndDate all open-end dated MasterRecord-Site combinations for which the corresponding Entity-to-Site mapping has ended
		UPDATE a 
		SET a.EndDate = b.EndedDate
		FROM map.tblProductToSiteRecordVersion a
		INNER JOIN map.tblEntityProductToSite b
		ON b.ProductToSiteKey = a.ProductToSiteKey
		WHERE a.EndDate IS NULL
		AND b.EndedDate IS NOT NULL
					
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: [staging].[usp_UpdateProductRecordVersionMappings]' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,16,1);      
	END CATCH    
	
END