/*
Do not change the database path or name variables.
Any sqlcmd variables will be properly substituted during 
build and deployment.
*/
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_Start]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2000]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2001]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2002]
GO 
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2003]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2004]
GO 
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2005]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2006]
GO 
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2007]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2008]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2009]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2010]
GO 
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2011]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2012]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2013]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2014]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2015]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2016]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2017]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2018]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2019]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2020]
GO 
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2021]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2022]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2023]
GO 
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2024]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2025]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2026]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2027]
GO 
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2028]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2029]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2030]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2031]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2032]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2033]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2034]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2035]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2036]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2037]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2038]
GO
ALTER DATABASE [$(DatabaseName)] ADD FILEGROUP [fg_FACT_2039]
GO
