// --------------------------------------------------------------------------------------------------------------------
// <copyright file="FMMenuItemType.cs" company="Varec, Inc.">
//   Copyright (c) Varec, Inc.  All rights reserved.
// </copyright>
// <summary>
//   Defines the FMMenuItemType type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace FMBusinessObjects.DataObjects
{
	/// <summary>
	/// This enumeration defines unique identifiers for all the menu items in the
	/// system. In the first group, "Dynamic menu item types", the enum is
	/// combined with a Guid to make a unique identifier. In the second group
	/// "Static menu item types", only the enum is needed.
	/// THIS ENUM IS SYNCHED WITH LOOKUP.TBLMENUITEMTYPE AND MUST BE KEPT IN SYNC!!!
	/// </summary>
	public enum FMMenuItemType
	{
		NONE = 0,

		/*** Dynamic menu item types ***/
		DYNAMIC_ACCOUNTING_IMPORT_EXPORT = 1,
		DYNAMIC_ACCOUNTING_INVOICE_ENTRY = 2,
		DYNAMIC_ADD_TRANSACTION = 3,
		DYNAMIC_ADD_SALES_ORDER = 4,
		DYNAMIC_ADD_SUPPLY_ORDER = 5,
		DYNAMIC_REPORT = 6,
		DYNAMIC_OPERATIONS_PROCUREMENT = 7,
		DYNAMIC_ACCOUNTING_INVOICE_ENTRY_ADF = 8,
		DYNAMIC_ACCOUNTING_TRANSACTION_EDITOR = 9,
		  DYNAMIC_GRAPHIC = 10,
		/*** Add new Dynamic menu item types here     ***/
		/*** Also add to lookup.tblMenuItemType       ***/
		/*** DO NOT CHANGE EXISTING NUMERIC VALUES!!! ***/


		/*** Static menu item types ***/
		/*** Accounting Items ***/
		ACCOUNTING_MAIN_CLOSEOUT_SUMMARY = 1001,
		ACCOUNTING_COMPANIES_CERTIFICATES_AND_PERMITS = 1002,
		ACCOUNTING_COMPANIES_COMPANIES = 1003,
		ACCOUNTING_COMPANIES_GROUPS = 1004,
		ACCOUNTING_COMPANIES_HIERARCHY = 1005,
		ACCOUNTING_COMPANIES_COMPANY_ROLE_ASSIGNMENTS = 1006,
		ACCOUNTING_COMPANIES_TYPES = 1007,
		ACCOUNTING_MAIN_END_OF_MONTH_APPROVAL = 1008,
		ACCOUNTING_IMPORT_EXPORT_6_0_ERROR_RETRIEVAL = 1009,
		ACCOUNTING_IMPORT_EXPORT_6_0_FILE_UPLOAD = 1010,
		ACCOUNTING_IMPORT_EXPORT_ARTS_IMPORT = 1011,
		ACCOUNTING_IMPORT_EXPORT_BASE_ENTERPRISE_EXPORT = 1012,
		ACCOUNTING_IMPORT_EXPORT_ENTERPRISE_EXPORT = 1013,
		ACCOUNTING_IMPORT_EXPORT_GAS_STATION_IMPORT = 1014,
		ACCOUNTING_IMPORT_EXPORT_MFCS_IMPORT = 1015,
		ACCOUNTING_IMPORT_EXPORT_SHIPMENT_DOCUMENT_IMPORT = 1016,
		ACCOUNTING_MAIN_INCOMING_TRUCK = 1017,
		ACCOUNTING_MAIN_INVENTORY_RECONCILIATION = 1018,
		ACCOUNTING_MAIN_WAC_SUMMARY = 1019,
		ACCOUNTING_INVOICE_ENTRY_BULK_PAYMENT_SUMMARY = 1020,
		ACCOUNTING_INVOICE_ENTRY_INVOICE_PAYABLE_SUMMARY = 1021,
		ACCOUNTING_INVOICE_ENTRY_INVOICE_SUMMARY = 1022,
		ACCOUNTING_INVOICE_ENTRY_RECEIVABLE_SUMMARY = 1023,
		ACCOUNTING_INVOICE_ENTRY_RECEIVABLE_SUMMARY_ADF = 1024,
		ACCOUNTING_MAIN_LEDGER = 1025,
		ACCOUNTING_MAIN_OPERATIONS = 1026,
		ACCOUNTING_MAIN_METER_RECONCILIATION = 1027,
		ACCOUNTING_AUTO_DISTRIBUTION = 1028,
		ACCOUNTING_EXTERNAL_SYSTEM_TRANSACTION_ERROR_SUMMARY = 1029,
		ACCOUNTING_IMPORT_EXPORT_BASE_ENTERPRISE_EXPORT_MANUAL = 1030,
		ACCOUNTING_IMPORT_EXPORT_BASE_ENTERPRISE_RESULT_IMPORT_MANUAL = 1031,
		ACCOUNTING_IMPORT_EXPORT_RAPS_IMPORT = 1032,
		ACCOUNTING_IMPORT_EXPORT_ENTERPRISE_UPLOAD_MANUAL = 1033,
		ACCOUNTING_IMPORT_EXPORT_SEND_ENTERPRISE_TRANSACTIONS = 1034,
		ACCOUNTING_MAIN_TRANSACTION_SUMMARY = 1035,
		ACCOUNTING_ERROR_SUMMARY = 1036,
		ACCOUNTING_IMPORT_INTOPLANE_DATA = 1037,
		  /*** Add new Accounting menu item types here  ***/
		ACCOUNTING_MAIN_MOVEMENT = 1038,
		ACCOUNTING_EXTERNAL_SYSTEM_UNACKNOWLEDGED_TRANSACTION_SUMMARY = 1039,
		  ACCOUNTING_STANDARD_IMPORT_TRANSACTION_DATA = 1040,

		  /*** Also add to lookup.tblMenuItemType       ***/
		  /*** DO NOT CHANGE EXISTING NUMERIC VALUES!!! ***/


		  /*** Admin Items ***/
		  ADMIN_SECURITY_CHANGE_PASSWORD = 2001,
		ADMIN_SECURITY_USERS = 2002,
		ADMIN_SITES_ENTITY_ASSIGNMENTS = 2003,
		ADMIN_SITES_ENTITY_OWNERSHIP = 2004,
		ADMIN_SYSTEM_DATA_DICTIONARY = 2005,
		ADMIN_SYSTEM_REGIONAL_SETTINGS = 2006,
		ADMIN_SYSTEM_SYSTEM_SETTINGS = 2007,
		ADMIN_SECURITY_USER_GROUPS = 2008,
		ADMIN_SITES_SITES = 2009,
		ADMIN_SECURITY_PASSWORD_SETTINGS = 2010,
		ADMIN_FIELD_LEVEL_CONFIGURATION = 2011,
		ADMIN_SECURITY_USER_PERMIMISSIONS = 2012,
		ADMIN_SYSTEM_CONFIGURATION_SETTINGS = 2013,
		ADMIN_SYSTEM_WEB_LINKS_CONFIGURATION = 2014,
		ADMIN_SYSTEM_DASHBOARD = 2015,
		/*** Add new Admin menu item types here       ***/
		/*** Also add to lookup.tblMenuItemType       ***/
		/*** DO NOT CHANGE EXISTING NUMERIC VALUES!!! ***/


		/*** Asset Items ***/
		ASSETS_EQUIPMENT_EQUIPMENT = 3001,
		ASSETS_EQUIPMENT_LICENSES = 3002,
		ASSETS_EQUIPMENT_MAINTENANCE_REASONS = 3003,
		ASSETS_EQUIPMENT_STATION = 3004,
		ASSETS_EQUIPMENT_TANKS = 3005,
		ASSETS_EQUIPMENT_TANK_GROUPS = 3006,
		ASSETS_EQUIPMENT_TESTS_AND_INSPECTIONS = 3007,
		ASSETS_EQUIPMENT_TYPE_CLASSES = 3008,
		ASSETS_PERSONNEL_HOUSE_CARDS = 3009,
		ASSETS_PERSONNEL_LICENSES = 3010,
		ASSETS_PERSONNEL_PERSONNEL = 3011,
		ASSETS_PERSONNEL_QUALIFICATIONS = 3012,
		ASSETS_PERSONNEL_TRAINING = 3013,
		ASSETS_PRODUCTS_ADDITIVE_PROFILES = 3014,
		ASSETS_PRODUCTS_DOT_HAZARDOUS_MESSAGES = 3015,
		ASSETS_PRODUCTS_PRODUCTS = 3016,
		ASSETS_PRODUCTS_PRODUCT_ENTRY_MESSAGES = 3017,
		ASSETS_PRODUCTS_PRODUCT_EXIT_MESSAGES = 3018,
		ASSETS_PRODUCTS_PRODUCT_GROUPS = 3019,
		ASSETS_PRODUCTS_PRODUCT_MESSAGES = 3020,
		ASSETS_EQUIPMENT_MOBILE_DEVICES = 3021,
		ASSETS_IMPORT_IM_TANK_DATA = 3022,
		/*** Add new Asset menu item types here       ***/
		/*** Also add to lookup.tblMenuItemType       ***/
		/*** DO NOT CHANGE EXISTING NUMERIC VALUES!!! ***/


		/*** Config Items ***/
		CONFIG_ACCOUNTING_AUTO_DISTRIBUTION_REASONS = 4001,
		CONFIG_ACCOUNTING_AUTO_DISTRIBUTION_RULES = 4002,
		CONFIG_ACCOUNTING_CURRENCIES = 4003,
		CONFIG_ACCOUNTING_EXCISE_TAX = 4004,
		CONFIG_ACCOUNTING_GENERAL_CONFIGURATION = 4005,
		CONFIG_ACCOUNTING_GST_TAX = 4006,
		CONFIG_ACCOUNTING_IMPORT_EXPORT = 4007,
		CONFIG_ACCOUNTING_LEDGER_AGGREGATE_COLUMNS = 4008,
		CONFIG_ACCOUNTING_LEDGER_VIEWS = 4009,
		CONFIG_ACCOUNTING_LOCK_DATES = 4010,
		CONFIG_ACCOUNTING_MARKUP = 4011,
		CONFIG_ACCOUNTING_STANDING_OFFER_PRICES = 4012,
		CONFIG_ACCOUNTING_TRANSACTION_ALIASES = 4013,
		CONFIG_CONTREC_OPC_PORTS = 4014,
		CONFIG_CONTREC_OPC_PRESETS = 4015,
		CONFIG_DANIEL_OPC_PORTS = 4016,
		CONFIG_DANIEL_OPC_PRESETS = 4017,
		CONFIG_IMPORT_EXPORT_ENTERPRISE_SETTINGS = 4018,
		CONFIG_IMPORT_EXPORT_ENTITY_IMPORT = 4019,
		CONFIG_IMPORT_EXPORT_ENTITY_EXPORT = 4020,
		CONFIG_LOAD_RACK_ALLOCATION_GROUPS = 4021,
		CONFIG_LOAD_RACK_DATA_EXCHANGE_PROFILE = 4022,
		CONFIG_LOAD_RACK_STATION_ARMS = 4023,
		CONFIG_OPTOMUX_OPC_CONTROLLERS = 4024,
		CONFIG_OPTOMUX_OPC_PORTS = 4025,
		CONFIG_OTHER_DATABASE_AUDIT_LOG = 4026,
		CONFIG_OTHER_FOOTNOTES = 4027,
		CONFIG_OTHER_FUEL_CARDS = 4028,
		CONFIG_OTHER_PROFILES = 4029,
		CONFIG_QUALITY_QUALITY_TAGS = 4030,
		CONFIG_QUALITY_TESTS_AND_INSPECTIONS = 4031,
		CONFIG_QUALITY_TESTS_SETS = 4032,
		CONFIG_REPORTS_QUERIES_MANAGE_QUERIES = 4033,
		CONFIG_REPORTS_QUERIES_QUERY_SETTINGS = 4034,
		CONFIG_REPORTS_QUERIES_REPORT_ASSIGNMENT = 4035,
		CONFIG_REPORTS_QUERIES_REPORT_GROUPS = 4036,
		CONFIG_SITES_RESERVE_LEVELS = 4037,
		CONFIG_SITES_GATES = 4038,
		CONFIG_SITES_IATA_CODES = 4039,
		CONFIG_SITES_PROCESS_VARIABLE_MESSAGES = 4040,
		CONFIG_SMITH_METER_OPC_PRESETS = 4041,
		CONFIG_SMITH_METER_OPC_CARD_READERS = 4042,
		CONFIG_SMITH_METER_OPC_PORTS = 4043,
		CONFIG_SYSTEM_ALARM_AND_EVENTS = 4044,
		CONFIG_SYSTEM_ARCHIVE_DATA = 4045,
		CONFIG_SYSTEM_USER_DATA = 4046,
		CONFIG_SYSTEM_VIEWS = 4047,
		CONFIG_WEIGHT_SCALES_OPC_WEIGHT_SCALES = 4048,
		CONFIG_SYSTEM_SYNCHRONIZATION_SETTINGS = 4049,
		CONFIG_OTHER_SERVICE_REQUEST_MESSAGING = 4050,
		CONFIG_OTHER_SERVICE_REQUEST_MESSAGING_ADAPTORS = 4051,
		CONFIG_OTHER_FMAE_INTERFACE_TRANSLATIONS = 4052,
		CONFIG_IMPORT_EXPORT_FUEL_CARD_IMPORT = 4053,			// NSPA fuel card import.
		CONFIG_OTHER_FUEL_CARD_TYPES = 4054,
		CONFIG_OTHER_FUEL_CARD_LIMITS = 4055,
		CONFIG_ACCOUNTING_IRS_EXSTARS = 4056,
		CONFIG_AUTOMATED_FUEL_SERVICE_STATIONS = 4057,
		CONFIG_IMPORT_EXPORT_AUTOMATED_FUEL_SERVICE_STATION_DATA_IMPORT = 4058,
		CONFIG_AUTOMATED_FUEL_SERVICE_STATION_GENERAL_CONFIGURATION = 4059,
		CONFIG_IMPORT_EXPORT_AUTOMATED_FUEL_SERVICE_STATION_IMPORT_BLACKLIST = 4060,
		CONFIG_EXPORT_USER_ACCESS_CONTROL_DATA = 4061,
		CONFIG_SECURITY_BASE_USER_PERMISSIONS = 4062,
		CONFIG_SECURITY_ENTERPRISE_USER_PERMISSIONS = 4063,
		CONFIG_PRODUCTS_PRODUCT_AUTHORIZATION_AND_CONTROL = 4064,
		CONFIG_AUTOMATED_FUEL_SERVICE_DEVICES = 4065,
		CONFIG_WEIGHT_SCALES_OPC_PORTS = 4066,
		CONFIG_SCULLY_OPC_DEVICES = 4067,
		CONFIG_SCULLY_OPC_PORTS = 4068,
		CONFIG_INVMGR_POINT_TEMPLATE_TYPE = 4069,
		CONFIG_INVMGR_POINT_TEMPLATES = 4070,
		CONFIG_INVMGR_DRAW = 4071,
		CONFIG_INVMGR_PICTURESUMMARY = 4072,
		CONFIG_INVMGR_POINT_CATEGORY = 4073,
		CONFIG_INVMGR_DRAW_PROTO = 4074,
		CONFIG_INVMGR_DRAW_PLATFORM = 4075,
		CONFIG_INVMGR_POINTS = 4076,
		CONFIG_INVMGR_MODULELIBRARY = 4077,
		CONFIG_INVMGR_POINT_ACCESS_CONFIGURATION = 4078,
		CONFIG_OTHER_ACCESSIBILITY = 4079,
		CONFIG_PRODUCTS_DEFAULT_PRODUCT_CONFIGURATION = 4080,
		CONFIG_PRODUCTS_CUSTOM_UNITS_OF_MEASURE = 4081,
		CONFIG_PRODUCTS_MOVEMENT_VISIBLE_FIELDS = 4082,
		CONFIG_INVMGR_FCEE_MAPPINGS = 4083,
		CONFIG_INVMGR_FCE_DEVICE_SUMMARY = 4084,
		CONFIG_OSDP_OPC_CONTROLLERS = 4085,
		CONFIG_OSDP_OPC_PORTS = 4086,
      CONFIG_INVMGR_ROLLING_STOCK_IMPORT = 4087,
	  CONFIG_IMPORT_EXPORT_STRAP_TABLE_FILE_IMPORT = 4088,

        /*** Add new Config menu item types here      ***/
        /*** Also add to lookup.tblMenuItemType       ***/
        /*** DO NOT CHANGE EXISTING NUMERIC VALUES!!! ***/


        /*** Dispatch Items ***/
        DISPATCH_CONFIG_GRID_COLUMNS = 5001,
		DISPATCH_CONFIG_SETTINGS = 5002,
		DISPATCH_CONFIG_TOOLBARS = 5003,
		DISPATCH_CONFIG_VALIDATIONS = 5004,
		DISPATCH_CONFIG_READY_ACCESS_FILTERS = 5005,
		DispatchConfigServiceRequestPlans = 5006,

		DISPATCH_OPERATION_EVACUATE = 5101,
		DISPATCH_OPERATION_RELEASE_TO_ACCOUNTING = 5102,
		DISPATCH_OPERATION_STANDBY_STATUS_BOARD = 5103,

		DISPATCH_VIEW_CONTROL_LOG = 5201,
		DISPATCH_VIEW_DISPATCHERS_LIST = 5202,
		DISPATCH_VIEW_GRAPHICAL_VIEW = 5203,
		DISPATCH_VIEW_TABULAR_VIEW = 5204,
		DISPATCH_VIEW_FLIGHT_LINE_STATUS_DISPLAY = 5205,
		/*** Add new Dispatch menu item types here    ***/
		/*** Also add to lookup.tblMenuItemType       ***/
		/*** DO NOT CHANGE EXISTING NUMERIC VALUES!!! ***/


		/*** My Menu items ***/
		MY_MENU_ADD_FAVORITE = 6001,
		MY_MENU_CONFIG_FAVORITES = 6002,
		/*** Add new My Menu menu item types here     ***/
		/*** Also add to lookup.tblMenuItemType       ***/
		/*** DO NOT CHANGE EXISTING NUMERIC VALUES!!! ***/


		/*** Operations items ***/
		OPERATIONS_INTERFACE_FUEL_TRANSACTIONS = 7001,
		OPERATIONS_INTERFACE_ADOFMS_GROUND_FUEL = 7002,
		OPERATIONS_MAINTENANCE_ADD_MAINTENANCE_RECORD = 7003,
		OPERATIONS_QUALITY_ADD_QUALITY_TAG_RECORD = 7004,
		OPERATIONS_QUALITY_ADD_TEST_SET_RESULTS = 7005,
		OPERATIONS_LOAD_RACK_ADDITIVE_INTERNAL_METERS = 7006,
		OPERATIONS_LOAD_RACK_BILLS_OF_LADING = 7007,
		OPERATIONS_LOAD_RACK_ENABLE_STATION_ARMS = 7008,
		OPERATIONS_LOAD_RACK_STATIONS = 7009,
		OPERATIONS_ENTERPRISE_DATA_DATA_TRANSMISSION_EXPORT = 7010,
		OPERATIONS_ENTERPRISE_DATA_DATA_TRANSMISSION_IMPORT = 7011,
		OPERATIONS_QUALITY_TAG_SUMMARY = 7012,
		OPERATIONS_INVENTORY_MANAGEMENT_PHYSICAL_INVENTORY = 7013,
		OPERATIONS_LOAD_RACK_ALLOCATIONS = 7014,
		OPERATIONS_LOAD_RACK_MESSAGES = 7015,
		OPERATIONS_LOAD_RACK_OPERATIONS = 7016,
		OPERATIONS_MAINTENANCE_MAINTENANCE_LOG = 7017,
		OPERATIONS_LOAD_RACK_RACK_STATUS = 7018,
		OPERATIONS_SALES_SALES_ORDER_SUMMARY = 7019,
		OPERATIONS_SCHEDULER_GET_TEST_SCHEDULE = 7020,
		OPERATIONS_SCHEDULER_SCHEDULER_SUMMARY = 7021,
		OPERATIONS_SYSTEM_LOGS_ALARM_AND_EVENT_LOG = 7022,
		OPERATIONS_SYSTEM_LOGS_AUDIT_LOG = 7023,
		OPERATIONS_SYSTEM_LOGS_DATABASE_AUDIT = 7024,
		OPERATIONS_LOAD_RACK_TANK_ASSIGNMENT = 7025,
		OPERATIONS_QUALITY_TESTING_RESULTS = 7026,
		OPERATIONS_TRAINING_TRAINING_ASSIGNMENTS = 7027,
		OPERATIONS_TRAINING_TRAINING_SUMMARY = 7028,
		OPERATIONS_PROCUREMENT_SUPPLY_ORDER_SUMMARY = 7029,
		OPERATIONS_ENTERPRISE_DATA_ONLINE_SYNCHRONIZATION = 7030,
		OPERATIONS_ENTERPRISE_DATA_OFFLINE_SYNCHRONIZATION = 7031,
		OPERATIONS_ENTERPRISE_DATA_OFFLINE_SYNCHRONIZATION_ENTERPRISE = 7032,
		OPERATIONS_SYNC_LOGS_CONFLICTS_ERRORS = 7033,
		OPERATIONS_MIGRATION_DATA_EXPORT_IMPORT = 7034,
		OPERATIONS_AUTOMATED_FUEL_SERVICE_STATION_LOG = 7035,
		OPERATIONS_AUTOMATED_FUEL_SERVICE_STATION_OPERATIONS = 7036,
		OPERATIONS_AUTOMATED_FUEL_SERVICE_STATION_FAILED_TRANSACTIONS = 7037,
		OPERATIONS_SYNC_DASHBOARD = 7038,
		OPERATIONS_INVENTORY_MANAGEMENT_TAG_VIEWER = 7039,
		// Decomissioned WCG 02/07/2017 OPERATIONS_INVENTORY_MANAGEMENT_POINT_EXPLORER = 7040,
		OPERATIONS_INVENTORY_MANAGEMENT_OPERATE = 7041,
		OPERATIONS_INVENTORY_MANAGEMENT_STATISTICS = 7043,
		OPERATIONS_INVENTORY_MANAGEMENT_FCEE_MESSAGES = 7044,
		OPERATIONS_INVENTORY_MANAGEMENT_OPERATE_STATISTICS = 7045,

		/*** Add new Operations menu item types here  ***/
		/*** Also add to lookup.tblMenuItemType       ***/
		/*** DO NOT CHANGE EXISTING NUMERIC VALUES!!! ***/


		/*** Quick Links items ***/
		QUICK_LINKS_ADD_QUICK_LINK = 8001,
		QUICK_LINKS_CONFIG_QUICK_LINKS = 8002,
		/*** Add new Quick Links menu item types here ***/
		/*** Also add to lookup.tblMenuItemType       ***/
		/*** DO NOT CHANGE EXISTING NUMERIC VALUES!!! ***/


		/*** Reports items ***/
		REPORTS_QUERY_WRITER_CREATE_NEW_QUERY = 9001,
		REPORTS_GENERAL_ALL_REPORTS = 9002,
		REPORTS_QUERY_WRITER_QUERIES = 9003,
		REPORTS_WEB_LINKS = 9004,
		/*** Add new Reports menu item types here     ***/
		/*** Also add to lookup.tblMenuItemType       ***/
		/*** DO NOT CHANGE EXISTING NUMERIC VALUES!!! ***/		

		  /* Data Analytics Menu items */
		  DATA_ANALYTICS_VIEWER = 10001,
		  /*** Add new Data Analytics menu item types here  ***/
		  /*** Also add to lookup.tblMenuItemType       ***/
		  /*** DO NOT CHANGE EXISTING NUMERIC VALUES!!! ***/

		  /* Map Menu items */
		  MAP_MAPS = 11001,
		  MAP_CONFIGURATION = 11002,
		MAP_ASSET_TRACKING_DEVICE_CONFIG = 11003,
		ICON_CONFIGURATION = 11004,
		  /*** Add new Map menu item types here  ***/
		  /*** Also add to lookup.tblMenuItemType       ***/
		  /*** DO NOT CHANGE EXISTING NUMERIC VALUES!!! ***/

		 VRU_THRESHOLD_CONFIG = 12001,

		/*** Wingware Dispatch Items ***/
		MOBILE_ROOT_MENU_DISPLAY = 13100,
		MOBILE_LAUNCH = 13001,
		MOBILE_GENERAL = 13002,
		MOBILE_VIEW_CONFIGURATION = 13101,
		MOBILE_MODIFY_CONFIGURATION = 13102,

	}
}
