CREATE TABLE [fmcdc].[tblEquipmentTypes](
	[EquipmentTypesSKey] [int] IDENTITY(1,1) NOT NULL,
	[EqTypeName] [nvarchar](50) NULL, 
	[EqTypeDescription] [nvarchar](50) NULL, 
	[Capacity] [float] NULL, 
	[SafeFill] [float] NULL, 
	[Make] [nvarchar](20) NULL, 
	[Model] [nvarchar](32) NULL, 
	[Year] [smallint] NULL, 
	[CreatedDate] [datetimeoffset](7) NULL, 
	[CreatedBy] [udtUserID] NULL, 
	[UpdatedDate] [datetimeoffset](7) NULL, 
	[UpdatedBy] [udtUserID] NULL, 
	[DeleteFlag] [bit] NULL, 
	[IssPt] [nvarchar](20) NULL, 
	[MultiCompartment] [bit] NULL, 
	[EquipmentTypeGuid] [uniqueidentifier] NULL, 
	[SourceRowVersion] [bigint] NULL, 
	[SiteGuid] [uniqueidentifier] NULL, 
	[LookupEquipmentTypeIndex] [int] NULL, 
	[ProductGuid] [uniqueidentifier] NULL, 
	[CustomerDesignator] [nvarchar](128) NULL, 
	[ServiceTime] [float] NULL, 
	[VolumeUnits] [int] NULL, 
	[VolumeDecimalPlaces] [smallint] NULL, 
	[MassUnits] [int] NULL, 
	[MassDecimalPlaces] [smallint] NULL, 
	[WingToWingToleranceType] [smallint] NULL, 
	[WingToWingToleranceValue] [float] NULL, 
	[TankToTankToleranceType] [smallint] NULL, 
	[TankToTankToleranceValue] [float] NULL, 
	[FuelServiceToleranceType] [smallint] NULL, 
	[FuelServiceToleranceValue] [float] NULL, 
	[FuelServiceToleranceMaxType] [smallint] NULL, 
	[FuelServiceToleranceMaxValue] [float] NULL, 
	[AllowFuelingByWeight] [bit] NULL, 
	[LookupCompanyRoleIndex] [int] NULL, 
	[_ClusterIdx] [bigint] NULL, 
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[IsRecordDeleted] [bit] NULL,
	[_RowVersion] [timestamp] NOT NULL,
CONSTRAINT [PK_tblEquipmentTypes] PRIMARY KEY CLUSTERED
(
	[EquipmentTypesSKey] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF)
)
GO