CREATE TABLE [fmcdc].[tblProducts](
	[ProductsSKey] [int] IDENTITY(1,1) NOT NULL,
	[ProductID] [nvarchar](30) NULL, 
	[Description] [nvarchar](50) NULL, 
	[GenericType] [nvarchar](10) NULL, 
	[StockResetDate] [datetimeoffset](7) NULL, 
	[StockTrack] [bit] NULL, 
	[DensityHighLimit] [float] NULL, 
	[DensityLowLimit] [float] NULL, 
	[DensityDeadband] [float] NULL, 
	[TemperatureHiHiLimit] [float] NULL, 
	[TemperatureHighLimit] [float] NULL, 
	[TemperatureLowLimit] [float] NULL, 
	[TemperatureLoLoLimit] [float] NULL, 
	[TemperatureDeadband] [float] NULL, 
	[Bonded] [bit] NULL, 
	[LowStockWarning] [float] NULL, 
	[GroundFuel] [bit] NULL, 
	[ProductCode] [nvarchar](15) NULL, 
	[Price] [money] NULL, 
	[AviationFuelFlag] [bit] NULL, 
	[StandardDensity] [float] NULL, 
	[ApplyVolumeCorrection] [bit] NULL, 
	[ApplyStandardDensity] [bit] NULL, 
	[ApplyDensityLimits] [bit] NULL, 
	[ApplyTemperatureLimits] [bit] NULL, 
	[VolumeUnitIndex] [int] NULL, 
	[TemperatureUnitIndex] [int] NULL, 
	[DensityUnitIndex] [int] NULL, 
	[VolumeDecimalPlaces] [tinyint] NULL, 
	[TemperatureDecimalPlaces] [tinyint] NULL, 
	[DensityDecimalPlaces] [tinyint] NULL, 
	[Capitalize] [bit] NULL, 
	[OctaneNumber] [float] NULL, 
	[ReidVaporPressure] [float] NULL, 
	[HazardousMaterial] [bit] NULL, 
	[RegulatoryClass] [int] NULL, 
	[LoadRackDisplayText] [nvarchar](10) NULL, 
	[ComponentTolerance] [float] NULL, 
	[VaporRecovery] [bit] NULL, 
	[LockedOut] [bit] NULL, 
	[LockedOutReason] [nvarchar](80) NULL, 
	[LockedOutDate] [datetimeoffset](7) NULL, 
	[VarianceTolerance] [float] NULL, 
	[DielectricTolerance] [float] NULL, 
	[LoadByWeight] [bit] NULL, 
	[PIDXCode] [nvarchar](4) NULL, 
	[ContaminationPromptLoadRackText] [nvarchar](10) NULL, 
	[InhibitAccounting] [bit] NULL, 
	[UserData1] [nvarchar](60) NULL, 
	[UserData2] [nvarchar](60) NULL, 
	[UserData3] [nvarchar](60) NULL, 
	[UserData4] [nvarchar](60) NULL, 
	[UserData5] [nvarchar](60) NULL, 
	[UserData6] [nvarchar](60) NULL, 
	[UserData7] [nvarchar](60) NULL, 
	[UserData8] [nvarchar](60) NULL, 
	[CreatedDate] [datetimeoffset](7) NULL, 
	[CreatedBy] [udtUserID] NULL, 
	[UpdatedDate] [datetimeoffset](7) NULL, 
	[UpdatedBy] [udtUserID] NULL, 
	[MassUnitIndex] [int] NULL, 
	[LevelUnitIndex] [int] NULL, 
	[FlowUnitIndex] [int] NULL, 
	[PressureUnitIndex] [int] NULL, 
	[MassDecimalPlaces] [tinyint] NULL, 
	[LevelDecimalPlaces] [tinyint] NULL, 
	[FlowDecimalPlaces] [tinyint] NULL, 
	[PressureDecimalPlaces] [tinyint] NULL, 
	[VolumePackageSize] [float] NULL, 
	[MassPackageSize] [float] NULL, 
	[ProductGuid] [uniqueidentifier] NULL, 
	[SourceRowVersion] [bigint] NULL, 
	[SiteGuid] [uniqueidentifier] NULL, 
	[LookupProductTypeIndex] [int] NULL, 
	[TrackingProductGuid] [uniqueidentifier] NULL, 
	[TaxCode] [nvarchar](10) NULL, 
	[VcfModuleSettings] [xml] NULL, 
	[ProductColor] [nvarchar](7) NULL, 
	[PatternColor] [nvarchar](7) NULL, 
	[PatternNumber] [int] NULL, 
	[_MasterRecordGuid] [uniqueidentifier] NULL, 
	[HiddenDate] [datetimeoffset](7) NULL, 
	[AutomaticCloseout] [bit] NULL, 
	[_ClusterIdx] [bigint] NULL, 
	[PIDXFamilyCode] [nvarchar](4) NULL,
   [IsEthanol] BIT DEFAULT ((0)) NOT NULL,
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[IsRecordDeleted] [bit] NULL,
	[_RowVersion] [timestamp] NOT NULL,
CONSTRAINT [PK_tblProducts] PRIMARY KEY CLUSTERED
(
	[ProductsSKey] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF)
)
GO