CREATE TABLE [fmcdc].[tblPersonnel](
	[PersonnelSKey] [int] IDENTITY(1,1) NOT NULL,
	[PersonID] [nvarchar](50) NULL, 
	[CardNumber] [nvarchar](30) NULL, 
	[FirstName] [nvarchar](20) NULL, 
	[MiddleName] [nvarchar](20) NULL, 
	[LastName] [nvarchar](30) NULL, 
	[Title] [nvarchar](50) NULL, 
	[Department] [nvarchar](20) NULL, 
	[Address1] [nvarchar](50) NULL, 
	[Address2] [nvarchar](50) NULL, 
	[City] [nvarchar](60) NULL, 
	[State] [nvarchar](20) NULL, 
	[Zip] [nvarchar](10) NULL, 
	[Country] [nvarchar](20) NULL, 
	[Phone1] [nvarchar](50) NULL, 
	[Phone2] [nvarchar](50) NULL, 
	[AssignmentDate] [datetimeoffset](7) NULL, 
	[SupervisionDate] [datetimeoffset](7) NULL, 
	[SSAN] [nvarchar](11) NULL, 
	[BirthDate] [datetimeoffset](7) NULL, 
	[PayRate] [money] NULL, 
	[LaborRate1] [float] NULL, 
	[LaborRate2] [float] NULL, 
	[LaborRate3] [float] NULL, 
	[LaborRate4] [float] NULL, 
	[Status] [smallint] NULL, 
	[Email] [nvarchar](50) NULL, 
	[ResponsibleOfficer] [bit] NULL, 
	[Shift] [smallint] NULL, 
	[PINNumber] [varbinary](256) NULL, 
	[PINRequired] [bit] NULL, 
	[LockedOut] [bit] NULL, 
	[LockedOutReason] [nvarchar](80) NULL, 
	[LockedOutDate] [datetimeoffset](7) NULL, 
	[LastActivityDate] [datetimeoffset](7) NULL, 
	[CardedIn] [bit] NULL, 
	[ShortCardNumber] [nvarchar](6) NULL, 
	[CreatedDate] [datetimeoffset](7) NULL, 
	[CreatedBy] [udtUserID] NULL, 
	[UpdatedDate] [datetimeoffset](7) NULL, 
	[UpdatedBy] [udtUserID] NULL, 
	[OnFileSignature] [varbinary](Max) NULL, 
	[UserData1] [nvarchar](60) NULL, 
	[UserData2] [nvarchar](60) NULL, 
	[UserData3] [nvarchar](60) NULL, 
	[UserData4] [nvarchar](60) NULL, 
	[UserData5] [nvarchar](60) NULL, 
	[UserData6] [nvarchar](60) NULL, 
	[UserData7] [nvarchar](60) NULL, 
	[UserData8] [nvarchar](60) NULL, 
	[UserData9] [nvarchar](60) NULL, 
	[UserData10] [nvarchar](60) NULL, 
	[UserData11] [nvarchar](60) NULL, 
	[UserData12] [nvarchar](60) NULL, 
	[UserData13] [nvarchar](60) NULL, 
	[UserData14] [nvarchar](60) NULL, 
	[UserData15] [nvarchar](60) NULL, 
	[UserData16] [nvarchar](60) NULL, 
	[UserData17] [nvarchar](60) NULL, 
	[UserData18] [nvarchar](60) NULL, 
	[UserData19] [nvarchar](60) NULL, 
	[UserData20] [nvarchar](60) NULL, 
	[UserData21] [nvarchar](60) NULL, 
	[UserData22] [nvarchar](60) NULL, 
	[UserData23] [nvarchar](60) NULL, 
	[UserData24] [nvarchar](60) NULL, 
	[InhibitInactivityLockout] [bit] NULL, 
	[SourceRowVersion] [bigint] NULL, 
	[PersonnelGuid] [uniqueidentifier] NULL, 
	[SiteGuid] [uniqueidentifier] NULL, 
	[CompanyGuid] [uniqueidentifier] NULL, 
	[SupervisorPersonnelGuid] [uniqueidentifier] NULL, 
	[UserGuid] [uniqueidentifier] NULL, 
	[AssignedEquipmentGuid] [uniqueidentifier] NULL, 
	[_MasterRecordGuid] [uniqueidentifier] NULL, 
	[HiddenDate] [datetimeoffset](7) NULL, 
	[_ClusterIdx] [bigint] NULL, 
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[IsRecordDeleted] [bit] NULL,
	[_RowVersion] [timestamp] NOT NULL,
CONSTRAINT [PK_tblPersonnel] PRIMARY KEY CLUSTERED
(
	[PersonnelSKey] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF)
)
GO
