CREATE TABLE [fmcdc].[tblStations](
	[StationsSKey] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](50) NULL, 
	[SwingArmPosition] [bit] NULL, 
	[VaporRecovery] [bit] NULL, 
	[Enabled] [bit] NULL, 
	[BOLPrinter] [nvarchar](80) NULL, 
	[PreloadPrinter] [nvarchar](80) NULL, 
	[BOLAgeInMinutes] [int] NULL, 
	[CardReader] [bit] NULL, 
	[ThirtyFiveBitCardSupport] [bit] NULL, 
	[NumberOfCopies] [int] NULL, 
	[NumberOfPreloadCopies] [int] NULL, 
	[InhibitLoadingByLoadID] [bit] NULL, 
	[InhibitOperatingModePrompt] [bit] NULL, 
	[SynchronizeReferenceDensity] [bit] NULL, 
	[SignatureDevice] [nvarchar](20) NULL, 
	[SetDefaultPresetToZero] [bit] NULL, 
	[ArmsServiced] [nvarchar](100) NULL, 
	[InhibitSettingRecipeNames] [bit] NULL, 
	[SignatureDevicePort] [int] NULL, 
	[SignatureDeviceBaudRate] [int] NULL, 
	[MeterRecircCardNumber] [nvarchar](30) NULL, 
	[TouchKeyReader] [bit] NULL, 
	[OffLoadByOffLoadID] [bit] NULL, 
	[UseManualMeterData] [bit] NULL, 
	[PromptForBOLNumber] [bit] NULL, 
	[QueryForTrailers] [bit] NULL, 
	[PromptForGravityCaptured] [bit] NULL, 
	[PromptForTemperatureCaptured] [bit] NULL, 
	[LastTransactionNumber] [int] NULL, 
	[LastTransactionNumberDateTime] [datetimeoffset](7) NULL, 
	[CreatedDate] [datetimeoffset](7) NULL, 
	[CreatedBy] [udtUserID] NULL, 
	[UpdatedDate] [datetimeoffset](7) NULL, 
	[UpdatedBy] [udtUserID] NULL, 
	[SourceRowVersion] [bigint] NULL, 
	[StationGuid] [uniqueidentifier] NULL, 
	[SiteGuid] [uniqueidentifier] NULL, 
	[LookupStationTypeIndex] [int] NULL, 
	[LookupStationInterfaceTypeIndex] [int] NULL, 
	[TankGuid] [uniqueidentifier] NULL, 
	[IssueByVolumeTransactionAliasGuid] [uniqueidentifier] NULL, 
	[IssueByWeightTransactionAliasGuid] [uniqueidentifier] NULL, 
	[ReceiptByVolumeTransactionAliasGuid] [uniqueidentifier] NULL, 
	[ReceiptByWeightTransactionAliasGuid] [uniqueidentifier] NULL, 
	[RecircTransactionAliasGuid] [uniqueidentifier] NULL, 
	[_ClusterIdx] [bigint] NULL, 
	[LogCommunications] [bit] NULL, 
	[LogCommPath] [nvarchar](255) NULL, 
	[EnableScully] [bit] NULL, 
	[EnableEquipmentValidate] [bit] NULL, 
	[StationPromptTimeout] [int] NULL, 
	[StationMessageTimeout] [int] NULL, 
	[AssignedMeterGuid] [uniqueidentifier] NULL, 
   [EnableDynamicRecipes]               BIT                NULL,
	[EthanolExcess] bit NULL,
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[IsRecordDeleted] [bit] NULL,
	[_RowVersion] [timestamp] NOT NULL,
CONSTRAINT [PK_tblStations] PRIMARY KEY CLUSTERED
(
	[StationsSKey] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF)
)
GO