CREATE TABLE [fmcdc].[tblTransactionAliases](
	[TransactionAliasesSKey] [int] IDENTITY(1,1) NOT NULL,
	[AliasName] [nvarchar](32) NULL, 
	[MeterCloseout] [bit] NULL, 
	[BulkShipment] [bit] NULL, 
	[DistributedImpact] [bit] NULL, 
	[MultipleLineItems] [bit] NULL, 
	[LimitSelectionsBasedOnHierarchy] [bit] NULL, 
	[LineItemEditControl] [bit] NULL, 
	[MultipleWeightReadings] [bit] NULL, 
	[WeightReadingEditControl] [bit] NULL, 
	[AssociatedReport] [nvarchar](80) NULL, 
	[AssociatedPreloadReport] [nvarchar](80) NULL, 
	[DestinationEquipmentTypes1] [bigint] NULL, 
	[DestinationEquipmentTypes2] [bigint] NULL, 
	[DestinationEquipmentTypes3] [bigint] NULL, 
	[SourceEquipmentTypes1] [bigint] NULL, 
	[SourceEquipmentTypes2] [bigint] NULL, 
	[SourceEquipmentTypes3] [bigint] NULL, 
	[CreatedDate] [datetimeoffset](7) NULL, 
	[CreatedBy] [udtUserID] NULL, 
	[UpdatedDate] [datetimeoffset](7) NULL, 
	[UpdatedBy] [udtUserID] NULL, 
	[ShowCompanyName] [smallint] NULL, 
	[AggregateAssocTrans] [bit] NULL, 
	[EnableTotalQuantityExceededWarning] [bit] NULL, 
	[EnableQuantityToleranceExceededWarning] [bit] NULL, 
	[EnableTotalValueExceededWarning] [bit] NULL, 
	[EnableValueToleranceExceededWarning] [bit] NULL, 
	[LevelUnitIndex] [int] NULL, 
	[TemperatureUnitIndex] [int] NULL, 
	[DensityUnitIndex] [int] NULL, 
	[PressureUnitIndex] [int] NULL, 
	[FlowUnitIndex] [int] NULL, 
	[VolumeUnitIndex] [int] NULL, 
	[MassUnitIndex] [int] NULL, 
	[AdditiveVolumeUnitIndex] [int] NULL, 
	[AdditiveProfileCycleAmountUnitIndex] [int] NULL, 
	[AdditiveProfileRateUnitIndex] [int] NULL, 
	[LevelDecimalPlaces] [tinyint] NULL, 
	[TemperatureDecimalPlaces] [tinyint] NULL, 
	[DensityDecimalPlaces] [tinyint] NULL, 
	[PressureDecimalPlaces] [tinyint] NULL, 
	[FlowDecimalPlaces] [tinyint] NULL, 
	[VolumeDecimalPlaces] [tinyint] NULL, 
	[MassDecimalPlaces] [tinyint] NULL, 
	[AdditiveVolumeDecimalPlaces] [tinyint] NULL, 
	[UseComboBoxControls] [bit] NULL, 
	[MultipleTransportLineItems] [bit] NULL, 
	[TransactionAliasGuid] [uniqueidentifier] NULL, 
	[SourceRowVersion] [bigint] NULL, 
	[SiteGuid] [uniqueidentifier] NULL, 
	[LookupTransTypeIndex] [smallint] NULL, 
	[LookupDefaultStatusIndex] [int] NULL, 
	[AssociatedTransactionAliasGuid] [uniqueidentifier] NULL, 
	[IncludeInDispatch] [bit] NULL, 
	[_MasterRecordGuid] [uniqueidentifier] NULL, 
	[EnableAutoCompleteControls] [bit] NULL, 
	[PermitNonReferenceData] [bit] NULL, 
	[_ClusterIdx] [bigint] NULL, 
	[UseTransactionDetailWithLayout] [bit] NULL, 
	[DefaultMeterToEquipmentID] [bit] NULL, 
	[LimitSourceEquipmentByProduct] [bit] NULL, 
	[RememberMeterEndForMeterID] [bit] NULL, 
	[PopulateCompaniesFromEquipment] [bit] NULL, 
	[PopulateGrossVolumeFromMeterValues] [bit] NULL, 
	[UseMeterAndCompressionFactorFromMeter] [bit] NULL, 
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[IsRecordDeleted] [bit] NULL,
	[_RowVersion] [timestamp] NOT NULL,
CONSTRAINT [PK_tblTransactionAliases] PRIMARY KEY CLUSTERED
(
	[TransactionAliasesSKey] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF)
)
GO
