CREATE TABLE [fmcdc].[tblTransactionLineItemUserData](
	[TransactionLineItemUserDataSKey] [int] IDENTITY(1,1) NOT NULL,
	[UserData1] [nvarchar](60) NULL, 
	[UserData2] [nvarchar](60) NULL, 
	[UserData3] [nvarchar](60) NULL, 
	[UserData4] [nvarchar](60) NULL, 
	[UserData5] [nvarchar](60) NULL, 
	[UserData6] [nvarchar](60) NULL, 
	[UserData7] [nvarchar](60) NULL, 
	[UserData8] [nvarchar](60) NULL, 
	[UserData9] [nvarchar](60) NULL, 
	[UserData10] [nvarchar](60) NULL, 
	[UserData11] [nvarchar](60) NULL, 
	[UserData12] [nvarchar](60) NULL, 
	[UserData13] [nvarchar](60) NULL, 
	[UserData14] [nvarchar](60) NULL, 
	[UserData15] [nvarchar](60) NULL, 
	[UserData16] [nvarchar](60) NULL, 
	[UserData17] [nvarchar](60) NULL, 
	[UserData18] [nvarchar](60) NULL, 
	[UserData19] [nvarchar](60) NULL, 
	[UserData20] [nvarchar](60) NULL, 
	[UserData21] [nvarchar](60) NULL, 
	[UserData22] [nvarchar](60) NULL, 
	[UserData23] [nvarchar](60) NULL, 
	[UserData24] [nvarchar](60) NULL, 
	[CreatedBy] [udtUserID] NULL, 
	[CreatedDate] [datetimeoffset](7) NULL, 
	[UpdatedBy] [udtUserID] NULL, 
	[UpdatedDate] [datetimeoffset](7) NULL, 
	[TransactionLineItemUserDataGuid] [uniqueidentifier] NULL, 
	[SourceRowVersion] [bigint] NULL, 
	[TransactionLineItemGuid] [uniqueidentifier] NULL, 
	[_ClusterIdx] [bigint] NULL, 
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[IsRecordDeleted] [bit] NULL,
	[BatchProcessNumber] [int] NULL,
	[IsProcessed] [bit] NULL,
	[InitialCDCRowVersion] [bigint] NULL,
	[_RowVersion] [timestamp] NOT NULL,
CONSTRAINT [PK_tblTransactionLineItemUserData] PRIMARY KEY CLUSTERED
(
	[TransactionLineItemUserDataSKey] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF)
)
GO
