CREATE TABLE [fmcdc].[tblUsers](
	[UsersSKey] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [udtUserID] NULL, 
	[Password] [varbinary](256) NULL, 
	[LastLoginDate] [datetimeoffset](7) NULL, 
	[LastLogoffDate] [datetimeoffset](7) NULL, 
	[ChangePassword] [bit] NULL, 
	[PasswordTimeStamp] [datetimeoffset](7) NULL, 
	[Name] [nvarchar](50) NULL, 
	[EmailAddress] [nvarchar](50) NULL, 
	[CreatedDate] [datetimeoffset](7) NULL, 
	[CreatedBy] [udtUserID] NULL, 
	[UpdatedDate] [datetimeoffset](7) NULL, 
	[UpdatedBy] [udtUserID] NULL, 
	[PasswordHistory1] [varbinary](256) NULL, 
	[PasswordHistory2] [varbinary](256) NULL, 
	[PasswordHistory3] [varbinary](256) NULL, 
	[PasswordHistory4] [varbinary](256) NULL, 
	[PasswordHistory5] [varbinary](256) NULL, 
	[PasswordHistory6] [varbinary](256) NULL, 
	[PasswordHistory7] [varbinary](256) NULL, 
	[PasswordHistory8] [varbinary](256) NULL, 
	[PasswordHistory9] [varbinary](256) NULL, 
	[PasswordHistory10] [varbinary](256) NULL, 
	[PasswordHistory11] [varbinary](256) NULL, 
	[PasswordHistory12] [varbinary](256) NULL, 
	[PasswordHistory13] [varbinary](256) NULL, 
	[PasswordHistory14] [varbinary](256) NULL, 
	[PasswordHistory15] [varbinary](256) NULL, 
	[PasswordHistory16] [varbinary](256) NULL, 
	[PasswordHistory17] [varbinary](256) NULL, 
	[PasswordHistory18] [varbinary](256) NULL, 
	[PasswordHistory19] [varbinary](256) NULL, 
	[PasswordHistory20] [varbinary](256) NULL, 
	[PasswordHistory21] [varbinary](256) NULL, 
	[PasswordHistory22] [varbinary](256) NULL, 
	[PasswordHistory23] [varbinary](256) NULL, 
	[PasswordHistory24] [varbinary](256) NULL, 
	[PasswordLockoutCount] [int] NULL, 
	[InactivityLockout] [bit] NULL, 
	[InactivityLockoutDate] [datetimeoffset](7) NULL, 
	[UserGuid] [uniqueidentifier] NULL, 
	[SourceRowVersion] [bigint] NULL, 
	[SiteGuid] [uniqueidentifier] NULL, 
	[PasswordHint] [varchar](80) NULL, 
	[UserData1] [nvarchar](120) NULL, 
	[UserData2] [nvarchar](120) NULL, 
	[UserData3] [nvarchar](120) NULL, 
	[UserData4] [nvarchar](120) NULL, 
	[UserData5] [nvarchar](120) NULL, 
	[UserData6] [nvarchar](120) NULL, 
	[UserData7] [nvarchar](120) NULL, 
	[UserData8] [nvarchar](120) NULL, 
	[PhoneNumber] [nvarchar](20) NULL, 
	[AccountExpirationDate] [datetime] NULL, 
	[ActiveDirectoryUser] [bit] NULL, 
	[_ClusterIdx] [bigint] NULL, 
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[IsRecordDeleted] [bit] NULL,
	[_RowVersion] [timestamp] NOT NULL,
CONSTRAINT [PK_tblUsers] PRIMARY KEY CLUSTERED
(
	[UsersSKey] ASC
)WITH (STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF)
)
GO