//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelsManager.FMWebApp
{


	public partial class ProductGeneralPage
	{

		/// <summary>
		/// ProductIdLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel ProductIdLabel;

		/// <summary>
		/// ProdIDAskLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel ProdIDAskLabel;

		/// <summary>
		/// IDTextbox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox IDTextbox;

		/// <summary>
		/// PidxCodeLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel PidxCodeLabel;

		/// <summary>
		/// PIDXCodeTextbox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox PIDXCodeTextbox;

		/// <summary>
		/// ProductCodeLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel ProductCodeLabel;

		/// <summary>
		/// CodeTextbox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox CodeTextbox;

		/// <summary>
		/// PidxFamilyCodeLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel PidxFamilyCodeLabel;

		/// <summary>
		/// PIDXFamilyCodeTextbox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox PIDXFamilyCodeTextbox;

		/// <summary>
		/// DescriptionLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel DescriptionLabel;

		/// <summary>
		/// DescriptionTextbox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox DescriptionTextbox;

		/// <summary>
		/// ContaminationLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel ContaminationLabel;

		/// <summary>
		/// ContaminationPromptLoadRackTextTextBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox ContaminationPromptLoadRackTextTextBox;

		/// <summary>
		/// TypeLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel TypeLabel;

		/// <summary>
		/// ProductTypeDropDownList control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMDropDownList ProductTypeDropDownList;

		/// <summary>
		/// TrackingProdLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel TrackingProdLabel;

		/// <summary>
		/// TrackingProductTextBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMProductTextBox TrackingProductTextBox;

		/// <summary>
		/// OctaneLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel OctaneLabel;

		/// <summary>
		/// OctaneTextbox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox OctaneTextbox;

		/// <summary>
		/// ReidVaporLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel ReidVaporLabel;

		/// <summary>
		/// ReidVaporPressureTextbox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox ReidVaporPressureTextbox;

		/// <summary>
		/// LRDisplayLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel LRDisplayLabel;

		/// <summary>
		/// LoadRackDisplayTextbox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox LoadRackDisplayTextbox;

		/// <summary>
		/// PriceLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel PriceLabel;

		/// <summary>
		/// PriceTextBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMTextBox PriceTextBox;

		/// <summary>
		/// TaxCodeLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel TaxCodeLabel;

		/// <summary>
		/// TaxCodeTextBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMTextBox TaxCodeTextBox;

		/// <summary>
		/// ProdClassLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel ProdClassLabel;

		/// <summary>
		/// ProductClassification control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMRadioButtonList ProductClassification;

		/// <summary>
		/// VarianceTolLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel VarianceTolLabel;

		/// <summary>
		/// VarianceTolAskLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel VarianceTolAskLabel;

		/// <summary>
		/// VarianceToleranceTextbox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox VarianceToleranceTextbox;

		/// <summary>
		/// VarianceTolPercentLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Label VarianceTolPercentLabel;

		/// <summary>
		/// DielectricTolLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel DielectricTolLabel;

		/// <summary>
		/// DielectricToleranceTextbox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox DielectricToleranceTextbox;

		/// <summary>
		/// DielectricTolPercentLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Label DielectricTolPercentLabel;

		/// <summary>
		/// VaporRecoveryCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox VaporRecoveryCheckBox;

		/// <summary>
		/// LoadByWeightCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox LoadByWeightCheckBox;

		/// <summary>
		/// HazardousMaterialCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox HazardousMaterialCheckBox;

		/// <summary>
		/// InhibitAccountingCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox InhibitAccountingCheckBox;

		/// <summary>
		/// HiddenCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox HiddenCheckBox;

		/// <summary>
		/// AutomaticCloseoutCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox AutomaticCloseoutCheckBox;

		/// <summary>
		/// IsEthanolCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox IsEthanolCheckBox;

		/// <summary>
		/// LockedOutDateLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel LockedOutDateLabel;

		/// <summary>
		/// LockedOutDateTextbox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox LockedOutDateTextbox;

		/// <summary>
		/// LockedOutCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox LockedOutCheckBox;

		/// <summary>
		/// LockedReasonLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel LockedReasonLabel;

		/// <summary>
		/// LockedOutReasonTextbox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMTextBox LockedOutReasonTextbox;
	}
}
