//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelsManager.FMWebApp
{


	public partial class StationLoadRackPage
	{

		/// <summary>
		/// Label2 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel Label2;

		/// <summary>
		/// SwingArmPositionDropDownList control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.DropDownList SwingArmPositionDropDownList;

		/// <summary>
		/// Label1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel Label1;

		/// <summary>
		/// BOLPrinterDropDownList control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.DropDownList BOLPrinterDropDownList;

		/// <summary>
		/// VaporRecoveryCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox VaporRecoveryCheckBox;

		/// <summary>
		/// NumberOfCopiesLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel NumberOfCopiesLabel;

		/// <summary>
		/// NumberOfCopiesTextBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox NumberOfCopiesTextBox;

		/// <summary>
		/// SetPreloadToZeroCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox SetPreloadToZeroCheckBox;

		/// <summary>
		/// Label16 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel Label16;

		/// <summary>
		/// IssueTransactionDropDownList control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.DropDownList IssueTransactionDropDownList;

		/// <summary>
		/// InhibitLoadingByLoadIDCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox InhibitLoadingByLoadIDCheckBox;

		/// <summary>
		/// StationPermissivesButton control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlInputButton StationPermissivesButton;

		/// <summary>
		/// SynchronizeReferenceDensityCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox SynchronizeReferenceDensityCheckBox;

		/// <summary>
		/// Label17 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel Label17;

		/// <summary>
		/// MeterRecircCardNumber control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox MeterRecircCardNumber;

		/// <summary>
		/// InhibitSettingRecipeNamesCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox InhibitSettingRecipeNamesCheckBox;

		/// <summary>
		/// EthanolExcessCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox EthanolExcessCheckBox;

		/// <summary>
		/// EnableScullyCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox EnableScullyCheckBox;

		/// <summary>
		/// EnableEquipmentValidateCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox EnableEquipmentValidateCheckBox;

		/// <summary>
		/// EnableDynamicRecipesCheckBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMCheckBox EnableDynamicRecipesCheckBox;

		/// <summary>
		/// Label18 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel Label18;

		/// <summary>
		/// RecircTransactionDropDownList control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.DropDownList RecircTransactionDropDownList;

		/// <summary>
		/// Label19 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel Label19;

		/// <summary>
		/// NumberOfLastTransaction control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox NumberOfLastTransaction;

		/// <summary>
		/// OPCServerLbl control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel OPCServerLbl;

		/// <summary>
		/// OPCServerDropDownList control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.DropDownList OPCServerDropDownList;

		/// <summary>
		/// OPCItemPathLbl control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel OPCItemPathLbl;

		/// <summary>
		/// OPCItemPathTextBox control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox OPCItemPathTextBox;
	}
}
