//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelsManager.FMWebApp
{


    public partial class StationMeterPage
    {

        /// <summary>
        /// MeterIDLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel MeterIDLabel;

        /// <summary>
        /// MeterIDTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMTextBox MeterIDTextBox;

        /// <summary>
        /// RotatesBackwardLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel RotatesBackwardLabel;

        /// <summary>
        /// RotatesBackwardCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMCheckBox RotatesBackwardCheckBox;

        /// <summary>
        /// NumberOfDigitsLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel NumberOfDigitsLabel;

        /// <summary>
        /// NumberOfDigitsTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMTextBox NumberOfDigitsTextBox;

        /// <summary>
        /// ReceiptMeterLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel ReceiptMeterLabel;

        /// <summary>
        /// ReceiptMeterCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMCheckBox ReceiptMeterCheckBox;

        /// <summary>
        /// MeterFactorLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel MeterFactorLabel;

        /// <summary>
        /// MeterFactorTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMTextBox MeterFactorTextBox;

        /// <summary>
        /// FuelCompressionFactorLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel FuelCompressionFactorLabel;

        /// <summary>
        /// FuelCompressionFactorTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMTextBox FuelCompressionFactorTextBox;

        /// <summary>
        /// ProcessVariablesDataGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMDataGrid ProcessVariablesDataGrid;

        /// <summary>
        /// AssociatedTankLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel AssociatedTankLabel;

        /// <summary>
        /// AssociatedTanks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList AssociatedTanks;

        /// <summary>
        /// ArmsServicedLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel ArmsServicedLabel;

        /// <summary>
        /// ArmsServiced control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ArmsServiced;
    }
}
