// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Interim step in updating application", Scope = "member", Target = "~M:LoadRackLibrary.StationManagerClass.CreateSubLineItem(LoadRackLibrary.LoadArmManagerClass,FMBusinessObjects.DataObjects.LineItemDO,FMBusinessObjects.DataObjects.ProductMapClass,FMBusinessObjects.DataObjects.ProductMapClass,Opc.Da.Server)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.StationManagerClass.GetEquipmentClass(System.String)~FMBusinessObjects.DataObjects.EquipmentClass")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Interim step in updating application", Scope = "member", Target = "~M:LoadRackLibrary.StationManagerClass.IssueCompartmentsEmptyPrompt(LoadRackLibrary.ContaminationPromptStatus)")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.LoadArmManagerClass.Bay(LoadRackLibrary.StationManagerClass)~LoadRackLibrary.BayInfo")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.LoadArmManagerClass.ArmNumber(LoadRackLibrary.StationManagerClass)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.LoadArmManagerClass.GetArmNumber(LoadRackLibrary.StationManagerClass)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.LoadArmManagerClass.GetStationManager~LoadRackLibrary.StationManagerClass")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~P:LoadRackLibrary.AcculoadIIILoadArmManagerClass.IsInAlarm")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.LoadArmManagerClass.IsOffloadProductServedByLoadArm(FMBusinessObjects.DataObjects.ProductClass)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Interim step in updating application", Scope = "member", Target = "~M:LoadRackLibrary.LoadArmManagerClass.PromptForNextBatch(LoadRackLibrary.StationManagerClass,System.Boolean)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.MultiloadIIStationManagerClass.ReadLineItemData(FMBusinessObjects.DataObjects.LineItemDO,Opc.Da.Server,LoadRackLibrary.LoadArmManagerClass)")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.MultiloadIILoadArmManagerClass.ProcessSplashBlendComponentPromptResponse(LoadRackLibrary.StationManagerClass,System.String)")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.StationManagerClass.CheckEquipmentInTransaction(FMBusinessObjects.DataObjects.EquipmentClass)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.VarecDETLoadArmManagerClass.IsOffloadProductServedByLoadArm(FMBusinessObjects.DataObjects.ProductClass)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.VarecDETStationManagerClass.DisplayMenu(LoadRackLibrary.DisplayMenuParameters)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Using non-standard casing to avoid name collision", Scope = "member", Target = "~M:LoadRackLibrary.VarecDETStationManagerClass.opengate")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "Still have to support older build tools on build server", Scope = "member", Target = "~M:LoadRackLibrary.VarecDETStationManagerClass.ProcessProduct(System.String)")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.LoadArmManagerClass.CheckAvailableVolume(LoadRackLibrary.StationManagerClass)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "Left as not inlined for clarity", Scope = "member", Target = "~M:LoadRackLibrary.MultiloadIILoadArmManagerClass.CaptureMeterValues")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "Left as not inlined for clarity", Scope = "member", Target = "~M:LoadRackLibrary.MultiloadIIStationManagerClass.CreateMeterReadingTransactions(FMBusinessObjects.ServiceRequests.SaveTransactionsSR,FMBusinessObjects.DataObjects.TransactionAliasClass,System.DateTimeOffset)")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "Left as not inlined for clarity", Scope = "member", Target = "~M:LoadRackLibrary.MultiloadIIStationManagerClass.ReadLineItemData(FMBusinessObjects.DataObjects.LineItemDO,Opc.Da.Server,LoadRackLibrary.LoadArmManagerClass)")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.SiteManagerClass.TanksScan")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.SiteManagerClass.UpdateWatchdogOutput")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.SiteManagerClass.GetStationTransaction(System.Guid)~FMBusinessObjects.DataObjects.TransactionDO")]
[assembly: SuppressMessage("Style", "IDE0270:Use coalesce expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.LoadArmManagerClass.StartLine(LoadRackLibrary.StationManagerClass,FMBusinessObjects.DataObjects.LineItemDO)")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.StationManagerClass.IssueOffloadSummaryPrompt")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "Left as not inlined for clarity", Scope = "member", Target = "~M:LoadRackLibrary.AcculoadIIIStationManagerClass.ReadBatchData(FMBusinessObjects.DataObjects.LineItemDO,Opc.Da.Server,LoadRackLibrary.AcculoadIIILoadArmManagerClass)")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "Left as not inlined for clarity", Scope = "member", Target = "~M:LoadRackLibrary.AcculoadIIIStationManagerClass.ReadComponentBatchData(FMBusinessObjects.DataObjects.ProductMapClass,FMBusinessObjects.DataObjects.SubLineItemDO,Opc.Da.Server,LoadRackLibrary.AcculoadIIILoadArmManagerClass)")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "Left as not inlined for clarity", Scope = "member", Target = "~M:LoadRackLibrary.AcculoadIIIStationManagerClass.ReadAdditiveBatchData(FMBusinessObjects.DataObjects.ProductMapClass,FMBusinessObjects.DataObjects.SubLineItemDO,Opc.Da.Server,LoadRackLibrary.AcculoadIIILoadArmManagerClass)")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.AcculoadIIIStationManagerClass.ReadAdditiveProductsUsingInjector(FMBusinessObjects.DataObjects.ProductMapClass,Opc.Da.Server,LoadRackLibrary.LoadArmManagerClass)~System.Byte")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.StationManagerClass.AuthorizeLoadArm(LoadRackLibrary.LoadArmManagerClass,FMBusinessObjects.DataObjects.LineItemDO,System.Double,System.UInt64)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Is clearer leaving as if blocks", Scope = "member", Target = "~M:LoadRackLibrary.StationManagerClass.AuthorizeLoadArm(LoadRackLibrary.LoadArmManagerClass,FMBusinessObjects.DataObjects.LineItemDO,System.Double,System.UInt64)~System.Boolean")]
