/*
	DROP TABLE [erv].[tblTempCompanyRecordVersioningFlag]
*/
CREATE TABLE [erv].[tblTempCompanyRecordVersioningFlag] (
    [CompanyRVFlagGuid]                              UNIQUEIDENTIFIER   CONSTRAINT [DF_tblTempCompanyRecordVersioningFlag_GUID] DEFAULT (newid()) NOT NULL,
    [CompanyGuid]                                    UNIQUEIDENTIFIER   NULL,
    [SiteGuid]                                       UNIQUEIDENTIFIER   NULL,
    [AccountNumber_RVFlag]                           BIT                NULL,
    [AdditiveAccounting_RVFlag]                      BIT                NULL,
    [Address1_RVFlag]                                BIT                NULL,
    [Address2_RVFlag]                                BIT                NULL,
    [AllowDriverEntry_RVFlag]                        BIT                NULL,
    [City_RVFlag]                                    BIT                NULL,
    [Code_RVFlag]                                    BIT                NULL,
	[ConsortiumTypeIndex_RVFlag]                          BIT                NULL,
    [Contact1Address1_RVFlag]                        BIT                NULL,
    [Contact1Address2_RVFlag]                        BIT                NULL,
    [Contact1City_RVFlag]                            BIT                NULL,
    [Contact1Country_RVFlag]                         BIT                NULL,
    [Contact1EmailAddress_RVFlag]                    BIT                NULL,
    [Contact1Fax_RVFlag]                             BIT                NULL,
    [Contact1Name_RVFlag]                            BIT                NULL,
    [Contact1PhoneMobile_RVFlag]                     BIT                NULL,
    [Contact1PhoneOffice_RVFlag]                     BIT                NULL,
    [Contact1State_RVFlag]                           BIT                NULL,
    [Contact1Zip_RVFlag]                             BIT                NULL,
    [Contact2Address1_RVFlag]                        BIT                NULL,
    [Contact2Address2_RVFlag]                        BIT                NULL,
    [Contact2City_RVFlag]                            BIT                NULL,
    [Contact2Country_RVFlag]                         BIT                NULL,
    [Contact2EmailAddress_RVFlag]                    BIT                NULL,
    [Contact2Fax_RVFlag]                             BIT                NULL,
    [Contact2Name_RVFlag]                            BIT                NULL,
    [Contact2PhoneMobile_RVFlag]                     BIT                NULL,
    [Contact2PhoneOffice_RVFlag]                     BIT                NULL,
    [Contact2State_RVFlag]                           BIT                NULL,
    [Contact2Zip_RVFlag]                             BIT                NULL,
    [Country_RVFlag]                                 BIT                NULL,
    [CreditOK_RVFlag]                                BIT                NULL,
    [CustomerBillToTypeApplicationStringGuid_RVFlag] BIT                NULL,
    [CustomerShipToTypeApplicationStringGuid_RVFlag] BIT                NULL,
    [DeliveryToTerminalPermitted_RVFlag]             BIT                NULL,
    [DisableBillToAllocationsCheck_RVFlag]           BIT                NULL,
    [DisableOwnerAllocationsCheck_RVFlag]            BIT                NULL,
    [DisableShipperAllocationsCheck_RVFlag]          BIT                NULL,
    [DisableShipToAllocationsCheck_RVFlag]           BIT                NULL,
    [EffectiveDate_RVFlag]                           BIT                NULL,
    [EmergencyContact_RVFlag]                        BIT                NULL,
    [EmergencyPhone_RVFlag]                          BIT                NULL,
    [EPANumber_RVFlag]                               BIT                NULL,
    [ExpirationDate_RVFlag]                          BIT                NULL,
    [FAX_RVFlag]                                     BIT                NULL,
    [FederalID_RVFlag]                               BIT                NULL,
	[FederalID2_RVFlag]                              BIT                NULL,
	[FederalID3_RVFlag]                              BIT                NULL,
	[FederalID4_RVFlag]                              BIT                NULL,
	[FederalID5_RVFlag]                              BIT                NULL,	
    [FlightPrefix_RVFlag]                            BIT                NULL,
    [FlushPermitted_RVFlag]                          BIT                NULL,
    [HazardousMaterialExclusion_RVFlag]              BIT                NULL,
	[HiddenDate_RVFlag]                              BIT                NULL,
    [IATAGuid_RVFlag]                                BIT                NULL,
    [ID_RVFlag]                                      BIT                NULL,
    [InsuranceCompany_RVFlag]                        BIT                NULL,
    [InsuranceExpiration_RVFlag]                     BIT                NULL,
    [InsurancePolicy_RVFlag]                         BIT                NULL,
    [LastActivityDate_RVFlag]                        BIT                NULL,
    [LiabilityAmount_RVFlag]                         BIT                NULL,
    [LicenseExpiration_RVFlag]                       BIT                NULL,
    [LicenseNumber_RVFlag]                           BIT                NULL,
    [LoadRackDisplayText_RVFlag]                     BIT                NULL,
    [LockedOut_RVFlag]                               BIT                NULL,
    [LockedOutDate_RVFlag]                           BIT                NULL,
    [LockedOutReason_RVFlag]                         BIT                NULL,
    [LowStockWarning_RVFlag]                         BIT                NULL,
    [MaximumVehicleWeight_RVFlag]                    BIT                NULL,
    [Name_RVFlag]                                    BIT                NULL,
    [Note_RVFlag]                                    BIT                NULL,
    [OnHold_RVFlag]                                  BIT                NULL,
    [Phone_RVFlag]                                   BIT                NULL,
    [PickupFLights_RVFlag]                           BIT                NULL,
    [PINRequired_RVFlag]                             BIT                NULL,
    [PumpOffPermitted_RVFlag]                        BIT                NULL,
    [PurchaseOrderRequired_RVFlag]                   BIT                NULL,
    [ReceivableAccount_RVFlag]                       BIT                NULL,
    [RefinerCode_RVFlag]                             BIT                NULL,
    [SCACCode_RVFlag]                                BIT                NULL,
	[ScullyRequired_RVFlag]                          BIT                NULL,
    [ShipperTypeApplicationStringGuid_RVFlag]        BIT                NULL,
    [ShortName_RVFlag]                               BIT                NULL,
	[State_RVFlag]                                   BIT                NULL,
	[StateId_RVFlag]                                 BIT                NULL,
    [StockTrack_RVFlag]                              BIT                NULL,
    [SufferLossGain_RVFlag]                          BIT                NULL,
    [TaxNumber_RVFlag]                               BIT                NULL,
    [UpdatedBy_RVFlag]                               BIT                NULL,
    [UpdatedDate_RVFlag]                             BIT                NULL,
    [UserData1_RVFlag]                               BIT                NULL,
    [UserData2_RVFlag]                               BIT                NULL,
    [UserData3_RVFlag]                               BIT                NULL,
    [UserData4_RVFlag]                               BIT                NULL,
    [UserData5_RVFlag]                               BIT                NULL,
    [UserData6_RVFlag]                               BIT                NULL,
    [UserData7_RVFlag]                               BIT                NULL,
    [UserData8_RVFlag]                               BIT                NULL,
    [WeightUnits_RVFlag]                             BIT                NULL,
    [Zip_RVFlag]                                     BIT                NULL,
    [_CallingReferenceGuid]                          UNIQUEIDENTIFIER   NOT NULL,
    [CreatedDate]                                    DATETIMEOFFSET (7) CONSTRAINT [DF_tblTempCompanyRecordVersioningFlag_CreatedDate] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CreatedBy]                                      [dbo].[udtUserID]  CONSTRAINT [DF_tblTempCompanyRecordVersioningFlag_CreatedBy] DEFAULT ('') NOT NULL,
    [UpdatedDate]                                    DATETIMEOFFSET (7) CONSTRAINT [DF_tblTempCompanyRecordVersioningFlag_UpdatedDate] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [UpdatedBy]                                      [dbo].[udtUserID]  CONSTRAINT [DF_tblTempCompanyRecordVersioningFlag_UpdatedBy] DEFAULT ('') NOT NULL,
    [_RowVersion]                                    ROWVERSION         NOT NULL,    
    [_ClusterIdx]                                    BIGINT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_tblTempCompanyRecordVersioningFlag] PRIMARY KEY NONCLUSTERED ([CompanyRVFlagGuid] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_tblTempCompanyRecordVersioningFlag_CompanyGuid]
    ON [erv].[tblTempCompanyRecordVersioningFlag]([CompanyGuid] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_tblTempCompanyRecordVersioningFlag_CallingReferenceGuid]
    ON [erv].[tblTempCompanyRecordVersioningFlag]([_CallingReferenceGuid] ASC);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_tblTempCompanyRecordVersioningFlag_ClusterIdx]
    ON [erv].[tblTempCompanyRecordVersioningFlag]([_ClusterIdx] ASC);

GO
