/*
	DROP TABLE [erv].[tblTempEquipmentRecordVersioningFlag]
*/
CREATE TABLE [erv].[tblTempEquipmentRecordVersioningFlag] (
    [EquipmentRVFlagGuid]             UNIQUEIDENTIFIER   CONSTRAINT [DF_tblTempEquipmentRecordVersioningFlag_GUID] DEFAULT (newid()) NOT NULL,
    [EquipmentGuid]                   UNIQUEIDENTIFIER   NULL,
    [SiteGuid]                        UNIQUEIDENTIFIER   NULL,
    [ActualGPM_RVFlag]                BIT                NULL,
    [AssetTrackingDeviceGuid_RVFlag]  BIT                NULL,
	[AssignedToMeterGuid_RVFlag]      BIT                NULL,
    [AttachedTo_RVFlag]               BIT                NULL,
    [CalibrationDate_RVFlag]          BIT                NULL,
    [Capacity_RVFlag]                 BIT                NULL,
    [CompanyEquipmentID_RVFlag]       BIT                NULL,
    [CompanyGuid_RVFlag]              BIT                NULL,
    [Consecutive_OOS_Variance_RVFlag] BIT                NULL,
    [DefuelMeterForwards_RVFlag]      BIT                NULL,
    [DensityDecimalPlaces_RVFlag]     BIT                NULL,
    [DensityUnitIndex_RVFlag]         BIT                NULL,
    [Description_RVFlag]              BIT                NULL,
    [EquipmentSequence_RVFlag]        BIT                NULL,
    [EquipmentTypeGuid_RVFlag]        BIT                NULL,
    [Fixed_RVFlag]                    BIT                NULL,
    [FixedVolume_RVFlag]              BIT                NULL,
    [FuelAdditiveFlag_RVFlag]         BIT                NULL,
    [FuelCardGuid_RVFlag]             BIT                NULL,
    [FuelingState_RVFlag]             BIT                NULL,
    [FuelingType_RVFlag]              BIT                NULL,
    [ID_RVFlag]                       BIT                NULL,
    [InspectionDate_RVFlag]           BIT                NULL,
    [InstallationDate_RVFlag]         BIT                NULL,
    [IntoPlane_RVFlag]                BIT                NULL,
    [InUse_RVFlag]                    BIT                NULL,
    [IssPtNum_RVFlag]                 BIT                NULL,
    [LockedOut_RVFlag]                BIT                NULL,
    [LockedOutDate_RVFlag]            BIT                NULL,
    [LockedOutReason_RVFlag]          BIT                NULL,
    [LowStockWarning_RVFlag]          BIT                NULL,
    [Make_RVFlag]                     BIT                NULL,
    [ManagedEquipmentFlag_RVFlag]     BIT                NULL,
    [ManufactureDate_RVFlag]          BIT                NULL,
    [MassDecimalPlaces_RVFlag]        BIT                NULL,
    [MassUnitIndex_RVFlag]            BIT                NULL,
    [MediaType_RVFlag]                BIT                NULL,
    [MeterReading_RVFlag]             BIT                NULL,
    [Meters_RVFlag]                   BIT                NULL,
    [Mobile_RVFlag]                   BIT                NULL,
    [Model_RVFlag]                    BIT                NULL,
    [Notes_RVFlag]                    BIT                NULL,
    [ParentEquipmentGuid_RVFlag]      BIT                NULL,
    [ProductGuid_RVFlag]              BIT                NULL,
    [PulseRatio_RVFlag]               BIT                NULL,
    [QCDate_RVFlag]                   BIT                NULL,
    [RatedGPM_RVFlag]                 BIT                NULL,
    [Round_RVFlag]                    BIT                NULL,
    [SafeFill_RVFlag]                 BIT                NULL,
	[ScullyRequired_RVFlag]           BIT                NULL,
    [SecondaryStorageFlag_RVFlag]     BIT                NULL,
    [SerialNumber_RVFlag]             BIT                NULL,
    [StockTrack_RVFlag]               BIT                NULL,
    [StorageType_RVFlag]              BIT                NULL,
    [TemperatureDecimalPlaces_RVFlag] BIT                NULL,
    [TemperatureUnitIndex_RVFlag]     BIT                NULL,
    [Totalisor1_RVFlag]               BIT                NULL,
    [Totalisor2_RVFlag]               BIT                NULL,
    [TruckCardNumber_RVFlag]          BIT                NULL,
    [UpdatedBy_RVFlag]                BIT                NULL,
    [UpdatedDate_RVFlag]              BIT                NULL,
    [UserData1_RVFlag]                BIT                NULL,
    [UserData10_RVFlag]               BIT                NULL,
    [UserData11_RVFlag]               BIT                NULL,
    [UserData12_RVFlag]               BIT                NULL,
    [UserData13_RVFlag]               BIT                NULL,
    [UserData14_RVFlag]               BIT                NULL,
    [UserData15_RVFlag]               BIT                NULL,
    [UserData16_RVFlag]               BIT                NULL,
    [UserData17_RVFlag]               BIT                NULL,
    [UserData18_RVFlag]               BIT                NULL,
    [UserData19_RVFlag]               BIT                NULL,
    [UserData2_RVFlag]                BIT                NULL,
    [UserData20_RVFlag]               BIT                NULL,
    [UserData21_RVFlag]               BIT                NULL,
    [UserData22_RVFlag]               BIT                NULL,
    [UserData23_RVFlag]               BIT                NULL,
    [UserData24_RVFlag]               BIT                NULL,
    [UserData3_RVFlag]                BIT                NULL,
    [UserData4_RVFlag]                BIT                NULL,
    [UserData5_RVFlag]                BIT                NULL,
    [UserData6_RVFlag]                BIT                NULL,
    [UserData7_RVFlag]                BIT                NULL,
    [UserData8_RVFlag]                BIT                NULL,
    [UserData9_RVFlag]                BIT                NULL,
    [Volume_RVFlag]                   BIT                NULL,
    [VolumeDecimalPlaces_RVFlag]      BIT                NULL,
    [VolumeUnitIndex_RVFlag]          BIT                NULL,
    [Xref_RVFlag]                     BIT                NULL,
    [Year_RVFlag]                     BIT                NULL,
    [_CallingReferenceGuid]           UNIQUEIDENTIFIER   NOT NULL,
    [CreatedDate]                     DATETIMEOFFSET (7) CONSTRAINT [DF_tblTempEquipmentRecordVersioningFlag_CreatedDate] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [CreatedBy]                       [dbo].[udtUserID]  CONSTRAINT [DF_tblTempEquipmentRecordVersioningFlag_CreatedBy] DEFAULT ('') NOT NULL,
    [UpdatedDate]                     DATETIMEOFFSET (7) CONSTRAINT [DF_tblTempEquipmentRecordVersioningFlag_UpdatedDate] DEFAULT (sysdatetimeoffset()) NOT NULL,
    [UpdatedBy]                       [dbo].[udtUserID]  CONSTRAINT [DF_tblTempEquipmentRecordVersioningFlag_UpdatedBy] DEFAULT ('') NOT NULL,
    [_RowVersion]                     ROWVERSION         NOT NULL,
    [HiddenDate_RVFlag]               BIT                NULL,
    [_ClusterIdx]                     BIGINT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_tblTempEquipmentRecordVersioningFlag] PRIMARY KEY NONCLUSTERED ([EquipmentRVFlagGuid] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_tblTempEquipmentRecordVersioningFlag_EquipmentGuid]
    ON [erv].[tblTempEquipmentRecordVersioningFlag]([EquipmentGuid] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_tblTempEquipmentRecordVersioningFlag_CallingReferenceGuid]
    ON [erv].[tblTempEquipmentRecordVersioningFlag]([_CallingReferenceGuid] ASC);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_tblTempEquipmentRecordVersioningFlag_ClusterIdx]
    ON [erv].[tblTempEquipmentRecordVersioningFlag]([_ClusterIdx] ASC);

GO
