/*
	DROP PROCEDURE [Staging].[usp_LoadTransactionHeaders]
 
	EXEC [staging].[usp_LoadTransactionHeaders]
 
*/
CREATE PROCEDURE [staging].[usp_LoadTransactionHeaders]
AS
BEGIN
------------------------------------------------------------------------------------------------------
-- Stored procedure: [staging].[usp_LoadTransactionHeaders]
-- Author: Hansraj Bapoo
-- Version/Date: 1.0.003 / 2012-07-13 14:21:10.4470770 -04:00
-- Purpose: Loads all the TransactionHeaders records from staging into the tblTransactions table in the Archive database.
-- Notes:
-- 1. This operation assumes that no referential integrity or dependencies are enforced on the tblTransactions table.
------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
 
		IF (
			(	SELECT COUNT(*) FROM staging.tblTransactions
				WHERE IsProcessed = 0
			) = 0)
		BEGIN
			RETURN
		END
 
	DECLARE @tblInsertedRecords TABLE
	(
		[SKey] [int] IDENTITY(1,1) NOT NULL,
		[RecordGuid] [uniqueidentifier] NOT NULL,
		[RecordIndex] [bigint] NOT NULL,
		[ParentRecordGuid] [uniqueidentifier] NULL
	)
 
	DECLARE @tblUpdatedRecords TABLE
	(
		[SKey] [int] IDENTITY(1,1) NOT NULL,
		[RecordGuid] [uniqueidentifier] NOT NULL,
		[RecordIndex] [bigint] NOT NULL,
		[ParentRecordGuid] [uniqueidentifier] NULL
	)
 
		INSERT INTO @tblUpdatedRecords ([RecordGuid], [RecordIndex], [ParentRecordGuid])
		SELECT src.[TransactionGuid], src.[SourceClusterIdx], src.[TransactionGuid]
		FROM staging.tblTransactions src
		WHERE src.TransactionGuid IS NOT NULL
		AND src.IsProcessed = 0
		AND src.IgnoreRecord = 0
		AND EXISTS
		(
			SELECT * FROM [dbo].[tblTransactions] tgt
			WHERE tgt.TransactionGuid = src.TransactionGuid
		)
 
 
		INSERT INTO @tblInsertedRecords ([RecordGuid], [RecordIndex], [ParentRecordGuid])
		SELECT src.[TransactionGuid], src.[SourceClusterIdx], src.[TransactionGuid]
		FROM staging.tblTransactions src
		WHERE src.TransactionGuid IS NOT NULL
		AND src.IsProcessed = 0
		AND src.IgnoreRecord = 0
		AND NOT EXISTS
		(
			SELECT * FROM [dbo].[tblTransactions] tgt
			WHERE tgt.TransactionGuid = src.TransactionGuid
		)
 
 
		INSERT INTO [dbo].[tblTransactions]
		(
		[TransID]
		, [AliasName]
		, [SubType]
		, [Site]
		, [TransReferenceID]
		, [InventoryDate]
		, [ShipToID]
		, [ShipToCode]
		, [SupplierID]
		, [SupplierCode]
		, [CreatedDate]
		, [CreatedBy]
		, [RequestedDeliveryDate]
		, [UpdatedDate]
		, [UpdatedBy]
		, [TransDateTime]
		, [TransVersion]
		, [SCACCode]
		, [CardNumber]
		, [ShipmentNumber]
		, [ShipperID]
		, [ShipperCode]
		, [OwnerID]
		, [OwnerCode]
		, [ManagerID]
		, [ManagerCode]
		, [CarrierID]
		, [CarrierCode]
		, [ConjoinTransID]
		, [ReversedTransID]
		, [LinkedDocumentNumber]
		, [ReversalType]
		, [PONumber]
		, [TimeIn]
		, [TimeOut]
		, [TimeEnd]
		, [RoutingID]
		, [TicketSource]
		, [LoadID]
		, [BillToID]
		, [BillToCode]
		, [DriverIdentificationNumber]
		, [CreditAmount]
		, [CardExpiration]
		, [CardName]
		, [CardType]
		, [CashAmount]
		, [RouteOriginationDate]
		, [InternationalRouteIndicator]
		, [PreviousRoutingID]
		, [ShippingDocumentNumber]
		, [DocumentNumber]
		, [STD]
		, [ETD]
		, [STA]
		, [ETA]
		, [SFT]
		, [FST]
		, [EstimatedFuelingDuration]
		, [DeleteFlag]
		, [TicketMode]
		, [DestinationRegistrationID1]
		, [DestinationSerialNumber1]
		, [DestinationEquipmentType1]
		, [DestinationEquipmentModel1]
		, [DestinationCompanyEquipmentID1]
		, [DestinationRegistrationID2]
		, [DestinationSerialNumber2]
		, [DestinationEquipmentType2]
		, [DestinationEquipmentModel2]
		, [DestinationCompanyEquipmentID2]
		, [DestinationRegistrationID3]
		, [DestinationSerialNumber3]
		, [DestinationEquipmentType3]
		, [DestinationEquipmentModel3]
		, [DestinationCompanyEquipmentID3]
		, [SourceRegistrationID1]
		, [SourceSerialNumber1]
		, [SourceEquipmentType1]
		, [SourceEquipmentModel1]
		, [SourceCompanyEquipmentID1]
		, [SourceRegistrationID2]
		, [SourceSerialNumber2]
		, [SourceEquipmentType2]
		, [SourceEquipmentModel2]
		, [SourceCompanyEquipmentID2]
		, [SourceRegistrationID3]
		, [SourceSerialNumber3]
		, [SourceEquipmentType3]
		, [SourceEquipmentModel3]
		, [SourceCompanyEquipmentID3]
		, [OperatorID]
		, [EffectiveDate]
		, [ExpirationDate]
		, [ScheduledDate]
		, [AutoComplete]
		, [Flag01]
		, [Flag02]
		, [Flag03]
		, [Flag04]
		, [Flag05]
		, [Flag06]
		, [Number01]
		, [Number02]
		, [Number03]
		, [Number04]
		, [Number05]
		, [Number06]
		, [ContactFirstName]
		, [ContactSurname]
		, [Date01]
		, [Date02]
		, [Date03]
		, [Date04]
		, [LegacyNumber]
		, [Country]
		, [ContactInfo]
		, [AssociatedDocNumber]
		, [AssociatedCLIN]
		, [SubmittedToAccounting]
		, [FuelCardID]
		, [AssociatedTransportOrderNumber]
		, [RequestedDateTime]
		, [DispatchedDateTime]
		, [ErrorFlag]
		, [TransactionGuid]
		, [SiteGuid]
		, [LookupTransTypeIndex]
		, [LookupTransactionStatusIndex]
		, [LookupOriginApplicationIndex]
		, [TransactionAliasGuid]
		, [BillToCompanyGuid]
		, [Destination1EquipmentGuid]
		, [Destination2EquipmentGuid]
		, [Destination3EquipmentGuid]
		, [FinalStationIATAGuid]
		, [FuelCardGuid]
		, [ManagerCompanyGuid]
		, [NextStationIATAGuid]
		, [OperatorPersonnelGuid]
		, [OriginStationIATAGuid]
		, [OwnerCompanyGuid]
		, [PreviousStationIATAGuid]
		, [ShipperCompanyGuid]
		, [ShipToCompanyGuid]
		, [Source1EquipmentGuid]
		, [Source2EquipmentGuid]
		, [Source3EquipmentGuid]
		, [SupplierCompanyGuid]
		, [CarrierCompanyGuid]
		, [ReasonCodeGuid]
		, [OriginStationIATAID]
		, [PreviousStationIATAID]
		, [NextStationIATAID]
		, [FinalStationIATAID]
		, [OperatorName]
		, [FuelAdditiveFlag]
		, [IssuePoint]
		, [IssuePointNumber]
		, [RadioNumber]
		, [GateID]
		, [GateGuid]
		, [ShippingMethod]
		, [InventoryDateKey]
		, [ArchiveDate]
		, [ETLProcessKey]
		)
		SELECT
		src.[TransID]
		, src.[AliasName]
		, src.[SubType]
		, src.[Site]
		, src.[TransReferenceID]
		, src.[InventoryDate]
		, src.[ShipToID]
		, src.[ShipToCode]
		, src.[SupplierID]
		, src.[SupplierCode]
		, src.[CreatedDate]
		, src.[CreatedBy]
		, src.[RequestedDeliveryDate]
		, src.[UpdatedDate]
		, src.[UpdatedBy]
		, src.[TransDateTime]
		, src.[TransVersion]
		, src.[SCACCode]
		, src.[CardNumber]
		, src.[ShipmentNumber]
		, src.[ShipperID]
		, src.[ShipperCode]
		, src.[OwnerID]
		, src.[OwnerCode]
		, src.[ManagerID]
		, src.[ManagerCode]
		, src.[CarrierID]
		, src.[CarrierCode]
		, src.[ConjoinTransID]
		, src.[ReversedTransID]
		, src.[LinkedDocumentNumber]
		, src.[ReversalType]
		, src.[PONumber]
		, src.[TimeIn]
		, src.[TimeOut]
		, src.[TimeEnd]
		, src.[RoutingID]
		, src.[TicketSource]
		, src.[LoadID]
		, src.[BillToID]
		, src.[BillToCode]
		, src.[DriverIdentificationNumber]
		, src.[CreditAmount]
		, src.[CardExpiration]
		, src.[CardName]
		, src.[CardType]
		, src.[CashAmount]
		, src.[RouteOriginationDate]
		, src.[InternationalRouteIndicator]
		, src.[PreviousRoutingID]
		, src.[ShippingDocumentNumber]
		, src.[DocumentNumber]
		, src.[STD]
		, src.[ETD]
		, src.[STA]
		, src.[ETA]
		, src.[SFT]
		, src.[FST]
		, src.[EstimatedFuelingDuration]
		, src.[DeleteFlag]
		, src.[TicketMode]
		, src.[DestinationRegistrationID1]
		, src.[DestinationSerialNumber1]
		, src.[DestinationEquipmentType1]
		, src.[DestinationEquipmentModel1]
		, src.[DestinationCompanyEquipmentID1]
		, src.[DestinationRegistrationID2]
		, src.[DestinationSerialNumber2]
		, src.[DestinationEquipmentType2]
		, src.[DestinationEquipmentModel2]
		, src.[DestinationCompanyEquipmentID2]
		, src.[DestinationRegistrationID3]
		, src.[DestinationSerialNumber3]
		, src.[DestinationEquipmentType3]
		, src.[DestinationEquipmentModel3]
		, src.[DestinationCompanyEquipmentID3]
		, src.[SourceRegistrationID1]
		, src.[SourceSerialNumber1]
		, src.[SourceEquipmentType1]
		, src.[SourceEquipmentModel1]
		, src.[SourceCompanyEquipmentID1]
		, src.[SourceRegistrationID2]
		, src.[SourceSerialNumber2]
		, src.[SourceEquipmentType2]
		, src.[SourceEquipmentModel2]
		, src.[SourceCompanyEquipmentID2]
		, src.[SourceRegistrationID3]
		, src.[SourceSerialNumber3]
		, src.[SourceEquipmentType3]
		, src.[SourceEquipmentModel3]
		, src.[SourceCompanyEquipmentID3]
		, src.[OperatorID]
		, src.[EffectiveDate]
		, src.[ExpirationDate]
		, src.[ScheduledDate]
		, src.[AutoComplete]
		, src.[Flag01]
		, src.[Flag02]
		, src.[Flag03]
		, src.[Flag04]
		, src.[Flag05]
		, src.[Flag06]
		, src.[Number01]
		, src.[Number02]
		, src.[Number03]
		, src.[Number04]
		, src.[Number05]
		, src.[Number06]
		, src.[ContactFirstName]
		, src.[ContactSurname]
		, src.[Date01]
		, src.[Date02]
		, src.[Date03]
		, src.[Date04]
		, src.[LegacyNumber]
		, src.[Country]
		, src.[ContactInfo]
		, src.[AssociatedDocNumber]
		, src.[AssociatedCLIN]
		, src.[SubmittedToAccounting]
		, src.[FuelCardID]
		, src.[AssociatedTransportOrderNumber]
		, src.[RequestedDateTime]
		, src.[DispatchedDateTime]
		, src.[ErrorFlag]
		, src.[TransactionGuid]
		, src.[SiteGuid]
		, src.[LookupTransTypeIndex]
		, src.[LookupTransactionStatusIndex]
		, src.[LookupOriginApplicationIndex]
		, src.[TransactionAliasGuid]
		, src.[BillToCompanyGuid]
		, src.[Destination1EquipmentGuid]
		, src.[Destination2EquipmentGuid]
		, src.[Destination3EquipmentGuid]
		, src.[FinalStationIATAGuid]
		, src.[FuelCardGuid]
		, src.[ManagerCompanyGuid]
		, src.[NextStationIATAGuid]
		, src.[OperatorPersonnelGuid]
		, src.[OriginStationIATAGuid]
		, src.[OwnerCompanyGuid]
		, src.[PreviousStationIATAGuid]
		, src.[ShipperCompanyGuid]
		, src.[ShipToCompanyGuid]
		, src.[Source1EquipmentGuid]
		, src.[Source2EquipmentGuid]
		, src.[Source3EquipmentGuid]
		, src.[SupplierCompanyGuid]
		, src.[CarrierCompanyGuid]
		, src.[ReasonCodeGuid]
		, src.[OriginStationIATAID]
		, src.[PreviousStationIATAID]
		, src.[NextStationIATAID]
		, src.[FinalStationIATAID]
		, src.[OperatorName]
		, src.[FuelAdditiveFlag]
		, src.[IssuePoint]
		, src.[IssuePointNumber]
		, src.[RadioNumber]
		, src.[GateID]
		, src.[GateGuid]
		, src.[ShippingMethod]
		, src.[InventoryDateKey]
		, src.[ArchiveDate]
		, src.[ETLProcessKey]
		FROM staging.tblTransactions src
		INNER JOIN @tblInsertedRecords b
		ON b.RecordGuid = src.TransactionGuid
		WHERE src.TransactionGuid IS NOT NULL
		AND src.IgnoreRecord = 0
		AND src.IsProcessed = 0
 
 
		UPDATE tgt
		SET tgt.[TransID] = src.[TransID]
		, tgt.[AliasName] = src.[AliasName]
		, tgt.[SubType] = src.[SubType]
		, tgt.[Site] = src.[Site]
		, tgt.[TransReferenceID] = src.[TransReferenceID]
		, tgt.[InventoryDate] = src.[InventoryDate]
		, tgt.[ShipToID] = src.[ShipToID]
		, tgt.[ShipToCode] = src.[ShipToCode]
		, tgt.[SupplierID] = src.[SupplierID]
		, tgt.[SupplierCode] = src.[SupplierCode]
		, tgt.[CreatedDate] = src.[CreatedDate]
		, tgt.[CreatedBy] = src.[CreatedBy]
		, tgt.[RequestedDeliveryDate] = src.[RequestedDeliveryDate]
		, tgt.[UpdatedDate] = src.[UpdatedDate]
		, tgt.[UpdatedBy] = src.[UpdatedBy]
		, tgt.[TransDateTime] = src.[TransDateTime]
		, tgt.[TransVersion] = src.[TransVersion]
		, tgt.[SCACCode] = src.[SCACCode]
		, tgt.[CardNumber] = src.[CardNumber]
		, tgt.[ShipmentNumber] = src.[ShipmentNumber]
		, tgt.[ShipperID] = src.[ShipperID]
		, tgt.[ShipperCode] = src.[ShipperCode]
		, tgt.[OwnerID] = src.[OwnerID]
		, tgt.[OwnerCode] = src.[OwnerCode]
		, tgt.[ManagerID] = src.[ManagerID]
		, tgt.[ManagerCode] = src.[ManagerCode]
		, tgt.[CarrierID] = src.[CarrierID]
		, tgt.[CarrierCode] = src.[CarrierCode]
		, tgt.[ConjoinTransID] = src.[ConjoinTransID]
		, tgt.[ReversedTransID] = src.[ReversedTransID]
		, tgt.[LinkedDocumentNumber] = src.[LinkedDocumentNumber]
		, tgt.[ReversalType] = src.[ReversalType]
		, tgt.[PONumber] = src.[PONumber]
		, tgt.[TimeIn] = src.[TimeIn]
		, tgt.[TimeOut] = src.[TimeOut]
		, tgt.[TimeEnd] = src.[TimeEnd]
		, tgt.[RoutingID] = src.[RoutingID]
		, tgt.[TicketSource] = src.[TicketSource]
		, tgt.[LoadID] = src.[LoadID]
		, tgt.[BillToID] = src.[BillToID]
		, tgt.[BillToCode] = src.[BillToCode]
		, tgt.[DriverIdentificationNumber] = src.[DriverIdentificationNumber]
		, tgt.[CreditAmount] = src.[CreditAmount]
		, tgt.[CardExpiration] = src.[CardExpiration]
		, tgt.[CardName] = src.[CardName]
		, tgt.[CardType] = src.[CardType]
		, tgt.[CashAmount] = src.[CashAmount]
		, tgt.[RouteOriginationDate] = src.[RouteOriginationDate]
		, tgt.[InternationalRouteIndicator] = src.[InternationalRouteIndicator]
		, tgt.[PreviousRoutingID] = src.[PreviousRoutingID]
		, tgt.[ShippingDocumentNumber] = src.[ShippingDocumentNumber]
		, tgt.[DocumentNumber] = src.[DocumentNumber]
		, tgt.[STD] = src.[STD]
		, tgt.[ETD] = src.[ETD]
		, tgt.[STA] = src.[STA]
		, tgt.[ETA] = src.[ETA]
		, tgt.[SFT] = src.[SFT]
		, tgt.[FST] = src.[FST]
		, tgt.[EstimatedFuelingDuration] = src.[EstimatedFuelingDuration]
		, tgt.[DeleteFlag] = src.[DeleteFlag]
		, tgt.[TicketMode] = src.[TicketMode]
		, tgt.[DestinationRegistrationID1] = src.[DestinationRegistrationID1]
		, tgt.[DestinationSerialNumber1] = src.[DestinationSerialNumber1]
		, tgt.[DestinationEquipmentType1] = src.[DestinationEquipmentType1]
		, tgt.[DestinationEquipmentModel1] = src.[DestinationEquipmentModel1]
		, tgt.[DestinationCompanyEquipmentID1] = src.[DestinationCompanyEquipmentID1]
		, tgt.[DestinationRegistrationID2] = src.[DestinationRegistrationID2]
		, tgt.[DestinationSerialNumber2] = src.[DestinationSerialNumber2]
		, tgt.[DestinationEquipmentType2] = src.[DestinationEquipmentType2]
		, tgt.[DestinationEquipmentModel2] = src.[DestinationEquipmentModel2]
		, tgt.[DestinationCompanyEquipmentID2] = src.[DestinationCompanyEquipmentID2]
		, tgt.[DestinationRegistrationID3] = src.[DestinationRegistrationID3]
		, tgt.[DestinationSerialNumber3] = src.[DestinationSerialNumber3]
		, tgt.[DestinationEquipmentType3] = src.[DestinationEquipmentType3]
		, tgt.[DestinationEquipmentModel3] = src.[DestinationEquipmentModel3]
		, tgt.[DestinationCompanyEquipmentID3] = src.[DestinationCompanyEquipmentID3]
		, tgt.[SourceRegistrationID1] = src.[SourceRegistrationID1]
		, tgt.[SourceSerialNumber1] = src.[SourceSerialNumber1]
		, tgt.[SourceEquipmentType1] = src.[SourceEquipmentType1]
		, tgt.[SourceEquipmentModel1] = src.[SourceEquipmentModel1]
		, tgt.[SourceCompanyEquipmentID1] = src.[SourceCompanyEquipmentID1]
		, tgt.[SourceRegistrationID2] = src.[SourceRegistrationID2]
		, tgt.[SourceSerialNumber2] = src.[SourceSerialNumber2]
		, tgt.[SourceEquipmentType2] = src.[SourceEquipmentType2]
		, tgt.[SourceEquipmentModel2] = src.[SourceEquipmentModel2]
		, tgt.[SourceCompanyEquipmentID2] = src.[SourceCompanyEquipmentID2]
		, tgt.[SourceRegistrationID3] = src.[SourceRegistrationID3]
		, tgt.[SourceSerialNumber3] = src.[SourceSerialNumber3]
		, tgt.[SourceEquipmentType3] = src.[SourceEquipmentType3]
		, tgt.[SourceEquipmentModel3] = src.[SourceEquipmentModel3]
		, tgt.[SourceCompanyEquipmentID3] = src.[SourceCompanyEquipmentID3]
		, tgt.[OperatorID] = src.[OperatorID]
		, tgt.[EffectiveDate] = src.[EffectiveDate]
		, tgt.[ExpirationDate] = src.[ExpirationDate]
		, tgt.[ScheduledDate] = src.[ScheduledDate]
		, tgt.[AutoComplete] = src.[AutoComplete]
		, tgt.[Flag01] = src.[Flag01]
		, tgt.[Flag02] = src.[Flag02]
		, tgt.[Flag03] = src.[Flag03]
		, tgt.[Flag04] = src.[Flag04]
		, tgt.[Flag05] = src.[Flag05]
		, tgt.[Flag06] = src.[Flag06]
		, tgt.[Number01] = src.[Number01]
		, tgt.[Number02] = src.[Number02]
		, tgt.[Number03] = src.[Number03]
		, tgt.[Number04] = src.[Number04]
		, tgt.[Number05] = src.[Number05]
		, tgt.[Number06] = src.[Number06]
		, tgt.[ContactFirstName] = src.[ContactFirstName]
		, tgt.[ContactSurname] = src.[ContactSurname]
		, tgt.[Date01] = src.[Date01]
		, tgt.[Date02] = src.[Date02]
		, tgt.[Date03] = src.[Date03]
		, tgt.[Date04] = src.[Date04]
		, tgt.[LegacyNumber] = src.[LegacyNumber]
		, tgt.[Country] = src.[Country]
		, tgt.[ContactInfo] = src.[ContactInfo]
		, tgt.[AssociatedDocNumber] = src.[AssociatedDocNumber]
		, tgt.[AssociatedCLIN] = src.[AssociatedCLIN]
		, tgt.[SubmittedToAccounting] = src.[SubmittedToAccounting]
		, tgt.[FuelCardID] = src.[FuelCardID]
		, tgt.[AssociatedTransportOrderNumber] = src.[AssociatedTransportOrderNumber]
		, tgt.[RequestedDateTime] = src.[RequestedDateTime]
		, tgt.[DispatchedDateTime] = src.[DispatchedDateTime]
		, tgt.[ErrorFlag] = src.[ErrorFlag]
		, tgt.[TransactionGuid] = src.[TransactionGuid]
		, tgt.[SiteGuid] = src.[SiteGuid]
		, tgt.[LookupTransTypeIndex] = src.[LookupTransTypeIndex]
		, tgt.[LookupTransactionStatusIndex] = src.[LookupTransactionStatusIndex]
		, tgt.[LookupOriginApplicationIndex] = src.[LookupOriginApplicationIndex]
		, tgt.[TransactionAliasGuid] = src.[TransactionAliasGuid]
		, tgt.[BillToCompanyGuid] = src.[BillToCompanyGuid]
		, tgt.[Destination1EquipmentGuid] = src.[Destination1EquipmentGuid]
		, tgt.[Destination2EquipmentGuid] = src.[Destination2EquipmentGuid]
		, tgt.[Destination3EquipmentGuid] = src.[Destination3EquipmentGuid]
		, tgt.[FinalStationIATAGuid] = src.[FinalStationIATAGuid]
		, tgt.[FuelCardGuid] = src.[FuelCardGuid]
		, tgt.[ManagerCompanyGuid] = src.[ManagerCompanyGuid]
		, tgt.[NextStationIATAGuid] = src.[NextStationIATAGuid]
		, tgt.[OperatorPersonnelGuid] = src.[OperatorPersonnelGuid]
		, tgt.[OriginStationIATAGuid] = src.[OriginStationIATAGuid]
		, tgt.[OwnerCompanyGuid] = src.[OwnerCompanyGuid]
		, tgt.[PreviousStationIATAGuid] = src.[PreviousStationIATAGuid]
		, tgt.[ShipperCompanyGuid] = src.[ShipperCompanyGuid]
		, tgt.[ShipToCompanyGuid] = src.[ShipToCompanyGuid]
		, tgt.[Source1EquipmentGuid] = src.[Source1EquipmentGuid]
		, tgt.[Source2EquipmentGuid] = src.[Source2EquipmentGuid]
		, tgt.[Source3EquipmentGuid] = src.[Source3EquipmentGuid]
		, tgt.[SupplierCompanyGuid] = src.[SupplierCompanyGuid]
		, tgt.[CarrierCompanyGuid] = src.[CarrierCompanyGuid]
		, tgt.[ReasonCodeGuid] = src.[ReasonCodeGuid]
		, tgt.[OriginStationIATAID] = src.[OriginStationIATAID]
		, tgt.[PreviousStationIATAID] = src.[PreviousStationIATAID]
		, tgt.[NextStationIATAID] = src.[NextStationIATAID]
		, tgt.[FinalStationIATAID] = src.[FinalStationIATAID]
		, tgt.[OperatorName] = src.[OperatorName]
		, tgt.[FuelAdditiveFlag] = src.[FuelAdditiveFlag]
		, tgt.[IssuePoint] = src.[IssuePoint]
		, tgt.[IssuePointNumber] = src.[IssuePointNumber]
		, tgt.[RadioNumber] = src.[RadioNumber]
		, tgt.[GateID] = src.[GateID]
		, tgt.[GateGuid] = src.[GateGuid]
		, tgt.[ShippingMethod] = src.[ShippingMethod]
		, tgt.[InventoryDateKey] = src.[InventoryDateKey]
		, tgt.[ArchiveDate] = src.[ArchiveDate]
		, tgt.[ETLProcessKey] = src.[ETLProcessKey]
		FROM [dbo].[tblTransactions] tgt
		INNER JOIN staging.tblTransactions src
		ON src.TransactionGuid = tgt.TransactionGuid
		INNER JOIN @tblUpdatedRecords b
		ON b.RecordGuid = src.TransactionGuid
		WHERE src.TransactionGuid IS NOT NULL
		AND src.IgnoreRecord = 0
		AND src.IsProcessed = 0
 
 
		UPDATE staging.tblTransactions SET IsProcessed = 1
 
		INSERT INTO staging.tblInsertedRecords
		(TargetTableName, RecordGuid, RecordIndex, ParentRecordGuid)
		SELECT '[dbo].[tblTransactions]', RecordGuid, RecordIndex, ParentRecordGuid
		FROM @tblInsertedRecords
 
		INSERT INTO staging.tblUpdatedRecords
		(TargetTableName, RecordGuid, RecordIndex, ParentRecordGuid)
		SELECT '[dbo].[tblTransactions]', RecordGuid, RecordIndex, ParentRecordGuid
		FROM @tblUpdatedRecords
 
	END TRY
	BEGIN CATCH
		DECLARE @_ErrMessage nvarchar(2048),
		@_ErrNumber int,
		@_ErrProcName nvarchar(126),
		@_ErrLineNumber int;
		SET @_ErrMessage = ERROR_MESSAGE();
		SET @_ErrNumber = ERROR_NUMBER();
		SET @_ErrProcName = ERROR_PROCEDURE();
		SET @_ErrLineNumber = ERROR_LINE();
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13) + CHAR(10)
		+ 'Number: ' + CAST(@_ErrNumber AS varchar(20)) + CHAR(13) + CHAR(10)
		+ 'Procedure Name: [staging].[usp_LoadTransactionHeaders]' + CHAR(13) + CHAR(10)
		+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS varchar(20)), '') + CHAR(13) + CHAR(10);
		RAISERROR (@_ErrMessage, 16, 1);
	END CATCH
END
