/*
	DROP PROCEDURE [Staging].[usp_LoadTransactionLineItems]
 
	EXEC [staging].[usp_LoadTransactionLineItems]
 
*/
CREATE PROCEDURE [staging].[usp_LoadTransactionLineItems]
AS
BEGIN
------------------------------------------------------------------------------------------------------
-- Stored procedure: [staging].[usp_LoadTransactionLineItems]
-- Author: Hansraj Bapoo
-- Version/Date: 1.0.003 / 2012-07-13 14:21:10.4470770 -04:00
-- Purpose: Loads all the TransactionLineItems records from staging into the tblTransactionLineItems table in the Archive database.
-- Notes:
-- 1. This operation assumes that no referential integrity or dependencies are enforced on the tblTransactionLineItems table.
------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
 
		IF (
			(	SELECT COUNT(*) FROM staging.tblTransactionLineItems
				WHERE IsProcessed = 0
			) = 0)
		BEGIN
			RETURN
		END
 
	DECLARE @tblInsertedRecords TABLE
	(
		[SKey] [int] IDENTITY(1,1) NOT NULL,
		[RecordGuid] [uniqueidentifier] NOT NULL,
		[RecordIndex] [bigint] NOT NULL,
		[ParentRecordGuid] [uniqueidentifier] NULL
	)
 
	DECLARE @tblUpdatedRecords TABLE
	(
		[SKey] [int] IDENTITY(1,1) NOT NULL,
		[RecordGuid] [uniqueidentifier] NOT NULL,
		[RecordIndex] [bigint] NOT NULL,
		[ParentRecordGuid] [uniqueidentifier] NULL
	)
 
		INSERT INTO @tblUpdatedRecords ([RecordGuid], [RecordIndex], [ParentRecordGuid])
		SELECT src.[TransactionLineItemGuid], src.[SourceClusterIdx], src.[TransactionGuid]
		FROM staging.tblTransactionLineItems src
		WHERE src.TransactionLineItemGuid IS NOT NULL
		AND src.IsProcessed = 0
		AND src.IgnoreRecord = 0
		AND EXISTS
		(
			SELECT * FROM [dbo].[tblTransactionLineItems] tgt
			WHERE tgt.TransactionLineItemGuid = src.TransactionLineItemGuid
		)
 
 
		INSERT INTO @tblInsertedRecords ([RecordGuid], [RecordIndex], [ParentRecordGuid])
		SELECT src.[TransactionLineItemGuid], src.[SourceClusterIdx], src.[TransactionGuid]
		FROM staging.tblTransactionLineItems src
		WHERE src.TransactionLineItemGuid IS NOT NULL
		AND src.IsProcessed = 0
		AND src.IgnoreRecord = 0
		AND NOT EXISTS
		(
			SELECT * FROM [dbo].[tblTransactionLineItems] tgt
			WHERE tgt.TransactionLineItemGuid = src.TransactionLineItemGuid
		)
 
 
		INSERT INTO [dbo].[tblTransactionLineItems]
		(
		[SequenceID]
		, [MeterStart]
		, [MeterStop]
		, [GrossQuantity]
		, [Temperature]
		, [Vcf]
		, [Density]
		, [Product]
		, [ProductCode]
		, [ProductType]
		, [ProductPrice]
		, [CLIN]
		, [NetQuantity]
		, [ContractNumber]
		, [DestinationRegistrationID]
		, [DestinationSerialNumber]
		, [DestinationEquipmentType]
		, [DestinationEquipmentModel]
		, [DestinationCompanyEquipmentID]
		, [DestinationCompartmentID]
		, [SourceRegistrationID]
		, [SourceSerialNumber]
		, [SourceEquipmentType]
		, [SourceEquipmentModel]
		, [SourceCompanyEquipmentID]
		, [SourceCompartmentID]
		, [MeterFactor]
		, [LineItemSequenceNumber]
		, [BatchNumber]
		, [DocumentNumber]
		, [LineFill]
		, [BottomVolume]
		, [NetCapacity]
		, [Customs]
		, [ArmNumber]
		, [LineNumber]
		, [OperatorID]
		, [TankStatus]
		, [MeterStartDateTime]
		, [MeterStopDateTime]
		, [Pit]
		, [RequestedDateTime]
		, [DispatchedDateTime]
		, [AcknowledgedDateTime]
		, [OnLocationTime]
		, [ValidationDateTime]
		, [CompletionDateTime]
		, [ReceiptVariance]
		, [DifferentialPressure]
		, [LoadRackVariance]
		, [RequestedBy]
		, [FreezePoint]
		, [DeleteFlag]
		, [StorageLocationID]
		, [MeterID]
		, [AdditiveProfileID]
		, [CreatedBy]
		, [CreatedDate]
		, [UpdatedBy]
		, [UpdatedDate]
		, [PresetAmount]
		, [EngineeringUnitsIndex]
		, [CustomerProductName]
		, [CustomerProductCode]
		, [TransactionInventoryDate]
		, [COAWaiver]
		, [COANote]
		, [COAID]
		, [Tax1]
		, [Tax2]
		, [Tax3]
		, [Tax4]
		, [Tax5]
		, [TransVersion]
		, [LoadingLocationID]
		, [ImproperAdditization]
		, [BrokenBlend]
		, [ContaminatePrompt]
		, [CompartmentsPreviouslyLoaded]
		, [CompartmentsEmpty]
		, [Flag01]
		, [Flag02]
		, [Flag03]
		, [Flag04]
		, [Flag05]
		, [Flag06]
		, [Number01]
		, [Number02]
		, [Number03]
		, [Number04]
		, [Number05]
		, [Number06]
		, [OdometerHours]
		, [EndDeliveryDate]
		, [RequestedDeliveryDate]
		, [InvoiceNumber]
		, [InvoiceLineNumber]
		, [AlternativeGrossVolume]
		, [AlternativeNetVolume]
		, [AlternativeUnits]
		, [TankLevel]
		, [TankLevelUnits]
		, [Date01]
		, [Date02]
		, [Date03]
		, [Date04]
		, [NonDomesticPrice]
		, [CurrencyUnit]
		, [ExchangeRate]
		, [QualityTestNumber]
		, [Odometer]
		, [DeliveryLocation]
		, [Variance]
		, [PartialFill]
		, [MassQuantity]
		, [NetManualValueFlag]
		, [MassManualValueFlag]
		, [GrossManualValueFlag]
		, [VcfManualValueFlag]
		, [TransactionLineItemGuid]
		, [LookupTransactionStatusIndex]
		, [LookupQualityIndex]
		, [StorageLocationTankGuid]
		, [AdditiveProfileGuid]
		, [DestinationCompartmentEquipmentGuid]
		, [DestinationEquipmentGuid]
		, [OperatorPersonnelGuid]
		, [ProductGuid]
		, [SourceCompartmentEquipmentGuid]
		, [SourceEquipmentGuid]
		, [TransactionGuid]
		, [CurrencyGuid]
		, [OrderReferenceTransactionLineItemGuid]
		, [LoadingLocationStationGuid]
		, [MeterGuid]
		, [PackageManualValueFlag]
		, [CleanLineItem]
		, [CleanLineDeductItem]
		, [CleanLineDeductQuantity]
		, [CleanLinePackQuantity]
		, [DualFuelingModeFlag]
		, [DualFuelingPrimaryFlag]
		, [EngineRunTime]
		, [FlowRate]
		, [FuelCompressionFactor]
		, [HydrantPressure]
		, [MobileDeviceID]
		, [MobileDeviceGuid]
		, [TemperatureQualityStatus]
		, [MeterStartObtainedAutomaticallyFlag]
		, [MeterStopObtainedAutomaticallyFlag]
		, [InventoryDateKey]
		, [ArchiveDate]
		, [ETLProcessKey]
		)
		SELECT
		src.[SequenceID]
		, src.[MeterStart]
		, src.[MeterStop]
		, src.[GrossQuantity]
		, src.[Temperature]
		, src.[Vcf]
		, src.[Density]
		, src.[Product]
		, src.[ProductCode]
		, src.[ProductType]
		, src.[ProductPrice]
		, src.[CLIN]
		, src.[NetQuantity]
		, src.[ContractNumber]
		, src.[DestinationRegistrationID]
		, src.[DestinationSerialNumber]
		, src.[DestinationEquipmentType]
		, src.[DestinationEquipmentModel]
		, src.[DestinationCompanyEquipmentID]
		, src.[DestinationCompartmentID]
		, src.[SourceRegistrationID]
		, src.[SourceSerialNumber]
		, src.[SourceEquipmentType]
		, src.[SourceEquipmentModel]
		, src.[SourceCompanyEquipmentID]
		, src.[SourceCompartmentID]
		, src.[MeterFactor]
		, src.[LineItemSequenceNumber]
		, src.[BatchNumber]
		, src.[DocumentNumber]
		, src.[LineFill]
		, src.[BottomVolume]
		, src.[NetCapacity]
		, src.[Customs]
		, src.[ArmNumber]
		, src.[LineNumber]
		, src.[OperatorID]
		, src.[TankStatus]
		, src.[MeterStartDateTime]
		, src.[MeterStopDateTime]
		, src.[Pit]
		, src.[RequestedDateTime]
		, src.[DispatchedDateTime]
		, src.[AcknowledgedDateTime]
		, src.[OnLocationTime]
		, src.[ValidationDateTime]
		, src.[CompletionDateTime]
		, src.[ReceiptVariance]
		, src.[DifferentialPressure]
		, src.[LoadRackVariance]
		, src.[RequestedBy]
		, src.[FreezePoint]
		, src.[DeleteFlag]
		, src.[StorageLocationID]
		, src.[MeterID]
		, src.[AdditiveProfileID]
		, src.[CreatedBy]
		, src.[CreatedDate]
		, src.[UpdatedBy]
		, src.[UpdatedDate]
		, src.[PresetAmount]
		, src.[EngineeringUnitsIndex]
		, src.[CustomerProductName]
		, src.[CustomerProductCode]
		, src.[TransactionInventoryDate]
		, src.[COAWaiver]
		, src.[COANote]
		, src.[COAID]
		, src.[Tax1]
		, src.[Tax2]
		, src.[Tax3]
		, src.[Tax4]
		, src.[Tax5]
		, src.[TransVersion]
		, src.[LoadingLocationID]
		, src.[ImproperAdditization]
		, src.[BrokenBlend]
		, src.[ContaminatePrompt]
		, src.[CompartmentsPreviouslyLoaded]
		, src.[CompartmentsEmpty]
		, src.[Flag01]
		, src.[Flag02]
		, src.[Flag03]
		, src.[Flag04]
		, src.[Flag05]
		, src.[Flag06]
		, src.[Number01]
		, src.[Number02]
		, src.[Number03]
		, src.[Number04]
		, src.[Number05]
		, src.[Number06]
		, src.[OdometerHours]
		, src.[EndDeliveryDate]
		, src.[RequestedDeliveryDate]
		, src.[InvoiceNumber]
		, src.[InvoiceLineNumber]
		, src.[AlternativeGrossVolume]
		, src.[AlternativeNetVolume]
		, src.[AlternativeUnits]
		, src.[TankLevel]
		, src.[TankLevelUnits]
		, src.[Date01]
		, src.[Date02]
		, src.[Date03]
		, src.[Date04]
		, src.[NonDomesticPrice]
		, src.[CurrencyUnit]
		, src.[ExchangeRate]
		, src.[QualityTestNumber]
		, src.[Odometer]
		, src.[DeliveryLocation]
		, src.[Variance]
		, src.[PartialFill]
		, src.[MassQuantity]
		, src.[NetManualValueFlag]
		, src.[MassManualValueFlag]
		, src.[GrossManualValueFlag]
		, src.[VcfManualValueFlag]
		, src.[TransactionLineItemGuid]
		, src.[LookupTransactionStatusIndex]
		, src.[LookupQualityIndex]
		, src.[StorageLocationTankGuid]
		, src.[AdditiveProfileGuid]
		, src.[DestinationCompartmentEquipmentGuid]
		, src.[DestinationEquipmentGuid]
		, src.[OperatorPersonnelGuid]
		, src.[ProductGuid]
		, src.[SourceCompartmentEquipmentGuid]
		, src.[SourceEquipmentGuid]
		, src.[TransactionGuid]
		, src.[CurrencyGuid]
		, src.[OrderReferenceTransactionLineItemGuid]
		, src.[LoadingLocationStationGuid]
		, src.[MeterGuid]
		, src.[PackageManualValueFlag]
		, src.[CleanLineItem]
		, src.[CleanLineDeductItem]
		, src.[CleanLineDeductQuantity]
		, src.[CleanLinePackQuantity]
		, src.[DualFuelingModeFlag]
		, src.[DualFuelingPrimaryFlag]
		, src.[EngineRunTime]
		, src.[FlowRate]
		, src.[FuelCompressionFactor]
		, src.[HydrantPressure]
		, src.[MobileDeviceID]
		, src.[MobileDeviceGuid]
		, src.[TemperatureQualityStatus]
		, src.[MeterStartObtainedAutomaticallyFlag]
		, src.[MeterStopObtainedAutomaticallyFlag]
		, src.[InventoryDateKey]
		, src.[ArchiveDate]
		, src.[ETLProcessKey]
		FROM staging.tblTransactionLineItems src
		INNER JOIN @tblInsertedRecords b
		ON b.RecordGuid = src.TransactionLineItemGuid
		WHERE src.TransactionLineItemGuid IS NOT NULL
		AND src.IgnoreRecord = 0
		AND src.IsProcessed = 0
 
 
		UPDATE tgt
		SET tgt.[SequenceID] = src.[SequenceID]
		, tgt.[MeterStart] = src.[MeterStart]
		, tgt.[MeterStop] = src.[MeterStop]
		, tgt.[GrossQuantity] = src.[GrossQuantity]
		, tgt.[Temperature] = src.[Temperature]
		, tgt.[Vcf] = src.[Vcf]
		, tgt.[Density] = src.[Density]
		, tgt.[Product] = src.[Product]
		, tgt.[ProductCode] = src.[ProductCode]
		, tgt.[ProductType] = src.[ProductType]
		, tgt.[ProductPrice] = src.[ProductPrice]
		, tgt.[CLIN] = src.[CLIN]
		, tgt.[NetQuantity] = src.[NetQuantity]
		, tgt.[ContractNumber] = src.[ContractNumber]
		, tgt.[DestinationRegistrationID] = src.[DestinationRegistrationID]
		, tgt.[DestinationSerialNumber] = src.[DestinationSerialNumber]
		, tgt.[DestinationEquipmentType] = src.[DestinationEquipmentType]
		, tgt.[DestinationEquipmentModel] = src.[DestinationEquipmentModel]
		, tgt.[DestinationCompanyEquipmentID] = src.[DestinationCompanyEquipmentID]
		, tgt.[DestinationCompartmentID] = src.[DestinationCompartmentID]
		, tgt.[SourceRegistrationID] = src.[SourceRegistrationID]
		, tgt.[SourceSerialNumber] = src.[SourceSerialNumber]
		, tgt.[SourceEquipmentType] = src.[SourceEquipmentType]
		, tgt.[SourceEquipmentModel] = src.[SourceEquipmentModel]
		, tgt.[SourceCompanyEquipmentID] = src.[SourceCompanyEquipmentID]
		, tgt.[SourceCompartmentID] = src.[SourceCompartmentID]
		, tgt.[MeterFactor] = src.[MeterFactor]
		, tgt.[LineItemSequenceNumber] = src.[LineItemSequenceNumber]
		, tgt.[BatchNumber] = src.[BatchNumber]
		, tgt.[DocumentNumber] = src.[DocumentNumber]
		, tgt.[LineFill] = src.[LineFill]
		, tgt.[BottomVolume] = src.[BottomVolume]
		, tgt.[NetCapacity] = src.[NetCapacity]
		, tgt.[Customs] = src.[Customs]
		, tgt.[ArmNumber] = src.[ArmNumber]
		, tgt.[LineNumber] = src.[LineNumber]
		, tgt.[OperatorID] = src.[OperatorID]
		, tgt.[TankStatus] = src.[TankStatus]
		, tgt.[MeterStartDateTime] = src.[MeterStartDateTime]
		, tgt.[MeterStopDateTime] = src.[MeterStopDateTime]
		, tgt.[Pit] = src.[Pit]
		, tgt.[RequestedDateTime] = src.[RequestedDateTime]
		, tgt.[DispatchedDateTime] = src.[DispatchedDateTime]
		, tgt.[AcknowledgedDateTime] = src.[AcknowledgedDateTime]
		, tgt.[OnLocationTime] = src.[OnLocationTime]
		, tgt.[ValidationDateTime] = src.[ValidationDateTime]
		, tgt.[CompletionDateTime] = src.[CompletionDateTime]
		, tgt.[ReceiptVariance] = src.[ReceiptVariance]
		, tgt.[DifferentialPressure] = src.[DifferentialPressure]
		, tgt.[LoadRackVariance] = src.[LoadRackVariance]
		, tgt.[RequestedBy] = src.[RequestedBy]
		, tgt.[FreezePoint] = src.[FreezePoint]
		, tgt.[DeleteFlag] = src.[DeleteFlag]
		, tgt.[StorageLocationID] = src.[StorageLocationID]
		, tgt.[MeterID] = src.[MeterID]
		, tgt.[AdditiveProfileID] = src.[AdditiveProfileID]
		, tgt.[CreatedBy] = src.[CreatedBy]
		, tgt.[CreatedDate] = src.[CreatedDate]
		, tgt.[UpdatedBy] = src.[UpdatedBy]
		, tgt.[UpdatedDate] = src.[UpdatedDate]
		, tgt.[PresetAmount] = src.[PresetAmount]
		, tgt.[EngineeringUnitsIndex] = src.[EngineeringUnitsIndex]
		, tgt.[CustomerProductName] = src.[CustomerProductName]
		, tgt.[CustomerProductCode] = src.[CustomerProductCode]
		, tgt.[TransactionInventoryDate] = src.[TransactionInventoryDate]
		, tgt.[COAWaiver] = src.[COAWaiver]
		, tgt.[COANote] = src.[COANote]
		, tgt.[COAID] = src.[COAID]
		, tgt.[Tax1] = src.[Tax1]
		, tgt.[Tax2] = src.[Tax2]
		, tgt.[Tax3] = src.[Tax3]
		, tgt.[Tax4] = src.[Tax4]
		, tgt.[Tax5] = src.[Tax5]
		, tgt.[TransVersion] = src.[TransVersion]
		, tgt.[LoadingLocationID] = src.[LoadingLocationID]
		, tgt.[ImproperAdditization] = src.[ImproperAdditization]
		, tgt.[BrokenBlend] = src.[BrokenBlend]
		, tgt.[ContaminatePrompt] = src.[ContaminatePrompt]
		, tgt.[CompartmentsPreviouslyLoaded] = src.[CompartmentsPreviouslyLoaded]
		, tgt.[CompartmentsEmpty] = src.[CompartmentsEmpty]
		, tgt.[Flag01] = src.[Flag01]
		, tgt.[Flag02] = src.[Flag02]
		, tgt.[Flag03] = src.[Flag03]
		, tgt.[Flag04] = src.[Flag04]
		, tgt.[Flag05] = src.[Flag05]
		, tgt.[Flag06] = src.[Flag06]
		, tgt.[Number01] = src.[Number01]
		, tgt.[Number02] = src.[Number02]
		, tgt.[Number03] = src.[Number03]
		, tgt.[Number04] = src.[Number04]
		, tgt.[Number05] = src.[Number05]
		, tgt.[Number06] = src.[Number06]
		, tgt.[OdometerHours] = src.[OdometerHours]
		, tgt.[EndDeliveryDate] = src.[EndDeliveryDate]
		, tgt.[RequestedDeliveryDate] = src.[RequestedDeliveryDate]
		, tgt.[InvoiceNumber] = src.[InvoiceNumber]
		, tgt.[InvoiceLineNumber] = src.[InvoiceLineNumber]
		, tgt.[AlternativeGrossVolume] = src.[AlternativeGrossVolume]
		, tgt.[AlternativeNetVolume] = src.[AlternativeNetVolume]
		, tgt.[AlternativeUnits] = src.[AlternativeUnits]
		, tgt.[TankLevel] = src.[TankLevel]
		, tgt.[TankLevelUnits] = src.[TankLevelUnits]
		, tgt.[Date01] = src.[Date01]
		, tgt.[Date02] = src.[Date02]
		, tgt.[Date03] = src.[Date03]
		, tgt.[Date04] = src.[Date04]
		, tgt.[NonDomesticPrice] = src.[NonDomesticPrice]
		, tgt.[CurrencyUnit] = src.[CurrencyUnit]
		, tgt.[ExchangeRate] = src.[ExchangeRate]
		, tgt.[QualityTestNumber] = src.[QualityTestNumber]
		, tgt.[Odometer] = src.[Odometer]
		, tgt.[DeliveryLocation] = src.[DeliveryLocation]
		, tgt.[Variance] = src.[Variance]
		, tgt.[PartialFill] = src.[PartialFill]
		, tgt.[MassQuantity] = src.[MassQuantity]
		, tgt.[NetManualValueFlag] = src.[NetManualValueFlag]
		, tgt.[MassManualValueFlag] = src.[MassManualValueFlag]
		, tgt.[GrossManualValueFlag] = src.[GrossManualValueFlag]
		, tgt.[VcfManualValueFlag] = src.[VcfManualValueFlag]
		, tgt.[TransactionLineItemGuid] = src.[TransactionLineItemGuid]
		, tgt.[LookupTransactionStatusIndex] = src.[LookupTransactionStatusIndex]
		, tgt.[LookupQualityIndex] = src.[LookupQualityIndex]
		, tgt.[StorageLocationTankGuid] = src.[StorageLocationTankGuid]
		, tgt.[AdditiveProfileGuid] = src.[AdditiveProfileGuid]
		, tgt.[DestinationCompartmentEquipmentGuid] = src.[DestinationCompartmentEquipmentGuid]
		, tgt.[DestinationEquipmentGuid] = src.[DestinationEquipmentGuid]
		, tgt.[OperatorPersonnelGuid] = src.[OperatorPersonnelGuid]
		, tgt.[ProductGuid] = src.[ProductGuid]
		, tgt.[SourceCompartmentEquipmentGuid] = src.[SourceCompartmentEquipmentGuid]
		, tgt.[SourceEquipmentGuid] = src.[SourceEquipmentGuid]
		, tgt.[TransactionGuid] = src.[TransactionGuid]
		, tgt.[CurrencyGuid] = src.[CurrencyGuid]
		, tgt.[OrderReferenceTransactionLineItemGuid] = src.[OrderReferenceTransactionLineItemGuid]
		, tgt.[LoadingLocationStationGuid] = src.[LoadingLocationStationGuid]
		, tgt.[MeterGuid] = src.[MeterGuid]
		, tgt.[PackageManualValueFlag] = src.[PackageManualValueFlag]
		, tgt.[CleanLineItem] = src.[CleanLineItem]
		, tgt.[CleanLineDeductItem] = src.[CleanLineDeductItem]
		, tgt.[CleanLineDeductQuantity] = src.[CleanLineDeductQuantity]
		, tgt.[CleanLinePackQuantity] = src.[CleanLinePackQuantity]
		, tgt.[DualFuelingModeFlag] = src.[DualFuelingModeFlag]
		, tgt.[DualFuelingPrimaryFlag] = src.[DualFuelingPrimaryFlag]
		, tgt.[EngineRunTime] = src.[EngineRunTime]
		, tgt.[FlowRate] = src.[FlowRate]
		, tgt.[FuelCompressionFactor] = src.[FuelCompressionFactor]
		, tgt.[HydrantPressure] = src.[HydrantPressure]
		, tgt.[MobileDeviceID] = src.[MobileDeviceID]
		, tgt.[MobileDeviceGuid] = src.[MobileDeviceGuid]
		, tgt.[TemperatureQualityStatus] = src.[TemperatureQualityStatus]
		, tgt.[MeterStartObtainedAutomaticallyFlag] = src.[MeterStartObtainedAutomaticallyFlag]
		, tgt.[MeterStopObtainedAutomaticallyFlag] = src.[MeterStopObtainedAutomaticallyFlag]
		, tgt.[InventoryDateKey] = src.[InventoryDateKey]
		, tgt.[ArchiveDate] = src.[ArchiveDate]
		, tgt.[ETLProcessKey] = src.[ETLProcessKey]
		FROM [dbo].[tblTransactionLineItems] tgt
		INNER JOIN staging.tblTransactionLineItems src
		ON src.TransactionLineItemGuid = tgt.TransactionLineItemGuid
		INNER JOIN @tblUpdatedRecords b
		ON b.RecordGuid = src.TransactionLineItemGuid
		WHERE src.TransactionLineItemGuid IS NOT NULL
		AND src.IgnoreRecord = 0
		AND src.IsProcessed = 0
 
 
		UPDATE staging.tblTransactionLineItems SET IsProcessed = 1
 
		INSERT INTO staging.tblInsertedRecords
		(TargetTableName, RecordGuid, RecordIndex, ParentRecordGuid)
		SELECT '[dbo].[tblTransactionLineItems]', RecordGuid, RecordIndex, ParentRecordGuid
		FROM @tblInsertedRecords
 
		INSERT INTO staging.tblUpdatedRecords
		(TargetTableName, RecordGuid, RecordIndex, ParentRecordGuid)
		SELECT '[dbo].[tblTransactionLineItems]', RecordGuid, RecordIndex, ParentRecordGuid
		FROM @tblUpdatedRecords
 
	END TRY
	BEGIN CATCH
		DECLARE @_ErrMessage nvarchar(2048),
		@_ErrNumber int,
		@_ErrProcName nvarchar(126),
		@_ErrLineNumber int;
		SET @_ErrMessage = ERROR_MESSAGE();
		SET @_ErrNumber = ERROR_NUMBER();
		SET @_ErrProcName = ERROR_PROCEDURE();
		SET @_ErrLineNumber = ERROR_LINE();
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13) + CHAR(10)
		+ 'Number: ' + CAST(@_ErrNumber AS varchar(20)) + CHAR(13) + CHAR(10)
		+ 'Procedure Name: [staging].[usp_LoadTransactionLineItems]' + CHAR(13) + CHAR(10)
		+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS varchar(20)), '') + CHAR(13) + CHAR(10);
		RAISERROR (@_ErrMessage, 16, 1);
	END CATCH
END
