//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DanielOPCServer.rc
//
#define IDS_PROJNAME                    100
#define IDR_DANIELOPCSERVER             101
#define IDS_VENDOR_INFO                 101
#define IDR_DATAACCESS                  102
#define IDS_ERROR_PORT_EXISTS           102
#define IDR_DANLOADS                    103
#define IDS_ERROR_PORT_NOT_FOUND        103
#define IDR_PORTS                       104
#define IDS_STARTED                     104
#define IDR_OPCSERVER                   105
#define IDS_HARDWARE_KEY_FAILURE        105
#define IDS_STOPPED                     106
#define IDS_ERROR_ID_REQUIRED           107
#define IDS_ERROR_DANLOAD_EXISTS        108
#define IDS_ERROR_DANLOAD_NOT_FOUND     109
#define IDS_STATUS                      110
#define IDS_PRIMARY_ALARM               111
#define IDS_PASS_CODE_ENTRY_IN_PROGRESS 112
#define IDS_OPERATION_TIMEDOUT          113
#define IDS_RECIPE_SELECTED             114
#define IDS_ADDITIVES_SELECTED          115
#define IDS_PRESET_ENTERED              116
#define IDS_KEYPAD_DATA_AVAILABLE       117
#define IDS_PROGRAM_CODE_CHANGED        118
#define IDS_TRANSACTION_IN_PROGRESS     119
#define IDS_BATCH_IN_PROGRESS           120
#define IDS_KEY_PRESSED                 121
#define IDS_TRANSACTION_ENDED           122
#define IDS_BATCH_COMPLTE               123
#define IDS_BATCH_ABORTED               124
#define IDS_INTERMEDIATE_ALARM_STOPPEd_BATCH 125
#define IDS_INTERMEDIATE_ALARM_STOPPED_BATCH 125
#define IDS_INTERMEDIATE_ALARM_STOPPEd_BATCH 125
#define IDS_MANUAL                      126
#define IDS_BATCH_AUTHORIZED            127
#define IDS_TRANSACTION_AUTHORIZED      128
#define IDS_TRANSACTION_END_REQUESTED   129
#define IDS_BATCH_ENDED                 130
#define IDS_KEYPAD_AND_DISPLAY_LOCKED   131
#define IDS_BATCH_STOPPED               132
#define IDS_PROGRAM_MODE                133
#define IDS_FLOWING                     134
#define IDS_START_COMMUNICATIONS        135
#define IDS_DISPLAY_MESSAGE             136
#define IDS_CHANGE_OPERATING_MODE       137
#define IDS_SWING_ARM                   138
#define IDS_GROSS_VOLUME                139
#define IDS_NET_VOLUME                  140
#define IDS_SAFETY                      141
#define IDS_SAFETY_2                    142
#define IDS_SAFETY_3                    143
#define IDS_SAFETY_4                    144
#define IDS_SAFETY_5                    145
#define IDS_SAFETY_6                    146
#define IDS_SAFETY_7                    147
#define IDS_SAFETY_8                    148
#define IDS_OLDEST_ALARM                149
#define IDS_PRIMARY_DISPLAY_FAILURE     150
#define IDS_SECONDARY_DISPLAY_FAILURE   151
#define IDS_CHANNEL_A_COMM_FAILURE      152
#define IDS_CHANNEL_B_COMM_FAILURE      153
#define IDS_BLEND                       154
#define IDS_ALARMS                      155
#define IDS_METER                       156
#define IDS_LOW_FLOW                    157
#define IDS_HIGH_FLOW                   158
#define IDS_VALVE_CLOSED_EARLY          159
#define IDS_FLOW_TIMEOUT                160
#define IDS_UNAUTHORIZED_FLOW           161
#define IDS_PULSE_SECURITY_ERROR        162
#define IDS_TEMPERATURE_FAILURE         163
#define IDS_PRESSURE_FAILURE            164
#define IDS_VALVE_CLOSE_FAILURE         165
#define IDS_DENSITY_FAILURE             166
#define IDS_COMPONENT                   167
#define IDS_BLOCK_VALVE_CLOSE_FAILURE   168
#define IDS_ADDITIVE                    169
#define IDS_FAILURE                     170
#define IDS_SET_DATE_AND_TIME           171
#define IDS_RESET_PRIMARY_ALARMS        172
#define IDS_TIMEOUT_OPERATION           173
#define IDS_PROMPT_RECIPE               174
#define IDS_REQUEST_SELECTED_RECIPE     175
#define IDS_KEYPAD_DATA                 176
#define IDS_SET_PROGRAM_CODE_VALUE      177
#define IDS_READ_PROGRAM_CODE_VALUE     178
#define IDS_COMPONENT_TOTALIZERS        179
#define IDS_END_TRANSACTION             180
#define IDS_CLEAR_DISPLAY               181
#define IDS_ADDITIVE_TOTALIZERS         182
#define IDS_AUTHORIZE_TRANSACTION       183
#define IDS_PROMPT_PRESET_VOLUME        184
#define IDS_REQUEST_PRESET_VOLUME       185
#define IDS_AUTHORIZE_BATCH             186
#define IDS_GROSS_TOTALIZER_START       187
#define IDS_AVERAGE_TEMPERATURE         188
#define IDS_AVERAGE_DENSITY             189
#define IDS_AVERAGE_PRESSURE            190
#define IDS_END_BATCH                   191
#define IDS_LAST_KEY_PRESSED            192
#define IDS_BATCH_VALUES                193
#define IDS_BATCH_SEQUENCE_NUMBER       194
#define IDS_TRANSACTION_SEQUENCE_NUMBER 195
#define IDS_RECIPE_NUMBER               196
#define IDS_START_DATETIME              197
#define IDS_END_DATETIME                198
#define IDS_NUMBER_OF_METERS            199
#define IDS_NUMBER_OF_COMPONENTS        200
#define IDS_NUMBER_OF_ADDITIVES         201
#define IDS_GROSS_TOTALIZER_END         202
#define IDS_NET_TOTALIZER_START         203
#define IDS_NET_TOTALIZER_END           204
#define IDS_NUMBER_OF_DATA_PROMPTS      205
#define IDS_PERCENT                     206
#define IDS_GROSS_TOTALIZER             207
#define IDS_NET_TOTALIZER               208
#define IDS_COMPONENT_VALUES            209
#define IDS_AVERAGE_VALVE_CLOSURES      210
#define IDS_INPUT                       211
#define IDS_RTD                         212
#define IDS_CURRENT_LOOP                213
#define IDS_DISCRETE                    214
#define IDS_OUTPUT                      215
#define IDS_OPC_E_INVALIDHANDLE         63000
#define IDS_OPC_E_BADTYPE               63001
#define IDS_OPC_E_PUBLIC                63002
#define IDS_OPC_E_BADRIGHTS             63003
#define IDS_OPC_E_UNKNOWNITEMID         63004
#define IDS_OPC_E_INVALIDITEMID         63005
#define IDS_OPC_E_INVALIDFILTER         63006
#define IDS_OPC_E_UNKNOWNPATH           63007
#define IDS_OPC_E_RANGE                 63008
#define IDS_OPC_E_DUPLICATENAME         63009
#define IDS_OPC_S_UNSUPPORTEDRATE       63010
#define IDS_OPC_S_CLAMP                 63011
#define IDS_OPC_S_INUSE                 63012
#define IDS_OPC_E_INVALIDCONFIGFILE     63013
#define IDS_OPC_E_NOTFOUND              63014

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
