// ContrecOPCObjects.idl : IDL source for ContrecOPCObjects
//
/******************************************************************************

	FILE NAME:		ContrecOPCObjects.idl


	PURPOSE:			IDL source for ContrecOPCObjects.dll


	COMMENTS:

		Copyright (C) Varec, Inc. Norcross, GA, USA, 2007

		This file shall not be copied or reproduced in any form without
				the express written consent of Varec.


	AUTHOR(S):	B. Schaal


	VERSION:		1.0.1  Current version



	MODIFICATION HISTORY:
		Date:			By:			Reason:
		---------	----------  -------------------------------------------
*******************************************************************************/

// This file will be processed by the MIDL tool to
// produce the type library (ContrecOPCObjects.tlb) and marshalling code.

#include "mtxattr.h"
#include "IComCollection.idl"
#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";

typedef enum CONTREC_TYPE
{
	CONTREC1010 = 0,
	MAX_CONTREC_TYPE = 1
} CONTREC_TYPE;

typedef enum CONTREC_BAUD
{
	CONTREC_BAUD_1200 = 0,
	CONTREC_BAUD_2400 = 1,
	CONTREC_BAUD_4800 = 2,
	CONTREC_BAUD_9600 = 3,
	CONTREC_BAUD_19200 = 4,
	CONTREC_BAUD_38400 = 5,
	MAX_CONTREC_BAUD = 6
} CONTREC_BAUD;

typedef enum CONTREC_PARITY
{
	CONTREC_PARITY_NONE = 0,
	CONTREC_PARITY_EVEN = 1,
	CONTREC_PARITY_ODD = 2,
	MAX_CONTREC_PARITY = 3
} CONTREC_PARITY;

typedef enum CONTREC_DATA_BITS
{
	DATA_BITS_7 = 0,
	DATA_BITS_8 = 1,
	MAX_CONTREC_DATA_BITS = 2
} CONTREC_DATA_BITS;

typedef enum CONTREC_STOP_BITS
{
	STOP_BITS_1 = 0,
	STOP_BITS_2 = 1,
	MAX_CONTREC_STOP_BITS = 2
} CONTREC_STOP_BITS;

[
	object,
	uuid(A936832E-3F54-4645-8D8F-FABFD66DA0B8),
	dual,
	nonextensible,
	helpstring("IPort Interface"),
	pointer_default(unique)
]
interface IPort : IDispatch{
	[propget, id(1), helpstring("property Index")] HRESULT Index([out, retval] LONG* pVal);
	[propput, id(1), helpstring("property Index")] HRESULT Index([in] LONG newVal);
	[propget, id(2), helpstring("property ID")] HRESULT ID([out, retval] BSTR* pVal);
	[propput, id(2), helpstring("property ID")] HRESULT ID([in] BSTR newVal);
	[propget, id(3), helpstring("property Baud")] HRESULT Baud([out, retval] CONTREC_BAUD* pVal);
	[propput, id(3), helpstring("property Baud")] HRESULT Baud([in] CONTREC_BAUD newVal);
	[propget, id(4), helpstring("property DataBits")] HRESULT DataBits([out, retval] CONTREC_DATA_BITS* pVal);
	[propput, id(4), helpstring("property DataBits")] HRESULT DataBits([in] CONTREC_DATA_BITS newVal);
	[propget, id(5), helpstring("property Parity")] HRESULT Parity([out, retval] CONTREC_PARITY* pVal);
	[propput, id(5), helpstring("property Parity")] HRESULT Parity([in] CONTREC_PARITY newVal);
	[propget, id(6), helpstring("property StopBits")] HRESULT StopBits([out, retval] CONTREC_STOP_BITS* pVal);
	[propput, id(6), helpstring("property StopBits")] HRESULT StopBits([in] CONTREC_STOP_BITS newVal);
	[id(7), helpstring("method BaudID")] HRESULT BaudID([in] CONTREC_BAUD Baud,[out,retval] BSTR* pVal);
	[id(8), helpstring("method DataBitsID")] HRESULT DataBitsID([in] CONTREC_DATA_BITS DataBits,[out,retval] BSTR* pVal);
	[id(9), helpstring("method ParityID")] HRESULT ParityID([in] CONTREC_PARITY Parity,[out,retval] BSTR* pVal);
	[id(10), helpstring("method StopBitsID")] HRESULT StopBitsID([in] CONTREC_STOP_BITS StopBits,[out,retval] BSTR* pVal);
	[id(11), helpstring("method Load")] HRESULT Load([in] IDispatch* pDispatch);
	[id(12), helpstring("method Reset")] HRESULT Reset(void);
	[propget, id(13), helpstring("property InsertSQL")] HRESULT InsertSQL([out, retval] BSTR* pVal);
	[propget, id(14), helpstring("property UpdateSQL")] HRESULT UpdateSQL([out, retval] BSTR* pVal);
	[propget, id(15), helpstring("property PurgeSQL")] HRESULT PurgeSQL([out, retval] BSTR* pVal);
	[propget, id(16), helpstring("property SelectSQL")] HRESULT SelectSQL([out, retval] BSTR* pVal);
	[propget, id(17), helpstring("property SelectByIDSQL")] HRESULT SelectByIDSQL([out, retval] BSTR* pVal);
	[propget, id(18), helpstring("property EnumerateSQL")] HRESULT EnumerateSQL([out, retval] BSTR* pVal);
};
[
	object,
	uuid(467BEDE3-088B-4D08-985F-F5EA5456C221),
	dual,
	nonextensible,
	helpstring("IContrec Interface"),
	pointer_default(unique)
]
interface IContrec : IDispatch{
	[propget, id(1), helpstring("property Index")] HRESULT Index([out, retval] LONG* pVal);
	[propput, id(1), helpstring("property Index")] HRESULT Index([in] LONG newVal);
	[propget, id(2), helpstring("property ID")] HRESULT ID([out, retval] BSTR* pVal);
	[propput, id(2), helpstring("property ID")] HRESULT ID([in] BSTR newVal);
	[propget, id(3), helpstring("property Type")] HRESULT Type([out, retval] CONTREC_TYPE* pVal);
	[propput, id(3), helpstring("property Type")] HRESULT Type([in] CONTREC_TYPE newVal);
	[propget, id(4), helpstring("property PortIndex")] HRESULT PortIndex([out, retval] LONG* pVal);
	[propput, id(4), helpstring("property PortIndex")] HRESULT PortIndex([in] LONG newVal);
	[propget, id(5), helpstring("property PortID")] HRESULT PortID([out, retval] BSTR* pVal);
	[propput, id(5), helpstring("property PortID")] HRESULT PortID([in] BSTR newVal);
	[propget, id(6), helpstring("property Address")] HRESULT Address([out, retval] unsigned char* pVal);
	[propput, id(6), helpstring("property Address")] HRESULT Address([in] unsigned char newVal);
	[id(7), helpstring("method TypeID")] HRESULT TypeID([in] CONTREC_TYPE Type,[out,retval] BSTR* pVal);
	[id(8), helpstring("method Load")] HRESULT Load([in] IDispatch* pDispatch);
	[id(9), helpstring("method Reset")] HRESULT Reset(void);
	[propget, id(10), helpstring("property InsertSQL")] HRESULT InsertSQL([out, retval] BSTR* pVal);
	[propget, id(11), helpstring("property UpdateSQL")] HRESULT UpdateSQL([out, retval] BSTR* pVal);
	[propget, id(12), helpstring("property PurgeSQL")] HRESULT PurgeSQL([out, retval] BSTR* pVal);
	[propget, id(13), helpstring("property SelectSQL")] HRESULT SelectSQL([out, retval] BSTR* pVal);
	[propget, id(14), helpstring("property SelectByIDSQL")] HRESULT SelectByIDSQL([out, retval] BSTR* pVal);
	[propget, id(15), helpstring("property EnumerateSQL")] HRESULT EnumerateSQL([out, retval] BSTR* pVal);
};
[
	object,
	uuid(8A5434A0-F101-4070-9263-1D3116E39EBA),
	dual,
	nonextensible,
	helpstring("IPortCollection Interface"),
	pointer_default(unique)
]
interface IPortCollection : IDispatch{
	DECLARE_COM_COLLECTION(IPort)
};
[
	object,
	uuid(C09BAFF5-A840-4023-8E96-23B44E0FA96B),
	dual,
	nonextensible,
	helpstring("IContrecCollection Interface"),
	pointer_default(unique)
]
interface IContrecCollection : IDispatch{
	DECLARE_COM_COLLECTION(IContrec)
};
[
	uuid(C31FF61C-5215-4A9F-A438-A426227D15A0),
	version(1.0),
	helpstring("ContrecOPCObjects 1.0 Type Library")
]
library ContrecOPCObjectsLib
{
	importlib("stdole2.tlb");
	[
		uuid(3C30C23A-8C48-4CC2-B992-9AFAD5394D8E),
		helpstring("Port Class")
	]
	coclass Port
	{
		[default] interface IPort;
	};
	[
		uuid(8A6F9478-08B3-47FC-B016-4BCCF709EE8F),
		helpstring("Contrec Class")
	]
	coclass Contrec
	{
		[default] interface IContrec;
	};
	[
		uuid(3789DC85-8F6C-47B4-A01E-3029755F82E6),
		helpstring("PortCollection Class")
	]
	coclass PortCollection
	{
		[default] interface IPortCollection;
	};
	[
		uuid(8185E935-2D3F-4CD4-B79A-F62A62794CAD),
		helpstring("ContrecCollection Class")
	]
	coclass ContrecCollection
	{
		[default] interface IContrecCollection;
	};
};
