CREATE TABLE [fmaudit].[OptomuxOPC_tblOptomuxControllers](
	[Index] [int] NULL,
	[ID] [nvarchar](50) NULL,
	[Type] [int] NULL,
	[Address] [int] NULL,
	[PortIndex] [int] NULL,
	[ModuleInputOutputMap] [int] NULL,
	[NetworkCommunications] [bit] NULL,
	[IPAddress] [nvarchar](15) NULL,
	[Port] [int] NULL,
	[_AuditEventType] [char](1) NULL,
	[_AuditEventSequence] [tinyint] NULL DEFAULT ((0)),
	[_AuditSiteGuid] [uniqueidentifier] NULL,
	[_AuditSessionGuid] [uniqueidentifier] NULL,
	[_AuditUserID] [dbo].[udtUserID] NULL,
	[_AuditSessionTokenID] [uniqueidentifier] NULL,
	[_AuditCreatedDate] [datetimeoffset](7) NULL DEFAULT (sysdatetimeoffset()) ,
	[_AuditGUID] [uniqueidentifier] NOT NULL DEFAULT (newid()),
	[_AuditRowVersion] [timestamp] NOT NULL,
	[_ClusterIdx] [bigint] IDENTITY(1,1) NOT NULL,
	[_AuditContext] [varbinary](128) NULL
)
