<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <Version Condition=" '$(BUILD_BUILDNUMBER)' == '' ">0.0.1-local</Version>
    <Version Condition=" '$(BUILD_BUILDNUMBER)' != '' ">$(BUILD_BUILDNUMBER)</Version>
    <ApplicationIcon />
    <OutputType>Exe</OutputType>
    <StartupObject />
  </PropertyGroup>
  
  <PropertyGroup>
	<IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
  </PropertyGroup>

  <PropertyGroup>
	<ANCMPreConfiguredForIIS>true</ANCMPreConfiguredForIIS>
  </PropertyGroup> 

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

 <Target Name="AddWwwRootFolder" AfterTargets="Publish">
    <Exec Command="xcopy &quot;..\RTU8810\dist\RTU8810\*.*&quot; &quot;$(PublishDir)wwwroot\&quot; /S /Y /I" />
  </Target>

  <Target Name="AddRtuXmlFileFolder" AfterTargets="Publish">
    <Exec Command="xcopy &quot;.\RTUXmlFile\*.*&quot; &quot;$(PublishDir)RTUXmlFile\&quot; /S /Y /I" />
  </Target>


 <ItemGroup>
    <Compile Remove="wwwroot\**" />
    <Content Remove="wwwroot\**" />
    <EmbeddedResource Remove="wwwroot\**" />
    <None Remove="wwwroot\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.8" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.WindowsServices" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.ResponseCompression" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.2.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.0" />
 </ItemGroup>

  <ItemGroup>
    <Reference Include="Softing.Opc.Ua.Sdk.Core">
      <HintPath>..\Binaries\SoftingOriginal\Softing.Opc.Ua.Sdk.Core.dll</HintPath>
    </Reference>
    <Reference Include="Softing.Opc.Ua.Toolkit">
      <HintPath>..\Binaries\SoftingOriginal\Softing.Opc.Ua.Toolkit.dll</HintPath>
    </Reference>
    <Reference Include="System.Configuration" />
  </ItemGroup>

</Project>
