CREATE PROCEDURE [dbo].[usp_PointTemplatePropertyUpdateByPK]
(
		@PointTemplatePropertyGuid uniqueidentifier
	,	@ID nvarchar(50)=NULL
	,	@ValueType nvarchar(max)=NULL
	,	@Value xml=NULL
	,	@UpdatedDate datetimeoffset(7)=NULL
	,	@UpdatedBy udtUserID=NULL
	,	@PointTemplateGuid uniqueidentifier=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideID BIT=0 
	,	@NullOverrideValueType BIT=0
	,	@NullOverrideValue BIT=0
	,	@NullOverrideUpdatedDate BIT=0 
	,	@NullOverridePointTemplateGuid BIT=0 
	,	@NullOverride_ClusterIdx BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[usp_PointTemplatePropertyUpdateByPK] 
	-- Author: Warren Gray
	-- Version/Date: 2.0 / 2019-04-29 15:44:54.8267684 -04:00
	-- Purpose: Update table [dbo].[tblPointTemplateProperty]
	-- Notes:
	-- 1. @PointTemplateTagGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblPointTemplateProperty] WHERE PointTemplatePropertyGuid=@PointTemplatePropertyGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		IF NOT EXISTS ( SELECT 1 FROM dbo.tblPointTemplateProperty target WHERE Target.[PointTemplateGuid] =@PointTemplateGuid AND Target.PointTemplatePropertyGuid = @PointTemplatePropertyGuid)
		BEGIN
			INSERT dbo.tblPointTemplateProperty([ID],[ValueType],[Value],[PointTemplatePropertyGuid],[PointTemplateGuid],[CreatedDate],[CreatedBy],[UpdatedDate],[UpdatedBy])
			SELECT @ID,@ValueType,@Value,@PointTemplatePropertyGuid,
				@PointTemplateGuid, ISNULL(@UpdatedDate,SYSDATETIMEOFFSET()),ISNULL(@UpdatedBy,SUSER_SNAME()),ISNULL(@UpdatedDate,SYSDATETIMEOFFSET()),ISNULL(@UpdatedBy,SUSER_SNAME())
		END
		ELSE
		BEGIN
			UPDATE target
				SET target.[ID] = (CASE ISNULL(@NullOverrideID,0) WHEN 1 THEN @ID ELSE ISNULL(@ID,target.[ID]) END),
								target.[ValueType] =(CASE ISNULL(@NullOverrideValueType,0) WHEN 1 THEN @ValueType ELSE ISNULL(@ValueType,target.[ValueType]) END),
								target.[Value] = (CASE ISNULL(@NullOverrideValue,0) WHEN 1 THEN @Value ELSE ISNULL(@Value,target.[Value]) END),
								target.[UpdatedDate] = ISNULL(@UpdatedDate,SYSDATETIMEOFFSET()),
								target.[UpdatedBy] = ISNULL(@UpdatedBy,SUSER_SNAME())
				FROM dbo.tblPointTemplateProperty target 
				WHERE Target.[PointTemplateGuid] = @PointTemplateGuid 
				AND Target.PointTemplatePropertyGuid = @PointTemplatePropertyGuid
				AND ( target.[ID] <> (CASE ISNULL(@NullOverrideID,0) WHEN 1 THEN @ID ELSE ISNULL(@ID,target.[ID]) END)
								OR target.[ValueType] <> (CASE ISNULL(@NullOverrideValueType,0) WHEN 1 THEN @ValueType ELSE ISNULL(@ValueType,target.[ValueType]) END)
								OR CAST( target.[Value] AS NVARCHAR(MAX)) <> (CASE ISNULL(@NullOverrideValue,0) WHEN 1 THEN CAST( @Value AS NVARCHAR(MAX)) ELSE ISNULL(CAST( @Value AS NVARCHAR(MAX)),CAST( target.[Value] AS NVARCHAR(MAX))) END)
				)
		END

		
		UPDATE target
		SET [ID] = (CASE ISNULL(@NullOverrideID,0) WHEN 1 THEN @ID ELSE ISNULL(@ID,target.[ID]) END),
					target.[UpdatedDate] = ISNULL(@UpdatedDate,SYSDATETIMEOFFSET()),
					target.[UpdatedBy] = ISNULL(@UpdatedBy,SUSER_SNAME())
		FROM dbo.tblPointProperty target
		JOIN dbo.tblPoint p
		ON Target.PointGuid = p.PointGuid
		AND PointTemplateGuid = @PointTemplateGuid
		WHERE Target.PointTemplatePropertyGuid = @PointTemplatePropertyGuid
		AND target.[ID] <> (CASE ISNULL(@NullOverrideID,0) WHEN 1 THEN @ID ELSE ISNULL(@ID,target.[ID]) END)

		INSERT  dbo.tblPointProperty ([ID],[ValueType],[Value],[CreatedDate],[CreatedBy],[UpdatedDate],[UpdatedBy],[PointPropertyGuid],[PointGuid],[PointTemplatePropertyGuid])
		SELECT @ID,@ValueType,dbo.udf_UpdateXmlForDataContractSerializer(@ValueType, @Value),ISNULL(@UpdatedDate,SYSDATETIMEOFFSET()), ISNULL(@UpdatedBy,SUSER_SNAME()),ISNULL(@UpdatedDate,SYSDATETIMEOFFSET()),ISNULL(@UpdatedBy,SUSER_SNAME()),
			NEWID(),source.PointGuid, @PointTemplatePropertyGuid
		FROM tblPoint source
		WHERE source.PointTemplateGuid = @PointTemplateGuid
		AND NOT EXISTS ( SELECT 1 FROM tblPointProperty pp WHERE pp.PointGuid = source.PointGuid AND pp.PointTemplatePropertyGuid = @PointTemplatePropertyGuid)


		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblPointTemplateProperty]           
		WHERE PointTemplatePropertyGuid=@PointTemplatePropertyGuid;

	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: usp_PointTemplatePropertyUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END
GO