CREATE PROCEDURE [dbo].[usp_TransactionHeaderInsertUpdate]
(
	@TransactionHeaders dbo.TransactionHeadersType READONLY
)
AS
BEGIN
	SET NOCOUNT ON
	
	BEGIN TRY

		MERGE tblTransactions AS target
		USING (
			SELECT 
				TransactionGuid,
				TransID,
				AliasName,
				SubType,
				[Site],
				TransReferenceID,
				InventoryDate,
				ShipToID,
				ShipToCode,
				SupplierID,
				SupplierCode,
				RequestedDeliveryDate,
				TransDateTime,
				TransVersion,
				SCACCode,
				CardNumber,
				ShipmentNumber,
				ShipperID,
				ShipperCode,
				OwnerID,
				OwnerCode,
				ManagerID,
				ManagerCode,
				CarrierID,
				CarrierCode,
				ConjoinTransID,
				ReversedTransID,
				LinkedDocumentNumber,
				ReversalType,
				PONumber,
				TimeIn,
				[TimeOut],
				TimeEnd,
				RoutingID,
				TicketSource,
				LoadID,
				BillToID,
				BillToCode,
				DriverIdentificationNumber,
				CreditAmount,
				CardExpiration,
				CardName,
				CardType,
				CashAmount,
				RouteOriginationDate,
				InternationalRouteIndicator,
				PreviousRoutingID,
				ShippingDocumentNumber,
				DocumentNumber,
				STD,
				ETD,
				STA,
				ETA,
				SFT,
				FST,
				EstimatedFuelingDuration,
				DeleteFlag,
				TicketMode,
				DestinationRegistrationID1,
				DestinationSerialNumber1,
				DestinationEquipmentType1,
				DestinationEquipmentModel1,
				DestinationCompanyEquipmentID1,
				DestinationRegistrationID2,
				DestinationSerialNumber2,
				DestinationEquipmentType2,
				DestinationEquipmentModel2,
				DestinationCompanyEquipmentID2,
				DestinationRegistrationID3,
				DestinationSerialNumber3,
				DestinationEquipmentType3,
				DestinationEquipmentModel3,
				DestinationCompanyEquipmentID3,
				SourceRegistrationID1,
				SourceSerialNumber1,
				SourceEquipmentType1,
				SourceEquipmentModel1,
				SourceCompanyEquipmentID1,
				SourceRegistrationID2,
				SourceSerialNumber2,
				SourceEquipmentType2,
				SourceEquipmentModel2,
				SourceCompanyEquipmentID2,
				SourceRegistrationID3,
				SourceSerialNumber3,
				SourceEquipmentType3,
				SourceEquipmentModel3,
				SourceCompanyEquipmentID3,
				OperatorID,
				EffectiveDate,
				ExpirationDate,
				ScheduledDate,
				AutoComplete,
				Flag01,
				Flag02,
				Flag03,
				Flag04,
				Flag05,
				Flag06,
				Number01,
				Number02,
				Number03,
				Number04,
				Number05,
				Number06,
				ContactFirstName,
				ContactSurname,
				Date01,
				Date02,
				Date03,
				Date04,
				LegacyNumber,
				Country,
				ContactInfo,
				AssociatedDocNumber,
				AssociatedCLIN,
				SubmittedToAccounting,
				FuelCardID,
				AssociatedTransportOrderNumber,
				RequestedDateTime,
				DispatchedDateTime,
				ErrorFlag,
				SiteGuid,
				LookupTransTypeIndex,
				LookupTransactionStatusIndex,
				LookupOriginApplicationIndex,
				TransactionAliasGuid,
				BillToCompanyGuid,
				Destination1EquipmentGuid,
				Destination2EquipmentGuid,
				Destination3EquipmentGuid,
				FinalStationIATAGuid,
				FuelCardGuid,
				ManagerCompanyGuid,
				NextStationIATAGuid,
				OperatorPersonnelGuid,
				OriginStationIATAGuid,
				OwnerCompanyGuid,
				PreviousStationIATAGuid,
				ShipperCompanyGuid,
				ShipToCompanyGuid,
				Source1EquipmentGuid,
				Source2EquipmentGuid,
				Source3EquipmentGuid,
				SupplierCompanyGuid,
				CarrierCompanyGuid,
				ReasonCodeGuid,
				OriginStationIATAID,
				PreviousStationIATAID,
				NextStationIATAID,
				FinalStationIATAID,
				OperatorName,
				FuelAdditiveFlag,
				IssuePoint,
				IssuePointNumber,
				RadioNumber,
				GateID,
				GateGuid,
				ShippingMethod,
				ReferencedTransactionGuid,
				CreatedUpdatedBy
			FROM @TransactionHeaders
			) AS source
		ON source.TransactionGuid = target.TransactionGuid
		WHEN MATCHED THEN UPDATE SET
			AliasName = source.AliasName,
			SubType = source.SubType,
			[Site] = source.[Site],
			TransReferenceID = source.TransReferenceID,
			InventoryDate = source.InventoryDate,
			ShipToID = source.ShipToID,
			ShipToCode = source.ShipToCode,
			SupplierID = source.SupplierID,
			SupplierCode = source.SupplierCode,			
			RequestedDeliveryDate = source.RequestedDeliveryDate,
			TransDateTime = source.TransDateTime,
			TransVersion = source.TransVersion,
			SCACCode = source.SCACCode,
			CardNumber = source.CardNumber,
			ShipmentNumber = source.ShipmentNumber,
			ShipperID = source.ShipperID,
			ShipperCode = source.ShipperCode,
			OwnerID = source.OwnerID,
			OwnerCode = source.OwnerCode,
			ManagerID = source.ManagerID,
			ManagerCode = source.ManagerCode,
			CarrierID = source.CarrierID,
			CarrierCode = source.CarrierCode,
			ConjoinTransID = source.ConjoinTransID,
			ReversedTransID = source.ReversedTransID,
			LinkedDocumentNumber = source.LinkedDocumentNumber,
			ReversalType = source.ReversalType,
			PONumber = source.PONumber,
			TimeIn = source.TimeIn,
			[TimeOut] = source.[TimeOut],
			TimeEnd = source.TimeEnd,
			RoutingID = source.RoutingID,
			TicketSource = source.TicketSource,
			LoadID = source.LoadID,
			BillToID = source.BillToID,
			BillToCode = source.BillToCode,
			DriverIdentificationNumber = source.DriverIdentificationNumber,
			CreditAmount = source.CreditAmount,
			CardExpiration = source.CardExpiration,
			CardName = source.CardName,
			CardType = source.CardType,
			CashAmount = source.CashAmount,
			RouteOriginationDate = source.RouteOriginationDate,
			InternationalRouteIndicator = source.InternationalRouteIndicator,
			PreviousRoutingID = source.PreviousRoutingID,
			ShippingDocumentNumber = source.ShippingDocumentNumber,
			DocumentNumber = source.DocumentNumber,
			STD = source.STD,
			ETD = source.ETD,
			STA = source.STA,
			ETA = source.ETA,
			SFT = source.SFT,
			FST = source.FST,
			EstimatedFuelingDuration = source.EstimatedFuelingDuration,
			DeleteFlag = source.DeleteFlag,
			TicketMode = source.TicketMode,
			DestinationRegistrationID1 = source.DestinationRegistrationID1,
			DestinationSerialNumber1 = source.DestinationSerialNumber1,
			DestinationEquipmentType1 = source.DestinationEquipmentType1,
			DestinationEquipmentModel1 = source.DestinationEquipmentModel1,
			DestinationCompanyEquipmentID1 = source.DestinationCompanyEquipmentID1,
			DestinationRegistrationID2 = source.DestinationRegistrationID2,
			DestinationSerialNumber2 = source.DestinationSerialNumber2,
			DestinationEquipmentType2 = source.DestinationEquipmentType2,
			DestinationEquipmentModel2 = source.DestinationEquipmentModel2,
			DestinationCompanyEquipmentID2 = source.DestinationCompanyEquipmentID2,
			DestinationRegistrationID3 = source.DestinationRegistrationID3,
			DestinationSerialNumber3 = source.DestinationSerialNumber3,
			DestinationEquipmentType3 = source.DestinationEquipmentType3,
			DestinationEquipmentModel3 = source.DestinationEquipmentModel3,
			DestinationCompanyEquipmentID3 = source.DestinationCompanyEquipmentID3,
			SourceRegistrationID1 = source.SourceRegistrationID1,
			SourceSerialNumber1 = source.SourceSerialNumber1,
			SourceEquipmentType1 = source.SourceEquipmentType1,
			SourceEquipmentModel1 = source.SourceEquipmentModel1,
			SourceCompanyEquipmentID1 = source.SourceCompanyEquipmentID1,
			SourceRegistrationID2 = source.SourceRegistrationID2,
			SourceSerialNumber2 = source.SourceSerialNumber2,
			SourceEquipmentType2 = source.SourceEquipmentType2,
			SourceEquipmentModel2 = source.SourceEquipmentModel2,
			SourceCompanyEquipmentID2 = source.SourceCompanyEquipmentID2,
			SourceRegistrationID3 = source.SourceRegistrationID3,
			SourceSerialNumber3 = source.SourceSerialNumber3,
			SourceEquipmentType3 = source.SourceEquipmentType3,
			SourceEquipmentModel3 = source.SourceEquipmentModel3,
			SourceCompanyEquipmentID3 = source.SourceCompanyEquipmentID3,
			OperatorID = source.OperatorID,
			EffectiveDate = source.EffectiveDate,
			ExpirationDate = source.ExpirationDate,
			ScheduledDate = source.ScheduledDate,
			AutoComplete = source.AutoComplete,
			Flag01 = source.Flag01,
			Flag02 = source.Flag02,
			Flag03 = source.Flag03,
			Flag04 = source.Flag04,
			Flag05 = source.Flag05,
			Flag06 = source.Flag06,
			Number01 = source.Number01,
			Number02 = source.Number02,
			Number03 = source.Number03,
			Number04 = source.Number04,
			Number05 = source.Number05,
			Number06 = source.Number06,
			ContactFirstName = source.ContactFirstName,
			ContactSurname = source.ContactSurname,
			Date01 = source.Date01,
			Date02 = source.Date02,
			Date03 = source.Date03,
			Date04 = source.Date04,
			LegacyNumber = source.LegacyNumber,
			Country = source.Country,
			ContactInfo = source.ContactInfo,
			AssociatedDocNumber = source.AssociatedDocNumber,
			AssociatedCLIN = source.AssociatedCLIN,
			SubmittedToAccounting = source.SubmittedToAccounting,
			FuelCardID = source.FuelCardID,
			AssociatedTransportOrderNumber = source.AssociatedTransportOrderNumber,
			RequestedDateTime = source.RequestedDateTime,
			DispatchedDateTime = source.DispatchedDateTime,
			ErrorFlag = source.ErrorFlag,
			SiteGuid = source.SiteGuid,
			LookupTransTypeIndex = source.LookupTransTypeIndex,
			LookupTransactionStatusIndex = source.LookupTransactionStatusIndex,
			LookupOriginApplicationIndex = source.LookupOriginApplicationIndex,
			TransactionAliasGuid = source.TransactionAliasGuid,
			BillToCompanyGuid = source.BillToCompanyGuid,
			Destination1EquipmentGuid = source.Destination1EquipmentGuid,
			Destination2EquipmentGuid = source.Destination2EquipmentGuid,
			Destination3EquipmentGuid = source.Destination3EquipmentGuid,
			FinalStationIATAGuid = source.FinalStationIATAGuid,
			FuelCardGuid = source.FuelCardGuid,
			ManagerCompanyGuid = source.ManagerCompanyGuid,
			NextStationIATAGuid = source.NextStationIATAGuid,
			OperatorPersonnelGuid = source.OperatorPersonnelGuid,
			OriginStationIATAGuid = source.OriginStationIATAGuid,
			OwnerCompanyGuid = source.OwnerCompanyGuid,
			PreviousStationIATAGuid = source.PreviousStationIATAGuid,
			ShipperCompanyGuid = source.ShipperCompanyGuid,
			ShipToCompanyGuid = source.ShipToCompanyGuid,
			Source1EquipmentGuid = source.Source1EquipmentGuid,
			Source2EquipmentGuid = source.Source2EquipmentGuid,
			Source3EquipmentGuid = source.Source3EquipmentGuid,
			SupplierCompanyGuid = source.SupplierCompanyGuid,
			CarrierCompanyGuid = source.CarrierCompanyGuid,
			ReasonCodeGuid = source.ReasonCodeGuid,
			OriginStationIATAID = source.OriginStationIATAID,
			PreviousStationIATAID = source.PreviousStationIATAID,
			NextStationIATAID = source.NextStationIATAID,
			FinalStationIATAID = source.FinalStationIATAID,
			OperatorName = source.OperatorName,
			FuelAdditiveFlag = source.FuelAdditiveFlag,
			IssuePoint = source.IssuePoint,
			IssuePointNumber = source.IssuePointNumber,
			RadioNumber	= source.RadioNumber,
			GateID = source.GateID,
			ShippingMethod = source.ShippingMethod,
			ReferencedTransactionGuid = source.ReferencedTransactionGuid,
			GateGuid = source.GateGuid,
			UpdatedDate = SYSDATETIMEOFFSET(),
			UpdatedBy = source.CreatedUpdatedBy
		WHEN NOT MATCHED THEN INSERT 
		(
			TransactionGuid,
			TransID,
			AliasName,
			SubType,
			[Site],
			TransReferenceID,
			InventoryDate,
			ShipToID,
			ShipToCode,
			SupplierID,
			SupplierCode,
			RequestedDeliveryDate,
			TransDateTime,
			TransVersion,
			SCACCode,
			CardNumber,
			ShipmentNumber,
			ShipperID,
			ShipperCode,
			OwnerID,
			OwnerCode,
			ManagerID,
			ManagerCode,
			CarrierID,
			CarrierCode,
			ConjoinTransID,
			ReversedTransID,
			LinkedDocumentNumber,
			ReversalType,
			PONumber,
			TimeIn,
			[TimeOut],
			TimeEnd,
			RoutingID,
			TicketSource,
			LoadID,
			BillToID,
			BillToCode,
			DriverIdentificationNumber,
			CreditAmount,
			CardExpiration,
			CardName,
			CardType,
			CashAmount,
			RouteOriginationDate,
			InternationalRouteIndicator,
			PreviousRoutingID,
			ShippingDocumentNumber,
			DocumentNumber,
			STD,
			ETD,
			STA,
			ETA,
			SFT,
			FST,
			EstimatedFuelingDuration,
			DeleteFlag,
			TicketMode,
			DestinationRegistrationID1,
			DestinationSerialNumber1,
			DestinationEquipmentType1,
			DestinationEquipmentModel1,
			DestinationCompanyEquipmentID1,
			DestinationRegistrationID2,
			DestinationSerialNumber2,
			DestinationEquipmentType2,
			DestinationEquipmentModel2,
			DestinationCompanyEquipmentID2,
			DestinationRegistrationID3,
			DestinationSerialNumber3,
			DestinationEquipmentType3,
			DestinationEquipmentModel3,
			DestinationCompanyEquipmentID3,
			SourceRegistrationID1,
			SourceSerialNumber1,
			SourceEquipmentType1,
			SourceEquipmentModel1,
			SourceCompanyEquipmentID1,
			SourceRegistrationID2,
			SourceSerialNumber2,
			SourceEquipmentType2,
			SourceEquipmentModel2,
			SourceCompanyEquipmentID2,
			SourceRegistrationID3,
			SourceSerialNumber3,
			SourceEquipmentType3,
			SourceEquipmentModel3,
			SourceCompanyEquipmentID3,
			OperatorID,
			EffectiveDate,
			ExpirationDate,
			ScheduledDate,
			AutoComplete,
			Flag01,
			Flag02,
			Flag03,
			Flag04,
			Flag05,
			Flag06,
			Number01,
			Number02,
			Number03,
			Number04,
			Number05,
			Number06,
			ContactFirstName,
			ContactSurname,
			Date01,
			Date02,
			Date03,
			Date04,
			LegacyNumber,
			Country,
			ContactInfo,
			AssociatedDocNumber,
			AssociatedCLIN,
			SubmittedToAccounting,
			FuelCardID,
			AssociatedTransportOrderNumber,
			RequestedDateTime,
			DispatchedDateTime,
			ErrorFlag,
			SiteGuid,
			LookupTransTypeIndex,
			LookupTransactionStatusIndex,
			LookupOriginApplicationIndex,
			TransactionAliasGuid,
			BillToCompanyGuid,
			Destination1EquipmentGuid,
			Destination2EquipmentGuid,
			Destination3EquipmentGuid,
			FinalStationIATAGuid,
			FuelCardGuid,
			ManagerCompanyGuid,
			NextStationIATAGuid,
			OperatorPersonnelGuid,
			OriginStationIATAGuid,
			OwnerCompanyGuid,
			PreviousStationIATAGuid,
			ShipperCompanyGuid,
			ShipToCompanyGuid,
			Source1EquipmentGuid,
			Source2EquipmentGuid,
			Source3EquipmentGuid,
			SupplierCompanyGuid,
			CarrierCompanyGuid,
			ReasonCodeGuid,
			OriginStationIATAID,
			PreviousStationIATAID,
			NextStationIATAID,
			FinalStationIATAID,
			OperatorName,
			FuelAdditiveFlag,
			IssuePoint,
			IssuePointNumber,
			RadioNumber,
			GateID,
			GateGuid,
			ShippingMethod,
			ReferencedTransactionGuid,
			CreatedDate,
			CreatedBy,
			UpdatedDate,
			UpdatedBy
		)
		VALUES
		(
			source.TransactionGuid,
			source.TransID,
			source.AliasName,
			source.SubType,
			source.[Site],
			source.TransReferenceID,
			source.InventoryDate,
			source.ShipToID,
			source.ShipToCode,
			source.SupplierID,
			source.SupplierCode,			
			source.RequestedDeliveryDate,
			source.TransDateTime,
			source.TransVersion,
			source.SCACCode,
			source.CardNumber,
			source.ShipmentNumber,
			source.ShipperID,
			source.ShipperCode,
			source.OwnerID,
			source.OwnerCode,
			source.ManagerID,
			source.ManagerCode,
			source.CarrierID,
			source.CarrierCode,
			source.ConjoinTransID,
			source.ReversedTransID,
			source.LinkedDocumentNumber,
			source.ReversalType,
			source.PONumber,
			source.TimeIn,
			source.[TimeOut],
			source.TimeEnd,
			source.RoutingID,
			source.TicketSource,
			source.LoadID,
			source.BillToID,
			source.BillToCode,
			source.DriverIdentificationNumber,
			source.CreditAmount,
			source.CardExpiration,
			source.CardName,
			source.CardType,
			source.CashAmount,
			source.RouteOriginationDate,
			source.InternationalRouteIndicator,
			source.PreviousRoutingID,
			source.ShippingDocumentNumber,
			source.DocumentNumber,
			source.STD,
			source.ETD,
			source.STA,
			source.ETA,
			source.SFT,
			source.FST,
			source.EstimatedFuelingDuration,
			source.DeleteFlag,
			source.TicketMode,
			source.DestinationRegistrationID1,
			source.DestinationSerialNumber1,
			source.DestinationEquipmentType1,
			source.DestinationEquipmentModel1,
			source.DestinationCompanyEquipmentID1,
			source.DestinationRegistrationID2,
			source.DestinationSerialNumber2,
			source.DestinationEquipmentType2,
			source.DestinationEquipmentModel2,
			source.DestinationCompanyEquipmentID2,
			source.DestinationRegistrationID3,
			source.DestinationSerialNumber3,
			source.DestinationEquipmentType3,
			source.DestinationEquipmentModel3,
			source.DestinationCompanyEquipmentID3,
			source.SourceRegistrationID1,
			source.SourceSerialNumber1,
			source.SourceEquipmentType1,
			source.SourceEquipmentModel1,
			source.SourceCompanyEquipmentID1,
			source.SourceRegistrationID2,
			source.SourceSerialNumber2,
			source.SourceEquipmentType2,
			source.SourceEquipmentModel2,
			source.SourceCompanyEquipmentID2,
			source.SourceRegistrationID3,
			source.SourceSerialNumber3,
			source.SourceEquipmentType3,
			source.SourceEquipmentModel3,
			source.SourceCompanyEquipmentID3,
			source.OperatorID,
			source.EffectiveDate,
			source.ExpirationDate,
			source.ScheduledDate,
			source.AutoComplete,
			source.Flag01,
			source.Flag02,
			source.Flag03,
			source.Flag04,
			source.Flag05,
			source.Flag06,
			source.Number01,
			source.Number02,
			source.Number03,
			source.Number04,
			source.Number05,
			source.Number06,
			source.ContactFirstName,
			source.ContactSurname,
			source.Date01,
			source.Date02,
			source.Date03,
			source.Date04,
			source.LegacyNumber,
			source.Country,
			source.ContactInfo,
			source.AssociatedDocNumber,
			source.AssociatedCLIN,
			source.SubmittedToAccounting,
			source.FuelCardID,
			source.AssociatedTransportOrderNumber,
			source.RequestedDateTime,
			source.DispatchedDateTime,
			source.ErrorFlag,
			source.SiteGuid,
			source.LookupTransTypeIndex,
			source.LookupTransactionStatusIndex,
			source.LookupOriginApplicationIndex,
			source.TransactionAliasGuid,
			source.BillToCompanyGuid,
			source.Destination1EquipmentGuid,
			source.Destination2EquipmentGuid,
			source.Destination3EquipmentGuid,
			source.FinalStationIATAGuid,
			source.FuelCardGuid,
			source.ManagerCompanyGuid,
			source.NextStationIATAGuid,
			source.OperatorPersonnelGuid,
			source.OriginStationIATAGuid,
			source.OwnerCompanyGuid,
			source.PreviousStationIATAGuid,
			source.ShipperCompanyGuid,
			source.ShipToCompanyGuid,
			source.Source1EquipmentGuid,
			source.Source2EquipmentGuid,
			source.Source3EquipmentGuid,
			source.SupplierCompanyGuid,
			source.CarrierCompanyGuid,
			source.ReasonCodeGuid,
			source.OriginStationIATAID,
			source.PreviousStationIATAID,
			source.NextStationIATAID,
			source.FinalStationIATAID,
			source.OperatorName,
			source.FuelAdditiveFlag,
			source.IssuePoint,
			source.IssuePointNumber,
			source.RadioNumber,
			source.GateID,
			source.GateGuid,
			source.ShippingMethod,
			source.ReferencedTransactionGuid,
			SYSDATETIMEOFFSET(), --CreatedDate
			source.CreatedUpdatedBy,
			SYSDATETIMEOFFSET(), --UpdatedDate
			source.CreatedUpdatedBy
		);

		MERGE tblTransactionNotes AS target
		USING (
			SELECT 
				TransactionNoteGuid,
				TransactionGuid,
				Notes,
				AdditionalInformation,			
				CreatedUpdatedBy
			FROM @TransactionHeaders
			-- Only retrieve values from the table that have meaningful notes information
			-- This prevents us from creating records with empty information
			WHERE TransactionNoteGuid IS NOT NULL 
				OR ISNULL(Notes, '') != '' 
				OR ISNULL(AdditionalInformation, '') != ''
			) AS source
		ON source.TransactionNoteGuid = target.TransactionNoteGuid
		WHEN MATCHED THEN UPDATE SET
			Notes = source.Notes,
			AdditionalInformation = source.AdditionalInformation,
			UpdatedDate = SYSDATETIMEOFFSET(),
			UpdatedBy = source.CreatedUpdatedBy
		WHEN NOT MATCHED THEN INSERT 
		(
			TransactionGuid,
			Notes,
			AdditionalInformation,
			CreatedDate,
			CreatedBy,
			UpdatedDate,
			UpdatedBy
		)
		VALUES
		(
			source.TransactionGuid,
			source.Notes,
			source.AdditionalInformation,
			SYSDATETIMEOFFSET(), --CreatedDate
			source.CreatedUpdatedBy,
			SYSDATETIMEOFFSET(), --UpdatedDate
			source.CreatedUpdatedBy
		);
	
		MERGE tblTransactionUserData AS target
		USING (
			SELECT 
				TransactionUserDataGuid,
				TransactionGuid,
				UserData1, 
				UserData2, 
				UserData3, 
				UserData4, 
				UserData5, 
				UserData6, 
				UserData7,
				UserData8, 
				UserData9, 
				UserData10,
				UserData11,
				UserData12,
				UserData13,
				UserData14,
				UserData15,
				UserData16,
				UserData17,
				UserData18,
				UserData19,
				UserData20,
				UserData21,
				UserData22,
				UserData23,
				UserData24,
				CreatedUpdatedBy
			FROM @TransactionHeaders
			-- Only retrieve values from the table that have meaningful user data information
			-- This prevents us from creating records with empty information
			WHERE TransactionUserDataGuid IS NOT NULL 
				OR ISNULL(UserData1, '') != ''
				OR ISNULL(UserData2, '') != '' 
				OR ISNULL(UserData3, '') != '' 
				OR ISNULL(UserData4, '') != '' 
				OR ISNULL(UserData5, '') != '' 
				OR ISNULL(UserData6, '') != '' 
				OR ISNULL(UserData7, '') != '' 
				OR ISNULL(UserData8, '') != '' 
				OR ISNULL(UserData9, '') != '' 
				OR ISNULL(UserData10, '') != ''
				OR ISNULL(UserData11, '') != ''
				OR ISNULL(UserData12, '') != ''
				OR ISNULL(UserData13, '') != ''
				OR ISNULL(UserData14, '') != ''
				OR ISNULL(UserData15, '') != ''
				OR ISNULL(UserData16, '') != ''
				OR ISNULL(UserData17, '') != ''
				OR ISNULL(UserData18, '') != ''
				OR ISNULL(UserData19, '') != ''
				OR ISNULL(UserData20, '') != ''
				OR ISNULL(UserData21, '') != ''
				OR ISNULL(UserData22, '') != ''
				OR ISNULL(UserData23, '') != ''
				OR ISNULL(UserData24, '') != ''
			) AS source
		ON source.TransactionUserDataGuid = target.TransactionUserDataGuid
		WHEN MATCHED THEN UPDATE SET
			UserData1 = source.UserData1, 
			UserData2 = source.UserData2, 
			UserData3 = source.UserData3, 
			UserData4 = source.UserData4, 
			UserData5 = source.UserData5, 
			UserData6 = source.UserData6, 
			UserData7 = source.UserData7,
			UserData8 = source.UserData8, 
			UserData9 = source.UserData9, 
			UserData10 = source.UserData10,
			UserData11 = source.UserData11,
			UserData12 = source.UserData12,
			UserData13 = source.UserData13,
			UserData14 = source.UserData14,
			UserData15 = source.UserData15,
			UserData16 = source.UserData16,
			UserData17 = source.UserData17,
			UserData18 = source.UserData18,
			UserData19 = source.UserData19,
			UserData20 = source.UserData20,
			UserData21 = source.UserData21,
			UserData22 = source.UserData22,
			UserData23 = source.UserData23,
			UserData24 = source.UserData24,
			UpdatedDate = SYSDATETIMEOFFSET(),
			UpdatedBy = source.CreatedUpdatedBy
		WHEN NOT MATCHED THEN INSERT 
		(
			TransactionGuid,
			UserData1, 
			UserData2, 
			UserData3, 
			UserData4, 
			UserData5, 
			UserData6, 
			UserData7,
			UserData8, 
			UserData9, 
			UserData10,
			UserData11,
			UserData12,
			UserData13,
			UserData14,
			UserData15,
			UserData16,
			UserData17,
			UserData18,
			UserData19,
			UserData20,
			UserData21,
			UserData22,
			UserData23,
			UserData24,
			CreatedDate,
			CreatedBy,
			UpdatedDate,
			UpdatedBy,
			TransactionUserDataGuid
		)
		VALUES
		(
			source.TransactionGuid,
			source.UserData1, 
			source.UserData2, 
			source.UserData3, 
			source.UserData4, 
			source.UserData5, 
			source.UserData6, 
			source.UserData7,
			source.UserData8, 
			source.UserData9, 
			source.UserData10,
			source.UserData11,
			source.UserData12,
			source.UserData13,
			source.UserData14,
			source.UserData15,
			source.UserData16,
			source.UserData17,
			source.UserData18,
			source.UserData19,
			source.UserData20,
			source.UserData21,
			source.UserData22,
			source.UserData23,
			source.UserData24,
			SYSDATETIMEOFFSET(), --CreatedDate
			source.CreatedUpdatedBy,
			SYSDATETIMEOFFSET(), --UpdatedDate
			source.CreatedUpdatedBy,
			NEWID()
		);

		MERGE tblTransactionSignature AS target
		USING (
			SELECT 
				TransactionSignatureGuid,
				TransactionGuid,
				[Signature],	
				CreatedUpdatedBy
			FROM @TransactionHeaders
			-- Only retrieve values from the table that have meaningful signature information
			-- This prevents us from creating records with empty information
			WHERE TransactionSignatureGuid IS NOT NULL 
				OR [Signature] IS NOT NULL
			) AS source
		ON source.TransactionSignatureGuid = target.TransactionSignatureGuid
		WHEN MATCHED THEN UPDATE SET
			[Signature] = source.[Signature],
			UpdatedDate = SYSDATETIMEOFFSET(),
			UpdatedBy = source.CreatedUpdatedBy
		WHEN NOT MATCHED THEN INSERT 
		(
			TransactionGuid,
			[Signature],
			CreatedDate,
			CreatedBy,
			UpdatedDate,
			UpdatedBy
		)
		VALUES
		(
			source.TransactionGuid,
			source.[Signature],
			SYSDATETIMEOFFSET(), --CreatedDate
			source.CreatedUpdatedBy,
			SYSDATETIMEOFFSET(), --UpdatedDate
			source.CreatedUpdatedBy
		);

	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();   
		         
		IF (@_ErrNumber = 50000 AND  @_ErrMessage = 'Cannot insert/update duplicate DocumentNumber.')
		BEGIN
			RAISERROR(@_ErrMessage, 16, 1);
		END
		ELSE
		BEGIN     
			SET @_ErrProcName= ERROR_PROCEDURE();        
			SET @_ErrLineNumber = ERROR_LINE();            
			SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
							+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
							+ 'Procedure Name: dbo.usp_TransactionHeaderInsertUpdate' + CHAR(13)+CHAR(10)                  
							+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
			RAISERROR(@_ErrMessage, 16, 1);
		END      
	END CATCH    
END 
