CREATE PROCEDURE [dbo].[usp_TransactionLineItemsInsertUpdate]
(
	@TransactionLineItems dbo.TransactionLineItemsType READONLY
)
AS
BEGIN
	SET NOCOUNT ON
	
	BEGIN TRY

		MERGE tblTransactionLineItems AS target
		USING (
			SELECT 
				TransactionLineItemGuid,
				TransactionGuid,
				SequenceID,
				MeterStart,
				MeterStop,
				GrossQuantity,
				DeliveredGrossQuantity,
				Temperature,
				Vcf,
				Pressure,
				Density,
				Product,
				ProductCode,
				ProductType,
				ProductPrice,
				CLIN,
				NetQuantity,
				DeliveredNetQuantity,
				ContractNumber,
				DestinationRegistrationID,
				DestinationSerialNumber,
				DestinationEquipmentType,
				DestinationEquipmentModel,
				DestinationCompanyEquipmentID,
				DestinationCompartmentID,
				SourceRegistrationID,
				SourceSerialNumber,
				SourceEquipmentType,
				SourceEquipmentModel,
				SourceCompanyEquipmentID,
				SourceCompartmentID,
				MeterFactor,
				BatchNumber,
				DocumentNumber,
				LineFill,
				BottomVolume,
				NetCapacity,
				Customs,
				ArmNumber,
				LineNumber,
				OperatorID,
				TankStatus,
				MeterStartDateTime,
				MeterStopDateTime,
				Pit,
				RequestedDateTime,
				DispatchedDateTime,
				AcknowledgedDateTime,
				OnLocationTime,
				ValidationDateTime,
				CompletionDateTime,
				ReceiptVariance,
				DifferentialPressure,
				LoadRackVariance,
				RequestedBy,
				FreezePoint,
				DeleteFlag,
				StorageLocationID,
				MeterID,
				AdditiveProfileID,
				PresetAmount,
				EngineeringUnitsIndex,
				CustomerProductName,
				CustomerProductCode,
				TransactionInventoryDate,
				COAWaiver,
				COANote,
				COAID,
				Tax1,
				Tax2,
				Tax3,
				Tax4,
				Tax5,
				TransVersion,
				LoadingLocationID,
				ImproperAdditization,
				BrokenBlend,
				ContaminatePrompt,
				CompartmentsPreviouslyLoaded,
				CompartmentsEmpty,
				Flag01,
				Flag02,
				Flag03,
				Flag04,
				Flag05,
				Flag06,
				Number01,
				Number02,
				Number03,
				Number04,
				Number05,
				Number06,
				OdometerHours,
				EndDeliveryDate,
				RequestedDeliveryDate,
				InvoiceNumber,
				InvoiceLineNumber,
				AlternativeGrossVolume,
				AlternativeNetVolume,
				AlternativeUnits,
				TankLevel,
				TankLevelUnits,
				Date01,
				Date02,
				Date03,
				Date04,
				NonDomesticPrice,
				ExchangeRate,
				QualityTestNumber,
				Odometer,
				DeliveryLocation,
				Variance,
				PartialFill,
				MassQuantity,
				NetManualValueFlag,
				GrossManualValueFlag,
				MassManualValueFlag,
				VcfManualValueFlag,
				DeliveredGrossManualValueFlag,
				DeliveredNetManualValueFlag,
				LookupTransactionStatusIndex,
				LookupQualityIndex,
				StorageLocationTankGuid,
				AdditiveProfileGuid,
				DestinationCompartmentEquipmentGuid,
				DestinationEquipmentGuid,
				OperatorPersonnelGuid,
				ProductGuid,
				SourceCompartmentEquipmentGuid,
				SourceEquipmentGuid,
				CurrencyGuid,
				OrderReferenceTransactionLineItemGuid,
				LoadingLocationStationGuid,
				MeterGuid,
				PackageManualValueFlag,
				CleanLineItem,
				CleanLineDeductItem,
				CleanLineDeductQuantity,
				CleanLinePackQuantity,
				DualFuelingModeFlag,
				DualFuelingPrimaryFlag,
				EngineRunTime,
				FlowRate,
				FuelCompressionFactor,
				HydrantPressure,
				MobileDeviceID,
				MobileDeviceGuid,
				TemperatureQualityStatus,
				MeterStartObtainedAutomaticallyFlag,
				MeterStopObtainedAutomaticallyFlag,
				NetVolumeIndicator,
				CreatedUpdatedBy
			FROM @TransactionLineItems
			) AS source
		ON source.TransactionLineItemGuid = target.TransactionLineItemGuid
		WHEN MATCHED THEN UPDATE SET
			SequenceID = source.SequenceID,
			MeterStart = source.MeterStart,
			MeterStop = source.MeterStop,
			GrossQuantity = source.GrossQuantity,
			DeliveredGrossQuantity = source.DeliveredGrossQuantity,
			Temperature = source.Temperature,
			Vcf = source.Vcf,
			Pressure= source.Pressure,
			Density = source.Density,
			Product = source.Product,
			ProductCode = source.ProductCode,
			ProductType = source.ProductType,
			ProductPrice = source.ProductPrice,
			CLIN = source.CLIN,
			NetQuantity = source.NetQuantity,
			DeliveredNetQuantity = source.DeliveredNetQuantity,
			ContractNumber = source.ContractNumber,
			DestinationRegistrationID = source.DestinationRegistrationID,
			DestinationSerialNumber = source.DestinationSerialNumber,
			DestinationEquipmentType = source.DestinationEquipmentType,
			DestinationEquipmentModel = source.DestinationEquipmentModel,
			DestinationCompanyEquipmentID = source.DestinationCompanyEquipmentID,
			DestinationCompartmentID = source.DestinationCompartmentID,
			SourceRegistrationID = source.SourceRegistrationID,
			SourceSerialNumber = source.SourceSerialNumber,
			SourceEquipmentType = source.SourceEquipmentType,
			SourceEquipmentModel = source.SourceEquipmentModel,
			SourceCompanyEquipmentID = source.SourceCompanyEquipmentID,
			SourceCompartmentID = source.SourceCompartmentID,
			MeterFactor = source.MeterFactor,
			BatchNumber = source.BatchNumber,
			DocumentNumber = source.DocumentNumber,
			LineFill = source.LineFill,
			BottomVolume = source.BottomVolume,
			NetCapacity = source.NetCapacity,
			Customs = source.Customs,
			ArmNumber = source.ArmNumber,
			LineNumber = source.LineNumber,
			OperatorID = source.OperatorID,
			TankStatus = source.TankStatus,
			MeterStartDateTime = source.MeterStartDateTime,
			MeterStopDateTime = source.MeterStopDateTime,
			Pit = source.Pit,
			RequestedDateTime = source.RequestedDateTime,
			DispatchedDateTime = source.DispatchedDateTime,
			AcknowledgedDateTime = source.AcknowledgedDateTime,
			OnLocationTime = source.OnLocationTime,
			ValidationDateTime = source.ValidationDateTime,
			CompletionDateTime = source.CompletionDateTime,
			ReceiptVariance = source.ReceiptVariance,
			DifferentialPressure = source.DifferentialPressure,
			LoadRackVariance = source.LoadRackVariance,
			RequestedBy = source.RequestedBy,
			FreezePoint = source.FreezePoint,
			DeleteFlag = source.DeleteFlag,
			StorageLocationID = source.StorageLocationID,
			MeterID = source.MeterID,
			AdditiveProfileID = source.AdditiveProfileID,
			PresetAmount = source.PresetAmount,
			EngineeringUnitsIndex = source.EngineeringUnitsIndex,
			CustomerProductName = source.CustomerProductName,
			CustomerProductCode = source.CustomerProductCode,
			TransactionInventoryDate = source.TransactionInventoryDate,
			COAWaiver = source.COAWaiver,
			COANote = source.COANote,
			COAID = source.COAID,
			Tax1 = source.Tax1,
			Tax2 = source.Tax2,
			Tax3 = source.Tax3,
			Tax4 = source.Tax4,
			Tax5 = source.Tax5,
			TransVersion = source.TransVersion,
			LoadingLocationID = source.LoadingLocationID,
			ImproperAdditization = source.ImproperAdditization,
			BrokenBlend = source.BrokenBlend,
			ContaminatePrompt = source.ContaminatePrompt,
			CompartmentsPreviouslyLoaded = source.CompartmentsPreviouslyLoaded,
			CompartmentsEmpty = source.CompartmentsEmpty,
			Flag01 = source.Flag01,
			Flag02 = source.Flag02,
			Flag03 = source.Flag03,
			Flag04 = source.Flag04,
			Flag05 = source.Flag05,
			Flag06 = source.Flag06,
			Number01 = source.Number01,
			Number02 = source.Number02,
			Number03 = source.Number03,
			Number04 = source.Number04,
			Number05 = source.Number05,
			Number06 = source.Number06,
			OdometerHours = source.OdometerHours,
			EndDeliveryDate = source.EndDeliveryDate,
			RequestedDeliveryDate = source.RequestedDeliveryDate,
			InvoiceNumber = source.InvoiceNumber,
			InvoiceLineNumber = source.InvoiceLineNumber,
			AlternativeGrossVolume = source.AlternativeGrossVolume,
			AlternativeNetVolume = source.AlternativeNetVolume,
			AlternativeUnits = source.AlternativeUnits,
			TankLevel = source.TankLevel,
			TankLevelUnits = source.TankLevelUnits,
			Date01 = source.Date01,
			Date02 = source.Date02,
			Date03 = source.Date03,
			Date04 = source.Date04,
			NonDomesticPrice = source.NonDomesticPrice,
			ExchangeRate = source.ExchangeRate,
			QualityTestNumber = source.QualityTestNumber,
			Odometer = source.Odometer,
			DeliveryLocation = source.DeliveryLocation,
			Variance = source.Variance,
			PartialFill = source.PartialFill,
			MassQuantity = source.MassQuantity,
			NetManualValueFlag = source.NetManualValueFlag,
			GrossManualValueFlag = source.GrossManualValueFlag,
			MassManualValueFlag = source.MassManualValueFlag,
			VcfManualValueFlag = source.VcfManualValueFlag,
			DeliveredGrossManualValueFlag = source.DeliveredGrossManualValueFlag,
			DeliveredNetManualValueFlag = source.DeliveredNetManualValueFlag,
			LookupTransactionStatusIndex = source.LookupTransactionStatusIndex,
			LookupQualityIndex = source.LookupQualityIndex,
			StorageLocationTankGuid = source.StorageLocationTankGuid,
			AdditiveProfileGuid = source.AdditiveProfileGuid,
			DestinationCompartmentEquipmentGuid = source.DestinationCompartmentEquipmentGuid,
			DestinationEquipmentGuid = source.DestinationEquipmentGuid,
			OperatorPersonnelGuid = source.OperatorPersonnelGuid,
			ProductGuid = source.ProductGuid,
			SourceCompartmentEquipmentGuid = source.SourceCompartmentEquipmentGuid,
			SourceEquipmentGuid = source.SourceEquipmentGuid,
			CurrencyGuid = source.CurrencyGuid,
			OrderReferenceTransactionLineItemGuid = source.OrderReferenceTransactionLineItemGuid,
			LoadingLocationStationGuid = source.LoadingLocationStationGuid,
			MeterGuid = source.MeterGuid,
			PackageManualValueFlag = source.PackageManualValueFlag,
			CleanLineItem = source.CleanLineItem,
			CleanLineDeductItem = source.CleanLineDeductItem,
			CleanLineDeductQuantity = source.CleanLineDeductQuantity,
			CleanLinePackQuantity = source.CleanLinePackQuantity,
			DualFuelingModeFlag = source.DualFuelingModeFlag,
			DualFuelingPrimaryFlag = source.DualFuelingPrimaryFlag,
			EngineRunTime = source.EngineRunTime,
			FlowRate = source.FlowRate,
			FuelCompressionFactor = source.FuelCompressionFactor,
			HydrantPressure = source.HydrantPressure,
			MobileDeviceID = source.MobileDeviceID,
			MobileDeviceGuid = source.MobileDeviceGuid,
			TemperatureQualityStatus = source.TemperatureQualityStatus,
			MeterStartObtainedAutomaticallyFlag = source.MeterStartObtainedAutomaticallyFlag,
			MeterStopObtainedAutomaticallyFlag = source.MeterStopObtainedAutomaticallyFlag,
			NetVolumeIndicator = source.NetVolumeIndicator,
			UpdatedDate = SYSDATETIMEOFFSET(),
			UpdatedBy = source.CreatedUpdatedBy
		WHEN NOT MATCHED THEN INSERT 
		(
			TransactionLineItemGuid,
			TransactionGuid,
			SequenceID,
			MeterStart,
			MeterStop,
			GrossQuantity,
			DeliveredGrossQuantity,
			Temperature,
			Vcf,
			Pressure,
			Density,
			Product,
			ProductCode,
			ProductType,
			ProductPrice,
			CLIN,
			NetQuantity,
			DeliveredNetQuantity,
			ContractNumber,
			DestinationRegistrationID,
			DestinationSerialNumber,
			DestinationEquipmentType,
			DestinationEquipmentModel,
			DestinationCompanyEquipmentID,
			DestinationCompartmentID,
			SourceRegistrationID,
			SourceSerialNumber,
			SourceEquipmentType,
			SourceEquipmentModel,
			SourceCompanyEquipmentID,
			SourceCompartmentID,
			MeterFactor,
			BatchNumber,
			DocumentNumber,
			LineFill,
			BottomVolume,
			NetCapacity,
			Customs,
			ArmNumber,
			LineNumber,
			OperatorID,
			TankStatus,
			MeterStartDateTime,
			MeterStopDateTime,
			Pit,
			RequestedDateTime,
			DispatchedDateTime,
			AcknowledgedDateTime,
			OnLocationTime,
			ValidationDateTime,
			CompletionDateTime,
			ReceiptVariance,
			DifferentialPressure,
			LoadRackVariance,
			RequestedBy,
			FreezePoint,
			DeleteFlag,
			StorageLocationID,
			MeterID,
			AdditiveProfileID,
			PresetAmount,
			EngineeringUnitsIndex,
			CustomerProductName,
			CustomerProductCode,
			TransactionInventoryDate,
			COAWaiver,
			COANote,
			COAID,
			Tax1,
			Tax2,
			Tax3,
			Tax4,
			Tax5,
			TransVersion,
			LoadingLocationID,
			ImproperAdditization,
			BrokenBlend,
			ContaminatePrompt,
			CompartmentsPreviouslyLoaded,
			CompartmentsEmpty,
			Flag01,
			Flag02,
			Flag03,
			Flag04,
			Flag05,
			Flag06,
			Number01,
			Number02,
			Number03,
			Number04,
			Number05,
			Number06,
			OdometerHours,
			EndDeliveryDate,
			RequestedDeliveryDate,
			InvoiceNumber,
			InvoiceLineNumber,
			AlternativeGrossVolume,
			AlternativeNetVolume,
			AlternativeUnits,
			TankLevel,
			TankLevelUnits,
			Date01,
			Date02,
			Date03,
			Date04,
			NonDomesticPrice,
			ExchangeRate,
			QualityTestNumber,
			Odometer,
			DeliveryLocation,
			Variance,
			PartialFill,
			MassQuantity,
			NetManualValueFlag,
			GrossManualValueFlag,
			MassManualValueFlag,
			VcfManualValueFlag,
			DeliveredGrossManualValueFlag,
			DeliveredNetManualValueFlag,
			LookupTransactionStatusIndex,
			LookupQualityIndex,
			StorageLocationTankGuid,
			AdditiveProfileGuid,
			DestinationCompartmentEquipmentGuid,
			DestinationEquipmentGuid,
			OperatorPersonnelGuid,
			ProductGuid,
			SourceCompartmentEquipmentGuid,
			SourceEquipmentGuid,
			CurrencyGuid,
			OrderReferenceTransactionLineItemGuid,
			LoadingLocationStationGuid,
			MeterGuid,
			PackageManualValueFlag,
			CleanLineItem,
			CleanLineDeductItem,
			CleanLineDeductQuantity,
			CleanLinePackQuantity,
			DualFuelingModeFlag,
			DualFuelingPrimaryFlag,
			EngineRunTime,
			FlowRate,
			FuelCompressionFactor,
			HydrantPressure,
			MobileDeviceID,
			MobileDeviceGuid,
			TemperatureQualityStatus,
			MeterStartObtainedAutomaticallyFlag,
			MeterStopObtainedAutomaticallyFlag,
			NetVolumeIndicator,
			CreatedDate,
			CreatedBy,
			UpdatedDate,
			UpdatedBy
		)
		VALUES
		(
			source.TransactionLineItemGuid,
			source.TransactionGuid,
			source.SequenceID,
			source.MeterStart,
			source.MeterStop,
			source.GrossQuantity,
			source.DeliveredGrossQuantity,
			source.Temperature,
			source.Vcf,
			source.Pressure,
			source.Density,
			source.Product,
			source.ProductCode,
			source.ProductType,
			source.ProductPrice,
			source.CLIN,
			source.NetQuantity,
			source.DeliveredNetQuantity,
			source.ContractNumber,
			source.DestinationRegistrationID,
			source.DestinationSerialNumber,
			source.DestinationEquipmentType,
			source.DestinationEquipmentModel,
			source.DestinationCompanyEquipmentID,
			source.DestinationCompartmentID,
			source.SourceRegistrationID,
			source.SourceSerialNumber,
			source.SourceEquipmentType,
			source.SourceEquipmentModel,
			source.SourceCompanyEquipmentID,
			source.SourceCompartmentID,
			source.MeterFactor,
			source.BatchNumber,
			source.DocumentNumber,
			source.LineFill,
			source.BottomVolume,
			source.NetCapacity,
			source.Customs,
			source.ArmNumber,
			source.LineNumber,
			source.OperatorID,
			source.TankStatus,
			source.MeterStartDateTime,
			source.MeterStopDateTime,
			source.Pit,
			source.RequestedDateTime,
			source.DispatchedDateTime,
			source.AcknowledgedDateTime,
			source.OnLocationTime,
			source.ValidationDateTime,
			source.CompletionDateTime,
			source.ReceiptVariance,
			source.DifferentialPressure,
			source.LoadRackVariance,
			source.RequestedBy,
			source.FreezePoint,
			source.DeleteFlag,
			source.StorageLocationID,
			source.MeterID,
			source.AdditiveProfileID,
			source.PresetAmount,
			source.EngineeringUnitsIndex,
			source.CustomerProductName,
			source.CustomerProductCode,
			source.TransactionInventoryDate,
			source.COAWaiver,
			source.COANote,
			source.COAID,
			source.Tax1,
			source.Tax2,
			source.Tax3,
			source.Tax4,
			source.Tax5,
			source.TransVersion,
			source.LoadingLocationID,
			source.ImproperAdditization,
			source.BrokenBlend,
			source.ContaminatePrompt,
			source.CompartmentsPreviouslyLoaded,
			source.CompartmentsEmpty,
			source.Flag01,
			source.Flag02,
			source.Flag03,
			source.Flag04,
			source.Flag05,
			source.Flag06,
			source.Number01,
			source.Number02,
			source.Number03,
			source.Number04,
			source.Number05,
			source.Number06,
			source.OdometerHours,
			source.EndDeliveryDate,
			source.RequestedDeliveryDate,
			source.InvoiceNumber,
			source.InvoiceLineNumber,
			source.AlternativeGrossVolume,
			source.AlternativeNetVolume,
			source.AlternativeUnits,
			source.TankLevel,
			source.TankLevelUnits,
			source.Date01,
			source.Date02,
			source.Date03,
			source.Date04,
			source.NonDomesticPrice,
			source.ExchangeRate,
			source.QualityTestNumber,
			source.Odometer,
			source.DeliveryLocation,
			source.Variance,
			source.PartialFill,
			source.MassQuantity,
			source.NetManualValueFlag,
			source.GrossManualValueFlag,
			source.MassManualValueFlag,
			source.VcfManualValueFlag,
			source.DeliveredGrossManualValueFlag,
			source.DeliveredNetManualValueFlag,
			source.LookupTransactionStatusIndex,
			source.LookupQualityIndex,
			source.StorageLocationTankGuid,
			source.AdditiveProfileGuid,
			source.DestinationCompartmentEquipmentGuid,
			source.DestinationEquipmentGuid,
			source.OperatorPersonnelGuid,
			source.ProductGuid,
			source.SourceCompartmentEquipmentGuid,
			source.SourceEquipmentGuid,
			source.CurrencyGuid,
			source.OrderReferenceTransactionLineItemGuid,
			source.LoadingLocationStationGuid,
			source.MeterGuid,
			source.PackageManualValueFlag,
			source.CleanLineItem,
			source.CleanLineDeductItem,
			source.CleanLineDeductQuantity,
			source.CleanLinePackQuantity,
			source.DualFuelingModeFlag,
			source.DualFuelingPrimaryFlag,
			source.EngineRunTime,
			source.FlowRate,
			source.FuelCompressionFactor,
			source.HydrantPressure,
			source.MobileDeviceID,
			source.MobileDeviceGuid,
			source.TemperatureQualityStatus,
			source.MeterStartObtainedAutomaticallyFlag,
			source.MeterStopObtainedAutomaticallyFlag,
			source.NetVolumeIndicator,
			SYSDATETIMEOFFSET(), --CreatedDate
			source.CreatedUpdatedBy,
			SYSDATETIMEOFFSET(), --UpdatedDate
			source.CreatedUpdatedBy
		);
	
		MERGE tblTransactionLineItemUserData AS target
		USING (
			SELECT 
				TransactionLineItemUserDataGuid,
				TransactionLineItemGuid,
				UserData1, 
				UserData2, 
				UserData3, 
				UserData4, 
				UserData5, 
				UserData6, 
				UserData7,
				UserData8, 
				UserData9, 
				UserData10,
				UserData11,
				UserData12,
				UserData13,
				UserData14,
				UserData15,
				UserData16,
				UserData17,
				UserData18,
				UserData19,
				UserData20,
				UserData21,
				UserData22,
				UserData23,
				UserData24,
				CreatedUpdatedBy
			FROM @TransactionLineItems
			-- Only retrieve values from the table that have meaningful user data information
			-- This prevents us from creating records with empty information
			WHERE TransactionLineItemUserDataGuid IS NOT NULL 
				OR ISNULL(UserData1, '') != ''
				OR ISNULL(UserData2, '') != '' 
				OR ISNULL(UserData3, '') != '' 
				OR ISNULL(UserData4, '') != '' 
				OR ISNULL(UserData5, '') != '' 
				OR ISNULL(UserData6, '') != '' 
				OR ISNULL(UserData7, '') != '' 
				OR ISNULL(UserData8, '') != '' 
				OR ISNULL(UserData9, '') != '' 
				OR ISNULL(UserData10, '') != ''
				OR ISNULL(UserData11, '') != ''
				OR ISNULL(UserData12, '') != ''
				OR ISNULL(UserData13, '') != ''
				OR ISNULL(UserData14, '') != ''
				OR ISNULL(UserData15, '') != ''
				OR ISNULL(UserData16, '') != ''
				OR ISNULL(UserData17, '') != ''
				OR ISNULL(UserData18, '') != ''
				OR ISNULL(UserData19, '') != ''
				OR ISNULL(UserData20, '') != ''
				OR ISNULL(UserData21, '') != ''
				OR ISNULL(UserData22, '') != ''
				OR ISNULL(UserData23, '') != ''
				OR ISNULL(UserData24, '') != ''
			) AS source
		ON source.TransactionLineItemUserDataGuid = target.TransactionLineItemUserDataGuid
		WHEN MATCHED THEN UPDATE SET
			UserData1 = source.UserData1, 
			UserData2 = source.UserData2, 
			UserData3 = source.UserData3, 
			UserData4 = source.UserData4, 
			UserData5 = source.UserData5, 
			UserData6 = source.UserData6, 
			UserData7 = source.UserData7,
			UserData8 = source.UserData8, 
			UserData9 = source.UserData9, 
			UserData10 = source.UserData10,
			UserData11 = source.UserData11,
			UserData12 = source.UserData12,
			UserData13 = source.UserData13,
			UserData14 = source.UserData14,
			UserData15 = source.UserData15,
			UserData16 = source.UserData16,
			UserData17 = source.UserData17,
			UserData18 = source.UserData18,
			UserData19 = source.UserData19,
			UserData20 = source.UserData20,
			UserData21 = source.UserData21,
			UserData22 = source.UserData22,
			UserData23 = source.UserData23,
			UserData24 = source.UserData24,
			UpdatedDate = SYSDATETIMEOFFSET(),
			UpdatedBy = source.CreatedUpdatedBy
		WHEN NOT MATCHED THEN INSERT 
		(
			TransactionLineItemGuid,
			UserData1, 
			UserData2, 
			UserData3, 
			UserData4, 
			UserData5, 
			UserData6, 
			UserData7,
			UserData8, 
			UserData9, 
			UserData10,
			UserData11,
			UserData12,
			UserData13,
			UserData14,
			UserData15,
			UserData16,
			UserData17,
			UserData18,
			UserData19,
			UserData20,
			UserData21,
			UserData22,
			UserData23,
			UserData24,
			CreatedDate,
			CreatedBy,
			UpdatedDate,
			UpdatedBy		
		)
		VALUES
		(
			source.TransactionLineItemGuid,
			source.UserData1, 
			source.UserData2, 
			source.UserData3, 
			source.UserData4, 
			source.UserData5, 
			source.UserData6, 
			source.UserData7,
			source.UserData8, 
			source.UserData9, 
			source.UserData10,
			source.UserData11,
			source.UserData12,
			source.UserData13,
			source.UserData14,
			source.UserData15,
			source.UserData16,
			source.UserData17,
			source.UserData18,
			source.UserData19,
			source.UserData20,
			source.UserData21,
			source.UserData22,
			source.UserData23,
			source.UserData24,
			SYSDATETIMEOFFSET(), --CreatedDate
			source.CreatedUpdatedBy,
			SYSDATETIMEOFFSET(), --UpdatedDate
			source.CreatedUpdatedBy
		);

	END TRY
	BEGIN CATCH
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: dbo.usp_TransactionLineItemsInsertUpdate' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END 
