CREATE PROCEDURE [dbo].[usp_TransactionSubLineItemsInsertUpdate]
(
	@TransactionSubLineItems dbo.TransactionSubLineItemsType READONLY
)
AS
BEGIN
	SET NOCOUNT ON
	
	BEGIN TRY

		MERGE tblTransactionSubLineItems AS target
		USING (
			SELECT 
				TransactionSubLineItemGuid,
				TransactionLineItemGuid,
				TransactionGuid,			
				SequenceID,
				Product,
				ProductCode,
				ProductType,
				GrossQuantity,
				DeliveredGrossQuantity,
				NetQuantity,
				DeliveredNetQuantity,
				Vcf,
				Pressure,
				Density,
				Temperature,
				Customs,
				ArmNumber,
				LineNumber,
				BatchNumber,
				LineFill,
				BottomVolume,
				NetCapacity,
				TankStatus,
				MeterFactor,
				MeterStart,
				MeterStop,
				MeterStopDateTime,
				MeterStartDateTime,
				FreezePoint,
				DifferentialPressure,
				DosageRate,
				DeleteFlag,
				PresetAmount,
				StorageLocationID,
				MeterID,
				COAID,
				TransactionInventoryDate,
				Tax1,
				Tax2,
				Tax3,
				Tax4,
				Tax5,
				TransVersion,
				ImproperAdditization,
				BrokenBlend,
				Flag01,
				Flag02,
				Flag03,
				Flag04,
				Flag05,
				Flag06,
				Number01,
				Number02,
				Number03,
				Number04,
				Number05,
				Number06,
				Date01,
				Date02,
				Date03,
				Date04,
				MassQuantity,
				NetManualValueFlag,
				GrossManualValueFlag,
				MassManualValueFlag,
				VcfManualValueFlag,
				DeliveredGrossManualValueFlag,
				DeliveredNetManualValueFlag,
				LookupTransactionStatusIndex,
				LookupQualityIndex,
				ProductGuid,
				StorageLocationTankGuid,
				MeterGuid,
				PackageManualValueFlag,
				CleanLineItem,
				CleanLineDeductItem,
				CleanLineDeductQuantity,
				CleanLinePackQuantity,
				CreatedUpdatedBy
			FROM @TransactionSubLineItems
			) AS source
		ON source.TransactionSubLineItemGuid = target.TransactionSubLineItemGuid
		WHEN MATCHED THEN UPDATE SET
			SequenceID = source.SequenceID,
			Product = source.Product,
			ProductCode = source.ProductCode,
			ProductType = source.ProductType,
			GrossQuantity = source.GrossQuantity,
			DeliveredGrossQuantity = source.DeliveredGrossQuantity,
			NetQuantity = source.NetQuantity,
			DeliveredNetQuantity = source.DeliveredNetQuantity,
			Vcf = source.Vcf,
			Pressure = source.Pressure,
			Density = source.Density,
			Temperature = source.Temperature,
			Customs = source.Customs,
			ArmNumber = source.ArmNumber,
			LineNumber = source.LineNumber,
			BatchNumber = source.BatchNumber,
			LineFill = source.LineFill,
			BottomVolume = source.BottomVolume,
			NetCapacity = source.NetCapacity,
			TankStatus = source.TankStatus,
			MeterFactor = source.MeterFactor,
			MeterStart = source.MeterStart,
			MeterStop = source.MeterStop,
			MeterStopDateTime = source.MeterStopDateTime,
			MeterStartDateTime = source.MeterStartDateTime,
			FreezePoint = source.FreezePoint,
			DifferentialPressure = source.DifferentialPressure,
			DosageRate = source.DosageRate,
			DeleteFlag = source.DeleteFlag,
			PresetAmount = source.PresetAmount,
			StorageLocationID = source.StorageLocationID,
			MeterID = source.MeterID,
			COAID = source.COAID,
			TransactionInventoryDate = source.TransactionInventoryDate,
			Tax1 = source.Tax1,
			Tax2 = source.Tax2,
			Tax3 = source.Tax3,
			Tax4 = source.Tax4,
			Tax5 = source.Tax5,
			TransVersion = source.TransVersion,
			ImproperAdditization = source.ImproperAdditization,
			BrokenBlend = source.BrokenBlend,
			Flag01 = source.Flag01,
			Flag02 = source.Flag02,
			Flag03 = source.Flag03,
			Flag04 = source.Flag04,
			Flag05 = source.Flag05,
			Flag06 = source.Flag06,
			Number01 = source.Number01,
			Number02 = source.Number02,
			Number03 = source.Number03,
			Number04 = source.Number04,
			Number05 = source.Number05,
			Number06 = source.Number06,
			Date01 = source.Date01,
			Date02 = source.Date02,
			Date03 = source.Date03,
			Date04 = source.Date04,
			MassQuantity = source.MassQuantity,
			NetManualValueFlag = source.NetManualValueFlag,
			GrossManualValueFlag = source.GrossManualValueFlag,
			MassManualValueFlag = source.MassManualValueFlag,
			VcfManualValueFlag = source.VcfManualValueFlag,
			DeliveredGrossManualValueFlag = source.DeliveredGrossManualValueFlag,
			DeliveredNetManualValueFlag = source.DeliveredNetManualValueFlag,
			LookupTransactionStatusIndex = source.LookupTransactionStatusIndex,
			LookupQualityIndex = source.LookupQualityIndex,
			ProductGuid = source.ProductGuid,
			StorageLocationTankGuid = source.StorageLocationTankGuid,
			MeterGuid = source.MeterGuid,
			PackageManualValueFlag = source.PackageManualValueFlag,
			CleanLineItem = source.CleanLineItem,
			CleanLineDeductItem = source.CleanLineDeductItem,
			CleanLineDeductQuantity = source.CleanLineDeductQuantity,
			CleanLinePackQuantity = source.CleanLinePackQuantity,
			UpdatedDate = SYSDATETIMEOFFSET(),
			UpdatedBy = source.CreatedUpdatedBy
		WHEN NOT MATCHED THEN INSERT 
		(
			TransactionSubLineItemGuid,
			TransactionLineItemGuid,
			TransactionGuid,			
			SequenceID,
			Product,
			ProductCode,
			ProductType,
			GrossQuantity,
			DeliveredGrossQuantity,
			NetQuantity,
			DeliveredNetQuantity,
			Vcf,
			Pressure,
			Density,
			Temperature,
			Customs,
			ArmNumber,
			LineNumber,
			BatchNumber,
			LineFill,
			BottomVolume,
			NetCapacity,
			TankStatus,
			MeterFactor,
			MeterStart,
			MeterStop,
			MeterStopDateTime,
			MeterStartDateTime,
			FreezePoint,
			DifferentialPressure,
			DosageRate,
			DeleteFlag,
			PresetAmount,
			StorageLocationID,
			MeterID,
			COAID,
			TransactionInventoryDate,
			Tax1,
			Tax2,
			Tax3,
			Tax4,
			Tax5,
			TransVersion,
			ImproperAdditization,
			BrokenBlend,
			Flag01,
			Flag02,
			Flag03,
			Flag04,
			Flag05,
			Flag06,
			Number01,
			Number02,
			Number03,
			Number04,
			Number05,
			Number06,
			Date01,
			Date02,
			Date03,
			Date04,
			MassQuantity,
			NetManualValueFlag,
			GrossManualValueFlag,
			MassManualValueFlag,
			VcfManualValueFlag,
			DeliveredGrossManualValueFlag,
			DeliveredNetManualValueFlag,
			LookupTransactionStatusIndex,
			LookupQualityIndex,
			ProductGuid,
			StorageLocationTankGuid,
			MeterGuid,
			PackageManualValueFlag,
			CleanLineItem,
			CleanLineDeductItem,
			CleanLineDeductQuantity,
			CleanLinePackQuantity,
			CreatedDate,
			CreatedBy,
			UpdatedDate,
			UpdatedBy
		)
		VALUES
		(
			source.TransactionSubLineItemGuid,
			source.TransactionLineItemGuid,
			source.TransactionGuid,
			source.SequenceID,
			source.Product,
			source.ProductCode,
			source.ProductType,
			source.GrossQuantity,
			source.DeliveredGrossQuantity,
			source.NetQuantity,
			source.DeliveredNetQuantity,
			source.Vcf,
			source.Pressure,
			source.Density,
			source.Temperature,
			source.Customs,
			source.ArmNumber,
			source.LineNumber,
			source.BatchNumber,
			source.LineFill,
			source.BottomVolume,
			source.NetCapacity,
			source.TankStatus,
			source.MeterFactor,
			source.MeterStart,
			source.MeterStop,
			source.MeterStopDateTime,
			source.MeterStartDateTime,
			source.FreezePoint,
			source.DifferentialPressure,
			source.DosageRate,
			source.DeleteFlag,
			source.PresetAmount,
			source.StorageLocationID,
			source.MeterID,
			source.COAID,
			source.TransactionInventoryDate,
			source.Tax1,
			source.Tax2,
			source.Tax3,
			source.Tax4,
			source.Tax5,
			source.TransVersion,
			source.ImproperAdditization,
			source.BrokenBlend,
			source.Flag01,
			source.Flag02,
			source.Flag03,
			source.Flag04,
			source.Flag05,
			source.Flag06,
			source.Number01,
			source.Number02,
			source.Number03,
			source.Number04,
			source.Number05,
			source.Number06,
			source.Date01,
			source.Date02,
			source.Date03,
			source.Date04,
			source.MassQuantity,
			source.NetManualValueFlag,
			source.GrossManualValueFlag,
			source.MassManualValueFlag,
			source.VcfManualValueFlag,
			source.DeliveredGrossManualValueFlag,
			source.DeliveredNetManualValueFlag,
			source.LookupTransactionStatusIndex,
			source.LookupQualityIndex,
			source.ProductGuid,
			source.StorageLocationTankGuid,
			source.MeterGuid,
			source.PackageManualValueFlag,
			source.CleanLineItem,
			source.CleanLineDeductItem,
			source.CleanLineDeductQuantity,
			source.CleanLinePackQuantity,
			SYSDATETIMEOFFSET(), --CreatedDate
			source.CreatedUpdatedBy,
			SYSDATETIMEOFFSET(), --UpdatedDate
			source.CreatedUpdatedBy
		);

	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: dbo.usp_TransactionSubLineItemsInsertUpdate' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END 
