IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[trg_Audit_del_tblTransactionLineItems]')) 
	DROP TRIGGER [dbo].[trg_Audit_del_tblTransactionLineItems]
GO

CREATE TRIGGER [dbo].[trg_Audit_del_tblTransactionLineItems] ON [dbo].[tblTransactionLineItems] AFTER DELETE 
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE  @context_info varbinary(128)
	DECLARE  @context_info_str varchar(128)
	SELECT @Context_Info = CONTEXT_INFO()  
	SELECT @context_info_str = CAST (@context_info as varchar(128))  
	IF (@context_info_str = 'TransactionArchiving')
	BEGIN				
		RETURN	--The archiving of transactions is not logged
	END

	-- Verifies whether the trigger is active based on configuration and Audit
	-- rules which are resolved by the User Defined Function [fmaudit].[udf_DisableTriggerByAuditRule]
	IF [fmaudit].[udf_DisableTriggerByAuditRule]('dbo','tblTransactionLineItems','D')=1 
		RETURN
	DECLARE @_AuditEventType CHAR(1)
	,	@_AuditEventSequence TINYINT
	,	@_AuditSessionGUID UNIQUEIDENTIFIER
	,	@_AuditSessionTokenID UNIQUEIDENTIFIER
	,	@_AuditSiteGUID UNIQUEIDENTIFIER
	,	@_AuditGUID UNIQUEIDENTIFIER
	,	@_AuditDateTime DATETIMEOFFSET
	,	@_UserId NVARCHAR(100)
	,	@_AuditContext varbinary(128);
	SET @_AuditDateTime = SYSDATETIMEOFFSET();
	SET @_AuditEventType= 'D'; -- For Deletes 
	SET @_AuditEventSequence= 1; 
	SELECT	@_AuditSessionGUID=s.SessionGuid 
		,	@_AuditSessionTokenID=s.SessionTokenID 
		,	@_AuditSiteGUID=s.SiteGuid
		,	@_UserId=u.UserId
		,	@_AuditContext=s.SynchronizationNodeGuid
	FROM map.tblSessionToSQLProcess m 
	INNER JOIN  tblSessions s ON m.SessionGuid=s.SessionGuid 
	LEFT JOIN dbo.tblUsers u ON u.UserGuid=s.UserGuid 
	WHERE m.SqlServerSessionID=@@SPID;

	-- If the changes were made as a result of a trigger being fired, then the update was not being done as a result of a synchronized changed directly to this table. 
	-- Treat the change as a local change so it can be synchronized back to the remote system. 
	IF ((SELECT trigger_nestlevel()) > 1) 
	BEGIN 
		SET @_AuditContext = NULL 
	END 

	-- If it has been determined that this trigger is being fired in response to the synchronization process propagating changes from one system to another, 
	-- do not audit the changes.  When tblAuditLog is synchronized, it will contain the original audit event(s) any and all changes to this record. 
	IF (@_AuditContext IS NOT NULL) 
	BEGIN 
		RETURN
	END

	IF @_UserId IS NULL
		SET @_UserId = SUSER_NAME()
	INSERT INTO [fmaudit].tblTransactionLineItems (
		[SequenceID]
	,	[MeterStart]
	,	[MeterStop]
	,	[GrossQuantity]
	,	[Temperature]
	,	[Vcf]
	,	[Density]
	,	[Product]
	,	[ProductCode]
	,	[ProductType]
	,	[ProductPrice]
	,	[CLIN]
	,	[NetQuantity]
	,	[ContractNumber]
	,	[DestinationRegistrationID]
	,	[DestinationSerialNumber]
	,	[DestinationEquipmentType]
	,	[DestinationEquipmentModel]
	,	[DestinationCompanyEquipmentID]
	,	[DestinationCompartmentID]
	,	[SourceRegistrationID]
	,	[SourceSerialNumber]
	,	[SourceEquipmentType]
	,	[SourceEquipmentModel]
	,	[SourceCompanyEquipmentID]
	,	[SourceCompartmentID]
	,	[MeterFactor]
	,	[LineItemSequenceNumber]
	,	[BatchNumber]
	,	[DocumentNumber]
	,	[LineFill]
	,	[BottomVolume]
	,	[NetCapacity]
	,	[Customs]
	,	[ArmNumber]
	,	[LineNumber]
	,	[OperatorID]
	,	[TankStatus]
	,	[MeterStartDateTime]
	,	[MeterStopDateTime]
	,	[Pit]
	,	[RequestedDateTime]
	,	[DispatchedDateTime]
	,	[AcknowledgedDateTime]
	,	[OnLocationTime]
	,	[ValidationDateTime]
	,	[CompletionDateTime]
	,	[ReceiptVariance]
	,	[DifferentialPressure]
	,	[LoadRackVariance]
	,	[RequestedBy]
	,	[FreezePoint]
	,	[DeleteFlag]
	,	[StorageLocationID]
	,	[MeterID]
	,	[AdditiveProfileID]
	,	[CreatedBy]
	,	[CreatedDate]
	,	[UpdatedBy]
	,	[UpdatedDate]
	,	[PresetAmount]
	,	[EngineeringUnitsIndex]
	,	[CustomerProductName]
	,	[CustomerProductCode]
	,	[TransactionInventoryDate]
	,	[COAWaiver]
	,	[COANote]
	,	[COAID]
	,	[Tax1]
	,	[Tax2]
	,	[Tax3]
	,	[Tax4]
	,	[Tax5]
	,	[TransVersion]
	,	[LoadingLocationID]
	,	[ImproperAdditization]
	,	[BrokenBlend]
	,	[ContaminatePrompt]
	,	[CompartmentsPreviouslyLoaded]
	,	[CompartmentsEmpty]
	,	[Flag01]
	,	[Flag02]
	,	[Flag03]
	,	[Flag04]
	,	[Flag05]
	,	[Flag06]
	,	[Number01]
	,	[Number02]
	,	[Number03]
	,	[Number04]
	,	[Number05]
	,	[Number06]
	,	[OdometerHours]
	,	[EndDeliveryDate]
	,	[RequestedDeliveryDate]
	,	[InvoiceNumber]
	,	[InvoiceLineNumber]
	,	[AlternativeGrossVolume]
	,	[AlternativeNetVolume]
	,	[AlternativeUnits]
	,	[TankLevel]
	,	[TankLevelUnits]
	,	[Date01]
	,	[Date02]
	,	[Date03]
	,	[Date04]
	,	[NonDomesticPrice]
	,	[CurrencyUnit]
	,	[ExchangeRate]
	,	[QualityTestNumber]
	,	[Odometer]
	,	[DeliveryLocation]
	,	[Variance]
	,	[PartialFill]
	,	[MassQuantity]
	,	[NetManualValueFlag]
	,	[MassManualValueFlag]
	,	[GrossManualValueFlag]
	,	[VcfManualValueFlag]
	,	[TransactionLineItemGuid]
	,	[OriginalRowVersion]
	,	[LookupTransactionStatusIndex]
	,	[LookupQualityIndex]
	,	[StorageLocationTankGuid]
	,	[AdditiveProfileGuid]
	,	[DestinationCompartmentEquipmentGuid]
	,	[DestinationEquipmentGuid]
	,	[OperatorPersonnelGuid]
	,	[ProductGuid]
	,	[SourceCompartmentEquipmentGuid]
	,	[SourceEquipmentGuid]
	,	[TransactionGuid]
	,	[CurrencyGuid]
	,	[OrderReferenceTransactionLineItemGuid]
	,	[LoadingLocationStationGuid]
	,	[MeterGuid]
	,	[PackageManualValueFlag]
	,	[CleanLineItem]
	,	[CleanLineDeductItem]
	,	[CleanLineDeductQuantity]
	,	[CleanLinePackQuantity]
	,	[DualFuelingModeFlag]
	,	[DualFuelingPrimaryFlag]
	,	[EngineRunTime]
	,	[FlowRate]
	,	[FuelCompressionFactor]
	,	[HydrantPressure]
	,	[MobileDeviceID]
	,	[MobileDeviceGuid]
	,	[TemperatureQualityStatus]
	,	[MeterStartObtainedAutomaticallyFlag]
	,	[MeterStopObtainedAutomaticallyFlag]
	,	[_AuditEventType]
	,	[_AuditEventSequence]
	,	[_AuditSessionGUID]
	,	[_AuditSessionTokenID]
	,	[_AuditCreatedDate]
	,	[_AuditSiteGUID]
	,	[_AuditGUID]
	,	[_AuditUserId]
	,	[_AuditContext]
	)
	SELECT 
		d.[SequenceID]
	,	d.[MeterStart]
	,	d.[MeterStop]
	,	d.[GrossQuantity]
	,	d.[Temperature]
	,	d.[Vcf]
	,	d.[Density]
	,	d.[Product]
	,	d.[ProductCode]
	,	d.[ProductType]
	,	d.[ProductPrice]
	,	d.[CLIN]
	,	d.[NetQuantity]
	,	d.[ContractNumber]
	,	d.[DestinationRegistrationID]
	,	d.[DestinationSerialNumber]
	,	d.[DestinationEquipmentType]
	,	d.[DestinationEquipmentModel]
	,	d.[DestinationCompanyEquipmentID]
	,	d.[DestinationCompartmentID]
	,	d.[SourceRegistrationID]
	,	d.[SourceSerialNumber]
	,	d.[SourceEquipmentType]
	,	d.[SourceEquipmentModel]
	,	d.[SourceCompanyEquipmentID]
	,	d.[SourceCompartmentID]
	,	d.[MeterFactor]
	,	d.[LineItemSequenceNumber]
	,	d.[BatchNumber]
	,	d.[DocumentNumber]
	,	d.[LineFill]
	,	d.[BottomVolume]
	,	d.[NetCapacity]
	,	d.[Customs]
	,	d.[ArmNumber]
	,	d.[LineNumber]
	,	d.[OperatorID]
	,	d.[TankStatus]
	,	d.[MeterStartDateTime]
	,	d.[MeterStopDateTime]
	,	d.[Pit]
	,	d.[RequestedDateTime]
	,	d.[DispatchedDateTime]
	,	d.[AcknowledgedDateTime]
	,	d.[OnLocationTime]
	,	d.[ValidationDateTime]
	,	d.[CompletionDateTime]
	,	d.[ReceiptVariance]
	,	d.[DifferentialPressure]
	,	d.[LoadRackVariance]
	,	d.[RequestedBy]
	,	d.[FreezePoint]
	,	d.[DeleteFlag]
	,	d.[StorageLocationID]
	,	d.[MeterID]
	,	d.[AdditiveProfileID]
	,	d.[CreatedBy]
	,	d.[CreatedDate]
	,	d.[UpdatedBy]
	,	d.[UpdatedDate]
	,	d.[PresetAmount]
	,	d.[EngineeringUnitsIndex]
	,	d.[CustomerProductName]
	,	d.[CustomerProductCode]
	,	d.[TransactionInventoryDate]
	,	d.[COAWaiver]
	,	d.[COANote]
	,	d.[COAID]
	,	d.[Tax1]
	,	d.[Tax2]
	,	d.[Tax3]
	,	d.[Tax4]
	,	d.[Tax5]
	,	d.[TransVersion]
	,	d.[LoadingLocationID]
	,	d.[ImproperAdditization]
	,	d.[BrokenBlend]
	,	d.[ContaminatePrompt]
	,	d.[CompartmentsPreviouslyLoaded]
	,	d.[CompartmentsEmpty]
	,	d.[Flag01]
	,	d.[Flag02]
	,	d.[Flag03]
	,	d.[Flag04]
	,	d.[Flag05]
	,	d.[Flag06]
	,	d.[Number01]
	,	d.[Number02]
	,	d.[Number03]
	,	d.[Number04]
	,	d.[Number05]
	,	d.[Number06]
	,	d.[OdometerHours]
	,	d.[EndDeliveryDate]
	,	d.[RequestedDeliveryDate]
	,	d.[InvoiceNumber]
	,	d.[InvoiceLineNumber]
	,	d.[AlternativeGrossVolume]
	,	d.[AlternativeNetVolume]
	,	d.[AlternativeUnits]
	,	d.[TankLevel]
	,	d.[TankLevelUnits]
	,	d.[Date01]
	,	d.[Date02]
	,	d.[Date03]
	,	d.[Date04]
	,	d.[NonDomesticPrice]
	,	d.[CurrencyUnit]
	,	d.[ExchangeRate]
	,	d.[QualityTestNumber]
	,	d.[Odometer]
	,	d.[DeliveryLocation]
	,	d.[Variance]
	,	d.[PartialFill]
	,	d.[MassQuantity]
	,	d.[NetManualValueFlag]
	,	d.[MassManualValueFlag]
	,	d.[GrossManualValueFlag]
	,	d.[VcfManualValueFlag]
	,	d.[TransactionLineItemGuid]
	,	d.[_RowVersion]
	,	d.[LookupTransactionStatusIndex]
	,	d.[LookupQualityIndex]
	,	d.[StorageLocationTankGuid]
	,	d.[AdditiveProfileGuid]
	,	d.[DestinationCompartmentEquipmentGuid]
	,	d.[DestinationEquipmentGuid]
	,	d.[OperatorPersonnelGuid]
	,	d.[ProductGuid]
	,	d.[SourceCompartmentEquipmentGuid]
	,	d.[SourceEquipmentGuid]
	,	d.[TransactionGuid]
	,	d.[CurrencyGuid]
	,	d.[OrderReferenceTransactionLineItemGuid]
	,	d.[LoadingLocationStationGuid]
	,	d.[MeterGuid]
	,	d.[PackageManualValueFlag]
	,	d.[CleanLineItem]
	,	d.[CleanLineDeductItem]
	,	d.[CleanLineDeductQuantity]
	,	d.[CleanLinePackQuantity]
	,	d.[DualFuelingModeFlag]
	,	d.[DualFuelingPrimaryFlag]
	,	d.[EngineRunTime]
	,	d.[FlowRate]
	,	d.[FuelCompressionFactor]
	,	d.[HydrantPressure]
	,	d.[MobileDeviceID]
	,	d.[MobileDeviceGuid]
	,	d.[TemperatureQualityStatus]
	,	d.[MeterStartObtainedAutomaticallyFlag]
	,	d.[MeterStopObtainedAutomaticallyFlag]
	,	@_AuditEventType
	,	@_AuditEventSequence
	,	@_AuditSessionGUID
	,	@_AuditSessionTokenID
	,	@_AuditDateTime
	,	@_AuditSiteGUID
	,	NEWID()
	,	@_UserId
	,	@_AuditContext
	FROM deleted d
END
