IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[trg_Audit_del_tblTransactions]')) 
	DROP TRIGGER [dbo].[trg_Audit_del_tblTransactions]
GO


CREATE TRIGGER [dbo].[trg_Audit_del_tblTransactions] ON [dbo].[tblTransactions] AFTER DELETE 
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE  @context_info varbinary(128)
	DECLARE  @context_info_str varchar(128)
	SELECT @Context_Info = CONTEXT_INFO()  
	SELECT @context_info_str = CAST (@context_info as varchar(128))  
	IF (@context_info_str = 'TransactionArchiving')
	BEGIN				
		RETURN	--The archiving of transactions is not logged
	END

	-- Verifies whether the trigger is active based on configuration and Audit
	-- rules which are resolved by the User Defined Function [fmaudit].[udf_DisableTriggerByAuditRule]
	IF [fmaudit].[udf_DisableTriggerByAuditRule]('dbo','tblTransactions','D')=1 
		RETURN
	DECLARE @_AuditEventType CHAR(1)
	,	@_AuditEventSequence TINYINT
	,	@_AuditSessionGUID UNIQUEIDENTIFIER
	,	@_AuditSessionTokenID UNIQUEIDENTIFIER
	,	@_AuditSiteGUID UNIQUEIDENTIFIER
	,	@_AuditGUID UNIQUEIDENTIFIER
	,	@_AuditDateTime DATETIMEOFFSET
	,	@_UserId NVARCHAR(100)
	,	@_AuditContext varbinary(128);
	SET @_AuditDateTime = SYSDATETIMEOFFSET();
	SET @_AuditEventType= 'D'; -- For Deletes 
	SET @_AuditEventSequence= 1; 
	SELECT	@_AuditSessionGUID=s.SessionGuid 
		,	@_AuditSessionTokenID=s.SessionTokenID 
		,	@_AuditSiteGUID=s.SiteGuid
		,	@_UserId=u.UserId
		,	@_AuditContext=s.SynchronizationNodeGuid
	FROM map.tblSessionToSQLProcess m 
	INNER JOIN  tblSessions s ON m.SessionGuid=s.SessionGuid 
	LEFT JOIN dbo.tblUsers u ON u.UserGuid=s.UserGuid 
	WHERE m.SqlServerSessionID=@@SPID;

	-- If the changes were made as a result of a trigger being fired, then the update was not being done as a result of a synchronized changed directly to this table. 
	-- Treat the change as a local change so it can be synchronized back to the remote system. 
	IF ((SELECT trigger_nestlevel()) > 1) 
	BEGIN 
		SET @_AuditContext = NULL 
	END 

	-- If it has been determined that this trigger is being fired in response to the synchronization process propagating changes from one system to another, 
	-- do not audit the changes.  When tblAuditLog is synchronized, it will contain the original audit event(s) any and all changes to this record. 
	IF (@_AuditContext IS NOT NULL) 
	BEGIN 
		RETURN
	END

	IF @_UserId IS NULL
		SET @_UserId = SUSER_NAME()
	INSERT INTO [fmaudit].tblTransactions (
		[TransID]
	,	[AliasName]
	,	[SubType]
	,	[Site]
	,	[TransReferenceID]
	,	[InventoryDate]
	,	[ShipToID]
	,	[ShipToCode]
	,	[SupplierID]
	,	[SupplierCode]
	,	[CreatedDate]
	,	[CreatedBy]
	,	[RequestedDeliveryDate]
	,	[UpdatedDate]
	,	[UpdatedBy]
	,	[TransDateTime]
	,	[TransVersion]
	,	[SCACCode]
	,	[CardNumber]
	,	[ShipmentNumber]
	,	[ShipperID]
	,	[ShipperCode]
	,	[OwnerID]
	,	[OwnerCode]
	,	[ManagerID]
	,	[ManagerCode]
	,	[CarrierID]
	,	[CarrierCode]
	,	[ConjoinTransID]
	,	[ReversedTransID]
	,	[LinkedDocumentNumber]
	,	[ReversalType]
	,	[PONumber]
	,	[TimeIn]
	,	[TimeOut]
	,	[TimeEnd]
	,	[RoutingID]
	,	[TicketSource]
	,	[LoadID]
	,	[BillToID]
	,	[BillToCode]
	,	[DriverIdentificationNumber]
	,	[CreditAmount]
	,	[CardExpiration]
	,	[CardName]
	,	[CardType]
	,	[CashAmount]
	,	[RouteOriginationDate]
	,	[InternationalRouteIndicator]
	,	[PreviousRoutingID]
	,	[ShippingDocumentNumber]
	,	[DocumentNumber]
	,	[STD]
	,	[ETD]
	,	[STA]
	,	[ETA]
	,	[SFT]
	,	[FST]
	,	[EstimatedFuelingDuration]
	,	[DeleteFlag]
	,	[TicketMode]
	,	[DestinationRegistrationID1]
	,	[DestinationSerialNumber1]
	,	[DestinationEquipmentType1]
	,	[DestinationEquipmentModel1]
	,	[DestinationCompanyEquipmentID1]
	,	[DestinationRegistrationID2]
	,	[DestinationSerialNumber2]
	,	[DestinationEquipmentType2]
	,	[DestinationEquipmentModel2]
	,	[DestinationCompanyEquipmentID2]
	,	[DestinationRegistrationID3]
	,	[DestinationSerialNumber3]
	,	[DestinationEquipmentType3]
	,	[DestinationEquipmentModel3]
	,	[DestinationCompanyEquipmentID3]
	,	[SourceRegistrationID1]
	,	[SourceSerialNumber1]
	,	[SourceEquipmentType1]
	,	[SourceEquipmentModel1]
	,	[SourceCompanyEquipmentID1]
	,	[SourceRegistrationID2]
	,	[SourceSerialNumber2]
	,	[SourceEquipmentType2]
	,	[SourceEquipmentModel2]
	,	[SourceCompanyEquipmentID2]
	,	[SourceRegistrationID3]
	,	[SourceSerialNumber3]
	,	[SourceEquipmentType3]
	,	[SourceEquipmentModel3]
	,	[SourceCompanyEquipmentID3]
	,	[OperatorID]
	,	[EffectiveDate]
	,	[ExpirationDate]
	,	[ScheduledDate]
	,	[AutoComplete]
	,	[Flag01]
	,	[Flag02]
	,	[Flag03]
	,	[Flag04]
	,	[Flag05]
	,	[Flag06]
	,	[Number01]
	,	[Number02]
	,	[Number03]
	,	[Number04]
	,	[Number05]
	,	[Number06]
	,	[ContactFirstName]
	,	[ContactSurname]
	,	[Date01]
	,	[Date02]
	,	[Date03]
	,	[Date04]
	,	[LegacyNumber]
	,	[Country]
	,	[ContactInfo]
	,	[AssociatedDocNumber]
	,	[AssociatedCLIN]
	,	[SubmittedToAccounting]
	,	[FuelCardID]
	,	[AssociatedTransportOrderNumber]
	,	[RequestedDateTime]
	,	[DispatchedDateTime]
	,	[ErrorFlag]
	,	[OriginalRowVersion]
	,	[TransactionGuid]
	,	[SiteGuid]
	,	[LookupTransTypeIndex]
	,	[LookupTransactionStatusIndex]
	,	[LookupOriginApplicationIndex]
	,	[TransactionAliasGuid]
	,	[BillToCompanyGuid]
	,	[Destination1EquipmentGuid]
	,	[Destination2EquipmentGuid]
	,	[Destination3EquipmentGuid]
	,	[FinalStationIATAGuid]
	,	[FuelCardGuid]
	,	[ManagerCompanyGuid]
	,	[NextStationIATAGuid]
	,	[OperatorPersonnelGuid]
	,	[OriginStationIATAGuid]
	,	[OwnerCompanyGuid]
	,	[PreviousStationIATAGuid]
	,	[ShipperCompanyGuid]
	,	[ShipToCompanyGuid]
	,	[Source1EquipmentGuid]
	,	[Source2EquipmentGuid]
	,	[Source3EquipmentGuid]
	,	[SupplierCompanyGuid]
	,	[CarrierCompanyGuid]
	,	[ReasonCodeGuid]
	,	[OriginStationIATAID]
	,	[PreviousStationIATAID]
	,	[NextStationIATAID]
	,	[FinalStationIATAID]
	,	[OperatorName]
	,	[FuelAdditiveFlag]
	,	[IssuePoint]
	,	[IssuePointNumber]
	,	[RadioNumber]
	,	[GateID]
	,	[GateGuid]
	,	[ShippingMethod]
	,	[_AuditEventType]
	,	[_AuditEventSequence]
	,	[_AuditSessionGUID]
	,	[_AuditSessionTokenID]
	,	[_AuditCreatedDate]
	,	[_AuditSiteGUID]
	,	[_AuditGUID]
	,	[_AuditUserId]
	,	[_AuditContext]
	)
	SELECT 
		d.[TransID]
	,	d.[AliasName]
	,	d.[SubType]
	,	d.[Site]
	,	d.[TransReferenceID]
	,	d.[InventoryDate]
	,	d.[ShipToID]
	,	d.[ShipToCode]
	,	d.[SupplierID]
	,	d.[SupplierCode]
	,	d.[CreatedDate]
	,	d.[CreatedBy]
	,	d.[RequestedDeliveryDate]
	,	d.[UpdatedDate]
	,	d.[UpdatedBy]
	,	d.[TransDateTime]
	,	d.[TransVersion]
	,	d.[SCACCode]
	,	d.[CardNumber]
	,	d.[ShipmentNumber]
	,	d.[ShipperID]
	,	d.[ShipperCode]
	,	d.[OwnerID]
	,	d.[OwnerCode]
	,	d.[ManagerID]
	,	d.[ManagerCode]
	,	d.[CarrierID]
	,	d.[CarrierCode]
	,	d.[ConjoinTransID]
	,	d.[ReversedTransID]
	,	d.[LinkedDocumentNumber]
	,	d.[ReversalType]
	,	d.[PONumber]
	,	d.[TimeIn]
	,	d.[TimeOut]
	,	d.[TimeEnd]
	,	d.[RoutingID]
	,	d.[TicketSource]
	,	d.[LoadID]
	,	d.[BillToID]
	,	d.[BillToCode]
	,	d.[DriverIdentificationNumber]
	,	d.[CreditAmount]
	,	d.[CardExpiration]
	,	d.[CardName]
	,	d.[CardType]
	,	d.[CashAmount]
	,	d.[RouteOriginationDate]
	,	d.[InternationalRouteIndicator]
	,	d.[PreviousRoutingID]
	,	d.[ShippingDocumentNumber]
	,	d.[DocumentNumber]
	,	d.[STD]
	,	d.[ETD]
	,	d.[STA]
	,	d.[ETA]
	,	d.[SFT]
	,	d.[FST]
	,	d.[EstimatedFuelingDuration]
	,	d.[DeleteFlag]
	,	d.[TicketMode]
	,	d.[DestinationRegistrationID1]
	,	d.[DestinationSerialNumber1]
	,	d.[DestinationEquipmentType1]
	,	d.[DestinationEquipmentModel1]
	,	d.[DestinationCompanyEquipmentID1]
	,	d.[DestinationRegistrationID2]
	,	d.[DestinationSerialNumber2]
	,	d.[DestinationEquipmentType2]
	,	d.[DestinationEquipmentModel2]
	,	d.[DestinationCompanyEquipmentID2]
	,	d.[DestinationRegistrationID3]
	,	d.[DestinationSerialNumber3]
	,	d.[DestinationEquipmentType3]
	,	d.[DestinationEquipmentModel3]
	,	d.[DestinationCompanyEquipmentID3]
	,	d.[SourceRegistrationID1]
	,	d.[SourceSerialNumber1]
	,	d.[SourceEquipmentType1]
	,	d.[SourceEquipmentModel1]
	,	d.[SourceCompanyEquipmentID1]
	,	d.[SourceRegistrationID2]
	,	d.[SourceSerialNumber2]
	,	d.[SourceEquipmentType2]
	,	d.[SourceEquipmentModel2]
	,	d.[SourceCompanyEquipmentID2]
	,	d.[SourceRegistrationID3]
	,	d.[SourceSerialNumber3]
	,	d.[SourceEquipmentType3]
	,	d.[SourceEquipmentModel3]
	,	d.[SourceCompanyEquipmentID3]
	,	d.[OperatorID]
	,	d.[EffectiveDate]
	,	d.[ExpirationDate]
	,	d.[ScheduledDate]
	,	d.[AutoComplete]
	,	d.[Flag01]
	,	d.[Flag02]
	,	d.[Flag03]
	,	d.[Flag04]
	,	d.[Flag05]
	,	d.[Flag06]
	,	d.[Number01]
	,	d.[Number02]
	,	d.[Number03]
	,	d.[Number04]
	,	d.[Number05]
	,	d.[Number06]
	,	d.[ContactFirstName]
	,	d.[ContactSurname]
	,	d.[Date01]
	,	d.[Date02]
	,	d.[Date03]
	,	d.[Date04]
	,	d.[LegacyNumber]
	,	d.[Country]
	,	d.[ContactInfo]
	,	d.[AssociatedDocNumber]
	,	d.[AssociatedCLIN]
	,	d.[SubmittedToAccounting]
	,	d.[FuelCardID]
	,	d.[AssociatedTransportOrderNumber]
	,	d.[RequestedDateTime]
	,	d.[DispatchedDateTime]
	,	d.[ErrorFlag]
	,	d.[_RowVersion]
	,	d.[TransactionGuid]
	,	d.[SiteGuid]
	,	d.[LookupTransTypeIndex]
	,	d.[LookupTransactionStatusIndex]
	,	d.[LookupOriginApplicationIndex]
	,	d.[TransactionAliasGuid]
	,	d.[BillToCompanyGuid]
	,	d.[Destination1EquipmentGuid]
	,	d.[Destination2EquipmentGuid]
	,	d.[Destination3EquipmentGuid]
	,	d.[FinalStationIATAGuid]
	,	d.[FuelCardGuid]
	,	d.[ManagerCompanyGuid]
	,	d.[NextStationIATAGuid]
	,	d.[OperatorPersonnelGuid]
	,	d.[OriginStationIATAGuid]
	,	d.[OwnerCompanyGuid]
	,	d.[PreviousStationIATAGuid]
	,	d.[ShipperCompanyGuid]
	,	d.[ShipToCompanyGuid]
	,	d.[Source1EquipmentGuid]
	,	d.[Source2EquipmentGuid]
	,	d.[Source3EquipmentGuid]
	,	d.[SupplierCompanyGuid]
	,	d.[CarrierCompanyGuid]
	,	d.[ReasonCodeGuid]
	,	d.[OriginStationIATAID]
	,	d.[PreviousStationIATAID]
	,	d.[NextStationIATAID]
	,	d.[FinalStationIATAID]
	,	d.[OperatorName]
	,	d.[FuelAdditiveFlag]
	,	d.[IssuePoint]
	,	d.[IssuePointNumber]
	,	d.[RadioNumber]
	,	d.[GateID]
	,	d.[GateGuid]
	,	d.[ShippingMethod]
	,	@_AuditEventType
	,	@_AuditEventSequence
	,	@_AuditSessionGUID
	,	@_AuditSessionTokenID
	,	@_AuditDateTime
	,	@_AuditSiteGUID
	,	NEWID()
	,	@_UserId
	,	@_AuditContext
	FROM deleted d
END
