
/// <summary>
/// **************************************************************************************************************
/// File name:	DispatchContainerForm 
/// 
/// Comments:	Copyright (C) Varec, Inc. Norcross, GA, USA, 2009 
///            This file shall not be copied or reproduced in any form 
///				without the express written consent of Varec, Inc.
///				
/// Author(s):	Gray, Kendall, Schaal, Sang
/// 
/// Modification History:
///	Date:			By:						Reason:
///	----------	--------------------	--------------------------------------------
///	2009-10-19	C. Knight				WI# 6795 - Change transaction IDs to unpunctuated GUIDs, generated by the
///												FuelsManagerId class
///	 
///	2009-10-20	C. Knight				WI# 8457 - Fix appearing/disappearing row header numbers
///  
///	2009-10-22	C. Knight				WI# 8675 - Vehicle dropdown now suggest-appends, with event handler
///												to prevent selecting invalid equipment
///                                     
///	2009-10-22	C. Knight				WI# 8696 - Fix crash on canx 3 or more requests at once
///  
///	2009-10-23	C. Knight				WI# 8696 - Improve fix to use .Net locking and to minimize locked time
///  
///	10-29-2009	B. Schaal				Finished lock implementation to preclude data interaction problems
///	
/// **************************************************************************************************************
/// </summary>

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading;
using System.Windows.Forms;
using System.Diagnostics;
using System.Xml;
using System.Runtime.InteropServices;
using System.Xml.Serialization;

using FMBusinessObjects.DataObjects;
using FMBusinessObjects.Exceptions;
using FMBusinessObjects.ServiceRequests;
using FMBusinessObjects.UtilityObjects;
using FMBusinessObjects.ChannelFactories;
using FMBusinessObjects.BusinessInterfaces;

namespace DispatchPrototype
{
	internal struct transactionIdAndRequestTypeType
	{
		public string transactionID;
		public string requestType;
	}

	public partial class DispatchContainerForm : FMBaseForm
	{
		delegate void ShowReminderFormCallback ( );

		public TodaysAppointmentsCollectionClass TodaysAppointmentsCollection = new TodaysAppointmentsCollectionClass ( );
		protected Thread SchedulerMessageThread = null;
		protected ManualResetEvent KillEvent = null;
		private int childFormNumber = 0;
		private int AppointmentWarnPeriod = 15;	// Minutes
		DateTime CurrentSelectedBeginDatePicker;
		DateTime CurrentSelectedEndDatePicker;

		public static DispatchTransactionsSR dispatchSR = null;

		public DispatchDataAccess DataAccess { get; set; }

		private ContextMenuStrip PopupContextMenuForDataGrid = new ContextMenuStrip ( );

		public static string UserID = string.Empty;

		private DateTime OperationLockDate = System.DateTime.UtcNow;

		// there are 22 columns and we only need to store the display index if it changes
		const int GRID1_NUMCOLS = 40;
		private int[] dataGridView1ColumnPositions = new int[GRID1_NUMCOLS];
		private int[] dataGridView1ColumnWidths = new int[GRID1_NUMCOLS];

		public DispatchContainerForm ( )
		{
			GetSecurity ( );

			GetDisplayGridColumnPositions ( );

			string WarnPeriod = ConfigurationManager.AppSettings["AppointmentWarningPeriod"] == null ? null : ConfigurationManager.AppSettings["AppointmentWarningPeriod"];

			if (WarnPeriod == null)
				throw new Exception ( "AppointmentWarningPeriod not in AppSettings" );

			if (WarnPeriod.Length > 0)
				AppointmentWarnPeriod = System.Convert.ToInt32 ( WarnPeriod );

			InitializeComponent ( );

			// format data grid dates based on site configuration (IGO 2010-Aug-16)
			GetSiteDateTimeFormatInfo ( );
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyleShortDate = new System.Windows.Forms.DataGridViewCellStyle ( );
			dataGridViewCellStyleShortDate.Format = SiteDateTimeFormatInfo.ShortDatePattern;
			dataGridViewCellStyleShortDate.NullValue = null;
			this.Column2.DefaultCellStyle = dataGridViewCellStyleShortDate;

			// format date controls based on site configuration (IGO 2010-Aug-13)
			BeginDatePicker.CustomFormat = SiteDateTimeFormatInfo.ShortDatePattern;
			BeginDatePicker.Format = DateTimePickerFormat.Custom;
			EndDatePicker.CustomFormat = SiteDateTimeFormatInfo.ShortDatePattern;
			EndDatePicker.Format = DateTimePickerFormat.Custom;

			FMChannelFactory<ISites> sitesClient = new FMChannelFactory<ISites> ( );
			ISites sites = sitesClient.CreateProxy ( );

			SiteClass site = sites.Get(Security, Security.SiteGuid, false, false, false);

			OperationLockDate = System.Convert.ToDateTime ( site.OperationalLockDate );

			dataGridView1.RowHeadersDefaultCellStyle.Padding = new Padding ( 0 );
			dataGridView1.CellFormatting += new DataGridViewCellFormattingEventHandler ( dataGridView1_CellFormatting );
			dataGridView1.RowHeaderMouseDoubleClick += new DataGridViewCellMouseEventHandler ( dataGridView1_RowHeaderMouseDoubleClick );
			dataGridView1.CellDoubleClick += new DataGridViewCellEventHandler ( dataGridView1_CellDoubleClick );
			dataGridView1.SelectionChanged += new EventHandler ( dataGridView1_SelectionChanged );
			dataGridView1.CellClick += new DataGridViewCellEventHandler ( dataGridView1_CellClick );

			GetColumnWidthsForGrid ( );

			// restore the column positions to what the user had last time
			for (int iLoop = 0; iLoop < GRID1_NUMCOLS; iLoop++)
			{
				dataGridView1.Columns[iLoop].DisplayIndex = dataGridView1ColumnPositions[iLoop];
				dataGridView1.Columns[iLoop].Width = dataGridView1ColumnWidths[iLoop];
			}

			// we enable this here so we do not get 22 events for each index that we have set above
			dataGridView1.ColumnDisplayIndexChanged += new DataGridViewColumnEventHandler ( dataGridView1_ColumnDisplayIndexChanged );

			// launch the thread for handling the schedule messages
			SchedulerMessageThread = new Thread ( SchedulerMessageProcessScan );
			SchedulerMessageThread.Start ( );
			AddAddInItemsToAddInMenu ( );

			// MOD specific functionality (IGO 2010-Sep-21)
			if (TargetCustomer.MOD == base.GetTargetCustomer ( ))
			{
				FMChannelFactory<IDataDictionariesClass> dataDictionaryClient = new FMChannelFactory<IDataDictionariesClass> ( );
				IDataDictionariesClass datadictionary = dataDictionaryClient.CreateProxy ( );

				// Update menu items based on the data dictionary for the current site
				string requestdd = datadictionary.Get ( site.IdentityGuid, "Request" );
				string transientdd = datadictionary.Get(site.IdentityGuid, "Transient");
				string fastlogdd = datadictionary.Get(site.IdentityGuid, "Fast Log");
				string fastlogfilldd = datadictionary.Get(site.IdentityGuid, "Fast Log Fillstand");

				this.requestRefuelToolStripMenuItem.Text = requestdd;
				this.transientToolStripMenuItem.Text = transientdd;
				this.fastLogToolStripMenuItem.Text = fastlogdd;
				this.fastLogFillstandToolStripMenuItem.Text = fastlogfilldd;

				// Update toolbar buttons/tooltips based on the data dictionary for the current site
				this.toolStripRequestRefuelButton.Text = requestdd;
				this.toolStripRequestRefuelButton.ToolTipText = requestdd + " F2";
				this.toolStripTransientButton.Text = transientdd;
				this.toolStripTransientButton.ToolTipText = transientdd + " F4";
				this.toolStripFastLogButton.Text = fastlogdd;
				this.toolStripFastLogButton.ToolTipText = fastlogdd + " F9";
				this.toolStripFastLofFillstandButton.Text = fastlogfilldd;
				this.toolStripFastLofFillstandButton.ToolTipText = fastlogfilldd + " Shift+F9";

				// Update the grid columns based on the data dictionary for the current site
				this.MDS.HeaderText = datadictionary.Get ( site.IdentityGuid, "MDS" );
				this.Column5.HeaderText = datadictionary.Get(site.IdentityGuid, "Location");
				this.DODAAC.HeaderText = datadictionary.Get(site.IdentityGuid, "DODAAC");
				this.SuppDODAAC.HeaderText = datadictionary.Get(site.IdentityGuid, "Supp DODAAC");
				this.BOS.HeaderText = datadictionary.Get(site.IdentityGuid, "BOS");

				// Remove all columns that are removed from the fuel request dialogs per the design document
				// Serial Number 
				this.SerialNum.Visible = false;
				// Iss Pt
				this.IssPt.Visible = false;
				// Iss Pt Num
				this.IssPtNum.Visible = false;
				// Signal Code
				this.SignalCode.Visible = false;
				// USE Code
				this.USECode.Visible = false;
				// Fund Code
				this.FundCode.Visible = false;
				// Card No
				this.CardNumber.Visible = false;
				// RPT/TEC/APC
				this.RPTTECAPC.Visible = false;
				// Fuel Additive Flag
				this.FuelAdditiveFlag.Visible = false;
			}
		}


		private void DispatchContainerForm_FormClosing ( object sender, FormClosingEventArgs e )
		{
			StoreDisplayGridColumnPositions ( );
			SetColumnWidthsForGridFromGrid ( );
			StoreGrid1ColumnWidths ( );
			Logout ( );
		}

		void dataGridView1_CellClick ( object sender, DataGridViewCellEventArgs e )
		{
			if (e.RowIndex == -1 && e.ColumnIndex == -1)
			{
				dataGridView1.Sort ( dataGridView1.Columns["Requested"], ListSortDirection.Ascending );
				foreach (DataGridViewRow Row in dataGridView1.SelectedRows)
				{
					Row.Selected = false;
				}
			}
		}

		void dataGridView1_SelectionChanged ( object sender, EventArgs e )
		{
			try
			{
				if (dataGridView1.SelectedRows.Count > 0)
				{
					SetPopupMenuEnableDisable ( );

					// Set the cancel and relog menu availability
					cancelToolStripMenuItem.Enabled = true;
					toolStripCancelButton.Enabled = true;
					relogToolStripMenuItem.Enabled = true;
					toolStripRelogButton.Enabled = true;

					lock (dataGridView1)
					{
						foreach (DataGridViewRow Row in dataGridView1.SelectedRows)
						{
							DataRowView dataRow = (DataRowView) Row.DataBoundItem;

							TransactionStatus status = (TransactionStatus) dataRow["TransactionStatusInt"];

							// if any selected transaction has a status of posted disable everything
							if (status == TransactionStatus.Posted)
							{
								cancelToolStripMenuItem.Enabled = false;
								toolStripCancelButton.Enabled = false;
								relogToolStripMenuItem.Enabled = false;
								toolStripRelogButton.Enabled = false;
								break;
							}

							if (status == TransactionStatus.Completed ||
								status == TransactionStatus.Cancelled)
							{
								cancelToolStripMenuItem.Enabled = false;
								toolStripCancelButton.Enabled = false;
								break;
							}

							short TransTypeID = (short) dataRow["TransTypeID"];
							if (TransTypeID != 4 && TransTypeID != 6)
							{
								relogToolStripMenuItem.Enabled = false;
								toolStripRelogButton.Enabled = false;
							}
						}
					}
				}
				else
				{
					cancelToolStripMenuItem.Enabled = false;
					toolStripCancelButton.Enabled = false;
					relogToolStripMenuItem.Enabled = false;
					toolStripRelogButton.Enabled = false;
				}

			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}
		}

		void dataGridView1_CellDoubleClick ( object sender, DataGridViewCellEventArgs e )
		{
			try
			{
				RowDoubleClicked ( e.RowIndex );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}
		}

		void dataGridView1_CellFormatting ( object sender, DataGridViewCellFormattingEventArgs e )
		{
			// Transactions need to be displayed in different colors by requirement
			// Red = open defuel
			// Gray = canceled or Complete requests
			// Blue = open refuel
			// Black = other dispatch transactions

			// Find the data record
			DataRowView row = (DataRowView) dataGridView1.Rows[e.RowIndex].DataBoundItem;

			// Set the appropriate color
			string aliasName = (string) row["AliasName"];
			TransactionStatus status = (TransactionStatus) Enum.Parse ( typeof ( TransactionStatus ), (string) row["TransactionStatus"] );
			bool transactionStatusOpen = TransactionStatusOpen ( status );

			e.CellStyle.SelectionBackColor = Color.Black;

			if (aliasName.Equals ( "Defuel" ) && transactionStatusOpen)
			{
				e.CellStyle.ForeColor = Color.Red;
				e.CellStyle.SelectionForeColor = Color.Cyan;
			}
			else if (aliasName.Equals ( "Refuel" ) && transactionStatusOpen)
			{
				e.CellStyle.ForeColor = Color.Blue;
				e.CellStyle.SelectionForeColor = Color.Yellow;
			}
			else if (transactionStatusOpen == false)
			{
				e.CellStyle.ForeColor = Color.Gray;
				e.CellStyle.SelectionForeColor = Color.Gray;
			}
			else
			{
				e.CellStyle.ForeColor = Color.Black;
				e.CellStyle.SelectionForeColor = Color.White;
			}

		}

		public static bool TransactionStatusOpen ( TransactionStatus status )
		{
			bool bClosed = status == TransactionStatus.Cancelled
			|| status == TransactionStatus.Closed
			|| status == TransactionStatus.Completed
			|| status == TransactionStatus.Posted
			|| status == TransactionStatus.OnHold;

			return !bClosed;

		}

		private void ShowNewForm ( object sender, EventArgs e )
		{
			Form childForm = new Form ( );
			childForm.MdiParent = this;
			childForm.Text = "Window " + childFormNumber++;
			childForm.Show ( );
		}

		private void OpenFile ( object sender, EventArgs e )
		{
			OpenFileDialog openFileDialog = new OpenFileDialog ( );
			openFileDialog.InitialDirectory = Environment.GetFolderPath ( Environment.SpecialFolder.Personal );
			openFileDialog.Filter = "Text Files (*.txt)|*.txt|All Files (*.*)|*.*";
			if (openFileDialog.ShowDialog ( this ) == DialogResult.OK)
			{
				string FileName = openFileDialog.FileName;
			}
		}

		private void SaveAsToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			SaveFileDialog saveFileDialog = new SaveFileDialog ( );
			saveFileDialog.InitialDirectory = Environment.GetFolderPath ( Environment.SpecialFolder.Personal );
			saveFileDialog.Filter = "Text Files (*.txt)|*.txt|All Files (*.*)|*.*";
			if (saveFileDialog.ShowDialog ( this ) == DialogResult.OK)
			{
				string FileName = saveFileDialog.FileName;
			}
		}

		void changeOfOperatorToolStripMenuItem_Click ( object sender, System.EventArgs e )
		{
			try
			{
				ChangeOperatorStatusForm changeForm = new ChangeOperatorStatusForm ( );
				changeForm.ShowDialog ( this );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}
		}

		private void ExitToolsStripMenuItem_Click ( object sender, EventArgs e )
		{
			this.Close ( );
		}

		private void Logout ( )
		{
			AppDomain appDomain = AppDomain.CurrentDomain;
			SecurityClass security = appDomain.GetData ( "Security" ) as SecurityClass;

			FMChannelFactory<ISites> sitesClient = new FMChannelFactory<ISites> ( );
			ISites sites = sitesClient.CreateProxy ( );

			sites.Logout ( security );
		}

		private void CutToolStripMenuItem_Click ( object sender, EventArgs e )
		{
		}

		private void CopyToolStripMenuItem_Click ( object sender, EventArgs e )
		{
		}

		private void PasteToolStripMenuItem_Click ( object sender, EventArgs e )
		{
		}

		private void ToolBarToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			toolStrip.Visible = toolBarToolStripMenuItem.Checked;
		}

		private void StatusBarToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			statusStrip.Visible = statusBarToolStripMenuItem.Checked;
		}

		private void CascadeToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			LayoutMdi ( MdiLayout.Cascade );
		}

		private void TileVerticalToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			LayoutMdi ( MdiLayout.TileVertical );
		}

		private void TileHorizontalToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			LayoutMdi ( MdiLayout.TileHorizontal );
		}

		private void ArrangeIconsToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			LayoutMdi ( MdiLayout.ArrangeIcons );
		}

		private void CloseAllToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			foreach (Form childForm in MdiChildren)
			{
				childForm.Close ( );
			}
		}

		private void dataGridView1_CellContentClick ( object sender, DataGridViewCellEventArgs e )
		{

		}

		private void toolStrip_ItemClicked ( object sender, ToolStripItemClickedEventArgs e )
		{

		}

		private void dispatchToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			try
			{
				string[] selectedTransID = new string[dataGridView1.SelectedRows.Count];
				lock (dataGridView1)
				{
					for (int iLoop = 0; iLoop < dataGridView1.SelectedRows.Count; iLoop++)
					{
						DataRowView Row = (DataRowView) dataGridView1.SelectedRows[iLoop].DataBoundItem;
						selectedTransID[iLoop] = (string) Row["TransID"];
					}
				}

				DispatchForm dispatch = new DispatchForm ( dispatchSR.Translations, selectedTransID, null, null, OperationLockDate );
				dispatch.ShowDialog ( this );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void queryWriterToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			try
			{
				string baseAddress = ConfigurationManager.AppSettings["WebAppAddress"];
				if (String.IsNullOrEmpty ( baseAddress ))
				{
					throw new ApplicationException ( "WebAppAddress not in configuration file." );
				}

				EmbeddedBrowser embeddedBrowser = new EmbeddedBrowser ( baseAddress + "/QueryWriterWebApp/ManageQueriesForm.aspx" );
				embeddedBrowser.ShowDialog ( this );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}
		}

		private void OnClickViewControlLog ( object sender, EventArgs e )
		{
			ControlLogForm ControlLog = new ControlLogForm ( );
			ControlLog.UserID = UserID;
			ControlLog.Show ( this );
		}

		void SchedulerMessageProcessScan ( )
		{
			KillEvent = new ManualResetEvent ( false );
			WaitHandle[] Events = { KillEvent };
			int WaitInterval = 100;
			int ReloadConfigCounter = 15;

			int WaitResult;
			while (0 != ( WaitResult = WaitHandle.WaitAny ( Events, WaitInterval, false ) ))
			{
				WaitInterval = 30000;	// check once every 30 seconds
				// get the scheduled events for today
				if (ReloadConfigCounter > 14)
				{
					GetTodaysScheduledEvents ( );
					ReloadConfigCounter = 0;
				}
				++ReloadConfigCounter;

				if (CheckIfAppoinmentIsDue ( ) == true)
				{
					// we do the following to ensure that the thread is safe
					ShowReminderForm ( );
				}
			}
		}

		private void ShowReminderForm ( )
		{
			if (this.InvokeRequired)
			{
				ShowReminderFormCallback spfc = new ShowReminderFormCallback ( ShowReminderForm );

				this.Invoke ( spfc );
			}
			else
			{
				AppointmentReminderForm ReminderForm = new AppointmentReminderForm ( this );

				ReminderForm.ShowDialog ( this );
			}
		}

		public void GetTodaysScheduledEvents ( )
		{
			try
			{
				DateTime TodaysDate = System.DateTime.Now;
				List<AppointmentClass> appointmentCollection = new List<AppointmentClass> ( );
				AppointmentClass appointment = new AppointmentClass ( );

				TodaysDate = TodaysDate.AddHours ( -TodaysDate.Hour );
				TodaysDate = TodaysDate.AddMinutes ( -TodaysDate.Minute );
				TodaysDate = TodaysDate.AddSeconds ( -TodaysDate.Second );
				TodaysDate = TodaysDate.AddMilliseconds ( -TodaysDate.Millisecond );

				DateTime EndDate = TodaysDate;

				FMChannelFactory<IAppointments> appointmentsClient = new FMChannelFactory<IAppointments> ( );
				IAppointments appointments = appointmentsClient.CreateProxy ( );

				TodaysDate = TodaysDate.AddSeconds ( -1 );	// this will set it at 1 second prior to midnight to ensure we get the whole day
				appointmentCollection = appointments.EnumerateByStartStopTime ( Security, "Personnel", TodaysDate, EndDate );

				foreach (AppointmentClass appointmentData in appointmentCollection)
				{
					// we got an appointment so check it and map it
					this.CheckAndMapAppointment ( appointmentData );
				}

				this.CheckForDateOverrun ( );
			}
			catch (Exception exception)
			{
				MessageBox.Show ( this, exception.Message, this.Text );
			}
		}

		private void CheckForDateOverrun ( )
		{
			DateTime TodaysDateTime = System.DateTime.Now;

		ReStartCheck:

			foreach (TodaysAppointmentClass TodaysAppointment in TodaysAppointmentsCollection)
			{
				// check that the date is correct. We may have run over 24 hours so delete any old records
				// we only need to check the day and month
				if (TodaysAppointment.DueDate.Day != TodaysDateTime.Day ||
			TodaysAppointment.DueDate.Month != TodaysDateTime.Month)
				{
					TodaysAppointmentsCollection.Remove ( TodaysAppointment );
					goto ReStartCheck;
				}
			}
		}

		private void CheckAndMapAppointment ( AppointmentClass AppointmentData )
		{
			bool AppointmentFound = false;

			foreach (TodaysAppointmentClass TodaysAppointment in TodaysAppointmentsCollection)
			{
				if (AppointmentData.Index == TodaysAppointment.Index)
				{
					AppointmentFound = true;
					// check that the date is correct. We may have run over 24 hours so delete any old records
					// check if any of the appointment data has changed
					if (HasAnyAppointmentDataChanged ( AppointmentData, TodaysAppointment ) == true)
					{
						// something has changed so remove and then readd the class
						TodaysAppointmentsCollection.Remove ( TodaysAppointment );
						TodaysAppointmentClass NewAppointment = new TodaysAppointmentClass ( );
						MapAppointment ( AppointmentData, NewAppointment );
						TodaysAppointmentsCollection.Add ( NewAppointment );
					}
					break;
				}
			}

			if (AppointmentFound == false)
			{
				// add this apointment to the collection
				TodaysAppointmentClass NewAppointment = new TodaysAppointmentClass ( );
				MapAppointment ( AppointmentData, NewAppointment );
				TodaysAppointmentsCollection.Add ( NewAppointment );
			}
		}

		public void MapAppointment ( AppointmentClass AppointmentData, TodaysAppointmentClass NewAppointment )
		{
			NewAppointment.Index = AppointmentData.Index;
			NewAppointment.DueDate = AppointmentData.DueDate;
			NewAppointment.Description = AppointmentData.Description;
			NewAppointment.AppointmentCategory = AppointmentData.AppointmentCategory;
			NewAppointment.AssetText = AppointmentData.AssetText;
			NewAppointment.Duration = AppointmentData.Duration;
		}

		private bool HasAnyAppointmentDataChanged ( AppointmentClass AppointmentData, TodaysAppointmentClass TodaysAppointment )
		{
			if (TodaysAppointment.Index != AppointmentData.Index ||
			 TodaysAppointment.DueDate != AppointmentData.DueDate ||
			 TodaysAppointment.Description != AppointmentData.Description ||
			 TodaysAppointment.AppointmentCategory != AppointmentData.AppointmentCategory ||
			 TodaysAppointment.AssetText != AppointmentData.AssetText ||
			 TodaysAppointment.Duration != AppointmentData.Duration)
				return true;

			return false;
		}

		public bool CheckIfAppoinmentIsDue ( )
		{
			bool AppointmentDue = false;
			DateTime TodaysDateTime = System.DateTime.Now;

			foreach (TodaysAppointmentClass TodaysAppointment in TodaysAppointmentsCollection)
			{
				if (TodaysAppointment.InSleepMode == false &&
			TodaysAppointment.DoNotNotifyAgain == false &&
			TodaysDateTime >= TodaysAppointment.DueDate.AddMinutes ( -AppointmentWarnPeriod ) &&
				TodaysAppointment.DueDate >= TodaysDateTime)
				{
					TodaysAppointment.AppointmentIsDue = true;
					AppointmentDue = true;
				}
				else if (TodaysAppointment.InSleepMode == true &&
			TodaysAppointment.DoNotNotifyAgain == false &&
			TodaysDateTime >= TodaysAppointment.SleepTimeInterval)
				{
					TodaysAppointment.AppointmentIsDue = true;
					AppointmentDue = true;
				}
				// do not show over due appointments per the DOD testing department
			}

			return AppointmentDue;
		}

		private void requestRefuelToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			FuelRequestForm fuelRequestForm = new FuelRequestForm ( OperationLockDate );
			fuelRequestForm.RequestType = FuelRequestForm.REQUEST_TYPE.RequestFuel;
			fuelRequestForm.ShowDialog ( this );
		}

		private void DispatchContainerForm_Load ( object sender, EventArgs e )
		{
			try
			{
				LoadStatusCombo ( );
				LoadRequestCombo ( );
				StartDataProcess ( );
				// Add context menu items
				SetContextPopupMenuItems ( );

				dataGridView1.Focus ( );

				RenumberGrid ( dataGridView1 );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void LoadRequestCombo ( )
		{
			RequestTypeCombo.Items.Clear ( );
			RequestTypeCombo.Sorted = false;

			RequestTypeCombo.Items.Add ( "{All}" );
			RequestTypeCombo.Items.Add ( "Refuel" );
			RequestTypeCombo.Items.Add ( "Defuel" );
			RequestTypeCombo.Items.Add ( "Fillstand" );
			RequestTypeCombo.Items.Add ( "Return to Bulk" );
			RequestTypeCombo.Items.Add ( "Recirculation" );

			RequestTypeCombo.SelectedIndex = 0;
		}

		private void LoadStatusCombo ( )
		{
			StatusCombo.Items.Clear ( );
			StatusCombo.Sorted = false;

			StatusCombo.Items.Add ( "{All}" );
			StatusCombo.Items.Add ( "Requested" );
			StatusCombo.Items.Add ( "Dispatched" );
			StatusCombo.Items.Add ( "Arrived" );
			StatusCombo.Items.Add ( "Started" );
			StatusCombo.Items.Add ( "Stopped" );
			StatusCombo.Items.Add ( "Completed" );
			StatusCombo.Items.Add ( "Cancelled" );
			StatusCombo.Items.Add ( "Posted" );

			StatusCombo.SelectedIndex = 0;
		}

		/// <summary>
		/// This method starts the data process for the form including a SQLDependency
		/// for obtaining update callbacks.
		/// </summary>
		private void StartDataProcess ( )
		{
			// Read alias translations and prepare service request
			dispatchSR = new DispatchTransactionsSR ( );
			dispatchSR.Security = Security;

			string fuelRequestAlias = ConfigurationManager.AppSettings["FuelRequestTransactionAlias"];
			dispatchSR.Translations.Add ( new DispatchTransactionsSR.DispatchTranslationPair ( ) { AccountingName = fuelRequestAlias, DispatchName = "Refuel" } );

			DataAccess = new DispatchDataAccess (Security);
			DataAccess.OnDataUpdated += new DispatchDataAccess.OnDataUpdatedHandler ( UpdateViewWithNotification );
			UpdateViewWithNotification ( );

			dataGridView1.Sort ( dataGridView1.Columns["Requested"], ListSortDirection.Ascending );

		}

		/// <summary>
		/// This method is responsible for updating the grid's datasource
		/// </summary>
		private void UpdateViewWithNotification ( )
		{
			ISynchronizeInvoke i = (ISynchronizeInvoke) this;

			// Check if the event was generated from another
			// thread and needs invoke instead
			if (i.InvokeRequired)
			{
				DispatchDataAccess.OnDataUpdatedHandler tempDelegate = new DispatchDataAccess.OnDataUpdatedHandler ( UpdateViewWithNotification );
				i.BeginInvoke ( tempDelegate, null );
				return;
			}

			UpdateView ( );

		}

		private void UpdateView ( )
		{
			// store the currently selected rows so we can reset them after an update
			string[] selectedTransID = new string[dataGridView1.SelectedRows.Count];
			int NumberOfSelectedRows = dataGridView1.SelectedRows.Count;
			string CurrentRowTransID = string.Empty;

			for (int iLoop = 0; iLoop < NumberOfSelectedRows; iLoop++)
			{
				DataRowView Row = (DataRowView) dataGridView1.SelectedRows[iLoop].DataBoundItem;
				selectedTransID[iLoop] = (string) Row["TransID"];
			}

			// store the current row so it can be restored
			if (dataGridView1.CurrentRow != null)
			{
				DataRowView CurrentRow = (DataRowView) dataGridView1.Rows[dataGridView1.CurrentRow.Index].DataBoundItem;
				if (CurrentRow != null)
					CurrentRowTransID = (string) CurrentRow["TransID"];
			}


			if (dispatchSR != null)
			{
				dispatchSR.Security = Security;
				dispatchSR.BeginDate = BeginDatePicker.Value;
				dispatchSR.EndDate = EndDatePicker.Value;

				GetStatusValues ( dispatchSR );
				GetAliases ( dispatchSR );

				DispatchTransactionsDO results = null;

				DataAccess.ClearOnChange ( );
				DataAccess = new DispatchDataAccess (Security);
				DataAccess.OnDataUpdated += new DispatchDataAccess.OnDataUpdatedHandler ( UpdateViewWithNotification );
				DataAccess.OnError += new DispatchDataAccess.OnErrorHandler ( ErrorHandler );

				results = DataAccess.GetTransactions ( dispatchSR );

				lock (dataGridView1)
				{
					dataGridView1.AutoGenerateColumns = false;

					DataView view = new DataView ( results.Transactions.Tables[0] );

					dataGridView1.DataSource = view;

					LoadVehicleDropDown ( results.Transactions.Tables[0] );

					// since the grid will autoselect the first row we need to reset the selection before we then set it
					// Set the row number display text values
					int index = 1;
					foreach (DataGridViewRow Row in dataGridView1.Rows)
					{
						DataRowView dataRow = (DataRowView) Row.DataBoundItem;
						Row.HeaderCell.Value = index.ToString ( );
						if (NumberOfSelectedRows > 0)
							Row.Selected = false;
						if (!string.IsNullOrEmpty ( CurrentRowTransID ) &&
						 CurrentRowTransID.Equals ( (string) dataRow["TransID"] ))
						{
							// restore the current selection
							// the only way to do this is by setting the currentcell variable since the currentrow is read only
							dataGridView1.CurrentCell = Row.Cells[0];
						}
						++index;
					}
					// we only do this if there are selections already made
					if (NumberOfSelectedRows > 0)
					{
						// restore the selected rows if they are still visible
						for (int iLoop = 0; iLoop < NumberOfSelectedRows; iLoop++)
						{
							foreach (DataGridViewRow Row in dataGridView1.Rows)
							{
								DataRowView dataRow = (DataRowView) Row.DataBoundItem;
								if (dataRow != null)
								{
									if (selectedTransID[iLoop].Equals ( (string) dataRow["TransID"] ))
									{
										Row.Selected = true;

										if (dataGridView1.FirstDisplayedScrollingRowIndex + dataGridView1.DisplayedRowCount ( false ) <= Row.Index)
										{
											dataGridView1.FirstDisplayedScrollingRowIndex =
											 Row.Index - dataGridView1.DisplayedRowCount ( false ) + 1;
										}
										break;
									}
								}
							}
						}
					}
				}
			}
		}

		/// <summary>
		/// This method loads the Vehicle combobox with unique, non-empty vehicle XREF values
		/// from the data items in the main grid data source.  Selection is preserved
		/// if appropriate.
		/// </summary>
		/// <param name="dataTable"></param>
		private void LoadVehicleDropDown ( DataTable dataTable )
		{
			// Set the vehicle combo box to the same - use a new view so they
			// are separate.

			// Save the current selection
			string selecteVehicleXref = vehicleComboBox.Text;

			// Clear the items from the combobox and add the ALL option
			vehicleComboBox.Items.Clear ( );
			vehicleComboBox.Items.Add ( "{All}" );

			// Get a list of vehicle XREFs that are not empty
			var vehicleIDs = from V in dataTable.AsEnumerable ( )
							 where string.IsNullOrEmpty ( V["XREF"].ToString ( ) ) == false
							 select V["XREF"] as string;

			// Load the combo box with unique values
			foreach (var V in vehicleIDs)
			{
				if (vehicleComboBox.FindStringExact ( V ) == -1)
				{
					vehicleComboBox.Items.Add ( V );
				}
			}

			// Set the selection back to what it was if the item exists in the
			// combo any more.
			if (vehicleComboBox.FindStringExact ( selecteVehicleXref ) > 0)
			{
				vehicleComboBox.Text = selecteVehicleXref;
			}
			else
			{
				vehicleComboBox.SelectedIndex = 0;
			}

		}

		private void GetStatusValues ( DispatchTransactionsSR sr )
		{
			sr.Statuses.Clear ( );
			if (StatusCombo.Text.Equals ( "{All}" ))
			{
				foreach (string status in StatusCombo.Items)
				{
					if (status.Equals ( "{All}" ) == false)
					{
						sr.Statuses.Add ( status );
					}
				}
			}
			else
			{
				sr.Statuses.Add ( StatusCombo.Text );
			}
		}

		private void GetAliases ( DispatchTransactionsSR sr )
		{
			sr.AliasNames.Clear ( );
			if (RequestTypeCombo.Text.Equals ( "{All}" ))
			{
				foreach (string requestType in RequestTypeCombo.Items)
				{
					if (requestType.Equals ( "{All}" ) == false)
					{
						sr.AliasNames.Add ( requestType );
					}
				}
			}
			else
			{
				sr.AliasNames.Add ( RequestTypeCombo.Text );
			}
		}

		protected override void OnClosing ( CancelEventArgs e )
		{
			base.OnClosing ( e );

			// Save the window dimensions
		}

		private void BeginDatePicker_Leave ( object sender, EventArgs e )
		{
			try
			{
				// if the user didi not change the date just exit
				if (CurrentSelectedBeginDatePicker == BeginDatePicker.Value)
					return;

				CurrentSelectedBeginDatePicker = BeginDatePicker.Value;
				Cursor = System.Windows.Forms.Cursors.WaitCursor;
				UpdateView ( );
				Cursor = System.Windows.Forms.Cursors.Default;
			}
			catch (Exception except)
			{
				Cursor = System.Windows.Forms.Cursors.Default;
				ErrorHandler ( except );
			}
		}

		private void BeginDatePicker_ValueChanged ( object sender, EventArgs e )
		{
		}

		private void EndDatePicker_Leave ( object sender, EventArgs e )
		{
			try
			{
				// if the user didi not change the date just exit
				if (CurrentSelectedEndDatePicker == EndDatePicker.Value)
					return;

				CurrentSelectedEndDatePicker = EndDatePicker.Value;
				Cursor = System.Windows.Forms.Cursors.WaitCursor;
				UpdateView ( );
				Cursor = System.Windows.Forms.Cursors.Default;
			}
			catch (Exception except)
			{
				Cursor = System.Windows.Forms.Cursors.Default;
				ErrorHandler ( except );
			}
		}

		private void EndDatePicker_ValueChanged ( object sender, EventArgs e )
		{
		}

		private void RequestTypeCombo_SelectedIndexChanged ( object sender, EventArgs e )
		{
			try
			{
				UpdateView ( );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void StatusCombo_SelectedIndexChanged ( object sender, EventArgs e )
		{
			try
			{
				UpdateView ( );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void recirculationToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			RecirculationForm RecirculationForm = new RecirculationForm ( );
			RecirculationForm.ShowDialog ( this );
		}

		private void transientToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			FuelRequestForm fuelRequestForm = new FuelRequestForm ( OperationLockDate );
			fuelRequestForm.RequestType = FuelRequestForm.REQUEST_TYPE.Transient;
			fuelRequestForm.ShowDialog ( this );
		}

		private void fastLogToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			FuelRequestForm fuelRequestForm = new FuelRequestForm ( OperationLockDate );
			fuelRequestForm.RequestType = FuelRequestForm.REQUEST_TYPE.FastLog;
			fuelRequestForm.ShowDialog ( this );
		}

		private void fastLogFillstandToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			FuelRequestForm fuelRequestForm = new FuelRequestForm ( OperationLockDate );
			fuelRequestForm.RequestType = FuelRequestForm.REQUEST_TYPE.FastLogFillStand;
			fuelRequestForm.ShowDialog ( this );
		}

		void dataGridView1_RowHeaderMouseDoubleClick ( object sender, DataGridViewCellMouseEventArgs e )
		{
			try
			{
				RowDoubleClicked ( e.RowIndex );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void RowDoubleClicked ( int RowIndex )
		{
			try
			{
				if (RowIndex >= 0)
				{
					DataRowView Row = (DataRowView) dataGridView1.Rows[RowIndex].DataBoundItem;
					if ((string) Row["AliasName"] == "Recirculation")
					{
						RecirculationForm RecirculationForm = new RecirculationForm ( );
						RecirculationForm.TransID = (string) Row["TransID"];
						RecirculationForm.ShowDialog ( this );
					}
					else
					{
						// if the transaction type is a refuel or a defuel we need to check the operational lock date and if it is before
						// that date not allow any modification if it is complete
						FuelRequestForm fuelRequestForm = new FuelRequestForm ( OperationLockDate );
						fuelRequestForm.TransID = (string) Row["TransID"];
						// if the transaction type is a refuel or a defuel we need to check the operational lock date and if it is before
						// that date not allow any modification if it is complete
						if (fuelRequestForm.transaction.Status == TransactionStatus.Completed &&
							( (string) Row["AliasName"] == "Refuel" ||
							(string) Row["AliasName"] == "Defuel" ))
						{
							DateTime CompletedDateTime = System.DateTime.UtcNow.AddYears ( -100 );
							if (Row["RequestedDateTime"].ToString ( ).Length > 0)
								CompletedDateTime = (DateTime) Row["RequestedDateTime"];

							// check the lock out date
							if (CompletedDateTime <= OperationLockDate)
							{
								MessageBox.Show ( "Can not edit completed transactions before the lock out date.\n\rEdit request ended." );
								return;
							}
						}
						fuelRequestForm.ShowDialog ( this );
					}
				}
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void OnAddInsConfigurationClicked ( object sender, EventArgs e )
		{
			AddInsForm AddInCofiguration = new AddInsForm ( );
			if (AddInCofiguration.ShowDialog ( this ) == DialogResult.OK)
			{
				// modify the add in menu with the selected values
				AddAddInItemsToAddInMenu ( );
			}
		}

		private void AddAddInItemsToAddInMenu ( )
		{
			string AppMenuItem = "";
			string AppPathItem = "";
			bool ExitWhile = false;
			int iLoop = 0;

		ReCheckMenuItems:
			if (addInsToolStripMenuItem.DropDownItems.Count > 1)
			{
				for (iLoop = 0; iLoop < addInsToolStripMenuItem.DropDownItems.Count; iLoop++)
				{
					if (iLoop == 0)
						continue;
					else
					{
						addInsToolStripMenuItem.DropDownItems.RemoveAt ( iLoop );
						goto ReCheckMenuItems;
					}
				}
			}

			iLoop = 0;
			while (ExitWhile == false)
			{
				AppMenuItem = "MenuItem" + iLoop.ToString ( );
				AppPathItem = "AppPath" + iLoop.ToString ( );

				string LVText = ConfigurationManager.AppSettings[AppMenuItem];
				string LVText1 = ConfigurationManager.AppSettings[AppPathItem];
				if (LVText != null &&
					LVText1 != null)
				{
					addInsToolStripMenuItem.DropDownItems.Add ( LVText, null, AddInItemClicked );
				}
				else
				{
					ExitWhile = true;
					break;
				}
				++iLoop;
			}
		}

		private void AddInItemClicked ( object sender, EventArgs e )
		{
			string AppMenuItem = "";
			string AppPathItem = "";
			bool ExitWhile = false;
			int iLoop = 0;


			ToolStripMenuItem menuItem = (ToolStripMenuItem) sender;
			iLoop = 0;
			while (ExitWhile == false)
			{
				AppMenuItem = "MenuItem" + iLoop.ToString ( );
				AppPathItem = "AppPath" + iLoop.ToString ( );

				string LVText = ConfigurationManager.AppSettings[AppMenuItem];
				string LVText1 = ConfigurationManager.AppSettings[AppPathItem];
				if (LVText != null &&
					LVText1 != null &&
					LVText == menuItem.Text)
				{
					XmlSerializer xmlFormat = new XmlSerializer ( typeof ( SecurityClass ) );
					System.IO.StringWriter sWriter = new System.IO.StringWriter ( );
					xmlFormat.Serialize ( sWriter, Security );
					sWriter.Close ( );
					string str = sWriter.ToString ( );
					Process p = new Process ( );
					ProcessStartInfo psi = new ProcessStartInfo ( LVText1 );
					psi.UseShellExecute = false;
					psi.EnvironmentVariables["Security"] = str;
					psi.EnvironmentVariables["Token"] = AppDomain.CurrentDomain.GetData ( "Token" ) as string;
					p.StartInfo = psi;
					if (!p.Start ( ))
					{
						MessageBox.Show ( "Could not start " + LVText1, "Warning" );
					}

					ExitWhile = true;
					break;
				}
				else if (LVText == null &&
							LVText1 == null)
				{
					ExitWhile = true;
					break;
				}
				++iLoop;
			}
		}

		private void operationToolStripMenuItem_DropDownOpening ( object sender, EventArgs e )
		{
			string useArrivalTime = ConfigurationManager.AppSettings["Use Arrival Time"];
			string useStartTime = ConfigurationManager.AppSettings["Use Start Time"];
			string useStopTime = ConfigurationManager.AppSettings["Use Stop Time"];
		}

		private void dataGridView1_MouseClick ( object sender, MouseEventArgs e )
		{
			if (e.Button == MouseButtons.Right)
			{
				// get the selected row and column
				DataGridView.HitTestInfo hti;
				hti = dataGridView1.HitTest ( e.X, e.Y );

				if (hti.RowIndex < 0)	// user selected a blank area in the grid
					return;

				if (dataGridView1.Rows[hti.RowIndex].Selected == false)
					dataGridView1.Rows[hti.RowIndex].Selected = true;

				if (dataGridView1.SelectedRows.Count <= 0)
					return;

				SetPopupMenuEnableDisable ( );
				// popup the context menu
				PopupContextMenuForDataGrid.Show ( dataGridView1, new Point ( e.X, e.Y ) );
			}
		}

		private void SetContextPopupMenuItems ( )
		{
			PopupContextMenuForDataGrid.Items.Add ( "Set Arrived", null, new EventHandler ( SetSelectedToArrived ) );
			PopupContextMenuForDataGrid.Items.Add ( "Set Service Started", null, new EventHandler ( SetSelectedToStarted ) );
			PopupContextMenuForDataGrid.Items.Add ( "Set Service Stopped", null, new EventHandler ( SetSelectedToStopped ) );
			PopupContextMenuForDataGrid.Items.Add ( "Set Service Completed", null, new EventHandler ( SetSelectedToCompleted ) );
			PopupContextMenuForDataGrid.Items.Add ( "Set Fillstand Completed", null, new EventHandler ( SetFillStandCompleted ) );
			PopupContextMenuForDataGrid.Items.Add ( "-", null, null );
			PopupContextMenuForDataGrid.Items.Add ( "Relog Transaction", null, new EventHandler ( Relog ) );
			PopupContextMenuForDataGrid.Items.Add ( "Cancel Transaction", null, new EventHandler ( CancelRequest ) );

		}

		private void TestContext ( object sender, EventArgs e )
		{
			int y = 0;
			++y;
		}

		private void Relog ( object sender, EventArgs e )
		{
			try
			{
				if (Security.HasRight ( RIGHT.MODIFY_DISPATCH ) == false)
				{
					return;
				}

				// Don't allow relog of FillStand
				foreach (DataGridViewRow SelectedRow in dataGridView1.SelectedRows)
				{
					DataRowView Row = (DataRowView) SelectedRow.DataBoundItem;
					TransactionTypes type = (TransactionTypes) Row["TransTypeID"];
					if (type == TransactionTypes.T7_FillStand)
					{
						throw new ApplicationException ( "Cannot relog fillstand requests." );
					}
				}

				foreach (DataGridViewRow SelectedRow in dataGridView1.SelectedRows)
				{
					FMChannelFactory<ISites> sitesClient = new FMChannelFactory<ISites> ( );
					ISites sites = sitesClient.CreateProxy ( );

					SiteClass site = sites.Get(Security, Security.SiteGuid, false, false, false);

					SiteTimeConverter timeConverter = new SiteTimeConverter ( site );

					DataRowView Row = (DataRowView) SelectedRow.DataBoundItem;
					string transID = (string) Row["TransID"];
					TransactionDO transaction = GetTransaction ( transID );

					transaction.TransID = FuelsManagerId.NewId ( );
					transaction.Status = TransactionStatus.Requested;
					transaction.TimeIn = null;
					transaction.TimeOut = null;
					transaction.TimeEnd = null;
					transaction.RouteSchedule.FST = null;

					foreach (LineItemDO LineItem in transaction.LineItems)
					{
						LineItem.Quantity = new QuantityDO ( );

						LineItem.Status = TransactionStatus.Requested;

						foreach (SubLineItemDO sublineitem in LineItem.SubLineItems)
						{
							sublineitem.Status = TransactionStatus.Requested;
						}
					}

					transaction.TransactionDateTime = timeConverter.Now();
					transaction.RequestedDateTime = transaction.TransactionDateTime;

					SelectedRow.Selected = false;

					UndispatchTransaction ( transaction );
				}
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}
		}

		private void CancelRequest ( object sender, EventArgs e )
		{
			try
			{
				if (Security.HasRight ( RIGHT.MODIFY_DISPATCH ) == false)
				{
					return;
				}

				// Check for completed transactions
				foreach (DataGridViewRow SelectedRow in dataGridView1.SelectedRows)
				{
					DataRowView Row = (DataRowView) SelectedRow.DataBoundItem;
					TransactionStatus status = (TransactionStatus) Row["transactionStatusInt"];

					if (status == TransactionStatus.Completed)
					{
						throw new ApplicationException ( "Completed requests cannot be cancelled." );
					}

				}

				string message = "Once an operation is canceled it cannot be un-canceled.\nAre you sure you want to cancel this job(s)?";
				DialogResult result = MessageBox.Show ( this, message, "Dispatch", MessageBoxButtons.YesNo );
				if (result == DialogResult.No)
				{
					return;
				}

				List<transactionIdAndRequestTypeType> transactionIdAndRequestTypeList = new List<transactionIdAndRequestTypeType> ( );

				// Lock on dataGridView1 to protect against changes
				lock (dataGridView1)
				{
					foreach (DataGridViewRow SelectedRow in dataGridView1.SelectedRows)
					{
						DataRowView Row = (DataRowView) SelectedRow.DataBoundItem;
						string transID = (string) Row["TransID"];
						string requesttype = (string) Row["AliasName"];

						transactionIdAndRequestTypeType transactionIdAndRequestType;
						transactionIdAndRequestType.transactionID = transID;
						transactionIdAndRequestType.requestType = requesttype;
						transactionIdAndRequestTypeList.Add ( transactionIdAndRequestType );
					}
				}

				dataGridView1.ClearSelection ( );

				foreach (transactionIdAndRequestTypeType transactionIdAndRequestType in transactionIdAndRequestTypeList)
				{
					string transID = transactionIdAndRequestType.transactionID;
					string requesttype = transactionIdAndRequestType.requestType;

					TransactionDO Transaction = GetTransaction ( transID );
					// prompt the user to enter a comment for the cancellation
					//				memoTextBox.Text=transaction.UserData["Transaction Aliases User Data 23"] as string;
					CommentForm CancelComment = new CommentForm ( );
					CancelComment.CurrentComment = Transaction.UserData["Transaction Aliases User Data 23"] as string;
					CancelComment.Forstring = "Request Type = " + requesttype;
					CancelComment.ShowDialog ( this );
					// restore the comment
					Transaction.Notes += " - " + CancelComment.CurrentComment;

					Transaction.Status = TransactionStatus.Cancelled;
					foreach (LineItemDO LineItem in Transaction.LineItems)
					{
						LineItem.Status = TransactionStatus.Cancelled;

						foreach (SubLineItemDO SubLineItem in LineItem.SubLineItems)
						{
							SubLineItem.Status = TransactionStatus.Cancelled;
						}
					}

					SaveTransaction ( Transaction );
				}
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}
		}

		private void SetSelectedToArrived ( object sender, EventArgs e )
		{
			TransactionDO transaction = null;
			string selectedTransID = "";
			SecurityClass security = AppDomain.CurrentDomain.GetData ( "Security" ) as SecurityClass;

			if (security == null)
			{
				throw new Exception ( "Security not in AppDomain" );
			}

			FMChannelFactory<ISites> sitesClient = new FMChannelFactory<ISites> ( );
			ISites sites = sitesClient.CreateProxy ( );

			SiteClass site = sites.Get(security, security.SiteGuid, false, false, false);

			SiteTimeConverter timeConverter = new SiteTimeConverter ( site );

			lock (dataGridView1)
			{
				foreach (DataGridViewRow SelectedRow in dataGridView1.SelectedRows)
				{
					DataRowView Row = (DataRowView) dataGridView1.Rows[SelectedRow.Index].DataBoundItem;

					selectedTransID = (string) Row["TransID"];
					TransactionSR transactionSR = new TransactionSR ( );
					transactionSR.Security = security;
					transactionSR.TransID = selectedTransID;

					FMChannelFactory<ITransactionProcessor> transProcessorClient = new FMChannelFactory<ITransactionProcessor> ( );
					ITransactionProcessor services = transProcessorClient.CreateProxy ( );

					transaction = services.Process ( transactionSR );

					// set the status and the time for arrived
					transaction.Status = TransactionStatus.Arrived;
					transaction.TimeIn = timeConverter.Now();

					this.SaveTransactionToDataBase ( security, transaction );
				}
			}

			this.SetPopupMenuEnableDisable ( );
		}

		private void SetSelectedToStarted ( object sender, EventArgs e )
		{
			TransactionDO transaction = null;
			string selectedTransID = "";
			SecurityClass security = AppDomain.CurrentDomain.GetData ( "Security" ) as SecurityClass;

			if (security == null)
			{
				throw new Exception ( "Security not in AppDomain" );
			}

			FMChannelFactory<ISites> sitesClient = new FMChannelFactory<ISites> ( );
			ISites sites = sitesClient.CreateProxy ( );

			SiteClass site = sites.Get(security, security.SiteGuid, false, false, false);

			SiteTimeConverter timeConverter = new SiteTimeConverter ( site );

			lock (dataGridView1)
			{
				foreach (DataGridViewRow SelectedRow in dataGridView1.SelectedRows)
				{
					DataRowView Row = (DataRowView) dataGridView1.Rows[SelectedRow.Index].DataBoundItem;

					selectedTransID = (string) Row["TransID"];
					TransactionSR transactionSR = new TransactionSR ( );
					transactionSR.Security = security;
					transactionSR.TransID = selectedTransID;

					FMChannelFactory<ITransactionProcessor> transProcessorClient = new FMChannelFactory<ITransactionProcessor> ( );
					ITransactionProcessor services = transProcessorClient.CreateProxy ( );

					transaction = services.Process ( transactionSR );

					// set the status and the time for arrived
					transaction.Status = TransactionStatus.Started;
					transaction.RouteSchedule.FST = timeConverter.Now();

					SaveTransactionToDataBase ( security, transaction );

				}
			}

			SetPopupMenuEnableDisable ( );

		}

		private void SetSelectedToStopped ( object sender, EventArgs e )
		{
			TransactionDO transaction = null;
			string selectedTransID = "";
			SecurityClass security = AppDomain.CurrentDomain.GetData ( "Security" ) as SecurityClass;

			if (security == null)
			{
				throw new Exception ( "Security not in AppDomain" );
			}

			FMChannelFactory<ISites> sitesClient = new FMChannelFactory<ISites> ( );
			ISites sites = sitesClient.CreateProxy ( );

			SiteClass site = sites.Get(security, security.SiteGuid, false, false, false);

			SiteTimeConverter timeConverter = new SiteTimeConverter ( site );

			lock (dataGridView1)
			{
				foreach (DataGridViewRow SelectedRow in dataGridView1.SelectedRows)
				{
					DataRowView Row = (DataRowView) dataGridView1.Rows[SelectedRow.Index].DataBoundItem;

					selectedTransID = (string) Row["TransID"];
					TransactionSR transactionSR = new TransactionSR ( );
					transactionSR.Security = security;
					transactionSR.TransID = selectedTransID;

					FMChannelFactory<ITransactionProcessor> transProcessorClient = new FMChannelFactory<ITransactionProcessor> ( );
					ITransactionProcessor services = transProcessorClient.CreateProxy ( );

					transaction = services.Process ( transactionSR );

					// set the status and the time for arrived
					transaction.Status = TransactionStatus.Stopped;
					transaction.TimeEnd = timeConverter.Now();

					this.SaveTransactionToDataBase ( security, transaction );

					this.SetPopupMenuEnableDisable ( );
				}
			}

			this.SetPopupMenuEnableDisable ( );
		}

		private void SetSelectedToCompleted ( object sender, EventArgs e )
		{
			SecurityClass security = AppDomain.CurrentDomain.GetData ( "Security" ) as SecurityClass;

			if (security == null)
			{
				throw new Exception ( "Security not in AppDomain" );
			}

			string[] SelectedTransID = new string[dataGridView1.SelectedRows.Count];
			string[] SelectedAircraftRefID = new string[dataGridView1.SelectedRows.Count];
			DateTime[] DispatchDateTime = new DateTime[dataGridView1.SelectedRows.Count];
			int SelectedGridItems = dataGridView1.SelectedRows.Count;
			int iLoop = 0;
			bool DisplayDispatchScreen = false;

			FMChannelFactory<ISites> sitesClient = new FMChannelFactory<ISites> ( );
			ISites sites = sitesClient.CreateProxy ( );

			SiteClass site = sites.Get(security, security.SiteGuid, false, false, false);

			SiteTimeConverter timeConverter = new SiteTimeConverter ( site );

			// since people can not grasp the concept of items being displayed in the order they are selected
			// we need to reorder the selected list based on the dispatch date and time	DispatchedDateTime

			iLoop = 0;
			lock (dataGridView1)
			{
				foreach (DataGridViewRow SelectedRow in dataGridView1.SelectedRows)
				{
					DataRowView Row = (DataRowView) dataGridView1.Rows[SelectedRow.Index].DataBoundItem;
					SelectedTransID[iLoop] = (string) Row["TransID"];
					SelectedAircraftRefID[iLoop] = (string) Row["SourceXREF"];
					DispatchDateTime[iLoop] = (DateTime) Row["DispatchedDateTime"];
					++iLoop;
				}
			}

		RecheckLoopData:
			// set the loop in the correct date time order
			for (iLoop = 0; iLoop < SelectedGridItems - 1; iLoop++)
			{
				if (DispatchDateTime[iLoop] > DispatchDateTime[iLoop + 1])
				{
					// move iLoop + 1 to iLoop location
					string TempSelectedTransID = SelectedTransID[iLoop];
					string TempSelectedAircraftRefID = SelectedAircraftRefID[iLoop];
					DateTime TempDispatchDateTime = DispatchDateTime[iLoop];
					SelectedTransID[iLoop] = SelectedTransID[iLoop + 1];
					SelectedAircraftRefID[iLoop] = SelectedAircraftRefID[iLoop + 1];
					DispatchDateTime[iLoop] = DispatchDateTime[iLoop + 1];
					SelectedTransID[iLoop + 1] = TempSelectedTransID;
					SelectedAircraftRefID[iLoop + 1] = TempSelectedAircraftRefID;
					DispatchDateTime[iLoop + 1] = TempDispatchDateTime;
					goto RecheckLoopData;
				}
			}


			string EquipmentRefID = string.Empty;
			string SelectedPerson = string.Empty;
			string[] selectedTransID = new string[1];
			selectedTransID[0] = string.Empty;
			for (iLoop = 0; iLoop < SelectedGridItems; iLoop++)
			{
				DialogResult DlgResult = DialogResult.Cancel;
				FuelRequestForm fuelRequestForm = new FuelRequestForm ( OperationLockDate );
				fuelRequestForm.TransID = SelectedTransID[iLoop];
				fuelRequestForm.TransactionWillBeSetToCompleted = true;
				fuelRequestForm.DialogHeaderText = "Service Completion for " + SelectedAircraftRefID[iLoop];
				fuelRequestForm.CompletionMode = true;
				// if there is only one selection store the data so we can select it when dispatch is opened
				DlgResult = fuelRequestForm.ShowDialog ( this );

				if (DlgResult == DialogResult.OK)	// this will store the last transaction updated which is what the DOD wants
				{
					FMChannelFactory<IPersonnel> personnelClient = new FMChannelFactory<IPersonnel> ( );
					IPersonnel personnel = personnelClient.CreateProxy ( );

					PersonClass person = personnel.Get(security, fuelRequestForm.transaction.OperatorPersonnelGuid);
					EquipmentRefID = fuelRequestForm.EquipmentRefID;
					SelectedPerson = person.LastName;
					selectedTransID[0] = SelectedTransID[iLoop];
					DisplayDispatchScreen = true;
				}
			}

			if (DisplayDispatchScreen == true)
			{
				DispatchForm dispatch = new DispatchForm ( dispatchSR.Translations, selectedTransID, SelectedPerson, EquipmentRefID, OperationLockDate );
				dispatch.ShowDialog ( this );
			}

			SetPopupMenuEnableDisable ( );

			ChangeStatusFilterIfNecessary ( TransactionStatus.Completed );

		}

		private void SetFillStandCompleted ( object sender, EventArgs e )
		{
			SecurityClass security = AppDomain.CurrentDomain.GetData ( "Security" ) as SecurityClass;
			if (security == null)
				throw new Exception ( "Security not in AppDomain" );

			string[] SelectedTransID = new string[dataGridView1.SelectedRows.Count];
			string[] SelectedVehicleID = new string[dataGridView1.SelectedRows.Count];
			DateTime[] DispatchDateTime = new DateTime[dataGridView1.SelectedRows.Count];
			int SelectedGridItems = dataGridView1.SelectedRows.Count;
			int iLoop = 0;
			bool DisplayDispatchScreen = false;

			FMChannelFactory<ISites> sitesClient = new FMChannelFactory<ISites> ( );
			ISites sites = sitesClient.CreateProxy ( );

			SiteClass site = sites.Get(security, security.SiteGuid, false, false, false);
			SiteTimeConverter timeConverter = new SiteTimeConverter ( site );

			// since people can not grasp the concept of items being displayed in the order they are selected
			// we need to reorder the selected list based on the dispatch date and time	DispatchedDateTime

			iLoop = 0;
			lock (dataGridView1)
			{
				foreach (DataGridViewRow SelectedRow in dataGridView1.SelectedRows)
				{
					DataRowView Row = (DataRowView) dataGridView1.Rows[SelectedRow.Index].DataBoundItem;
					SelectedTransID[iLoop] = (string) Row["TransID"];
					SelectedVehicleID[iLoop] = (string) Row["VehicleID"];
					DispatchDateTime[iLoop] = (DateTime) Row["DispatchedDateTime"];
					++iLoop;
				}
			}

		RecheckLoopData:
			// set the loop in the correct date time order
			for (iLoop = 0; iLoop < SelectedGridItems - 1; iLoop++)
			{
				if (DispatchDateTime[iLoop] > DispatchDateTime[iLoop + 1])
				{
					// move iLoop + 1 to iLoop location
					string TempSelectedTransID = SelectedTransID[iLoop];
					string TempSelectedSelectedVehicleID = SelectedVehicleID[iLoop];
					DateTime TempDispatchDateTime = DispatchDateTime[iLoop];
					SelectedTransID[iLoop] = SelectedTransID[iLoop + 1];
					SelectedVehicleID[iLoop] = SelectedVehicleID[iLoop + 1];
					DispatchDateTime[iLoop] = DispatchDateTime[iLoop + 1];
					SelectedTransID[iLoop + 1] = TempSelectedTransID;
					SelectedVehicleID[iLoop + 1] = TempSelectedSelectedVehicleID;
					DispatchDateTime[iLoop + 1] = TempDispatchDateTime;
					goto RecheckLoopData;
				}
			}


			string EquipmentRefID = string.Empty;
			string SelectedPerson = string.Empty;
			string[] selectedTransID = new string[1];
			selectedTransID[0] = string.Empty;
			for (iLoop = 0; iLoop < SelectedGridItems; iLoop++)
			{
				DialogResult DlgResult = DialogResult.Cancel;
				FuelRequestForm fuelRequestForm = new FuelRequestForm ( OperationLockDate );
				fuelRequestForm.TransID = SelectedTransID[iLoop];
				fuelRequestForm.TransactionWillBeSetToCompleted = true;
				fuelRequestForm.DialogHeaderText = "Fillstand Completion for " + SelectedVehicleID[iLoop];
				fuelRequestForm.CompletionMode = true;
				// if there is only one selection store the data so we can select it when dispatch is opened
				DlgResult = fuelRequestForm.ShowDialog ( this );

				if (DlgResult == DialogResult.OK)	// this will store the last transaction updated which is what the DOD wants
				{
					FMChannelFactory<IPersonnel> personnelClient = new FMChannelFactory<IPersonnel> ( );
					IPersonnel personnel = personnelClient.CreateProxy ( );

					PersonClass person = personnel.Get(security, fuelRequestForm.transaction.OperatorPersonnelGuid);
					EquipmentRefID = fuelRequestForm.EquipmentRefID;
					SelectedPerson = person.LastName;
					selectedTransID[0] = SelectedTransID[iLoop];
					DisplayDispatchScreen = true;
				}
				else if (DlgResult == DialogResult.OK)
				{
					DisplayDispatchScreen = true;
				}
			}

			if (DisplayDispatchScreen == true)
			{
				DispatchForm dispatch = new DispatchForm ( dispatchSR.Translations, selectedTransID, SelectedPerson, EquipmentRefID, OperationLockDate );
				dispatch.ShowDialog ( this );
			}

			this.SetPopupMenuEnableDisable ( );

		}

		private bool SaveTransactionToDataBase ( SecurityClass security, TransactionDO transaction )
		{
			SaveTransactionsSR saveTransactionsSR = new SaveTransactionsSR ( );
			saveTransactionsSR.IndividualDbTransaction = false;
			saveTransactionsSR.Security = security;
			saveTransactionsSR.CurrentSiteGuid = security.SiteGuid;
			saveTransactionsSR.ConvertUnits = true;
			saveTransactionsSR.Transactions.Add ( transaction );

			for (int Retry = 0; Retry < 3; Retry++)
			{
				try
				{
					FMChannelFactory<ISaveTransactionsProcessor> saveTransProcessorClient = new FMChannelFactory<ISaveTransactionsProcessor> ( );
					ISaveTransactionsProcessor service = saveTransProcessorClient.CreateProxy ( );

					service.SaveTransactions ( saveTransactionsSR );
					return true;
				}
				catch (Exception e)
				{
					if (typeof ( SaveTransactionsException ).IsInstanceOfType ( e ))
					{
						SaveTransactionsException saveTransactionsException = (SaveTransactionsException) e;
						if (saveTransactionsException.Results.Count >= 1
							&& typeof ( TransactionValidationResult ).IsInstanceOfType ( saveTransactionsException.Results[0] )
							&& ( (TransactionValidationResult) saveTransactionsException.Results[0] ).ErrorList.Count >= 1)
						{
							MessageBox.Show ( ( (TransactionValidationResult) saveTransactionsException.Results[0] ).ErrorList[0], "Error" );
						}
						else
						{
							MessageBox.Show ( "Unknown SaveTransactionException", "Error" );
						}
					}

					if (Retry < 2)
					{
						continue;
					}

					break;
				}
			}
			return false;
		}

		private void dataGridView1_OnKeyDown ( object sender, KeyEventArgs e )
		{
			// if the user presses the space bar and there are selections open the popup menu
			if (e.KeyCode == Keys.Space && dataGridView1.SelectedRows.Count > 0)
			{
				// get the menu position based on the first selected item
				foreach (DataGridViewRow SelectedRow in dataGridView1.SelectedRows)
				{
					DataRowView Row = (DataRowView) dataGridView1.Rows[SelectedRow.Index].DataBoundItem;

					Rectangle Rt = Screen.PrimaryScreen.Bounds;
					SetPopupMenuEnableDisable ( );
					// popup the context menu
					PopupContextMenuForDataGrid.Show ( dataGridView1, new Point ( Rt.Width / 4, Rt.Height / 4 ) );
				}
			}
		}

		/// <summary>
		/// This function enables and disables the appropriate state transitions on
		/// the Dispatch grid popup menu and the Operation menu on the menu bar
		/// 
		/// The states of a transaction in Dispatch are:
		/// <list type="bullet">
		/// <item><term>In-process states</term><descriptions>Active transactions; i.e., not completed or cancelled</descriptions></item>
		/// <list type="bullet">
		/// <item><term>Requested</term></item>
		/// <item><term>Dispatched</term></item>
		/// <item><term>Arrived</term></item>
		/// <item><term>Started</term></item>
		/// <item><term>Stopped</term></item>
		/// </list>
		/// <item><term>Completed</term></item>
		/// <item><term>Cancelled</term></item>
		/// </list>
		/// 
		/// Possible state transitions are determined by the current state and the Optional Times configuration
		/// </summary>
		/// <remarks>
		/// Logic changed 3.7.2010 by CHK to allow a transition away from a state not currently required by the Optional Times configuration
		/// See bug 12158
		/// 
		/// Logic change is that now the assumption starts that a transition is valid.  We then look for disqualifiers
		/// <list>
		/// <listheader><term>Disqualifiers for in-process transitions</term></listheader>
		/// <item><term>Any selected transaction is already in an end state:  id est, Completed or Cancelled</term></item>
		/// <item><term>Any selected transaction is already at or past the state moved to by the tested transition</term></item>
		/// <item><term>Any selected transaction would skip a standard or configured state to make the tested transition</term></item>
		/// <item><term>Any selected transaction is a recirculation</term></item>
		/// </list>
		/// <list>
		/// <listheader><term>Disqualifiers for Completion transition</term></listheader>
		/// <item><term>Any selected transaction is already in an end state:  id est, Completed or Cancelled</term></item>
		/// <item><term>Any selected transaction would skip a standard or configured state to make the tested transition</term></item>
		/// <item><term>Any selected transaction is a recirculation</term></item>
		/// </list>
		/// <list>
		/// <listheader><term>Disqualifiers for Cancellation transitions</term></listheader>
		/// <item><term>Any selected transaction is already in an end state:  id est, Completed or Cancelled</term></item>
		/// <item><term>Any selected transaction is a recirculation</term></item>
		/// </list>
		/// 
		/// Note that the check for recirculations really is redundant; recirculations are created as completed.
		/// This check will be left in for now, as recirculations could change in the future.
		/// </remarks>
		private void SetPopupMenuEnableDisable ( )
		{
			bool anyDispatched = false;
			bool anyStarted = false;
			bool anyStopped = false;
			bool anyArrived = false;
			bool allCompleteCapable = true;
			bool allFillstandCapable = true;
			bool refuelDefuelSelected = true;
			bool allCancelCapable = true;
			bool anyRecirculation = false;
			bool anyRequested = false;
			bool anyCompletedCanceled = false;
			bool anyPostedSelected = false;

			string useArrivalTime = ConfigurationManager.AppSettings["Use Arrival Time"];
			string useStartTime = ConfigurationManager.AppSettings["Use Start Time"];
			string useStopTime = ConfigurationManager.AppSettings["Use Stop Time"];

			// items selected so deal with those
			lock (dataGridView1)
			{
				if (dataGridView1.SelectedRows.Count > 0)
				{
					foreach (DataGridViewRow SelectedRow in dataGridView1.SelectedRows)
					{
						DataRowView Row = (DataRowView) SelectedRow.DataBoundItem;
						TransactionStatus status = (TransactionStatus) Enum.Parse ( typeof ( TransactionStatus ), (string) Row["TransactionStatus"] );
						string aliasName = (string) Row["AliasName"];
						if (aliasName.Equals ( "Recirculation" ))
						{
							allCompleteCapable = false;
							allFillstandCapable = false;

							if (status == TransactionStatus.Cancelled ||
								 status == TransactionStatus.Completed)
							{
								allCancelCapable = false;
								anyCompletedCanceled = true;
							}

							anyRecirculation = true;
						}
						else
						{
							if (status == TransactionStatus.Requested)
							{
								anyRequested = true;
							}

							if (status == TransactionStatus.Dispatched)
							{
								anyDispatched = true;
							}

							if (status == TransactionStatus.Arrived)
							{
								anyArrived = true;
							}

							if (status == TransactionStatus.Started)
							{
								anyStarted = true;
							}

							if (status == TransactionStatus.Stopped)
							{
								anyStopped = true;
							}

							if (status == TransactionStatus.Posted)
							{
								anyPostedSelected = true;
							}

							if (aliasName.Equals ( "Fillstand" ) ||
								aliasName.Equals ( "Return to Bulk" ))
								allCompleteCapable = false;
							else
								allFillstandCapable = false;

							if (status == TransactionStatus.Cancelled ||
								 status == TransactionStatus.Completed)
							{
								allCancelCapable = false;
								allCompleteCapable = false;
								allFillstandCapable = false;
								anyCompletedCanceled = true;
							}
						}

						short TransTypeID = (short) Row["TransTypeID"];
						if (TransTypeID != 4 && TransTypeID != 6)
						{
							refuelDefuelSelected = true;
						}
					}
				}
				else
				{
					allCompleteCapable = false;
					allFillstandCapable = false;
					refuelDefuelSelected = false;
					allCancelCapable = false;
				}
			}

			if (PopupContextMenuForDataGrid == null || PopupContextMenuForDataGrid.Items.Count == 0)
			{
				return;
			}

			// if any transaction with status of posted is selected disable everything
			if (anyPostedSelected == true)
			{
				PopupContextMenuForDataGrid.Items[0].Enabled = false;
				PopupContextMenuForDataGrid.Items[1].Enabled = false;
				PopupContextMenuForDataGrid.Items[2].Enabled = false;
				PopupContextMenuForDataGrid.Items[3].Enabled = false;
				PopupContextMenuForDataGrid.Items[4].Enabled = false;
				PopupContextMenuForDataGrid.Items[6].Enabled = false;
				PopupContextMenuForDataGrid.Items[7].Enabled = false;
				arrivalToolStripMenuItem.Enabled = PopupContextMenuForDataGrid.Items[0].Enabled;
				startOfServiceToolStripMenuItem.Enabled = PopupContextMenuForDataGrid.Items[1].Enabled;
				stopOfServiceToolStripMenuItem.Enabled = PopupContextMenuForDataGrid.Items[2].Enabled;
				serviceCompletionToolStripMenuItem.Enabled = PopupContextMenuForDataGrid.Items[3].Enabled;
				fillstandCompletionToolStripMenuItem.Enabled = PopupContextMenuForDataGrid.Items[4].Enabled;
				return;
			}

			if (System.Convert.ToBoolean ( useArrivalTime ) == false &&
			 System.Convert.ToBoolean ( useStartTime ) == false &&
			 System.Convert.ToBoolean ( useStopTime ) == false)
			{
				PopupContextMenuForDataGrid.Items[0].Enabled = false;	// set arrived
				PopupContextMenuForDataGrid.Items[1].Enabled = false;	//Set Service Started
				PopupContextMenuForDataGrid.Items[2].Enabled = false;	//Set Service Stopped

				if (!anyRequested && allCompleteCapable)
				{
					// The only in-process status which invalidates the state transition to 
					// Completed is Requested (must still be Dispatched)
					PopupContextMenuForDataGrid.Items[3].Enabled = true;	//Set Service Completed
				}
				else
					PopupContextMenuForDataGrid.Items[3].Enabled = false; //Set Service Completed

				if (!anyRequested && allFillstandCapable)
				{
					// The only in-process status which invalidates the state transition to 
					// Completed is Requested (must still be Dispatched)
					PopupContextMenuForDataGrid.Items[4].Enabled = true;	//Set Service Completed
				}
				else
					PopupContextMenuForDataGrid.Items[4].Enabled = false; //Set Fillstand Completed
			}
			else if (System.Convert.ToBoolean ( useArrivalTime ) == true &&
			 System.Convert.ToBoolean ( useStartTime ) == false &&
			 System.Convert.ToBoolean ( useStopTime ) == false)
			{
				PopupContextMenuForDataGrid.Items[0].Enabled = !( anyRequested || anyArrived || anyStarted || anyStopped || anyCompletedCanceled || anyRecirculation );	// set arrived
				PopupContextMenuForDataGrid.Items[1].Enabled = false;	//Set Service Started
				PopupContextMenuForDataGrid.Items[2].Enabled = false;	//Set Service Stopped

				if (!( anyRequested || anyDispatched ) && allCompleteCapable)
					PopupContextMenuForDataGrid.Items[3].Enabled = true;	//Set Service Completed
				else
					PopupContextMenuForDataGrid.Items[3].Enabled = false; //Set Service Completed

				if (!( anyRequested || anyDispatched ) && allFillstandCapable)
					PopupContextMenuForDataGrid.Items[4].Enabled = true; //Set Fillstand Completed
				else
					PopupContextMenuForDataGrid.Items[4].Enabled = false; //Set Fillstand Completed
			}
			else if (System.Convert.ToBoolean ( useArrivalTime ) == false &&
			 System.Convert.ToBoolean ( useStartTime ) == true &&
			 System.Convert.ToBoolean ( useStopTime ) == false)
			{
				PopupContextMenuForDataGrid.Items[0].Enabled = false;	// set arrived
				PopupContextMenuForDataGrid.Items[1].Enabled = !( anyRequested || anyStarted || anyStopped || anyCompletedCanceled || anyRecirculation );	// set arrived;	//Set Service Started
				PopupContextMenuForDataGrid.Items[2].Enabled = false;	//Set Service Stopped

				if (!( anyRequested || anyDispatched ) && allCompleteCapable)
					PopupContextMenuForDataGrid.Items[3].Enabled = true;	//Set Service Completed
				else
					PopupContextMenuForDataGrid.Items[3].Enabled = false; //Set Service Completed

				if (!( anyRequested || anyDispatched ) && allFillstandCapable)
					PopupContextMenuForDataGrid.Items[4].Enabled = true; //Set Fillstand Completed
				else
					PopupContextMenuForDataGrid.Items[4].Enabled = false; //Set Fillstand Completed
			}
			else if (System.Convert.ToBoolean ( useArrivalTime ) == false &&
			 System.Convert.ToBoolean ( useStartTime ) == false &&
			 System.Convert.ToBoolean ( useStopTime ) == true)
			{
				PopupContextMenuForDataGrid.Items[0].Enabled = false;	// set arrived
				PopupContextMenuForDataGrid.Items[1].Enabled = false;	//Set Service Started
				PopupContextMenuForDataGrid.Items[2].Enabled = !( anyRequested || anyStopped || anyCompletedCanceled || anyRecirculation );	//Set Service Stopped

				if (!( anyRequested || anyDispatched ) && allCompleteCapable)
					PopupContextMenuForDataGrid.Items[3].Enabled = true;	//Set Service Completed
				else
					PopupContextMenuForDataGrid.Items[3].Enabled = false; //Set Service Completed
				if (!( anyRequested || anyDispatched ) && allFillstandCapable)
					PopupContextMenuForDataGrid.Items[4].Enabled = true; //Set Fillstand Completed
				else
					PopupContextMenuForDataGrid.Items[4].Enabled = false; //Set Fillstand Completed
			}
			else if (System.Convert.ToBoolean ( useArrivalTime ) == true &&
			 System.Convert.ToBoolean ( useStartTime ) == true &&
			 System.Convert.ToBoolean ( useStopTime ) == false)
			{
				PopupContextMenuForDataGrid.Items[0].Enabled = !( anyRequested || anyArrived || anyStarted || anyStopped || anyCompletedCanceled || anyRecirculation );	// set arrived
				PopupContextMenuForDataGrid.Items[1].Enabled = !( anyRequested || anyDispatched || anyStarted || anyStopped || anyCompletedCanceled || anyRecirculation );	//Set Service Started
				PopupContextMenuForDataGrid.Items[2].Enabled = false;	//Set Service Stopped

				if (!( anyRequested || anyDispatched || anyArrived ) && allCompleteCapable)
					PopupContextMenuForDataGrid.Items[3].Enabled = true;	//Set Service Completed
				else
					PopupContextMenuForDataGrid.Items[3].Enabled = false; //Set Service Completed

				if (!( anyRequested || anyDispatched || anyArrived ) && allFillstandCapable)
					PopupContextMenuForDataGrid.Items[4].Enabled = true; //Set Fillstand Completed
				else
					PopupContextMenuForDataGrid.Items[4].Enabled = false; //Set Fillstand Completed
			}
			else if (System.Convert.ToBoolean ( useArrivalTime ) == true &&
			 System.Convert.ToBoolean ( useStartTime ) == false &&
			 System.Convert.ToBoolean ( useStopTime ) == true)
			{
				PopupContextMenuForDataGrid.Items[0].Enabled = !( anyRequested || anyArrived || anyStarted || anyStopped || anyCompletedCanceled || anyRecirculation );	// set arrived
				PopupContextMenuForDataGrid.Items[1].Enabled = false;	//Set Service Started
				PopupContextMenuForDataGrid.Items[2].Enabled = !( anyRequested || anyDispatched || anyStopped || anyCompletedCanceled || anyRecirculation );	//Set Service Stopped

				if (!( anyRequested || anyDispatched || anyArrived || anyStarted ) && allCompleteCapable)
					PopupContextMenuForDataGrid.Items[3].Enabled = true;	//Set Service Completed
				else
					PopupContextMenuForDataGrid.Items[3].Enabled = false; //Set Service Completed

				if (!( anyRequested || anyDispatched || anyArrived || anyStarted ) && allFillstandCapable)
					PopupContextMenuForDataGrid.Items[4].Enabled = true; //Set Fillstand Completed
				else
					PopupContextMenuForDataGrid.Items[4].Enabled = false; //Set Fillstand Completed
			}
			else if (System.Convert.ToBoolean ( useArrivalTime ) == false &&
			 System.Convert.ToBoolean ( useStartTime ) == true &&
			 System.Convert.ToBoolean ( useStopTime ) == true)
			{
				PopupContextMenuForDataGrid.Items[0].Enabled = false;	// set arrived
				PopupContextMenuForDataGrid.Items[1].Enabled = !( anyRequested || anyStarted || anyStopped || anyCompletedCanceled || anyRecirculation );	//Set Service Started
				PopupContextMenuForDataGrid.Items[2].Enabled = !( anyRequested || anyDispatched || anyStopped || anyCompletedCanceled || anyRecirculation );	//Set Service Stopped

				if (!( anyRequested || anyDispatched || anyArrived || anyStarted ) && allCompleteCapable)
					PopupContextMenuForDataGrid.Items[3].Enabled = true;	//Set Service Completed
				else
					PopupContextMenuForDataGrid.Items[3].Enabled = false; //Set Service Completed

				if (!( anyRequested || anyDispatched || anyArrived || anyStarted ) && allFillstandCapable)
					PopupContextMenuForDataGrid.Items[4].Enabled = true; //Set Fillstand Completed
				else
					PopupContextMenuForDataGrid.Items[4].Enabled = false; //Set Fillstand Completed
			}
			else if (System.Convert.ToBoolean ( useArrivalTime ) == true &&
			 System.Convert.ToBoolean ( useStartTime ) == true &&
			 System.Convert.ToBoolean ( useStopTime ) == true)
			{
				PopupContextMenuForDataGrid.Items[0].Enabled = !( anyRequested || anyArrived || anyStarted || anyStopped || anyCompletedCanceled || anyRecirculation );	// set arrived
				PopupContextMenuForDataGrid.Items[1].Enabled = !( anyRequested || anyDispatched || anyStarted || anyStopped || anyCompletedCanceled || anyRecirculation );	//Set Service Started
				PopupContextMenuForDataGrid.Items[2].Enabled = !( anyRequested || anyDispatched || anyArrived || anyStopped || anyCompletedCanceled || anyRecirculation );	//Set Service Stopped

				if (!( anyRequested || anyDispatched || anyArrived || anyStarted ) && allCompleteCapable)
					PopupContextMenuForDataGrid.Items[3].Enabled = true;	//Set Service Completed
				else
					PopupContextMenuForDataGrid.Items[3].Enabled = false; //Set Service Completed

				if (!( anyRequested || anyDispatched || anyArrived || anyStarted ) && allFillstandCapable)
					PopupContextMenuForDataGrid.Items[4].Enabled = true; //Set Fillstand Completed
				else
					PopupContextMenuForDataGrid.Items[4].Enabled = false; //Set Fillstand Completed
			}

			arrivalToolStripMenuItem.Enabled = PopupContextMenuForDataGrid.Items[0].Enabled;
			startOfServiceToolStripMenuItem.Enabled = PopupContextMenuForDataGrid.Items[1].Enabled;
			stopOfServiceToolStripMenuItem.Enabled = PopupContextMenuForDataGrid.Items[2].Enabled;
			serviceCompletionToolStripMenuItem.Enabled = PopupContextMenuForDataGrid.Items[3].Enabled;
			fillstandCompletionToolStripMenuItem.Enabled = PopupContextMenuForDataGrid.Items[4].Enabled;

			// Only allow relog of Refuel or Defuel
			PopupContextMenuForDataGrid.Items[6].Enabled = refuelDefuelSelected;
			PopupContextMenuForDataGrid.Items[7].Enabled = allCancelCapable;

			// auto select the available menu option
			AutoSelectFirstAvailableMenuItem ( );
		}

		private void AutoSelectFirstAvailableMenuItem ( )
		{
			for (int iLoop = 0; iLoop < PopupContextMenuForDataGrid.Items.Count; iLoop++)
			{
				if (PopupContextMenuForDataGrid.Items[iLoop].Enabled == true &&
					iLoop != 5)	// this is the "-" menu line
				{
					PopupContextMenuForDataGrid.Items[iLoop].Select ( );
					break;
				}
			}
		}

		private void standByToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			StandbyStatusForm StandbyStatusForm = new StandbyStatusForm ( );
			if (StandbyStatusForm.ShowDialog ( this ) == DialogResult.OK)
			{
				// get the person and the equipment selected
				string SelectedPerson = StandbyStatusForm.SelectedPerson;
				string SelectedEquipment = StandbyStatusForm.SelectedEquipment;
				// set the values for the dispatch dialog and then open
				try
				{
					string[] selectedTransID = new string[dataGridView1.SelectedRows.Count];
					lock (dataGridView1)
					{
						for (int iLoop = 0; iLoop < dataGridView1.SelectedRows.Count; iLoop++)
						{
							DataRowView Row = (DataRowView) dataGridView1.SelectedRows[iLoop].DataBoundItem;
							selectedTransID[iLoop] = (string) Row["TransID"];
						}
					}

					DispatchForm dispatch = new DispatchForm ( dispatchSR.Translations, selectedTransID, SelectedPerson, SelectedEquipment, OperationLockDate );
					dispatch.ShowDialog ( this );
				}
				catch (Exception except)
				{
					ErrorHandler ( except );
				}
			}
		}

		private void ViewDispatched_Click ( object sender, EventArgs e )
		{
			// filter for dispatch
			int SelectedIndex = StatusCombo.FindString ( "Dispatched" );
			if (SelectedIndex >= 0)
				StatusCombo.SelectedIndex = SelectedIndex;

			vehicleComboBox.Focus ( );

		}

		private void ViewArrived_Click ( object sender, EventArgs e )
		{
			// filter for arrived
			int SelectedIndex = StatusCombo.FindString ( "Arrived" );
			if (SelectedIndex >= 0)
				StatusCombo.SelectedIndex = SelectedIndex;

			vehicleComboBox.Focus ( );

		}

		private void ViewStarted_Click ( object sender, EventArgs e )
		{
			// filter for started
			int SelectedIndex = StatusCombo.FindString ( "Started" );
			if (SelectedIndex >= 0)
				StatusCombo.SelectedIndex = SelectedIndex;

			vehicleComboBox.Focus ( );

		}

		private void ViewStopped_Click ( object sender, EventArgs e )
		{
			// filter for started
			int SelectedIndex = StatusCombo.FindString ( "Stopped" );
			if (SelectedIndex >= 0)
				StatusCombo.SelectedIndex = SelectedIndex;

			vehicleComboBox.Focus ( );

		}

		private void FlightLineStatus_Click ( object sender, EventArgs e )
		{
			// filter for flight line
			int SelectedIndex = StatusCombo.FindString ( "Flight Line" );
			if (SelectedIndex >= 0)
				StatusCombo.SelectedIndex = SelectedIndex;

		}

		private void ViewAll_Click ( object sender, EventArgs e )
		{
			// filter for all
			int SelectedIndex = StatusCombo.FindString ( "{All}" );
			if (SelectedIndex >= 0)
				StatusCombo.SelectedIndex = SelectedIndex;

			SelectedIndex = RequestTypeCombo.FindString ( "{All}" );
			if (SelectedIndex >= 0)
				RequestTypeCombo.SelectedIndex = SelectedIndex;

			SelectedIndex = vehicleComboBox.FindString ( "{All}" );
			if (SelectedIndex >= 0)
				vehicleComboBox.SelectedIndex = SelectedIndex;

			dataGridView1.Focus ( );
		}

		private void ViewRequested_Click ( object sender, EventArgs e )
		{
			// filter for requested
			int SelectedIndex = StatusCombo.FindString ( "Requested" );
			if (SelectedIndex >= 0)
				StatusCombo.SelectedIndex = SelectedIndex;

			vehicleComboBox.Focus ( );

		}

		private void ViewCompleted_Click ( object sender, EventArgs e )
		{
			// filter for Complete
			int SelectedIndex = StatusCombo.FindString ( "Completed" );
			if (SelectedIndex >= 0)
				StatusCombo.SelectedIndex = SelectedIndex;

			vehicleComboBox.Focus ( );

		}

		private void ViewCanceled_Click ( object sender, EventArgs e )
		{
			// filter for cancelled
			int SelectedIndex = StatusCombo.FindString ( "Cancelled" );
			if (SelectedIndex >= 0)
				StatusCombo.SelectedIndex = SelectedIndex;

			vehicleComboBox.Focus ( );

		}

		private void totalAndAverageToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			TotalAndAverageForm TotalandAverageForm = new TotalAndAverageForm ( DataAccess, dispatchSR.Translations, BeginDatePicker.Value, EndDatePicker.Value );
			TotalandAverageForm.ShowDialog ( this );
		}

		private void relogToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			try
			{
				Relog ( sender, e );
				ChangeStatusFilterIfNecessary ( TransactionStatus.Requested );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void cancelToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			try
			{
				CancelRequest ( sender, e );
				ChangeStatusFilterIfNecessary ( TransactionStatus.Cancelled );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void reportsToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			try
			{
				string baseAddress = ConfigurationManager.AppSettings["WebAppAddress"];
				if (String.IsNullOrEmpty ( baseAddress ))
				{
					throw new ApplicationException ( "WebAppAddress not in configuration file." );
				}

				EmbeddedBrowser embeddedBrowser = new EmbeddedBrowser ( baseAddress + "/FMReportWebMain/FMReportDynamicSelectionPage.aspx" );
				embeddedBrowser.ShowDialog ( this );

			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void evacuateToolStripMenuItemOnClick ( object sender, EventArgs e )
		{
			EvacuateForm openEvacuateForm = new EvacuateForm ( BeginDatePicker.Value, dispatchSR.Translations );
			openEvacuateForm.ShowDialog ( this );
		}

		private void flightLineStatusToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			try
			{
				string[] TransId = null;
				DispatchForm dispatch = new DispatchForm ( dispatchSR.Translations, TransId, null, null, OperationLockDate );
				dispatch.DisplayMode = DispatchForm.DisplayModeType.FlightLineStatus;
				dispatch.ShowDialog ( this );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void FlightLineButton_Click ( object sender, EventArgs e )
		{
			try
			{
				flightLineStatusToolStripMenuItem_Click ( null, null );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void arrivalToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			SetSelectedToArrived ( sender, e );
			ChangeStatusFilterIfNecessary ( TransactionStatus.Arrived );
		}

		private void ChangeStatusFilterIfNecessary ( TransactionStatus transactionStatus )
		{
			if (vehicleComboBox.SelectedIndex != 0)
			{
				StatusCombo.Text = Enum.GetName ( typeof ( TransactionStatus ), transactionStatus );
				dataGridView1.SelectAll ( );
			}
		}

		private void startOfServiceToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			SetSelectedToStarted ( sender, e );
			ChangeStatusFilterIfNecessary ( TransactionStatus.Started );
		}

		private void stToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			SetSelectedToStopped ( sender, e );
			ChangeStatusFilterIfNecessary ( TransactionStatus.Stopped );
		}

		private void serviceCompletionToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			SetSelectedToCompleted ( sender, e );
			ChangeStatusFilterIfNecessary ( TransactionStatus.Completed );
		}

		private void fillstandCompletionToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			SetFillStandCompleted ( sender, e );
		}

		private void operationToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			SetPopupMenuEnableDisable ( );
		}

		private void optionalTimesToolStripMenuItem1_Click ( object sender, EventArgs e )
		{
			OptionalTimesForm optionalTimesForm = new OptionalTimesForm ( );
			optionalTimesForm.ShowDialog ( this );
		}

		private void julianDateTimer_Tick ( object sender, EventArgs e )
		{
			try
			{
				FMChannelFactory<ISites> sitesClient = new FMChannelFactory<ISites> ( );
				ISites sites = sitesClient.CreateProxy ( );

				SiteClass site = sites.Get(Security, Security.SiteGuid, false, false, false);
				SiteTimeConverter timeConverter = new SiteTimeConverter ( site );

				// Initial Julian Date Display
				julianDateLabel.Text = "Date: " + timeConverter.Now ( ).ToMilitaryJulianDateString ( );

				// Also set the date ranges to the new time
				BeginDatePicker.Value = timeConverter.Today().Date;
				CurrentSelectedBeginDatePicker = BeginDatePicker.Value;

				EndDatePicker.Value = timeConverter.Today().Date;
				CurrentSelectedEndDatePicker = EndDatePicker.Value;

				julianDateTimer.Interval = ( ( ( 24 - timeConverter.Now ( ).Hour - 1 ) * 60 * 60 ) + ( ( 60 - timeConverter.Now ( ).Minute - 1 ) * 60 ) + ( 60 - DateTime.Now.Second ) ) * 1000;

				refreshToolStripMenuItem_Click ( this, null );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void contentsToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			try
			{
				Help.ShowHelp ( this, @"FMDispatchHelp.chm", HelpNavigator.TableOfContents );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void indexToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			try
			{
				Help.ShowHelpIndex ( this, @"FMDispatchHelp.chm" );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void vehicleComboBox_SelectedIndexChanged ( object sender, EventArgs e )
		{
			try
			{
				// Limit grid view to only this vehicle
				DataView view = (DataView) dataGridView1.DataSource;
				if (vehicleComboBox.SelectedIndex > 0)
				{
					string vehicleXREF = vehicleComboBox.Text;
					view.RowFilter = String.Format ( "XREF = '{0}'", vehicleXREF );

					// now select all the vehicle rows
					dataGridView1.SelectAll ( );

				}
				else
				{
					// when the filter is cleared the grid is deselecting all of the records
					// we need to store the current selected records so we can then restore them
					// Clear the filter
					string[] selectedTransID = new string[dataGridView1.SelectedRows.Count];
					string CurrentRowTransID = string.Empty;
					int NumberOfSelectedRows = dataGridView1.SelectedRows.Count;

					// store the current row so it can be restored
					lock (dataGridView1)
					{
						if (dataGridView1.CurrentRow != null)
						{
							DataRowView CurrentRow = (DataRowView) dataGridView1.Rows[dataGridView1.CurrentRow.Index].DataBoundItem;
							if (CurrentRow != null)
								CurrentRowTransID = (string) CurrentRow["TransID"];
						}

						for (int iLoop = 0; iLoop < NumberOfSelectedRows; iLoop++)
						{
							DataRowView Row = (DataRowView) dataGridView1.SelectedRows[iLoop].DataBoundItem;
							selectedTransID[iLoop] = (string) Row["TransID"];
						}

						view.RowFilter = string.Empty;

						// we need to set the current cell first since the grid will change the number of selections to 1 when it is set
						foreach (DataGridViewRow Row in dataGridView1.Rows)
						{
							DataRowView dataRow = (DataRowView) Row.DataBoundItem;
							if (NumberOfSelectedRows > 0)
								Row.Selected = false;
							if (!string.IsNullOrEmpty ( CurrentRowTransID ) &&
								CurrentRowTransID.Equals ( (string) dataRow["TransID"] ))
							{
								// restore the current selection
								// the only way to do this is by setting the currentcell variable since the currentrow is read only
								dataGridView1.CurrentCell = Row.Cells[0];
							}
						}

						for (int iLoop = 0; iLoop < NumberOfSelectedRows; iLoop++)
						{
							foreach (DataGridViewRow Row in dataGridView1.Rows)
							{
								DataRowView dataRow = (DataRowView) Row.DataBoundItem;
								if (dataRow != null)
								{
									if (selectedTransID[iLoop].Equals ( (string) dataRow["TransID"] ))
									{
										Row.Selected = true;

										break;
									}
								}
							}
						}
					}
				}

				RenumberGrid ( dataGridView1 );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void refreshToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			try
			{
				UpdateView ( );
			}
			catch (Exception except)
			{
				ErrorHandler ( except );
			}

		}

		private void exportToAccountingToolStripMenuItem_Click ( object sender, EventArgs e )
		{
			DispatchExportForm dispatchExportForm = new DispatchExportForm ( DataAccess, OperationLockDate, dispatchSR.Translations );
			if (dispatchExportForm.ShowDialog ( this ) == DialogResult.OK)
			{
				OperationLockDate = dispatchExportForm.OperationLockDate;
			}
		}

		private void HelpAboutClicked ( object sender, EventArgs e )
		{
			AboutBox1 HelpAbout = new AboutBox1 ( );
			HelpAbout.ShowDialog ( this );
		}

		private void vehicleComboBox_KeyPress ( object sender, KeyPressEventArgs e )
		{
			if (!( base.UpdatedItemInList ( sender as ComboBox, e ) ))
			{
				System.Console.Beep ( );
				e.Handled = true;
			}
		}

		private void dataGridView1_ColumnDisplayIndexChanged ( object sender, DataGridViewColumnEventArgs e )
		{
			dataGridView1ColumnPositions[e.Column.Index] = e.Column.DisplayIndex;
		}

		private void GetDisplayGridColumnPositions ( )
		{
			string AppConfigItem = Security.UserID + "Grid1ColumnPositions";
			int iStartPosistion = 0;
			int iEndPosistion = 0;

			// check if there are configurations for this user
			System.Configuration.Configuration config = ConfigurationManager.OpenExeConfiguration ( ConfigurationUserLevel.None );
			string FileColumnPositions = ConfigurationManager.AppSettings[AppConfigItem];
			if (FileColumnPositions != null)
			{
				// data exists so read into the array
				// there are 22 columns seperated by a semi-colon so parse the received string into the interger array
				for (int iLoop = 0; iLoop < GRID1_NUMCOLS; iLoop++)
				{
					iEndPosistion = FileColumnPositions.IndexOf ( ';', iStartPosistion );
					dataGridView1ColumnPositions[iLoop] = System.Convert.ToInt32 ( FileColumnPositions.Substring ( iStartPosistion, iEndPosistion - iStartPosistion ) );
					iStartPosistion = iEndPosistion + 1;
				}
			}
			else
			{
				// no data so just set at the default
				for (int iLoop = 0; iLoop < GRID1_NUMCOLS; iLoop++)
				{
					dataGridView1ColumnPositions[iLoop] = iLoop;
				}
			}
		}

		private void StoreDisplayGridColumnPositions ( )
		{
			string AppConfigItem = Security.UserID + "Grid1ColumnPositions";
			string CombinedColumnPositionString = string.Empty;
			//dataGridView1ColumnPositions
			// check if there are configurations for this user
			System.Configuration.Configuration config = ConfigurationManager.OpenExeConfiguration ( ConfigurationUserLevel.None );
			string FileColumnPositions = ConfigurationManager.AppSettings[AppConfigItem];
			// check if the data already exists and delete it before we add it
			if (FileColumnPositions != null)
			{
				// data exists so read into the array
				config.AppSettings.Settings.Remove ( AppConfigItem );
			}

			// build up a string with the values seperated by semi-colons
			for (int iLoop = 0; iLoop < GRID1_NUMCOLS; iLoop++)
			{
				CombinedColumnPositionString += dataGridView1ColumnPositions[iLoop];
				CombinedColumnPositionString += ";";
			}

			// write the data to the config file
			config.AppSettings.Settings.Add ( AppConfigItem, CombinedColumnPositionString );

			// Save the configuration file.
			config.Save ( ConfigurationSaveMode.Modified );

			// Force a reload of a changed section.
			ConfigurationManager.RefreshSection ( "appSettings" );

		}

		private void GetColumnWidthsForGrid ( )
		{
			// get grid1 positions

			string AppConfigItem = Security.UserID + "Grid1ColumnWidths";
			int iStartPosistion = 0;
			int iEndPosistion = 0;

			// check if there are configurations for this user
			System.Configuration.Configuration config = ConfigurationManager.OpenExeConfiguration ( ConfigurationUserLevel.None );
			string FileColumnPositions = ConfigurationManager.AppSettings[AppConfigItem];
			if (FileColumnPositions != null)
			{
				// data exists so read into the array
				// there are 22 columns seperated by a semi-colon so parse the received string into the interger array
				for (int iLoop = 0; iLoop < GRID1_NUMCOLS; iLoop++)
				{
					iEndPosistion = FileColumnPositions.IndexOf ( ';', iStartPosistion );
					dataGridView1ColumnWidths[iLoop] = System.Convert.ToInt32 ( FileColumnPositions.Substring ( iStartPosistion, iEndPosistion - iStartPosistion ) );
					iStartPosistion = iEndPosistion + 1;
				}
			}
			else
			{
				// no data so just set at the default
				SetColumnWidthsForGridFromGrid ( );
			}
		}

		private void SetColumnWidthsForGridFromGrid ( )
		{
			for (int iLoop = 0; iLoop < GRID1_NUMCOLS; iLoop++)
			{
				dataGridView1ColumnWidths[iLoop] = dataGridView1.Columns[iLoop].Width;
			}
		}

		private void StoreGrid1ColumnWidths ( )
		{
			string AppConfigItem = Security.UserID + "Grid1ColumnWidths";
			string CombinedColumnPositionString = string.Empty;
			//dataGridView1ColumnPositions
			// check if there are configurations for this user
			System.Configuration.Configuration config = ConfigurationManager.OpenExeConfiguration ( ConfigurationUserLevel.None );
			string FileColumnPositions = ConfigurationManager.AppSettings[AppConfigItem];
			// check if the data already exists and delete it before we add it
			if (FileColumnPositions != null)
			{
				// data exists so read into the array
				config.AppSettings.Settings.Remove ( AppConfigItem );
			}

			// build up a string with the values seperated by semi-colons
			for (int iLoop = 0; iLoop < GRID1_NUMCOLS; iLoop++)
			{
				CombinedColumnPositionString += dataGridView1ColumnWidths[iLoop];
				CombinedColumnPositionString += ";";
			}

			// write the data to the config file
			config.AppSettings.Settings.Add ( AppConfigItem, CombinedColumnPositionString );

			// Save the configuration file.
			config.Save ( ConfigurationSaveMode.Modified );

			// Force a reload of a changed section.
			ConfigurationManager.RefreshSection ( "appSettings" );

		}

	}

}
