/*

	DROP TABLE [staging].[tblTransactionLineItems]

*/
CREATE TABLE [staging].[tblTransactionLineItems] (
    [SequenceID]                            SMALLINT           NULL,
    [MeterStart]                            FLOAT (53)         NULL,
    [MeterStop]                             FLOAT (53)         NULL,
    [GrossQuantity]                         FLOAT (53)         NULL,
    [Temperature]                           FLOAT (53)         NULL,
    [Vcf]                                   FLOAT (53)         NULL,
    [Density]                               FLOAT (53)         NULL,
    [Product]                               NVARCHAR (30)      NULL,
    [ProductCode]                           NVARCHAR (30)      NULL,
    [ProductType]                           NVARCHAR (20)      NULL,
    [ProductPrice]                          FLOAT (53)         NULL,
    [CLIN]                                  NVARCHAR (10)      NULL,
    [NetQuantity]                           FLOAT (53)         NULL,
    [ContractNumber]                        NVARCHAR (30)      NULL,
    [DestinationRegistrationID]             NVARCHAR (30)      NULL,
    [DestinationSerialNumber]               NVARCHAR (10)      NULL,
    [DestinationEquipmentType]              NVARCHAR (50)      NULL,
    [DestinationEquipmentModel]             NVARCHAR (20)      NULL,
    [DestinationCompanyEquipmentID]         NVARCHAR (30)      NULL,
    [DestinationCompartmentID]              NVARCHAR (50)      NULL,
    [SourceRegistrationID]                  NVARCHAR (30)      NULL,
    [SourceSerialNumber]                    NVARCHAR (10)      NULL,
    [SourceEquipmentType]                   NVARCHAR (50)      NULL,
    [SourceEquipmentModel]                  NVARCHAR (20)      NULL,
    [SourceCompanyEquipmentID]              NVARCHAR (30)      NULL,
    [SourceCompartmentID]                   NVARCHAR (50)      NULL,
    [MeterFactor]                           FLOAT (53)         NULL,
    [LineItemSequenceNumber]                NVARCHAR (5)       NULL,
    [BatchNumber]                           NVARCHAR (20)      NULL,
    [DocumentNumber]                        NVARCHAR (30)      NULL,
    [LineFill]                              FLOAT (53)         NULL,
    [BottomVolume]                          FLOAT (53)         NULL,
    [NetCapacity]                           FLOAT (53)         NULL,
    [Customs]                               NVARCHAR (20)      NULL,
    [ArmNumber]                             INT                NULL,
    [LineNumber]                            INT                NULL,
    [OperatorID]                            NVARCHAR (50)      NULL,
    [TankStatus]                            NVARCHAR (30)      NULL,
    [MeterStartDateTime]                    DATETIMEOFFSET (7) NULL,
    [MeterStopDateTime]                     DATETIMEOFFSET (7) NULL,
    [Pit]                                   NVARCHAR (10)      NULL,
    [RequestedDateTime]                     DATETIMEOFFSET (7) NULL,
    [DispatchedDateTime]                    DATETIMEOFFSET (7) NULL,
    [AcknowledgedDateTime]                  DATETIMEOFFSET (7) NULL,
    [OnLocationTime]                        DATETIMEOFFSET (7) NULL,
    [ValidationDateTime]                    DATETIMEOFFSET (7) NULL,
    [CompletionDateTime]                    DATETIMEOFFSET (7) NULL,
    [ReceiptVariance]                       FLOAT (53)         NULL,
    [DifferentialPressure]                  FLOAT (53)         NULL,
    [LoadRackVariance]                      FLOAT (53)         NULL,
    [RequestedBy]                           NVARCHAR (50)      NULL,
    [FreezePoint]                           FLOAT (53)         NULL,
    [DeleteFlag]                            BIT                NULL,
    [StorageLocationID]                     NVARCHAR (50)      NULL,
    [MeterID]                               NVARCHAR (50)      NULL,
    [AdditiveProfileID]                     NVARCHAR (50)      NULL,
    [CreatedBy]                             [dbo].[udtUserID]  NULL,
    [CreatedDate]                           DATETIMEOFFSET (7) NULL,
    [UpdatedBy]                             [dbo].[udtUserID]  NULL,
    [UpdatedDate]                           DATETIMEOFFSET (7) NULL,
    [PresetAmount]                          FLOAT (53)         NULL,
    [EngineeringUnitsIndex]                 INT                NULL,
    [CustomerProductName]                   NVARCHAR (50)      NULL,
    [CustomerProductCode]                   NVARCHAR (20)      NULL,
    [TransactionInventoryDate]              DATE               NULL,
    [COAWaiver]                             BIT                NULL,
    [COANote]                               NVARCHAR (50)      NULL,
    [COAID]                                 NVARCHAR (40)      NULL,
    [Tax1]                                  FLOAT (53)         NULL,
    [Tax2]                                  FLOAT (53)         NULL,
    [Tax3]                                  FLOAT (53)         NULL,
    [Tax4]                                  FLOAT (53)         NULL,
    [Tax5]                                  FLOAT (53)         NULL,
    [TransVersion]                          BIGINT             NULL,
    [LoadingLocationID]                     NVARCHAR (30)      NULL,
    [ImproperAdditization]                  BIT                NULL,
    [BrokenBlend]                           BIT                NULL,
    [ContaminatePrompt]                     BIT                NULL,
    [CompartmentsPreviouslyLoaded]          BIT                NULL,
    [CompartmentsEmpty]                     BIT                NULL,
    [Flag01]                                BIT                NULL,
    [Flag02]                                BIT                NULL,
    [Flag03]                                BIT                NULL,
    [Flag04]                                BIT                NULL,
    [Flag05]                                BIT                NULL,
    [Flag06]                                BIT                NULL,
    [Number01]                              FLOAT (53)         NULL,
    [Number02]                              FLOAT (53)         NULL,
    [Number03]                              FLOAT (53)         NULL,
    [Number04]                              FLOAT (53)         NULL,
    [Number05]                              FLOAT (53)         NULL,
    [Number06]                              FLOAT (53)         NULL,
    [OdometerHours]                         FLOAT (53)         NULL,
    [EndDeliveryDate]                       DATETIMEOFFSET (7) NULL,
    [RequestedDeliveryDate]                 DATETIMEOFFSET (7) NULL,
    [InvoiceNumber]                         NVARCHAR (50)      NULL,
    [InvoiceLineNumber]                     NVARCHAR (50)      NULL,
    [AlternativeGrossVolume]                FLOAT (53)         NULL,
    [AlternativeNetVolume]                  FLOAT (53)         NULL,
    [AlternativeUnits]                      INT                NULL,
    [TankLevel]                             FLOAT (53)         NULL,
    [TankLevelUnits]                        INT                NULL,
    [Date01]                                DATETIMEOFFSET (7) NULL,
    [Date02]                                DATETIMEOFFSET (7) NULL,
    [Date03]                                DATETIMEOFFSET (7) NULL,
    [Date04]                                DATETIMEOFFSET (7) NULL,
    [NonDomesticPrice]                      FLOAT (53)         NULL,
    [CurrencyUnit]                          INT                NULL,
    [ExchangeRate]                          FLOAT (53)         NULL,
    [QualityTestNumber]                     NVARCHAR (50)      NULL,
    [Odometer]                              FLOAT (53)         NULL,
    [DeliveryLocation]                      NVARCHAR (50)      NULL,
    [Variance]                              FLOAT (53)         NULL,
    [PartialFill]                           BIT                NULL,
    [MassQuantity]                          FLOAT (53)         NULL,
    [NetManualValueFlag]                    BIT                NULL,
    [MassManualValueFlag]                   BIT                NULL,
    [GrossManualValueFlag]                  BIT                NULL,
    [VcfManualValueFlag]                    BIT                NULL,
    [TransactionLineItemGuid]               UNIQUEIDENTIFIER   NULL,    
    [LookupTransactionStatusIndex]          INT                NULL,
    [LookupQualityIndex]                    INT                NULL,
    [StorageLocationTankGuid]               UNIQUEIDENTIFIER   NULL,
    [AdditiveProfileGuid]                   UNIQUEIDENTIFIER   NULL,
    [DestinationCompartmentEquipmentGuid]   UNIQUEIDENTIFIER   NULL,
    [DestinationEquipmentGuid]              UNIQUEIDENTIFIER   NULL,
    [OperatorPersonnelGuid]                 UNIQUEIDENTIFIER   NULL,
    [ProductGuid]                           UNIQUEIDENTIFIER   NULL,
    [SourceCompartmentEquipmentGuid]        UNIQUEIDENTIFIER   NULL,
    [SourceEquipmentGuid]                   UNIQUEIDENTIFIER   NULL,
    [TransactionGuid]                       UNIQUEIDENTIFIER   NULL,
    [CurrencyGuid]                          UNIQUEIDENTIFIER   NULL,
    [OrderReferenceTransactionLineItemGuid] UNIQUEIDENTIFIER   NULL,
    [LoadingLocationStationGuid]            UNIQUEIDENTIFIER   NULL,
    [MeterGuid]                             UNIQUEIDENTIFIER   NULL,
    [PackageManualValueFlag]                BIT                NULL,
    [CleanLineItem]                         BIT                NULL,
    [CleanLineDeductItem]                   BIT                NULL,
    [CleanLineDeductQuantity]               FLOAT (53)         NULL,
    [CleanLinePackQuantity]                 FLOAT (53)         NULL,
    [DualFuelingModeFlag]                   BIT                NULL,
    [DualFuelingPrimaryFlag]                BIT                NULL,
    [EngineRunTime]                         FLOAT (53)         NULL,
    [FlowRate]                              FLOAT (53)         NULL,
    [FuelCompressionFactor]                 FLOAT (53)         NULL,
    [HydrantPressure]                       FLOAT (53)         NULL,
    [MobileDeviceID]                        NVARCHAR (50)      NULL,
    [MobileDeviceGuid]                      UNIQUEIDENTIFIER   NULL,
    [TemperatureQualityStatus]              NVARCHAR (50)      NULL,
    [MeterStartObtainedAutomaticallyFlag]   BIT                NULL,
    [MeterStopObtainedAutomaticallyFlag]    BIT                NULL,
	[InventoryDateKey]						INT                NULL,
	[ArchiveDate]							DATETIMEOFFSET (7) NULL,
	[ETLProcessKey]							BIGINT			   NULL,
	[SourceClusterIdx]						BIGINT			   NULL,
	[SourceRowVersion]						BIGINT			   NULL,
	[IgnoreRecord]							BIT				   NOT NULL,
	[IsProcessed]							BIT				   NOT NULL,
	[_RowVersion]							ROWVERSION		   NOT NULL,
	[SKey]									INT				   IDENTITY (1, 1) NOT NULL
    CONSTRAINT [PK_tblTransactionLineItems_SKey] PRIMARY KEY CLUSTERED ([SKey] ASC)
);

GO


ALTER TABLE [staging].[tblTransactionLineItems] ADD  DEFAULT ((0)) FOR [IgnoreRecord]
GO


ALTER TABLE [staging].[tblTransactionLineItems] ADD  DEFAULT ((0)) FOR [IsProcessed]
GO