//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelsManager.FMEntityImportWebApp {
    
    
    public partial class EnterpriseSyncSettingsPage {
        
        /// <summary>
        /// InstructionsLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel InstructionsLabel;
        
        /// <summary>
        /// EnableGlobalSynchronizationLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel EnableGlobalSynchronizationLabel;
        
        /// <summary>
        /// EnableGlobalSynchronizationCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMCheckBox EnableGlobalSynchronizationCheckBox;
        
        /// <summary>
        /// FuelsManagerAuthSectionLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel FuelsManagerAuthSectionLabel;
        
        /// <summary>
        /// FuelsManagerAcceptUserIDLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel FuelsManagerAcceptUserIDLabel;
        
        /// <summary>
        /// FuelsManagerAcceptUserIDCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMCheckBox FuelsManagerAcceptUserIDCheckBox;
        
        /// <summary>
        /// FuelsManagerAcceptClientCertificateLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel FuelsManagerAcceptClientCertificateLabel;
        
        /// <summary>
        /// FuelsManagerAcceptClientCertificateCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMCheckBox FuelsManagerAcceptClientCertificateCheckBox;
        
        /// <summary>
        /// MessageSecuritySectionLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel MessageSecuritySectionLabel;
        
        /// <summary>
        /// MessageSecurityClientSignatureRequiredLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel MessageSecurityClientSignatureRequiredLabel;
        
        /// <summary>
        /// MessageSecurityClientSignatureRequiredCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMCheckBox MessageSecurityClientSignatureRequiredCheckBox;
        
        /// <summary>
        /// MessageSecurityClientEncryptionRequiredLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel MessageSecurityClientEncryptionRequiredLabel;
        
        /// <summary>
        /// MessageSecurityClientEncryptionRequiredCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMCheckBox MessageSecurityClientEncryptionRequiredCheckBox;
        
        /// <summary>
        /// FuelsManagerAuthInstructionLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel FuelsManagerAuthInstructionLabel;
        
        /// <summary>
        /// NodeHealthSectionLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel NodeHealthSectionLabel;
        
        /// <summary>
        /// NodeHealthCriticalThresholdLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel NodeHealthCriticalThresholdLabel;
        
        /// <summary>
        /// NodeHealthCriticalThresholdHoursTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox NodeHealthCriticalThresholdHoursTextBox;
        
        /// <summary>
        /// NodeHealthCriticalThresholdLabel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label NodeHealthCriticalThresholdLabel2;
        
        /// <summary>
        /// NodeHealthCautionThresholdLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FMControls.FMLabel NodeHealthCautionThresholdLabel;
        
        /// <summary>
        /// NodeHealthCautionThresholdHoursTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox NodeHealthCautionThresholdHoursTextBox;
        
        /// <summary>
        /// NodeHealthCautionThresholdLabel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label NodeHealthCautionThresholdLabel2;
    }
}
