//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelsManager.FMEntityImportWebApp
{


	public partial class SynchronizationSessionConflicts
	{

		/// <summary>
		/// SynchronizationSessionSummaryDetails control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlForm SynchronizationSessionSummaryDetails;

		/// <summary>
		/// ScriptManager control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.ScriptManager ScriptManager;

		/// <summary>
		/// Image1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Image Image1;

		/// <summary>
		/// labSynchronizationSummary control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel labSynchronizationSummary;

		/// <summary>
		/// StatusLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel StatusLabel;

		/// <summary>
		/// StatusDropDownList control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.DropDownList StatusDropDownList;

		/// <summary>
		/// RefreshButton control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMButton RefreshButton;

		/// <summary>
		/// ConflictErrorLabel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMLabel ConflictErrorLabel;

		/// <summary>
		/// SyncSessionConflictDataGrid control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::FMControls.FMDataGridFixedPaging SyncSessionConflictDataGrid;
	}
}
