// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage( "Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId="FMBusinessObjects.LogClient.Logger.Debug(System.String)", Scope="member", Target="FMBusinessServices.ServiceClasses.AdjustmentDistributionProcessorClass.#GetAdjustmentAliasTransType()" )]
[assembly: SuppressMessage("Style", "IDE0038:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.CompanyMapsClass.FMBusinessServices#InternalClasses#IDependency#Insert(FMBusinessObjects.DataObjects.SecurityClass,FMBusinessObjects.DataObjects.BaseDataObject,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0019:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.CompanyMapsClass.FMBusinessServices#InternalClasses#IDependency#Purge(FMBusinessObjects.DataObjects.SecurityClass,FMBusinessObjects.DataObjects.BaseDataObject)")]
[assembly: SuppressMessage("Style", "IDE0019:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.CompaniesClass.ExcelImportImpl(FMBusinessObjects.DataObjects.SecurityClass,System.Object)")]
[assembly: SuppressMessage("Style", "IDE0019:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.CompaniesClass.FMBusinessServices#InternalClasses#IDependency#Insert(FMBusinessObjects.DataObjects.SecurityClass,FMBusinessObjects.DataObjects.BaseDataObject,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0019:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.CompaniesClass.FMBusinessServices#InternalClasses#IDependency#Purge(FMBusinessObjects.DataObjects.SecurityClass,FMBusinessObjects.DataObjects.BaseDataObject)")]
[assembly: SuppressMessage("Style", "IDE0019:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.CompaniesClass.FMBusinessServices#InternalClasses#IDependency#Update(FMBusinessObjects.DataObjects.SecurityClass,FMBusinessObjects.DataObjects.BaseDataObject)")]
[assembly: SuppressMessage("Style", "IDE0019:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.SitesClass.FMBusinessServices#InternalClasses#IDependency#Purge(FMBusinessObjects.DataObjects.SecurityClass,FMBusinessObjects.DataObjects.BaseDataObject)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "API has been published and is in use", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.SitesClass.Login(System.String,System.String,System.String,System.Boolean,System.Int32)~FMBusinessObjects.ServiceRequests.SecurityLoginResponse")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "API has been published and is in use", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.SitesClass.Login(System.String,System.String,System.String,System.Boolean,System.Int32,System.Boolean@,System.Int32@,FMBusinessObjects.DataObjects.SecurityClass@)~System.String")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Need to preserve the different types", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.GroupsClass.EnumerateByUserForSiteHierarchy(FMBusinessObjects.DataObjects.SecurityClass,System.Guid,System.Guid)~FMBusinessObjects.DataObjects.GroupCollectionClass")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Clearer leaving as if block", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.PidxBolProcessorClass.GetProductInfo(FMBusinessServices.ServiceClasses.PidxBolProcessorClass.BolTypes)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Clearer leaving as if block", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.PidxBolProcessorClass.CreateBl(FMBusinessObjects.DataObjects.PIDXProfileClass,FMBusinessObjects.DataObjects.TransactionPIDXDO)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Clearer leaving as if block", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.LeakTestsClass.Run(FMBusinessObjects.DataObjects.SecurityClass,FMBusinessObjects.DataObjects.Point,FMBusinessObjects.DataObjects.LeakAnalysisType,FMBusinessObjects.DataObjects.LeakAnalysisMethod,System.DateTimeOffset,System.DateTimeOffset,FMBusinessObjects.DataObjects.LeakAnalysisResult@)~FMBusinessObjects.DataObjects.LeakDetectionError")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "Change to inline declaration not needed; does not really make code any cleaner", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.SitesClass.Login(System.String,System.String,System.String,System.Boolean,System.Int32)~FMBusinessObjects.ServiceRequests.SecurityLoginResponse")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "Change to inline declaration not needed; does not really make code any cleaner", Scope = "member", Target = "~M:FMBusinessServices.ServiceClasses.SitesClass.Login(System.String,System.String,System.String,System.Boolean,System.Int32,System.Boolean@,System.Int32@,FMBusinessObjects.DataObjects.SecurityClass@)~System.String")]
