CREATE PROCEDURE [dbo].[gsp_ReportApprovalsUpdateByPK]
(
		@ReportApprovalGuid uniqueidentifier
	,	@EventIndex bigint=NULL
	,	@ReportName nvarchar(75)=NULL
	,	@ParameterValue nvarchar(50)=NULL
	,	@MaximumRowVersionNumber bigint=NULL
	,	@NextApprovalUser udtUserID=NULL
	,	@NextApprovalEmail nvarchar(50)=NULL
	,	@ApprovalName nvarchar(50)=NULL
    ,   @CompanyManagerGuid uniqueidentifier=NULL
	,	@SiteGuid uniqueidentifier=NULL
	,	@LookupReportApprovalStateIndex int=NULL
	,	@_RowVersion timestamp=NULL OUTPUT
	,	@NullOverrideEventIndex BIT=0 
	,	@NullOverrideReportName BIT=0 
	,	@NullOverrideParameterValue BIT=0 
	,	@NullOverrideMaximumRowVersionNumber BIT=0 
	,	@NullOverrideNextApprovalUser BIT=0 
	,	@NullOverrideNextApprovalEmail BIT=0 
	,	@NullOverrideApprovalName BIT=0 
    ,   @NullOverrideCompanyManagerGuid BIT=0
	,	@NullOverrideSiteGuid BIT=0 
	,	@NullOverrideLookupReportApprovalStateIndex BIT=0 
)
	AS
	BEGIN
	------------------------------------------------------------------------------------------------------
	-- Stored procedure: [dbo].[gsp_ReportApprovalsUpdateByPK] 
	-- Author: DBA - Auto generated
	-- Version/Date: 1.0.003 / 2014-02-05 16:52:29.7204192 -05:00
	-- Purpose: Update table [dbo].[tblReportApprovals]
	-- Notes:
	-- 1. @ReportApprovalGuid and @UpdatedBy are required parameter.
	-- 2. If a value other than NULL is passed on @_RowVersion parameter then the stored procedure verifies whether _RowVersion of the record matches with the  
	--    @_RowVersion parameter and it will throw an exception if they don't match, otherwise it saves the parameters regardless.
	-- 3. The @_RowVersion output parameter will always be updated with new timestamp generated by the updating of the record.
	-- 4. To update a column with NULL then set the corresponding "@NullOverride..." parameter to 1 and either pass NULL through the correlated parameter 
	--    or do not include the parameter at all. 
	--    Example - Saving NULL to SiteGuid on tblEquipment:
	--            EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...',@SiteGuid=NULL, @NullOverrideSiteGuid=1 
	--       or   EXEC gsp_EquipmentUpdateByPK @EquipmentGuid='0000-...', @NullOverrideSiteGuid=1 
	------------------------------------------------------------------------------------------------------
	SET NOCOUNT ON;
	BEGIN TRY
		IF @_RowVersion IS NOT NULL AND NOT EXISTS(SELECT 1 FROM [dbo].[tblReportApprovals] WHERE ReportApprovalGuid=@ReportApprovalGuid AND _RowVersion=@_RowVersion)
		BEGIN
			RAISERROR('Attempted to modify a stale copy of the record',16,1);
			RETURN;
		END
 
		UPDATE [dbo].[tblReportApprovals] SET
			[ReportName]=(CASE ISNULL(@NullOverrideReportName,0) WHEN 1 THEN @ReportName ELSE ISNULL(@ReportName,[ReportName]) END)
		,	[ParameterValue]=(CASE ISNULL(@NullOverrideParameterValue,0) WHEN 1 THEN @ParameterValue ELSE ISNULL(@ParameterValue,[ParameterValue]) END)
		,	[MaximumRowVersionNumber]=(CASE ISNULL(@NullOverrideMaximumRowVersionNumber,0) WHEN 1 THEN @MaximumRowVersionNumber ELSE ISNULL(@MaximumRowVersionNumber,[MaximumRowVersionNumber]) END)
		,	[NextApprovalUser]=(CASE ISNULL(@NullOverrideNextApprovalUser,0) WHEN 1 THEN @NextApprovalUser ELSE ISNULL(@NextApprovalUser,[NextApprovalUser]) END)
		,	[NextApprovalEmail]=(CASE ISNULL(@NullOverrideNextApprovalEmail,0) WHEN 1 THEN @NextApprovalEmail ELSE ISNULL(@NextApprovalEmail,[NextApprovalEmail]) END)
		,	[ApprovalName]=(CASE ISNULL(@NullOverrideApprovalName,0) WHEN 1 THEN @ApprovalName ELSE ISNULL(@ApprovalName,[ApprovalName]) END)
		,	[CompanyManagerGuid]=(CASE ISNULL(@NullOverrideCompanyManagerGuid,0) WHEN 1 THEN @CompanyManagerGuid ELSE ISNULL(@CompanyManagerGuid,[CompanyManagerGuid]) END)
		,	[SiteGuid]=(CASE ISNULL(@NullOverrideSiteGuid,0) WHEN 1 THEN @SiteGuid ELSE ISNULL(@SiteGuid,[SiteGuid]) END)
		,	[LookupReportApprovalStateIndex]=(CASE ISNULL(@NullOverrideLookupReportApprovalStateIndex,0) WHEN 1 THEN @LookupReportApprovalStateIndex ELSE ISNULL(@LookupReportApprovalStateIndex,[LookupReportApprovalStateIndex]) END)
		WHERE	ReportApprovalGuid=@ReportApprovalGuid;
 
		SELECT @_RowVersion=_RowVersion        
		FROM [dbo].[tblReportApprovals]           
		WHERE ReportApprovalGuid=@ReportApprovalGuid;
	
 
	END TRY
	BEGIN CATCH        
		DECLARE	@_ErrMessage NVARCHAR(2048)      
				, @_ErrNumber INT           
				, @_ErrProcName NVARCHAR(126)           
				, @_ErrLineNumber INT;            
		SET @_ErrMessage = ERROR_MESSAGE();        
		SET @_ErrNumber = ERROR_NUMBER();        
		SET @_ErrProcName= ERROR_PROCEDURE();        
		SET @_ErrLineNumber = ERROR_LINE();            
		SET @_ErrMessage = 'Error: ' + @_ErrMessage + CHAR(13)+CHAR(10)                 
						+ 'Number: ' + CAST(@_ErrNumber AS VARCHAR(20)) + CHAR(13)+CHAR(10)                 
						+ 'Procedure Name: gsp_ReportApprovalsUpdateByPK' + CHAR(13)+CHAR(10)                  
						+ 'Line Number: ' + ISNULL(CAST(@_ErrLineNumber AS VARCHAR(20)),'') + CHAR(13)+CHAR(10);         
		RAISERROR(@_ErrMessage,18,1);      
	END CATCH    
END     
	
