CREATE TABLE [staging].[tblCompanies](
	[SKey] [int] IDENTITY(1,1) NOT NULL,
	[CompanyGuid] [uniqueidentifier] NULL,
	[CompanyKey] [nvarchar](50) NULL,
	[ID] [nvarchar](100) NULL,
	[Code] [nvarchar](10) NULL,
	[Name] [nvarchar](100) NULL,
	[ShortName] [nvarchar](4) NULL,
	[Address1] [nvarchar](60) NULL,
	[Address2] [nvarchar](60) NULL,
	[City] [nvarchar](60) NULL,
	[State] [nvarchar](20) NULL,
	[Zip] [nvarchar](11) NULL,
	[Country] [nvarchar](30) NULL,
	[Phone] [nvarchar](20) NULL,
	[FAX] [nvarchar](20) NULL,
	[EmergencyContact] [nvarchar](30) NULL,
	[EmergencyPhone] [nvarchar](20) NULL,
	[FlightPrefix] [nvarchar](5) NULL,
	[EffectiveDate] [datetimeoffset](7) NULL,
	[ExpirationDate] [datetimeoffset](7) NULL,
	[OnHold] [bit] NULL,
	[PickupFLights] [bit] NULL,
	[StockTrack] [bit] NULL,
	[SufferLossGain] [bit] NULL,
	[LowStockWarning] [float] NULL,
	[LockedOut] [bit] NULL,
	[LockedOutReason] [nvarchar](80) NULL,
	[LockedOutDate] [datetimeoffset](7) NULL,
	[ReceivableAccount] [nvarchar](20) NULL,
	[RefinerCode] [nvarchar](20) NULL,
	[LastActivityDate] [datetimeoffset](7) NULL,
	[CreditOK] [bit] NULL,
	[AdditiveAccounting] [bit] NULL,
	[PurchaseOrderRequired] [bit] NULL,
	[EPANumber] [nvarchar](20) NULL,
	[FederalID] [nvarchar](20) NULL,
	[FederalID2] [nvarchar](20) NULL,
	[FederalID3] [nvarchar](20) NULL,
	[FederalID4] [nvarchar](20) NULL,
	[FederalID5] [nvarchar](20) NULL,
	[StateID] [nvarchar](20) NULL,
	[TaxNumber] [nvarchar](20) NULL,
	[FlushPermitted] [bit] NULL,
	[PumpOffPermitted] [bit] NULL,
	[DeliveryToTerminalPermitted] [bit] NULL,
	[LicenseNumber] [nvarchar](20) NULL,
	[LicenseExpiration] [datetimeoffset](7) NULL,
	[InsuranceCompany] [nvarchar](20) NULL,
	[InsurancePolicy] [nvarchar](20) NULL,
	[LiabilityAmount] [money] NULL,
	[HazardousMaterialExclusion] [bit] NULL,
	[InsuranceExpiration] [datetimeoffset](7) NULL,
	[AllowDriverEntry] [bit] NULL,
	[PINRequired] [bit] NULL,
	[MaximumVehicleWeight] [float] NULL,
	[WeightUnits] [smallint] NULL,
	[AccountNumber] [nvarchar](30) NULL,
	[SCACCode] [nvarchar](4) NULL,
	[DisableOwnerAllocationsCheck] [bit] NULL,
	[DisableShipperAllocationsCheck] [bit] NULL,
	[DisableBillToAllocationsCheck] [bit] NULL,
	[DisableShipToAllocationsCheck] [bit] NULL,
	[LoadRackDisplayText] [nvarchar](30) NULL,
	[UserData1] [nvarchar](60) NULL,
	[UserData2] [nvarchar](60) NULL,
	[UserData3] [nvarchar](60) NULL,
	[UserData4] [nvarchar](60) NULL,
	[UserData5] [nvarchar](60) NULL,
	[UserData6] [nvarchar](60) NULL,
	[UserData7] [nvarchar](60) NULL,
	[UserData8] [nvarchar](60) NULL,
	[SiteGuid] [uniqueidentifier] NULL,
	[SiteKey] [nvarchar](50) NULL,
	[SiteSKey] [int] NULL,
	[IATAGuid] [uniqueidentifier] NULL,
	[IATAKey] [nvarchar](50) NULL,
	[IATASKey] [int] NULL,
	[ShipperTypeApplicationStringGuid] [uniqueidentifier] NULL,
	[ShipperTypeKey] [nvarchar](50) NULL,
	[ShipperTypeApplicationStringSKey] [int] NULL,
	[CustomerBillToTypeApplicationStringGuid] [uniqueidentifier] NULL,
	[CustomerBillToTypeKey] [nvarchar](50) NULL,
	[CustomerBillToTypeApplicationStringSKey] [int] NULL,
	[CustomerShipToTypeApplicationStringGuid] [uniqueidentifier] NULL,
	[CustomerShipToTypeKey] [nvarchar](50) NULL,
	[CustomerShipToTypeApplicationStringSKey] [int] NULL,
	[Contact1Name] [nvarchar](30) NULL,
	[Contact1Address1] [nvarchar](30) NULL,
	[Contact1Address2] [nvarchar](30) NULL,
	[Contact1City] [nvarchar](60) NULL,
	[Contact1State] [nvarchar](20) NULL,
	[Contact1Zip] [nvarchar](11) NULL,
	[Contact1Country] [nvarchar](30) NULL,
	[Contact1PhoneOffice] [nvarchar](20) NULL,
	[Contact1Fax] [nvarchar](20) NULL,
	[Contact1EmailAddress] [nvarchar](30) NULL,
	[Contact2Name] [nvarchar](30) NULL,
	[Contact2Address1] [nvarchar](30) NULL,
	[Contact2Address2] [nvarchar](30) NULL,
	[Contact2City] [nvarchar](60) NULL,
	[Contact2State] [nvarchar](20) NULL,
	[Contact2Zip] [nvarchar](11) NULL,
	[Contact2Country] [nvarchar](30) NULL,
	[Contact2PhoneOffice] [nvarchar](20) NULL,
	[Contact2Fax] [nvarchar](20) NULL,
	[Contact2EmailAddress] [nvarchar](30) NULL,
	[Contact1PhoneMobile] [nvarchar](20) NULL,
	[Contact2PhoneMobile] [nvarchar](20) NULL,
	[CompanyIATACode] [nvarchar](50) NULL,
	[CompanyICAOCode] [nvarchar](50) NULL,
	[MasterRecordGuid] [uniqueidentifier] NULL,
	[MasterRecordKey] [nvarchar](50) NULL,
	[Note] [nvarchar](2000) NULL,
	[HiddenDate] [datetimeoffset](7) NULL,
	[ScullyRequired] [bit] NULL,
	[ConsortiumTypeIndex] [int] NULL,
	[_ClusterIdx] [bigint] NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[CreatedDate] [datetimeoffset](7) NULL,
	[UpdatedBy] [nvarchar](100) NULL,
	[UpdatedDate] [datetimeoffset](7) NULL,
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[CombinedUpdatedDate] [datetimeoffset](7) NULL,
	[IsRecordDeleted] [bit] NOT NULL,
	[IsRecordAddedByETL] [bit] NOT NULL,
	[IgnoreRecord] [bit] NOT NULL,
	[StartDate] [datetimeoffset](7) NULL,
	[EndDate] [datetimeoffset](7) NULL,
	[CDCSKey] [int] NULL,
	[SourceRowVersion] [bigint] NULL,
	[CDCRowVersion] [bigint] NULL,
	[_RowVersion] [timestamp] NOT NULL,
 CONSTRAINT [PK_tblCompanies] PRIMARY KEY CLUSTERED 
(
	[SKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [staging].[tblCompanies] ADD  DEFAULT ((0)) FOR [IsRecordDeleted]
GO
ALTER TABLE [staging].[tblCompanies] ADD  DEFAULT ((0)) FOR [IsRecordAddedByETL]
GO
ALTER TABLE [staging].[tblCompanies] ADD  DEFAULT ((0)) FOR [IgnoreRecord]