/*
	DROP TABLE [staging].[tblConjoinTransactions]
*/
CREATE TABLE [staging].[tblConjoinTransactions](
	[SKey] [int] IDENTITY(1,1) NOT NULL,
	[TransactionGuid] [uniqueidentifier] NULL,
	[TransactionKey] [nvarchar](50) NULL,
	
	[AssociatedCLIN] [nvarchar](10) NULL,
	[AssociatedDocNumber] [nvarchar](30) NULL,
	[AssociatedTransportOrderNumber] [nvarchar](30) NULL,
	[AutoComplete] [bit] NULL,
	[BillToCode] [nvarchar](10) NULL,
	[BillToCompanyGuid] [uniqueidentifier] NULL,
	[BillToCompanyKey] [nvarchar](50) NULL,
	[BillToCompanySKey] [int] NULL,
	[BillToID] [nvarchar](100) NULL,
	[BillToID_Orig] [nvarchar](100) NULL,	
	[CardExpiration] [datetimeoffset](7) NULL,
	[CardExpirationDateSKey] [int] NULL,
	[CardName] [nvarchar](30) NULL,
	[CardNumber] [nvarchar](30) NULL,
	[CardType] [nvarchar](30) NULL,
	[CarrierCode] [nvarchar](10) NULL,
	[CarrierCompanyGuid] [uniqueidentifier] NULL,
	[CarrierCompanyKey] [nvarchar](50) NULL,
	[CarrierCompanySKey] [int] NULL,
	[CarrierID] [nvarchar](100) NULL,
	[CarrierID_Orig] [nvarchar](100) NULL,	
	[CashAmount] [float] NULL,
	[ConjoinOwnerGuid] [uniqueidentifier] NULL,
	[ConjoinOwnerKey] [nvarchar](50) NULL,
	[ConjoinOwnerId] [nvarchar](100) NULL,
	[ConjoinOwnerSKey] [int] NULL,
	[ConjoinTransID] [nvarchar](64) NULL,
	[ContactFirstName] [nvarchar](50) NULL,
	[ContactInfo] [nvarchar](50) NULL,
	[ContactSurname] [nvarchar](50) NULL,
	[Country] [nvarchar](50) NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[CreatedDate] [datetimeoffset](7) NULL,
	[CreatedDateSKey] [int] NULL,
	[CreatedTimeSKey] [int] NULL,
	[CreditAmount] [float] NULL,
	[Date01] [datetimeoffset](7) NULL,
	[Date01DateSKey] [int] NULL,
	[Date01TimeSKey] [int] NULL,
	[Date02] [datetimeoffset](7) NULL,
	[Date03] [datetimeoffset](7) NULL,
	[Date04] [datetimeoffset](7) NULL,
	[DeleteFlag] [bit] NULL,
	[DestinationEquipment1Guid] [uniqueidentifier] NULL,
	[DestinationEquipment1Key] [nvarchar](50) NULL,
	[DestinationEquipment1SKey] [int] NULL,	
	[DestinationEquipment2Guid] [uniqueidentifier] NULL,
	[DestinationEquipment2Key] [nvarchar](50) NULL,
	[DestinationEquipment2SKey] [int] NULL,
	[DestinationEquipment3Guid] [uniqueidentifier] NULL,
	[DestinationEquipment3Key] [nvarchar](50) NULL,
	[DestinationEquipment3SKey] [int] NULL,
	[DestinationCompanyEquipmentID1] [nvarchar](30) NULL,
	[DestinationCompanyEquipmentID1_Orig] [nvarchar](30) NULL,
	[DestinationCompanyEquipmentID2] [nvarchar](30) NULL,
	[DestinationCompanyEquipmentID2_Orig] [nvarchar](30) NULL,
	[DestinationCompanyEquipmentID3] [nvarchar](30) NULL,
	[DestinationCompanyEquipmentID3_Orig] [nvarchar](30) NULL,		
	[DestinationEquipmentModel1] [nvarchar](20) NULL,
	[DestinationEquipmentModel2] [nvarchar](20) NULL,
	[DestinationEquipmentModel3] [nvarchar](20) NULL,
	[DestinationEquipmentType1] [nvarchar](50) NULL,
	[DestinationEquipmentType2] [nvarchar](50) NULL,
	[DestinationEquipmentType3] [nvarchar](50) NULL,
	[DestinationRegistrationID1] [nvarchar](30) NULL,
	[DestinationRegistrationID2] [nvarchar](30) NULL,
	[DestinationRegistrationID3] [nvarchar](30) NULL,
	[DestinationSerialNumber1] [nvarchar](30) NULL,
	[DestinationSerialNumber2] [nvarchar](30) NULL,
	[DestinationSerialNumber3] [nvarchar](30) NULL,
	[DispatchedDateTime] [datetimeoffset](7) NULL,
	[DispatchedDateSKey] [int] NULL,	
	[DispatchedTimeSKey] [int] NULL,
	[DocumentNumber] [nvarchar](30) NULL,
	[DriverIdentificationNumber] [nvarchar](50) NULL,
	[EffectiveDate] [datetimeoffset](7) NULL,
	[EffectiveDateSKey] [int] NULL,
	[ErrorFlag] [bit] NULL,
	[EstimatedFuelingDuration] [int] NULL,
	[ETA] [datetimeoffset](7) NULL,
	[ETD] [datetimeoffset](7) NULL,
	[ExpirationDate] [datetimeoffset](7) NULL,
	[ExpirationDateSKey] [int] NULL,
	[FinalStationIATAGuid] [uniqueidentifier] NULL,
	[FinalStationIATAKey] [nvarchar](50) NULL,
	[FinalStationIATAID] [nvarchar](50) NULL,
	[Flag01] [bit] NULL,
	[Flag02] [bit] NULL,
	[Flag03] [bit] NULL,
	[Flag04] [bit] NULL,
	[Flag05] [bit] NULL,
	[Flag06] [bit] NULL,
	[FST] [datetimeoffset](7) NULL,
	[FuelAdditiveFlag] [bit] NULL,
	[FuelCardGuid] [uniqueidentifier] NULL,
	[FuelCardKey] [nvarchar](50) NULL,
	[FuelCardID] [nvarchar](50) NULL,
	[FuelCardID_Orig] [nvarchar](50) NULL,
	[GateGuid] [uniqueidentifier] NULL,
	[GateKey] [nvarchar](50) NULL,
	[GateID] [nvarchar](10) NULL,
	[InternationalRouteIndicator] [bit] NULL,
	[InventoryDate] [datetimeoffset](7) NULL,
	[InventoryDateSKey] [int] NULL,
	[IssuePoint] [nvarchar](max) NULL,
	[IssuePointNumber] [nvarchar](max) NULL,
	[LegacyNumber] [nvarchar](50) NULL,
	[LinkedDocumentNumber] [nvarchar](64) NULL,
	[LoadID] [nvarchar](50) NULL,		
	[ManagerCode] [nvarchar](10) NULL,
	[ManagerCompanyGuid] [uniqueidentifier] NULL,
	[ManagerCompanyKey] [nvarchar](50) NULL,
	[ManagerCompanySKey] [int] NULL,
	[ManagerID] [nvarchar](100) NULL,
	[ManagerID_Orig] [nvarchar](100) NULL,	
	[NextStationIATAGuid] [uniqueidentifier] NULL,
	[NextStationIATAKey] [nvarchar](50) NULL,
	[NextStationIATAID] [nvarchar](50) NULL,
	[Number01] [float] NULL,
	[Number02] [float] NULL,
	[Number03] [float] NULL,
	[Number04] [float] NULL,
	[Number05] [float] NULL,
	[Number06] [float] NULL,
	[OperatorID] [nvarchar](50) NULL,
	[OperatorID_Orig] [nvarchar](50) NULL,
	[OperatorName] [nvarchar](150) NULL,
	[OperatorPersonnelGuid] [uniqueidentifier] NULL,
	[OperatorPersonnelKey] [nvarchar](50) NULL,
	[OperatorPersonnelSKey] [int] NULL,	
	[OriginApplicationIndex] [int] NULL,
	[OriginApplicationName] [nvarchar](100) NULL,
	[OriginStationIATAGuid] [uniqueidentifier] NULL,
	[OriginStationIATAKey] [nvarchar](50) NULL,
	[OriginStationIATAID] [nvarchar](50) NULL,
	[OwnerCode] [nvarchar](10) NULL,
	[OwnerCompanyGuid] [uniqueidentifier] NULL,
	[OwnerCompanyKey] [nvarchar](50) NULL,
	[OwnerCompanySKey] [int] NULL,
	[OwnerID] [nvarchar](100) NULL,
	[OwnerID_Orig] [nvarchar](100) NULL,	
	[PONumber] [nvarchar](14) NULL,
	[PreviousRoutingID] [nvarchar](30) NULL,
	[PreviousStationIATAGuid] [uniqueidentifier] NULL,
	[PreviousStationIATAKey] [nvarchar](50) NULL,
	[PreviousStationIATAID] [nvarchar](50) NULL,
	[RadioNumber] [nvarchar](max) NULL,
	[ReasonCode] [nvarchar](50) NULL,
	[ReasonCode_Orig] [nvarchar](50) NULL,
	[ReasonCodeGuid] [uniqueidentifier] NULL,
	[ReasonCodeKey] [nvarchar](50) NULL,
	[ReasonCodeSKey] [int] NULL,	
	[ReferencedTransactionGuid] [uniqueidentifier] NULL,
	[ReferencedTransactionKey] [nvarchar](50) NULL,
	[RequestedDateSKey] [int] NULL,
	[RequestedDateTime] [datetimeoffset](7) NULL,
	[RequestedDeliveryDate] [datetimeoffset](7) NULL,
	[RequestedDeliveryDateSKey] [int] NULL,
	[ReversalType] [nvarchar](2) NULL,
	[ReversedTransID] [nvarchar](64) NULL,
	[RouteOriginationDate] [datetimeoffset](7) NULL,
	[RouteOriginationDateSKey] [int] NULL,
	[RoutingID] [nvarchar](30) NULL,
	[SCACCode] [nvarchar](4) NULL,
	[ScheduledDate] [datetimeoffset](7) NULL,
	[ScheduledDateSKey] [int] NULL,
	[SFT] [datetimeoffset](7) NULL,
	[ShipmentNumber] [nvarchar](30) NULL,
	[ShipperCode] [nvarchar](10) NULL,
	[ShipperCompanyGuid] [uniqueidentifier] NULL,
	[ShipperCompanyKey] [nvarchar](50) NULL,
	[ShipperCompanySKey] [int] NULL,
	[ShipperID] [nvarchar](100) NULL,
	[ShipperID_Orig] [nvarchar](100) NULL,	
	[ShippingMethod] [nvarchar](150) NULL,
	[ShippingDocumentNumber] [nvarchar](30) NULL,
	[ShipToCode] [nvarchar](10) NULL,
	[ShipToCompanyGuid] [uniqueidentifier] NULL,
	[ShipToCompanyKey] [nvarchar](50) NULL,
	[ShipToCompanySKey] [int] NULL,
	[ShipToID] [nvarchar](100) NULL,
	[ShipToID_Orig] [nvarchar](100) NULL,	
	[SiteId] [nvarchar](30) NULL,
	[SiteId_Orig] [nvarchar](30) NULL,
	[SiteAddress1] [nvarchar](30) NULL,
	[SiteAddress2] [nvarchar](30) NULL,
	[SiteCity] [nvarchar](50) NULL,
	[SiteContact1Name] [nvarchar](30) NULL,
	[SiteCountry] [nvarchar](50) NULL,
	[SiteDensityDecimalPlaces] [tinyint] NULL,
	[SiteDensityUnitIndex] [int] NULL,
	[SiteEnabled] [bit] NULL,
	[SiteGuid] [uniqueidentifier] NULL,	
	[SiteKey] [nvarchar](50) NULL,
	[SiteGroupFlag] [bit] NULL,
	[SitePhone] [nvarchar](20) NULL,
	[SiteSKey] [int] NULL,
	[SiteState] [nvarchar](20) NULL,
	[SiteTemperatureDecimalPlaces] [tinyint] NULL,
	[SiteTemperatureUnitIndex] [int] NULL,
	[SiteTimeZone] [nvarchar](50) NULL,
	[SiteVolumeDecimalPlaces] [tinyint] NULL,
	[SiteVolumeUnitIndex] [int] NULL,
	[SiteZip] [nvarchar](11) NULL,
	[SourceEquipment1Guid] [uniqueidentifier] NULL,
	[SourceEquipment1Key] [nvarchar](50) NULL,
	[SourceEquipment1SKey] [int] NULL,	
	[SourceEquipment2Guid] [uniqueidentifier] NULL,
	[SourceEquipment2Key] [nvarchar](50) NULL,
	[SourceEquipment2SKey] [int] NULL,
	[SourceEquipment3Guid] [uniqueidentifier] NULL,
	[SourceEquipment3Key] [nvarchar](50) NULL,
	[SourceEquipment3SKey] [int] NULL,
	[SourceCompanyEquipmentID1] [nvarchar](30) NULL,
	[SourceCompanyEquipmentID1_Orig] [nvarchar](30) NULL,
	[SourceCompanyEquipmentID2] [nvarchar](30) NULL,
	[SourceCompanyEquipmentID2_Orig] [nvarchar](30) NULL,
	[SourceCompanyEquipmentID3] [nvarchar](30) NULL,
	[SourceCompanyEquipmentID3_Orig] [nvarchar](30) NULL,
	[SourceEquipmentModel1] [nvarchar](20) NULL,
	[SourceEquipmentModel2] [nvarchar](20) NULL,
	[SourceEquipmentModel3] [nvarchar](20) NULL,
	[SourceEquipmentType1] [nvarchar](50) NULL,
	[SourceEquipmentType2] [nvarchar](50) NULL,
	[SourceEquipmentType3] [nvarchar](50) NULL,
	[SourceRegistrationID1] [nvarchar](30) NULL,
	[SourceRegistrationID2] [nvarchar](30) NULL,
	[SourceRegistrationID3] [nvarchar](30) NULL,
	[SourceSerialNumber1] [nvarchar](30) NULL,
	[SourceSerialNumber2] [nvarchar](30) NULL,
	[SourceSerialNumber3] [nvarchar](30) NULL,
	[STA] [datetimeoffset](7) NULL,
	[STD] [datetimeoffset](7) NULL,
	[SubmittedToAccounting] [bit] NULL,
	[SubType] [nvarchar](20) NULL,
	[SupplierCode] [nvarchar](10) NULL,
	[SupplierCompanyGuid] [uniqueidentifier] NULL,
	[SupplierCompanyKey] [nvarchar](50) NULL,
	[SupplierCompanySKey] [int] NULL,
	[SupplierID] [nvarchar](100) NULL,
	[SupplierID_Orig] [nvarchar](100) NULL,	
	[TicketMode] [nvarchar](15) NULL,
	[TicketSource] [nvarchar](20) NULL,
	[TimeEnd] [datetimeoffset](7) NULL,
	[TimeEndDateSKey] [int] NULL,
	[TimeEndTimeSKey] [int] NULL,
	[TimeIn] [datetimeoffset](7) NULL,
	[TimeInDateSKey] [int] NULL,
	[TimeInTimeSKey] [int] NULL,
	[TimeOut] [datetimeoffset](7) NULL,
	[TimeOutDateSKey] [int] NULL,
	[TimeOutTimeSKey] [int] NULL,	
	[TransactionAliasGuid] [uniqueidentifier] NULL,
	[TransactionAliasKey] [nvarchar](50) NULL,
	[TransactionAliasName] [nvarchar](32) NULL,
	[TransactionAliasName_Orig] [nvarchar](32) NULL,
	[TransactionAliasSKey] [int] NULL,	
	[TransactionStatusIndex] [int] NULL,
	[TransactionStatusName] [nvarchar](100) NULL,
	[TransDateSKey] [int] NULL,
	[TransDateTime] [datetimeoffset](7) NULL,
	[TransID] [nvarchar](64) NULL,
	[TransReferenceID] [nvarchar](64) NULL,
	[TransTimeSKey] [int] NULL,	
	[TransactionTypeIndex] [smallint] NULL,
	[TransactionTypeKey] [nvarchar](50) NULL,
	[TransactionTypeSKey] [int] NULL,
	[TransVersion] [bigint] NULL,
	[UpdatedBy] [nvarchar](100) NULL,
	[UpdatedDate] [datetimeoffset](7) NULL,

	--System Fields
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[CombinedUpdatedDate] [datetimeoffset](7) NULL,
	[CombinedUpdatedDateSKey] [int] NULL,
	[IsRecordDeleted] [bit] NOT NULL,
	[IsRecordAddedByETL] [bit] NOT NULL,
	[SourceFactSKey] [int] NULL,
	[IgnoreRecord] [bit] NOT NULL,
	[IsProcessed] [bit] NOT NULL,
	[CDCSKey] [int] NULL,
	[SourceRowVersion] [bigint] NULL,
	[CDCRowVersion] [bigint] NULL,
	[_RowVersion] [timestamp] NOT NULL,

CONSTRAINT [PK_tblConjoinTransactions] PRIMARY KEY CLUSTERED 
(
	[SKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_tblConjoinTransactions_TransactionKey] ON [staging].[tblConjoinTransactions]
(
	[TransactionKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_tblConjoinTransactions_IgnoreRecord] ON [staging].[tblConjoinTransactions]
(
	[IgnoreRecord] ASC
)
INCLUDE ( [IsProcessed] )
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_tblConjoinTransactions_IsProcessed] ON [staging].[tblConjoinTransactions]
(
	[IsProcessed] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_tblConjoinTransactions_TransId] ON [staging].[tblConjoinTransactions]
(
	[TransId] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_tblConjoinTransactions_ConjoinTransId] ON [staging].[tblConjoinTransactions]
(
	[ConjoinTransId] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]