CREATE TABLE [staging].[tblEquipment](
	[SKey] [int] IDENTITY(1,1) NOT NULL,
	[EquipmentGuid] [uniqueidentifier] NULL,
	[EquipmentKey] [nvarchar](50) NULL,
	[ID] [nvarchar](30) NULL,
	[Description] [nvarchar](50) NULL,
	[Make] [nvarchar](20) NULL,
	[Model] [nvarchar](50) NULL,
	[Year] [int] NULL,
	[IssPtNum] [nvarchar](20) NULL,
	[Fixed] [bit] NULL,
	[StorageType] [nvarchar](2) NULL,
	[InUse] [bit] NULL,
	[FixedVolume] [bit] NULL,
	[IntoPlane] [bit] NULL,
	[Mobile] [bit] NULL,
	[AttachedTo] [nvarchar](6) NULL,
	[MediaType] [char](1) NULL,
	[Meters] [int] NULL,
	[DefuelMeterForwards] [bit] NULL,
	[PulseRatio] [float] NULL,
	[Round] [bit] NULL,
	[Xref] [nvarchar](10) NULL,
	[LowStockWarning] [float] NULL,
	[StockTrack] [bit] NULL,
	[Totalisor1] [nvarchar](10) NULL,
	[Totalisor2] [nvarchar](10) NULL,
	[FuelingState] [nvarchar](10) NULL,
	[Volume] [float] NULL,
	[MeterReading] [float] NULL,
	[Consecutive_OOS_Variance] [int] NULL,
	[Notes] [nvarchar](1000) NULL,
	[Capacity] [float] NULL,
	[SafeFill] [float] NULL,
	[VolumeUnitIndex] [int] NULL,
	[VolumeUnitName] [nvarchar](100) NULL,
	[TemperatureUnitIndex] [int] NULL,
	[TemperatureUnitName] [nvarchar](100) NULL,
	[DensityUnitIndex] [int] NULL,
	[DensityUnitName] [nvarchar](100) NULL,
	[MassUnitIndex] [int] NULL,
	[MassUnitName] [nvarchar](100) NULL,
	[VolumeDecimalPlaces] [tinyint] NULL,
	[TemperatureDecimalPlaces] [tinyint] NULL,
	[DensityDecimalPlaces] [tinyint] NULL,
	[MassDecimalPlaces] [tinyint] NULL,
	[EquipmentSequence] [nvarchar](50) NULL,
	[LockedOut] [bit] NULL,
	[LockedOutReason] [nvarchar](80) NULL,
	[LockedOutDate] [datetimeoffset](7) NULL,
	[SerialNumber] [nvarchar](30) NULL,
	[CompanyEquipmentID] [nvarchar](30) NULL,
	[TruckCardNumber] [nvarchar](32) NULL,
	[RatedGPM] [float] NULL,
	[ActualGPM] [float] NULL,
	[FuelAdditiveFlag] [bit] NULL,
	[ManufactureDate] [datetimeoffset](7) NULL,
	[InstallationDate] [datetimeoffset](7) NULL,
	[InspectionDate] [datetimeoffset](7) NULL,
	[CalibrationDate] [datetimeoffset](7) NULL,
	[QCDate] [datetimeoffset](7) NULL,
	[SecondaryStorageFlag] [bit] NULL,
	[ManagedEquipmentFlag] [bit] NULL,
	[FuelingType] [smallint] NULL,
	[UserData1] [nvarchar](60) NULL,
	[UserData2] [nvarchar](60) NULL,
	[UserData3] [nvarchar](60) NULL,
	[UserData4] [nvarchar](60) NULL,
	[UserData5] [nvarchar](60) NULL,
	[UserData6] [nvarchar](60) NULL,
	[UserData7] [nvarchar](60) NULL,
	[UserData8] [nvarchar](60) NULL,
	[UserData9] [nvarchar](60) NULL,
	[UserData10] [nvarchar](60) NULL,
	[UserData11] [nvarchar](60) NULL,
	[UserData12] [nvarchar](60) NULL,
	[UserData13] [nvarchar](60) NULL,
	[UserData14] [nvarchar](60) NULL,
	[UserData15] [nvarchar](60) NULL,
	[UserData16] [nvarchar](60) NULL,
	[UserData17] [nvarchar](60) NULL,
	[UserData18] [nvarchar](60) NULL,
	[UserData19] [nvarchar](60) NULL,
	[UserData20] [nvarchar](60) NULL,
	[UserData21] [nvarchar](60) NULL,
	[UserData22] [nvarchar](60) NULL,
	[UserData23] [nvarchar](60) NULL,
	[UserData24] [nvarchar](60) NULL,	
	[SiteGuid] [uniqueidentifier] NULL,
	[SiteKey] [nvarchar](50) NULL,
	[SiteSKey] [int] NULL,
	[CompanyGuid] [uniqueidentifier] NULL,
	[CompanyKey] [nvarchar](50) NULL,
	[CompanySKey] [int] NULL,
	[ParentEquipmentGuid] [uniqueidentifier] NULL,
	[ParentEquipmentKey] [nvarchar](50) NULL,
	[ParentEquipmentSKey] [int] NULL,
	[EquipmentTypeGuid] [uniqueidentifier] NULL,
	[EquipmentTypeKey] [nvarchar](50) NULL,
	[EquipmentTypeSKey] [int] NULL,
	[FuelCardGuid] [uniqueidentifier] NULL,
	[FuelCardKey] [nvarchar](50) NULL,
	[FuelCardSKey] [int] NULL,
	[ProductGuid] [uniqueidentifier] NULL,
	[ProductKey] [nvarchar](50) NULL,
	[ProductSKey] [int] NULL,
	[AssignedToMeterGuid] [uniqueidentifier] NULL,
	[AssignedToMeterKey] [nvarchar](50) NULL,
	[AssignedToMeterSKey] [int] NULL,
	[AssetTrackingDeviceGuid] [uniqueidentifier] NULL,
	[AssetTrackingDeviceKey] [nvarchar](50) NULL,
	[AssetTrackingDeviceSKey] [int] NULL,
	[MasterRecordGuid] [uniqueidentifier] NULL,
	[MasterRecordKey] [nvarchar](50) NULL,
	[HiddenDate] [datetimeoffset](7) NULL,
	[ScullyRequired] [bit] NULL,

	[_ClusterIdx] [bigint] NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[CreatedDate] [datetimeoffset](7) NULL,
	[UpdatedBy] [nvarchar](100) NULL,
	[UpdatedDate] [datetimeoffset](7) NULL,
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[CombinedUpdatedDate] [datetimeoffset](7) NULL,
	[IsRecordDeleted] [bit] NOT NULL,
	[IsRecordAddedByETL] [bit] NOT NULL,
	[IgnoreRecord] [bit] NOT NULL,
	[StartDate] [datetimeoffset](7) NULL,
	[EndDate] [datetimeoffset](7) NULL,
	[CDCSKey] [int] NULL,
	[SourceRowVersion] [bigint] NULL,
	[CDCRowVersion] [bigint] NULL,
	[_RowVersion] [timestamp] NOT NULL,
 CONSTRAINT [PK_tblEquipment] PRIMARY KEY CLUSTERED 
(
	[SKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [staging].[tblEquipment] ADD  DEFAULT ((0)) FOR [IsRecordDeleted]
GO
ALTER TABLE [staging].[tblEquipment] ADD  DEFAULT ((0)) FOR [IsRecordAddedByETL]
GO
ALTER TABLE [staging].[tblEquipment] ADD  DEFAULT ((0)) FOR [IgnoreRecord]