CREATE TABLE [staging].[tblProcessedInventoryYears](
	[SKey] [int] IDENTITY(1,1) NOT NULL,
	[InventoryYear] [int] NOT NULL,
 CONSTRAINT [PK_ProcessedInventoryYears] PRIMARY KEY CLUSTERED 
(
	[SKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]