CREATE TABLE [staging].[tblProducts](
	[SKey] [int] IDENTITY(1,1) NOT NULL,
	[ProductGuid] [uniqueidentifier] NULL,
	[ProductKey] [nvarchar](50) NULL,
	[ProductID] [nvarchar](30) NULL,
	[Description] [nvarchar](50) NULL,
	[GenericType] [nvarchar](10) NULL,
	[StockResetDate] [datetimeoffset](7) NULL,
	[StockTrack] [bit] NULL,
	[DensityHighLimit] [float] NULL,
	[DensityLowLimit] [float] NULL,
	[DensityDeadband] [float] NULL,
	[TemperatureHiHiLimit] [float] NULL,
	[TemperatureHighLimit] [float] NULL,
	[TemperatureLowLimit] [float] NULL,
	[TemperatureLoLoLimit] [float] NULL,
	[TemperatureDeadband] [float] NULL,
	[Bonded] [bit] NULL,
	[LowStockWarning] [float] NULL,
	[GroundFuel] [bit] NULL,
	[ProductCode] [nvarchar](15) NULL,
	[Price] [money] NULL,
	[AviationFuelFlag] [bit] NULL,
	[StandardDensity] [float] NULL,
	[ApplyVolumeCorrection] [bit] NULL,
	[ApplyStandardDensity] [bit] NULL,
	[ApplyDensityLimits] [bit] NULL,
	[ApplyTemperatureLimits] [bit] NULL,
	[VolumeUnitIndex] [int] NULL,
	[VolumeUnitName] [nvarchar](100) NULL,
	[TemperatureUnitIndex] [int] NULL,
	[TemperatureUnitName] [nvarchar](100) NULL,
	[DensityUnitIndex] [int] NULL,
	[DensityUnitName] [nvarchar](100) NULL,
	[VolumeDecimalPlaces] [tinyint] NULL,
	[TemperatureDecimalPlaces] [tinyint] NULL,
	[DensityDecimalPlaces] [tinyint] NULL,
	[Capitalize] [bit] NULL,
	[OctaneNumber] [float] NULL,
	[ReidVaporPressure] [float] NULL,
	[HazardousMaterial] [bit] NULL,
	[RegulatoryClass] [int] NULL,
	[LoadRackDisplayText] [nvarchar](10) NULL,
	[ComponentTolerance] [float] NULL,
	[VaporRecovery] [bit] NULL,
	[LockedOut] [bit] NULL,
	[LockedOutReason] [nvarchar](80) NULL,
	[LockedOutDate] [datetimeoffset](7) NULL,
	[VarianceTolerance] [float] NULL,
	[DielectricTolerance] [float] NULL,
	[LoadByWeight] [bit] NULL,
	[PIDXCode] [nvarchar](4) NULL,
	[ContaminationPromptLoadRackText] [nvarchar](10) NULL,
	[InhibitAccounting] [bit] NULL,
	[UserData1] [nvarchar](60) NULL,
	[UserData2] [nvarchar](60) NULL,
	[UserData3] [nvarchar](60) NULL,
	[UserData4] [nvarchar](60) NULL,
	[UserData5] [nvarchar](60) NULL,
	[UserData6] [nvarchar](60) NULL,
	[UserData7] [nvarchar](60) NULL,
	[UserData8] [nvarchar](60) NULL,
	[MassUnitIndex] [int] NULL,
	[MassUnitName] [nvarchar](100) NULL,
	[LevelUnitIndex] [int] NULL,
	[LevelUnitName] [nvarchar](100) NULL,
	[FlowUnitIndex] [int] NULL,
	[FlowUnitName] [nvarchar](100) NULL,
	[PressureUnitIndex] [int] NULL,
	[PressureUnitName] [nvarchar](100) NULL,
	[MassDecimalPlaces] [tinyint] NULL,
	[LevelDecimalPlaces] [tinyint] NULL,
	[FlowDecimalPlaces] [tinyint] NULL,
	[PressureDecimalPlaces] [tinyint] NULL,
	[VolumePackageSize] [float] NULL,
	[MassPackageSize] [float] NULL,	
	[SiteGuid] [uniqueidentifier] NULL,
	[SiteKey] [nvarchar](50) NULL,
	[SiteSKey] [int] NULL,
	[LookupProductTypeIndex] [int] NULL,
	[ProductTypeName] [nvarchar](100) NULL,
	[TrackingProductGuid] [uniqueidentifier] NULL,
	[TrackingProductKey] [nvarchar](50) NULL,
	[TrackingProductSKey] [int] NULL,
	[TaxCode] [nvarchar](10) NULL,
	[TrackingProductID] [nvarchar](30) NULL,
	[VcfModuleSettings] [xml] NULL,
	[ProductColor] [nvarchar](7) NULL,
	[PatternColor] [nvarchar](7) NULL,
	[PatternNumber] [int] NULL,
	[MasterRecordGuid] [uniqueidentifier] NULL,
	[MasterRecordKey] [nvarchar](50) NULL,
	[HiddenDate] [datetimeoffset](7) NULL,
	[AutomaticCloseout] [bit] NULL,
	[PIDXFamilyCode] [nvarchar](4) NULL,
	[_ClusterIdx] [bigint] NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[CreatedDate] [datetimeoffset](7) NULL,
	[UpdatedBy] [nvarchar](100) NULL,
	[UpdatedDate] [datetimeoffset](7) NULL,
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[CombinedUpdatedDate] [datetimeoffset](7) NULL,
	[IsRecordDeleted] [bit] NOT NULL,
	[IsRecordAddedByETL] [bit] NOT NULL,
	[IgnoreRecord] [bit] NOT NULL,
	[StartDate] [datetimeoffset](7) NULL,
	[EndDate] [datetimeoffset](7) NULL,
	[CDCSKey] [int] NULL,
	[SourceRowVersion] [bigint] NULL,
	[CDCRowVersion] [bigint] NULL,
	[_RowVersion] [timestamp] NOT NULL,
 CONSTRAINT [PK_tblProducts] PRIMARY KEY CLUSTERED 
(
	[SKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [staging].[tblProducts] ADD  DEFAULT ((0)) FOR [IsRecordDeleted]
GO
ALTER TABLE [staging].[tblProducts] ADD  DEFAULT ((0)) FOR [IsRecordAddedByETL]
GO
ALTER TABLE [staging].[tblProducts] ADD  DEFAULT ((0)) FOR [IgnoreRecord]