CREATE TABLE [staging].[tblPersonnel](
	[SKey] [int] IDENTITY(1,1) NOT NULL,
	[PersonnelGuid] [uniqueidentifier] NULL,
	[PersonnelKey] [nvarchar](50) NULL,
	[PersonID] [nvarchar](50) NULL,
	[CardNumber] [nvarchar](30) NULL,
	[FirstName] [nvarchar](20) NULL,
	[MiddleName] [nvarchar](20) NULL,
	[LastName] [nvarchar](30) NULL,
	[Title] [nvarchar](50) NULL,
	[Department] [nvarchar](20) NULL,
	[Address1] [nvarchar](50) NULL,
	[Address2] [nvarchar](50) NULL,
	[City] [nvarchar](60) NULL,
	[State] [nvarchar](20) NULL,
	[Zip] [nvarchar](10) NULL,
	[Country] [nvarchar](20) NULL,
	[Phone1] [nvarchar](50) NULL,
	[Phone2] [nvarchar](50) NULL,
	[AssignmentDate] [datetimeoffset](7) NULL,
	[SupervisionDate] [datetimeoffset](7) NULL,
	[SSAN] [nvarchar](11) NULL,
	[BirthDate] [datetimeoffset](7) NULL,
	[PayRate] [money] NULL,
	[LaborRate1] [float] NULL,
	[LaborRate2] [float] NULL,
	[LaborRate3] [float] NULL,
	[LaborRate4] [float] NULL,
	[Status] [smallint] NULL,
	[Email] [nvarchar](50) NULL,
	[ResponsibleOfficer] [bit] NULL,
	[Shift] [smallint] NULL,
	[PINNumber] [varbinary](256) NULL,
	[PINRequired] [bit] NULL,
	[LockedOut] [bit] NULL,
	[LockedOutReason] [nvarchar](80) NULL,
	[LockedOutDate] [datetimeoffset](7) NULL,
	[LastActivityDate] [datetimeoffset](7) NULL,
	[CardedIn] [bit] NULL,
	[ShortCardNumber] [nvarchar](6) NULL,
	[OnFileSignature] [varbinary](max) NULL,
	[UserData1] [nvarchar](60) NULL,
	[UserData2] [nvarchar](60) NULL,
	[UserData3] [nvarchar](60) NULL,
	[UserData4] [nvarchar](60) NULL,
	[UserData5] [nvarchar](60) NULL,
	[UserData6] [nvarchar](60) NULL,
	[UserData7] [nvarchar](60) NULL,
	[UserData8] [nvarchar](60) NULL,
	[UserData9] [nvarchar](60) NULL,
	[UserData10] [nvarchar](60) NULL,
	[UserData11] [nvarchar](60) NULL,
	[UserData12] [nvarchar](60) NULL,
	[UserData13] [nvarchar](60) NULL,
	[UserData14] [nvarchar](60) NULL,
	[UserData15] [nvarchar](60) NULL,
	[UserData16] [nvarchar](60) NULL,
	[UserData17] [nvarchar](60) NULL,
	[UserData18] [nvarchar](60) NULL,
	[UserData19] [nvarchar](60) NULL,
	[UserData20] [nvarchar](60) NULL,
	[UserData21] [nvarchar](60) NULL,
	[UserData22] [nvarchar](60) NULL,
	[UserData23] [nvarchar](60) NULL,
	[UserData24] [nvarchar](60) NULL,
	[InhibitInactivityLockout] [bit] NULL,
	[SiteGuid] [uniqueidentifier] NULL,
	[SiteKey] [nvarchar](50) NULL,
	[SiteSKey] [int] NULL,
	[CompanyGuid] [uniqueidentifier] NULL,
	[CompanyKey] [nvarchar](50) NULL,
	[CompanySKey] [int] NULL,
	[SupervisorPersonnelGuid] [uniqueidentifier] NULL,
	[SupervisorPersonnelKey] [nvarchar](50) NULL,
	[SupervisorPersonnelSKey] [int] NULL,
	[UserGuid] [uniqueidentifier] NULL,
	[UserKey] [nvarchar](50) NULL,
	[UserSKey] [int] NULL,
	[AssignedEquipmentGuid] [uniqueidentifier] NULL,
	[AssignedEquipmentKey] [nvarchar](50) NULL,
	[AssignedEquipmentSKey] [int] NULL,
	[MasterRecordGuid] [uniqueidentifier] NULL,
	[MasterRecordKey] [nvarchar](50) NULL,
	[HiddenDate] [datetimeoffset](7) NULL,
	[_ClusterIdx] [bigint] NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[CreatedDate] [datetimeoffset](7) NULL,
	[UpdatedBy] [nvarchar](100) NULL,
	[UpdatedDate] [datetimeoffset](7) NULL,
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[CombinedUpdatedDate] [datetimeoffset](7) NULL,
	[IsRecordDeleted] [bit] NOT NULL,
	[IsRecordAddedByETL] [bit] NOT NULL,
	[IgnoreRecord] [bit] NOT NULL,
	[StartDate] [datetimeoffset](7) NULL,
	[EndDate] [datetimeoffset](7) NULL,
	[CDCSKey] [int] NULL,
	[SourceRowVersion] [bigint] NULL,
	[CDCRowVersion] [bigint] NULL,
	[_RowVersion] [timestamp] NOT NULL,
 CONSTRAINT [PK_tblPersonnel] PRIMARY KEY NONCLUSTERED 
(
	[SKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [staging].[tblPersonnel] ADD  DEFAULT ((0)) FOR [IsRecordDeleted]
GO
ALTER TABLE [staging].[tblPersonnel] ADD  DEFAULT ((0)) FOR [IsRecordAddedByETL]
GO
ALTER TABLE [staging].[tblPersonnel] ADD  DEFAULT ((0)) FOR [IgnoreRecord]