CREATE TABLE [staging].[tblStations]
(
	[SKey] [int] IDENTITY(1,1) NOT NULL,
	[ID] [nvarchar](50) NULL,
	[SwingArmPosition] [bit] NULL,
	[VaporRecovery] [bit] NULL,
	[Enabled] [bit] NULL,
	[BOLPrinter] [nvarchar](80) NULL,
	[PreloadPrinter] [nvarchar](80) NULL,
	[BOLAgeInMinutes] [int] NULL,
	[CardReader] [bit] NULL,
	[ThirtyFiveBitCardSupport] [bit] NULL,
	[NumberOfCopies] [int] NULL,
	[NumberOfPreloadCopies] [int] NULL,
	[InhibitLoadingByLoadID] [bit] NULL,
	[InhibitOperatingModePrompt] [bit] NULL,
	[SynchronizeReferenceDensity] [bit] NULL,
	[SignatureDevice] [nvarchar](20) NULL,
	[SetDefaultPresetToZero] [bit] NULL,
	[ArmsServiced] [nvarchar](100) NULL,
	[InhibitSettingRecipeNames] [bit] NULL,
	[SignatureDevicePort] [int] NULL,
	[SignatureDeviceBaudRate] [int] NULL,
	[MeterRecircCardNumber] [nvarchar](30) NULL,
	[TouchKeyReader] [bit] NULL,
	[OffLoadByOffLoadID] [bit] NULL,
	[UseManualMeterData] [bit] NULL,
	[PromptForBOLNumber] [bit] NULL,
	[QueryForTrailers] [bit] NULL,
	[PromptForGravityCaptured] [bit] NULL,
	[PromptForTemperatureCaptured] [bit] NULL,
	[LastTransactionNumber] [int] NULL,
	[LastTransactionNumberDateTime] [datetimeoffset](7) NULL,
	[StationGuid] [uniqueidentifier] NULL,
	[StationKey] [nvarchar](50) NULL,
	[SiteGuid] [uniqueidentifier] NULL,
	[SiteKey] [nvarchar](50) NULL,
	[SiteSKey] [int] NULL,
	[LookupStationTypeIndex] [int] NULL,
	[LookupStationInterfaceTypeIndex] [int] NULL,
	[StationInterfaceTypeCode] [nvarchar](100) NULL,
	[TankGuid] [uniqueidentifier] NULL,
	[TankKey] [nvarchar](50) NULL,
	[IssueByVolumeTransactionAliasGuid] [uniqueidentifier] NULL,
	[IssueByVolumeTransactionAliasKey] [nvarchar](50) NULL,
	[IssueByWeightTransactionAliasGuid] [uniqueidentifier] NULL,
	[IssueByWeightTransactionAliasKey] [nvarchar](50) NULL,
	[ReceiptByVolumeTransactionAliasGuid] [uniqueidentifier] NULL,
	[ReceiptByVolumneTransactionAliasKey] [nvarchar](50) NULL,
	[ReceiptByWeightTransactionAliasGuid] [uniqueidentifier] NULL,
	[ReceiptByWeightTransactionAliasKey] [nvarchar](50) NULL,
	[RecircTransactionAliasGuid] [uniqueidentifier] NULL,
	[RecircTransactionAliasKey] [nvarchar](50) NULL,
	[LogCommunications] [bit] NULL,
	[LogCommPath] [nvarchar](255) NULL,
	[EnableScully] [bit] NULL,
	[EnableEquipmentValidate] [bit] NULL,
	[StationPromptTimeout] [int] NULL,
	[StationMessageTimeout] [int] NULL,
	[AssignedMeterGuid] [uniqueidentifier] NULL,
	[AssignedMeterKey] [nvarchar](50) NULL,

	[_ClusterIdx] [bigint] NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[CreatedDate] [datetimeoffset](7) NULL,
	[UpdatedBy] [nvarchar](100) NULL,
	[UpdatedDate] [datetimeoffset](7) NULL,
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[CombinedUpdatedDate] [datetimeoffset](7) NULL,
	[IsRecordDeleted] [bit] NOT NULL,
	[IsRecordAddedByETL] [bit] NOT NULL,
	[IgnoreRecord] [bit] NOT NULL,
	[CDCSKey] [int] NULL,
	[SourceRowVersion] [bigint] NULL,
	[CDCRowVersion] [bigint] NULL,
	[_RowVersion] [timestamp] NOT NULL
 CONSTRAINT [PK_tblStations] PRIMARY KEY CLUSTERED 
(
	[SKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [staging].[tblStations] ADD  DEFAULT ((0)) FOR [IsRecordDeleted]
GO
ALTER TABLE [staging].[tblStations] ADD  DEFAULT ((0)) FOR [IsRecordAddedByETL]
GO
ALTER TABLE [staging].[tblStations] ADD  DEFAULT ((0)) FOR [IgnoreRecord]