CREATE TABLE [staging].[tblTransactionAliases](
	[SKey] [int] IDENTITY(1,1) NOT NULL,
	[TransactionAliasGuid] [uniqueidentifier] NULL,
	[TransactionAliasKey] nvarchar(50) NULL,
	[AliasName] [nvarchar](32) NULL,
	[MeterCloseout] [bit] NULL,
	[BulkShipment] [bit] NULL,
	[DistributedImpact] [bit] NULL,
	[MultipleLineItems] [bit] NULL,
	[LimitSelectionsBasedOnHierarchy] [bit] NULL,
	[LineItemEditControl] [bit] NULL,
	[MultipleWeightReadings] [bit] NULL,
	[WeightReadingEditControl] [bit] NULL,
	[AssociatedReport] [nvarchar](80) NULL,
	[AssociatedPreloadReport] [nvarchar](80) NULL,
	[DestinationEquipmentTypes1] [bigint] NULL,
	[DestinationEquipmentTypes2] [bigint] NULL,
	[DestinationEquipmentTypes3] [bigint] NULL,
	[SourceEquipmentTypes1] [bigint] NULL,
	[SourceEquipmentTypes2] [bigint] NULL,
	[SourceEquipmentTypes3] [bigint] NULL,
	[ShowCompanyName] [smallint] NULL,
	[AggregateAssocTrans] [bit] NULL,
	[EnableTotalQuantityExceededWarning] [bit] NULL,
	[EnableQuantityToleranceExceededWarning] [bit] NULL,
	[EnableTotalValueExceededWarning] [bit] NULL,
	[EnableValueToleranceExceededWarning] [bit] NULL,
	[LevelUnitIndex] [int] NULL,
	[TemperatureUnitIndex] [int] NULL,
	[DensityUnitIndex] [int] NULL,
	[PressureUnitIndex] [int] NULL,
	[FlowUnitIndex] [int] NULL,
	[VolumeUnitIndex] [int] NULL,
	[MassUnitIndex] [int] NULL,
	[AdditiveVolumeUnitIndex] [int] NULL,
	[AdditiveProfileCycleAmountUnitIndex] [int] NULL,
	[AdditiveProfileRateUnitIndex] [int] NULL,
	[LevelDecimalPlaces] [tinyint] NULL,
	[TemperatureDecimalPlaces] [tinyint] NULL,
	[DensityDecimalPlaces] [tinyint] NULL,
	[PressureDecimalPlaces] [tinyint] NULL,
	[FlowDecimalPlaces] [tinyint] NULL,
	[VolumeDecimalPlaces] [tinyint] NULL,
	[MassDecimalPlaces] [tinyint] NULL,
	[AdditiveVolumeDecimalPlaces] [tinyint] NULL,
	[UseComboBoxControls] [bit] NULL,
	[MultipleTransportLineItems] [bit] NULL,	
	[SiteGuid] [uniqueidentifier] NULL,
	[SiteKey] nvarchar(50) NULL,
	[SiteSKey] [int] NULL,
	[LookupTransTypeIndex] [smallint] NULL,
	[TransactionTypeSKey] [int] NULL,
	[LookupDefaultStatusIndex] [int] NULL,
	[AssociatedTransactionAliasGuid] [uniqueidentifier] NULL,
	[AssociatedTransactionAliasKey] nvarchar(50) NULL,
	[IncludeInDispatch] [bit] NULL,
	[MasterRecordGuid] [uniqueidentifier] NULL,
	[MasterRecordKey] nvarchar(50) NULL,
	[EnableAutoCompleteControls] [bit] NULL,
	[PermitNonReferenceData] [bit] NULL,
	[UseTransactionDetailWithLayout] [bit] NULL,
	[DefaultMeterToEquipmentID] [bit] NULL,
	[LimitSourceEquipmentByProduct] [bit] NULL,
	[RememberMeterEndForMeterID] [bit] NULL,
	[PopulateCompaniesFromEquipment] [bit] NULL,
	[PopulateGrossVolumeFromMeterValues] [bit] NULL,
	[UseMeterAndCompressionFactorFromMeter] [bit] NULL,
	[_ClusterIdx] [bigint] NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[CreatedDate] [datetimeoffset](7) NULL,
	[UpdatedBy] [nvarchar](100) NULL,
	[UpdatedDate] [datetimeoffset](7) NULL,
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[CombinedUpdatedDate] [datetimeoffset](7) NULL,
	[IsRecordDeleted] [bit] NOT NULL,
	[IsRecordAddedByETL] [bit] NOT NULL,
	[IgnoreRecord] [bit] NOT NULL,
	[StartDate] [datetimeoffset](7) NULL,
	[EndDate] [datetimeoffset](7) NULL,
	[CDCSKey] [int] NULL,
	[SourceRowVersion] [bigint] NULL,
	[CDCRowVersion] [bigint] NULL,
	[_RowVersion] [timestamp] NOT NULL,		
CONSTRAINT [PK_tblTransactionAliases] PRIMARY KEY CLUSTERED 
(
	[SKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [staging].[tblTransactionAliases] ADD  DEFAULT ((0)) FOR [IsRecordDeleted]
GO
ALTER TABLE [staging].[tblTransactionAliases] ADD  DEFAULT ((0)) FOR [IsRecordAddedByETL]
GO
ALTER TABLE [staging].[tblTransactionAliases] ADD  DEFAULT ((0)) FOR [IgnoreRecord]