CREATE TABLE [staging].[tblTransactionSubLineItems]
(
	[SKey] [int] IDENTITY(1,1) NOT NULL,
	[TransactionSubLineItemGuid] [uniqueidentifier] NULL,
	[TransactionSubLineItemKey] [nvarchar](50) NULL,
	
	[BatchNumber] [nvarchar](20) NULL,
	[BottomVolumeSI] [float] NULL,
	[BottomVolumeUSGallon] [float] NULL,
	[BrokenBlend] [bit] NULL,
	[CleanLineItem] [bit] NULL,
	[CleanLineDeductItem] [bit] NULL,
	[CleanLineDeductQuantitySI] [float] NULL,
	[CleanLineDeductQuantityUSGallon] [float] NULL,
	[CleanLinePackQuantitySI] [float] NULL,
	[CleanLinePackQuantityUSGallon] [float] NULL,
	[COAID] [nvarchar](40) NULL,
	[ConjoinProductKey] [nvarchar](50) NULL,
	[ConjoinProductSKey] [int] NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[CreatedDate] [datetimeoffset](7) NULL,
	[Customs] [nvarchar](20) NULL,	
	[Date01] [datetimeoffset](7) NULL,
	[Date02] [datetimeoffset](7) NULL,
	[Date03] [datetimeoffset](7) NULL,
	[Date04] [datetimeoffset](7) NULL,
	[DeleteFlag] [bit] NULL,
	[Density] [float] NULL,
	[DifferentialPressure] [float] NULL,
	[DosageRate] [float] NULL,
	[Flag01] [bit] NULL,
	[Flag02] [bit] NULL,
	[Flag03] [bit] NULL,
	[Flag04] [bit] NULL,
	[Flag05] [bit] NULL,
	[Flag06] [bit] NULL,
	[FreezePoint] [float] NULL,
	[GrossManualValueFlag] [bit] NULL,
	[GrossQuantitySI] [float] NULL,
	[GrossQuantityUSGallon] [float] NULL,
	[ImproperAdditization] [bit] NULL,
	[LineFillSI] [float] NULL,
	[LineFillUSGallon] [float] NULL,
	[LineNumber] [int] NULL,		
	[LoadArmKey] [nvarchar](50) NULL,
	[LoadArmNumber] [int] NULL,
	[LoadArmSKey] [int] NULL,
	[MassManualValueFlag] [bit] NULL,
	[MassQuantitySI] [float] NULL,
	[MassQuantityLb] [float] NULL,
	[MeterID] [nvarchar](50) NULL,
	[MeterFactor] [float] NULL,	
	[MeterGuid] [uniqueidentifier] NULL,
	[MeterKey] [nvarchar](50) NULL,
	[MeterStart] [float] NULL,
	[MeterStartStopTimeDiff] [int] NULL,		
	[MeterStartDateTime] [datetimeoffset](7) NULL,
	[MeterStop] [float] NULL,
	[MeterStopDateTime] [datetimeoffset](7) NULL,
	[NetCapacitySI] [float] NULL,	
	[NetCapacityUSGallon] [float] NULL,
	[NetManualValueFlag] [bit] NULL,
	[NetQuantitySI] [float] NULL,
	[NetQuantityUSGallon] [float] NULL,
	[Number01] [float] NULL,
	[Number02] [float] NULL,
	[Number03] [float] NULL,
	[Number04] [float] NULL,
	[Number05] [float] NULL,
	[Number06] [float] NULL,
	[PackageManualValueFlag] [bit] NULL,
	[PresetAmount] [float] NULL,	
	[ProductCode] [nvarchar](50) NULL,
	[ProductGuid] [uniqueidentifier] NULL,
	[ProductId] [nvarchar](30) NULL,
	[ProductKey] [nvarchar](50) NULL,
	[Product_Orig] [nvarchar](30) NULL,
	[ProductSKey] [int] NULL,
	[ProductType] [nvarchar](20) NULL,
	[QualityIndex] [int] NULL,	
	[QualityName] [nvarchar](100) NULL,
	[SequenceID] [int] NULL,	
	[SiteSKey] [int] NULL,
	[StorageLocationID] [nvarchar](50) NULL,
	[StorageLocationTankGuid] [uniqueidentifier] NULL,
	[StorageLocationTankKey] [nvarchar](50) NULL,
	[StorageLocationTankSKey] [int] NULL,
	[TankStatus] [nvarchar](30) NULL,	
	[Tax1] [float] NULL,
	[Tax2] [float] NULL,
	[Tax3] [float] NULL,
	[Tax4] [float] NULL,
	[Tax5] [float] NULL,
	[Temperature] [float] NULL,
	[TransactionGuid] [uniqueidentifier] NULL,	
	[TransactionKey] [nvarchar](50) NULL,
	[TransactionInventoryDate] [date] NULL,
	[TransactionLineItemGuid] [uniqueidentifier] NULL,
	[TransactionLineItemKey] [nvarchar](50) NULL,
	[TransactionStatusIndex] [int] NULL,
	[TransactionStatusName] [nvarchar](100) NULL,
	[TransVersion] [bigint] NULL,	
	[UpdatedBy] [nvarchar](100) NULL,
	[UpdatedDate] [datetimeoffset](7) NULL,
	[Vcf] [float] NULL,
	[VcfManualValueFlag] [bit] NULL,

	--Extra fields to support FactTransaction fields that are found in tblTransactions but not in tblTransactionSubLineItems			
	[HeaderBillToCode] [nvarchar](10) NULL,
	[HeaderBillToCompanyKey] [nvarchar](50) NULL,
	[HeaderBillToCompanySKey] [int] NULL,
	[HeaderBillToId] [nvarchar](100) NULL,
	[HeaderCardExpirationDateSKey] [int] NULL,
	[HeaderCardName] [nvarchar](50) NULL,
	[HeaderCardNumber] [nvarchar](50) NULL,
	[HeaderCardType] [nvarchar](50) NULL,	
	[HeaderCarrierCode] [nvarchar](10) NULL,
	[HeaderCarrierCompanyKey] [nvarchar](50) NULL,
	[HeaderCarrierCompanySKey] [int] NULL,
	[HeaderCarrierId] [nvarchar](100) NULL,
	[HeaderCashAmount] [float] NULL,
	[HeaderConjoinOwnerKey] [nvarchar](50) NULL,
	[HeaderConjoinOwnerId] [nvarchar](100) NULL,
	[HeaderConjoinOwnerSKey] [int] NULL,
	[HeaderConjoinTransID] [nvarchar](64) NULL,
	[HeaderContactFirstName] [nvarchar](50) NULL,
	[HeaderContactInfo] [nvarchar](50) NULL,
	[HeaderContactSurname] [nvarchar](50) NULL,
	[HeaderCountry] [nvarchar](50) NULL,
	[HeaderCreatedDateSKey] [int] NULL,
	[HeaderCreatedDate] [datetimeoffset](7) NULL,
	[HeaderCreatedTimeSKey] [int] NULL,
	[HeaderCreditAmount] [float] NULL,
	[HeaderDate01] [datetimeoffset](7) NULL,
	[HeaderDate01DateSKey] [int] NULL,
	[HeaderDate01TimeSKey] [int] NULL,
	[HeaderDate02] [datetimeoffset](7) NULL,
	[HeaderDate03] [datetimeoffset](7) NULL,
	[HeaderDate04] [datetimeoffset](7) NULL,
	[HeaderDeleteFlag] [bit] NULL,
	[HeaderDestinationEquipment1Key] [nvarchar](50) NULL,
	[HeaderDestinationEquipment1SKey] [int] NULL,
	[HeaderDispatchedDateSKey] [int] NULL,
	[HeaderDispatchedTimeSKey] [int] NULL,
	[HeaderDriverIdentificationNumber] [nvarchar](50) NULL,
	[HeaderDocumentNumber] [nvarchar](30) NULL,
	[HeaderEffectiveDateSKey] [int] NULL,
	[HeaderFlag01] [bit] NULL,
	[HeaderFlag02] [bit] NULL,
	[HeaderFlag03] [bit] NULL,
	[HeaderFlag04] [bit] NULL,
	[HeaderFlag05] [bit] NULL,
	[HeaderFlag06] [bit] NULL,
	[HeaderInternationalRouteIndicator] [bit] NULL,
	[HeaderInventoryDate] [datetimeoffset](7) NULL,
	[HeaderInventoryDateSKey] [int] NULL,
	[HeaderLegacyNumber] [nvarchar](50) NULL,
	[HeaderLinkedDocumentNumber] [nvarchar](75) NULL,
	[HeaderLoadID] [nvarchar](50) NULL,	
	[HeaderManagerCode] [nvarchar](10) NULL,
	[HeaderManagerCompanyKey] [nvarchar](50) NULL,
	[HeaderManagerCompanySKey] [int] NULL,
	[HeaderManagerId] [nvarchar](100) NULL,
	[HeaderNumber01] [float] NULL,
	[HeaderNumber02] [float] NULL,
	[HeaderNumber03] [float] NULL,
	[HeaderNumber04] [float] NULL,
	[HeaderNumber05] [float] NULL,
	[HeaderNumber06] [float] NULL,
	[HeaderOperatorPersonnelKey] [nvarchar](50) NULL,
	[HeaderOperatorPersonnelSKey] [int] NULL,	
	[HeaderOperatorID] [nvarchar](50) NULL,
	[HeaderOperatorName] [nvarchar](150) NULL,
	[HeaderOwnerCode] [nvarchar](10) NULL,
	[HeaderOwnerCompanyKey] [nvarchar](50) NULL,
	[HeaderOwnerCompanySKey] [int] NULL,
	[HeaderOwnerId] [nvarchar](100) NULL,
	[HeaderPONumber] [nvarchar](14) NULL,
	[HeaderPreviousRoutingID] [nvarchar](30) NULL,
	[HeaderReasonCode] [nvarchar](50) NULL,
	[HeaderReasonCodeKey] [nvarchar](50) NULL,
	[HeaderReasonCodeSKey] [int] NULL,	
	[HeaderRequestedDateSKey] [int] NULL,
	[HeaderRequestedDateTime] [datetimeoffset](7) NULL,
	[HeaderReversalType] [nvarchar](2) NULL,
	[HeaderReversedTransID] [nvarchar](64) NULL,
	[HeaderRouteOriginationDateSKey] [int] NULL,
	[HeaderRoutingID] [nvarchar](50) NULL,	
	[HeaderShipperCode] [nvarchar](10) NULL,
	[HeaderShipperCompanyKey] [nvarchar](50) NULL,
	[HeaderShipperCompanySKey] [int] NULL,
	[HeaderShipperId] [nvarchar](100) NULL,
	[HeaderShipToCode] [nvarchar](10) NULL,
	[HeaderShipToCompanyKey] [nvarchar](50) NULL,
	[HeaderShipToCompanySKey] [int] NULL,
	[HeaderShipToId] [nvarchar](100) NULL,
	[HeaderShipmentNumber] [nvarchar](50) NULL,			
	[HeaderSourceEquipment1Key] [nvarchar](50) NULL,
	[HeaderSourceEquipment1SKey] [int] NULL,
	[HeaderSubmittedToAccounting] [bit] NULL,
	[HeaderSubType] [nvarchar](20) NULL,	
	[HeaderSupplierCode] [nvarchar](10) NULL,
	[HeaderSupplierCompanyKey] [nvarchar](50) NULL,
	[HeaderSupplierCompanySKey] [int] NULL,
	[HeaderSupplierId] [nvarchar](100) NULL,
	[HeaderTicketMode] [nvarchar](25) NULL,
	[HeaderTicketSource] [nvarchar](25) NULL,
	[HeaderTimeEnd] [datetimeoffset](7) NULL,
	[HeaderTimeEndDateSKey] [int] NULL,
	[HeaderTimeEndTimeSKey] [int] NULL,
	[HeaderTimeIn] [datetimeoffset](7) NULL,
	[HeaderTimeInDateSKey] [int] NULL,
	[HeaderTimeInTimeSKey] [int] NULL,
	[HeaderTimeOut] [datetimeoffset](7) NULL,
	[HeaderTimeOutDateSKey] [int] NULL,
	[HeaderTimeOutTimeSKey] [int] NULL,		
	[HeaderTransactionAliasKey] [nvarchar](50) NULL,
	[HeaderTransactionAliasName] [nvarchar](32) NULL,	
	[HeaderTransactionAliasSKey] [int] NULL,
	[HeaderTransactionStatusIndex] [int] NULL,
	[HeaderTransactionStatusName] [nvarchar](100) NULL,	
	[HeaderTransactionTypeIndex] [smallint] NULL,
	[HeaderTransactionTypeKey] [nvarchar](50) NULL,
	[HeaderTransactionTypeSKey] [int] NULL,
	[HeaderTransDateSKey] [int] NULL,
	[HeaderTransDateTime] [datetimeoffset](7) NULL,
	[HeaderTransID] [nvarchar](64) NULL,
	[HeaderTransReferenceID] [nvarchar](100) NULL,
	[HeaderTransTimeSKey] [int] NULL,
	[HeaderTransVersion] [bigint] NULL,		

	--Extra fields to support FactTransaction fields that are found in tblTransactionLineItems but not in tblTransactionSubLineItems			
	[LineItemLoadArmNumber] [int] NULL,
	[LineItemDestinationEquipmentKey] [nvarchar](50) NULL,
	[LineItemDestinationEquipmentID] [nvarchar](30) NULL,
	[LineItemDestinationEquipmentSKey] [int] NULL,
	[LineItemSourceEquipmentKey] [nvarchar](50) NULL,
	[LineItemSourceEquipmentID] [nvarchar](30) NULL,
	[LineItemSourceEquipmentSKey] [int] NULL,
	[LineItemLoadingLocationStationKey] [nvarchar](50) NULL,
	[LineItemLoadingLocationStationSKey] [int] NULL,
	[LineItemStorageLocationTankKey] [nvarchar](50) NULL,
	[LineItemStorageLocationTankSKey] [int] NULL,
	
	--System Fields
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[CombinedUpdatedDate] [datetimeoffset](7) NULL,
	[CombinedUpdatedDateSKey] [int] NULL,
	[IsRecordDeleted] [bit] NOT NULL,
	[IsRecordAddedByETL] [bit] NOT NULL,
	[SourceFactSKey] [int] NULL,
	[IgnoreRecord] [bit] NOT NULL,
	[IsProcessed] [bit] NOT NULL,
	[CDCSKey] [int] NULL,
	[SourceRowVersion] [bigint] NULL,
	[CDCRowVersion] [bigint] NULL,
	[_RowVersion] [timestamp] NOT NULL,

 CONSTRAINT [PK_tblTransactionSubLineItems] PRIMARY KEY CLUSTERED 
(
	[SKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [staging].[tblTransactionSubLineItems] ADD  DEFAULT ((0)) FOR [IsRecordDeleted]
GO
ALTER TABLE [staging].[tblTransactionSubLineItems] ADD  DEFAULT ((0)) FOR [IsRecordAddedByETL]
GO
ALTER TABLE [staging].[tblTransactionSubLineItems] ADD  DEFAULT ((0)) FOR [IgnoreRecord]
GO
ALTER TABLE [staging].[tblTransactionSubLineItems] ADD  DEFAULT ((0)) FOR [IsProcessed]
GO
CREATE NONCLUSTERED INDEX [IX_tblTransactionSubLineItems_TransactionSubLineItemKey_TransactionLineItemKey_TransactionKey] ON [staging].[tblTransactionSubLineItems]
(
	[TransactionSubLineItemKey] ASC,
	[TransactionLineItemKey] ASC,
	[TransactionKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
