CREATE TABLE [staging].[tblUsers](
	[SKey] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [nvarchar](100) NULL,
	[Password] [varbinary](256) NULL,
	[LastLoginDate] [datetimeoffset](7) NULL,
	[LastLogoffDate] [datetimeoffset](7) NULL,
	[ChangePassword] [bit] NULL,
	[PasswordTimeStamp] [datetimeoffset](7) NULL,
	[Name] [nvarchar](50) NULL,
	[EmailAddress] [nvarchar](50) NULL,
	[PasswordHistory1] [varbinary](256) NULL,
	[PasswordHistory2] [varbinary](256) NULL,
	[PasswordHistory3] [varbinary](256) NULL,
	[PasswordHistory4] [varbinary](256) NULL,
	[PasswordHistory5] [varbinary](256) NULL,
	[PasswordHistory6] [varbinary](256) NULL,
	[PasswordHistory7] [varbinary](256) NULL,
	[PasswordHistory8] [varbinary](256) NULL,
	[PasswordHistory9] [varbinary](256) NULL,
	[PasswordHistory10] [varbinary](256) NULL,
	[PasswordHistory11] [varbinary](256) NULL,
	[PasswordHistory12] [varbinary](256) NULL,
	[PasswordHistory13] [varbinary](256) NULL,
	[PasswordHistory14] [varbinary](256) NULL,
	[PasswordHistory15] [varbinary](256) NULL,
	[PasswordHistory16] [varbinary](256) NULL,
	[PasswordHistory17] [varbinary](256) NULL,
	[PasswordHistory18] [varbinary](256) NULL,
	[PasswordHistory19] [varbinary](256) NULL,
	[PasswordHistory20] [varbinary](256) NULL,
	[PasswordHistory21] [varbinary](256) NULL,
	[PasswordHistory22] [varbinary](256) NULL,
	[PasswordHistory23] [varbinary](256) NULL,
	[PasswordHistory24] [varbinary](256) NULL,
	[PasswordLockoutCount] [int] NULL,
	[InactivityLockout] [bit] NULL,
	[InactivityLockoutDate] [datetimeoffset](7) NULL,
	[UserGuid] [uniqueidentifier] NULL,
	[UserKey] [nvarchar](50) NULL,
	[SiteGuid] [uniqueidentifier] NOT NULL,
	[SiteKey] [nvarchar](50) NULL,
	[PasswordHint] [varchar](80) NULL,
	[UserData1] [nvarchar](120) NULL,
	[UserData2] [nvarchar](120) NULL,
	[UserData3] [nvarchar](120) NULL,
	[UserData4] [nvarchar](120) NULL,
	[UserData5] [nvarchar](120) NULL,
	[UserData6] [nvarchar](120) NULL,
	[UserData7] [nvarchar](120) NULL,
	[UserData8] [nvarchar](120) NULL,
	[PhoneNumber] [nvarchar](20) NULL,
	[AccountExpirationDate] [datetime] NULL,
	[ActiveDirectoryUser] [bit] NULL,
	[_ClusterIdx] [bigint] NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[CreatedDate] [datetimeoffset](7) NULL,
	[UpdatedBy] [nvarchar](100) NULL,
	[UpdatedDate] [datetimeoffset](7) NULL,
	[RecordUpdatedDate] [datetimeoffset](7) NULL,
	[CombinedUpdatedDate] [datetimeoffset](7) NULL,
	[IsRecordDeleted] [bit] NOT NULL,
	[IsRecordAddedByETL] [bit] NOT NULL,
	[IgnoreRecord] [bit] NOT NULL,
	[CDCSKey] [int] NULL,
	[SourceRowVersion] [bigint] NULL,
	[CDCRowVersion] [bigint] NULL,
	[_RowVersion] [timestamp] NOT NULL,
 CONSTRAINT [PK_tblUsers] PRIMARY KEY CLUSTERED 
(
	[SKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [staging].[tblUsers] ADD  DEFAULT ((0)) FOR [IsRecordDeleted]
GO
ALTER TABLE [staging].[tblUsers] ADD  DEFAULT ((0)) FOR [IsRecordAddedByETL]
GO
ALTER TABLE [staging].[tblUsers] ADD  DEFAULT ((0)) FOR [IgnoreRecord]